src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>InternalOrganisation</fullName>
        <active>true</active>
        <description>Use this record type for AS organisational units, local services, area, region, directorate etc</description>
        <label>Internal Organisation</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Funding_Requirement__c.object
<CustomObject>
    <description>A single figure representing the funding requirement to cover the costs of providing the service, including FCR</description>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Financial Year</label>
        <picklist>
            <picklistValues>
                <fullName>2010/11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011/12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012/13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013/14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014/15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015/16</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <description>The Service to which this Funding Requirement relates</description>
        <inlineHelpText>Select the service for which this funding requirement applies</inlineHelpText>
        <label>Service</label>
        <referenceTo>Services__c</referenceTo>
        <relationshipName>Funding_Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Cover_Potential_Percent__c</fullName>
        <formula>if(BLANKVALUE(Total_Cover_Potential__c,0) ==0,0,   
    if(BLANKVALUE(Total_Amount__c,0)==0,0,
        Total_Cover_Potential__c  /  Total_Amount__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cover Potential Percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>BDR Service Cost</label>
    <nameField>
        <displayFormat>FR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDR Service Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>Locality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Locality in which this service is based (left blank for national services).</description>
        <label>Locality</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select an Alzheimer&apos;s Society Locality.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Organisation</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>contains</operation>
                <value>Locality</value>
            </filterItems>
            <infoMessage>Please select a Locality.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Services_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operated_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the Organisation which operates this service.</description>
        <inlineHelpText>For internal services this should be a local service office unless operated at the locality level</inlineHelpText>
        <label>Operated By</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND (3 OR 4)) OR (5 AND 6)</booleanFilter>
            <errorMessage>Internal Services can only be operated by a Locality or a Local Service Office (this lookup is filtered based on the Locality you selected in the previous field).
External Services can only be Operated By an External Organisation.</errorMessage>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Service</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Organisation</value>
            </filterItems>
            <filterItems>
                <field>Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Locality__c</valueField>
            </filterItems>
            <filterItems>
                <field>Account.Parent.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Locality__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Service</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>External organisation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dementia Connect - Services (Operated By)</relationshipLabel>
        <relationshipName>Services_Activities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>service_status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>service_type__c</fullName>
        <inlineHelpText>Service description will be automatically populated from the service type (or sub type if there is one)</inlineHelpText>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult education &amp; training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (emotional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (financial)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (general)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awareness raising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending / home support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counselling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day support / day care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafés</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exercise / Fitness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home facilities &amp; services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Dementia)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Financial &amp; Legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programmes &amp; provision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>Internal Service/Activity</description>
        <label>Internal Service</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Locality__c</fullName>
        <description>The Society Locality to which the user is assigned (if any).</description>
        <inlineHelpText>Must match the Name of the corresponding Internal Organisation.</inlineHelpText>
        <label>Locality</label>
        <picklist>
            <controllingField>Area__c</controllingField>
            <picklistValues>
                <fullName>Abertawe Bro Morgannwg Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avon, Gloucestershire &amp; Wiltshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bedfordshire &amp; Luton Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Berkshire, Buckinghamshire, Oxfordshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambridgeshire &amp; Peterborough Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiff and the Vale Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheshire &amp; St Helens Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cumbria Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cwm Taff Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Darlington &amp; Teesside Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Derbyshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Devon, Cornwall &amp; Isles of Scilly Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dorset &amp; Somerset Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durham Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Riding &amp; Humber Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Essex Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Manchester Central &amp; West Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Manchester Central South and East Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gwent Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hampshire, Isle of Wight and the Channel Islands Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Herefordshire &amp; Worcestershire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hertfordshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent &amp; Medway Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lancashire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leicestershire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lincolnshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merseyside &amp; Isle of Man Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Midlands Central Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norfolk Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North &amp; East Northern Ireland Locality</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BDRServicesFundCoverageController.cls
public with sharing class BDRServicesFundCoverageController {


   /***********************************************************************************************************
    *
    * gary.grant@conseq.co.uk
    * Jan 2013
    *  A search controller used to find Services where Costs have been defined via a BDR
    *  
    *  The 'Funding_Requirement__c' object has the label 'BDR Service Cost'
    *
    ************************************************************************************************************/
 
  private String soql {get;set;}
  
  // Fields used for applying filters to the results    
  public String name {get;set;}
  public String locality {get;set;}
  public String service_type {get;set;}
  public String fiscal_year {get;set;}
  public String funding_type {get;set;}
  public String service_status {get;set;}
  

   // The  soql without the order and limit
  public static final String QUERY =   
  
  			 ' select Id, Name, Fiscal_Year__c, Total_Cover_Potential_Percent__c, '+
  			 
			 ' Service__r.Locality__r.Name, '+
			 ' Service__r.Name, '+
		
			 ' Service__r.Operated_by__c, '+
			 ' Service__r.service_type__c, '+
			 ' Service__r.service_status__c' +
			 
			 ' from Funding_Requirement__c where Name != null';

  // The collection of Services to display  
  public List<BdrFundReqWrapper> Services 
  {
    get {
            if (Services == null) Services = new List<BdrFundReqWrapper>();
            return Services;
        }
        set;
  }      

     
  // The current sort direction. defaults to asc
  public String sortDir {
    get  { if (sortDir == null) {  sortDir = 'desc'; } return sortDir;  }
    set;
  }
 
  // The field to sort by. Defaults to Service Name
  public String sortField {
    get  { if (sortField == null) {sortField = 'service__r.Name,Fiscal_Year__c'; } return sortField;  }
    set;
  }
 

  
  // Params for manipulating the dialog
  public String parent_domain{get;set;}
  public String pid{get;set;}
    
 
  // Constructor: Init the controller and display some sample data when the page loads
  public BDRServicesFundCoverageController() {

    soql = QUERY;
       runQuery();
  //  services=new List<BdrFundReqWrapper>();
    
     /* The search is now called from the document.ready so that when the user returns to the page using
     * the browser back button the same filters still apply so the user can return to the filterdd list
     */
  }
 
  // toggles the sorting of query from asc<-->desc
  public void toggleSort() {
    // Toggle the direction
    sortDir = sortDir.equals('asc') ? 'desc' : 'asc';
    
    // Run the query again
    runQuery();
  }
 
  // Runs the query to get the Service Cost objects  (called Funding Requirements)
  private void runQuery() {
 
    try {
      List<Funding_Requirement__c> results = Database.query(soql + ' order by ' + sortField + ' ' + sortDir + ' limit 200');
      
      services=new List<BdrFundReqWrapper>();  
      
      for (Funding_Requirement__c freq : results) {
        		services.add(new BdrFundReqWrapper(freq));
      }
    } catch (Exception e) {
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage() ));
    }
    finally { }
 
  }
 
  // Runs the search with parameters passed via Javascript
  public PageReference runApexSearch() {
  	
  	System.debug('*****************Now in BDRServiceFundCoverageController - runSearch method');
  	
  	// Map of PageParameters 
    Map<string,string> pageParams=ApexPages.currentPage().getParameters();
 
    String name = pageParams.get('name');
    String locality =pageParams.get('locality');
    String service_type = pageParams.get('service_type');
    String fiscal_year = pageParams.get('fiscal_year');    
    String funding_type = pageParams.get('funding_type');
    String service_status = pageParams.get('service_status');
  
     
    soql = QUERY;
    
    if (!locality.equals(''))
      soql += ' and Service__r.Locality__r.Id = \''+locality+'\'';
      
      
    if (!service_type.equals(''))
      soql += ' and Service__r.service_type__c = \''+escapeSQ(service_type)+'\'';  
      
            
    if (!service_status.equals(''))
      soql += ' and Service__r.service_status__c = \''+escapeSQ(service_status)+'\'';  
      
    if (!fiscal_year.equals(''))
      soql += ' and Fiscal_year__c = \''+escapeSQ(fiscal_year)+'\'';    
      
    if (funding_type.equals('Funded'))
      soql += ' and total_cover_potential_percent__c >= 100';    
      
    if (funding_type.equals('UnFunded'))
      soql += ' and total_cover_potential_percent__c < 100';    
    
    System.debug('*********************************'+soql)  ;
     
    // Run the query again
    runQuery();
 
    return null;
  }
  
    private String escapeSQ(String field) {
  			return String.escapeSingleQuotes(field);
  }
 
  // Use Apex Describe to build the picklist values for Service Types
  public List<SelectOption> getService_Types() {
   
       List<SelectOption> optionList = new List<SelectOption>();  
       optionList.add(new SelectOption('', ''));	 
 
        Schema.DescribeFieldResult field = Services__c.service_type__c.getDescribe();
 
        for (Schema.PicklistEntry f : field.getPicklistValues()) {
            optionList.add(new SelectOption(f.getLabel(), f.getLabel()));  
      }
      return optionList;          
  }
  
    public List<SelectOption> getService_Status_Options() {
   
       List<SelectOption> optionList = new List<SelectOption>();  
       optionList.add(new SelectOption('', ''));	 
 
        Schema.DescribeFieldResult field = Services__c.service_status__c.getDescribe();
 
        for (Schema.PicklistEntry f : field.getPicklistValues()) {
            optionList.add(new SelectOption(f.getLabel(), f.getLabel()));  
      }
      return optionList;          
  }
  
    // Get the list of Internal Organisations to populate select
      public List<SelectOption>  getLocalities() { 
  	  
		  List<SelectOption> optionList = new List<SelectOption>();   		    
          String word = 'Locality';
	
    	  optionList.add(new SelectOption('', ''));	
    	
          for (Account A : [Select Id, Name From Account where RecordType.DeveloperName = 'InternalOrganisation' And Name like :'%'+word order by Name asc limit 200]) {
               String showName = A.Name.replaceAll(word,'');
               optionList.add(new SelectOption(A.Id, showName));  
          }
          return optionList;  
      }

 
  public List<SelectOption> getFunding_types() {
  	
  	 List<SelectOption> optionList = new List<SelectOption>();   
     optionList.add(new SelectOption('',''));
     optionList.add(new SelectOption('Funded','Funded'));
     optionList.add(new SelectOption('UnFunded','UnFunded'));
      return optionList;          
  }


  // Use apex describe to build the picklist values
      public List<SelectOption> getYearsOptions() { 
  	  
		  List<SelectOption> optionList = new List<SelectOption>();   
          optionList.add(new SelectOption('',''));
  	      String year = '';
  	 	  for (SObject o : [ Select Fiscal_Year__c from Funding_Requirement__c group by Fiscal_Year__c]) {
                year = String.valueOf(o.get('Fiscal_Year__c'));
      			optionList.add(new SelectOption(year, year));
     		}
	  	
  		return optionList;
  }
  


}