src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>$RecordType.DeveloperName</formula>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>$RecordType.DeveloperName</formula>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Usage__c.object
<CustomObject>
    <fields>
        <fullName>Service_Type__c</fullName>
        <description>The type of Service to which Service Usage relates.
Used as a filter when selecting Service.
Used to set Record Type on saving a new Service Usage.</description>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (one to one)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peer support group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered home care and support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singing for the Brain</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Usage</label>
    <nameField>
        <label>Service Usage Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Usage</pluralLabel>
    <recordTypes>
        <fullName>Outgoing_Referral</fullName>
        <active>true</active>
        <description>Used by the Service Referral module to record outgoing referrals i.e. referrals TO external services.  Not directly available to any user roles.</description>
        <label>Outgoing Referral</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>Locality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Locality in which this service is based (left blank for national services).</description>
        <label>Locality</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select an Alzheimer&apos;s Society Locality.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Organisation</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>contains</operation>
                <value>Locality</value>
            </filterItems>
            <infoMessage>Please select a Locality.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Services_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operated_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the Organisation which operates this service.</description>
        <inlineHelpText>For internal services this should be a local service office unless operated at the locality level</inlineHelpText>
        <label>Operated By</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND (3 OR 4)) OR (5 AND 6)</booleanFilter>
            <errorMessage>Internal Services can only be operated by a Locality or a Local Service Office (this lookup is filtered based on the Locality you selected in the previous field).
External Services can only be Operated By an External Organisation.</errorMessage>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Service</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Organisation</value>
            </filterItems>
            <filterItems>
                <field>Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Locality__c</valueField>
            </filterItems>
            <filterItems>
                <field>Account.Parent.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Locality__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Service</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>External organisation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dementia Connect - Services (Operated By)</relationshipLabel>
        <relationshipName>Services_Activities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>service_status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>service_type__c</fullName>
        <inlineHelpText>Service description will be automatically populated from the service type (or sub type if there is one)</inlineHelpText>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult education &amp; training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (emotional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (financial)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (general)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awareness raising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending / home support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counselling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day support / day care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafés</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exercise / Fitness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home facilities &amp; services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Dementia)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Financial &amp; Legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programmes &amp; provision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <recordTypes>
        <fullName>External</fullName>
        <active>true</active>
        <description>External Service/Activity</description>
        <label>External Service</label>
    </recordTypes>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>Internal Service/Activity</description>
        <label>Internal Service</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Locality__c</fullName>
        <description>The Society Locality to which the user is assigned (if any).</description>
        <inlineHelpText>Must match the Name of the corresponding Internal Organisation.</inlineHelpText>
        <label>Locality</label>
        <picklist>
            <controllingField>Area__c</controllingField>
            <picklistValues>
                <fullName>Abertawe Bro Morgannwg Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avon, Gloucestershire &amp; Wiltshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bedfordshire &amp; Luton Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Berkshire, Buckinghamshire, Oxfordshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambridgeshire &amp; Peterborough Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiff and the Vale Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheshire &amp; St Helens Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cumbria Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cwm Taff Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Darlington &amp; Teesside Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Derbyshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Devon, Cornwall &amp; Isles of Scilly Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dorset &amp; Somerset Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durham Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Riding &amp; Humber Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Essex Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Manchester Central &amp; West Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Manchester Central South and East Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gwent Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hampshire, Isle of Wight and the Channel Islands Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Herefordshire &amp; Worcestershire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hertfordshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent &amp; Medway Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lancashire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leicestershire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lincolnshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merseyside &amp; Isle of Man Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Midlands Central Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norfolk Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North &amp; East Northern Ireland Locality</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/mergeServices.cls
public with sharing class mergeServices {
// copies referrals and service users to master record and closes child service  (does not delete it)
public  Services__c master{get;set;}
public  Services__c child{get;set;}
public String masterOrgLocality {get;set;}
public String childOrgLocality {get;set;}
public String masterOrgOperatedBy {get;set;}
public String childOrgOperatedBy {get;set;}

public Boolean canMerge {get;set;}
public Boolean mergeRequested {get;set;}

private List<Account> masterOrg;
private List<Account> childOrg;
// Standard controller constructor.
    public mergeServices () {
        mergeRequested = false;
        
        master=  [select id, Name,Locality__c ,Operated_By__c ,service_status__c ,service_type__c ,Record_Type_Name__c from Services__c where id = :ApexPages.currentPage().getParameters().get('masterid') LIMIT 1];
        system.debug('@@@@@@@@@@@@@@@'+master.id);
        
        child= [select id, Name,Locality__c ,Operated_By__c ,service_status__c ,service_type__c ,Record_Type_Name__c from Services__c  where id = :ApexPages.currentPage().getParameters().get('childid') LIMIT 1];
        system.debug('@@@@@@@@@@@@@@@'+child.id);
        
        List<Account> masterOrg = [select id, name from Account where id =:master.Locality__c LIMIT 1];
        if (masterOrg.size()==0){
            masterOrgLocality = '';}
        else {
            masterOrgLocality = masterOrg[0].name;}
            
        List<Account> childOrg= [select id, name from Account where id =:child.Locality__c LIMIT 1];
        if (childOrg.size()==0){
            childOrgLocality = '';}
        else {
        	childOrgLocality = childOrg[0].name;}
        	
        //get operated by
        masterOrg = [select id, name from Account where id =:master.Operated_By__c LIMIT 1];
        if (masterOrg.size()==0){
            masterOrgOperatedBy = '';}
        else {
            masterOrgOperatedBy = masterOrg[0].name;}
            
        childOrg= [select id, name from Account where id =:child.Operated_By__c LIMIT 1];
        if (childOrg.size()==0){
            childOrgOperatedBy = '';}
        else {childOrgOperatedBy = childOrg[0].name;}

        
        //check to see if user can delete contacts.  If they cannot they they will have to contact CRS support.
        Boolean canDelete = Services__c.sObjectType.getDescribe().isDeletable();
        if (canDelete==true) {
            ApexPages.Message message = new ApexPages.message(ApexPages.severity.Info,'Please check that records should be merged together. Before merging, please copy any data you need to keep from the service record to be merged. (Attached records such as Service Usages  will be copied over.) Once you have checked the records, please click the "Merge Service" button. ');
            ApexPages.addMessage(message);
        
            canMerge=true;}
        else {
            ApexPages.Message message = new ApexPages.message(ApexPages.severity.Info,'Please check that records should be merged together. Before merging, please copy any data you need to keep from the service record to be merged. (Attached records such as Service Usages will be copied over.) Once you have checked the records, please click the "Request Merge Service" button. ');
            ApexPages.addMessage(message);
            canMerge=false;}
    
    }
    
    
    public PageReference mergeService(){
        List<Service_Usage__c> lstSUToUpdate = new List<Service_Usage__c>();
        List<Service_Usage__c> lstSURefToUpdate = new List<Service_Usage__c>();
        try {
             List<Service_Usage__c> lstSU = new List<Service_Usage__c>();
             lstSU= [Select Id, Name,Service_Field__c, Referring_Service__c from Service_Usage__c where (Service_Field__c =:child.id ) ];
             if (lstSU.size() > 0){
             
                 for (Service_Usage__c rec: lstSU ){
                     System.debug('>>>>>>>>>>>Name:' + rec.Name);
                     System.debug('>>>>>>>>>>>Id:  ' + rec.id);
                     rec.Service_Field__c = master.id;
                     lstSUToUpdate.add(rec);
                 }
                 
                 if (lstSUToUpdate.size() > 0){
                     Savepoint sp = Database.setSavepoint();
                    try
                      {
                      //Update ServiceUsage records.
                      upsert lstSUToUpdate;
                      }catch(Exception ex){Database.rollback(sp);
                           ApexPages.Message message = new ApexPages.message(ApexPages.severity.ERROR,'An error occurred while updating Service Usages.');
                           ApexPages.addMessage(message);
                           return null;}
                 
                 }
              }
              
             //now do referrals
             lstSU= [Select Id, Name,Service_Field__c, Referring_Service__c from Service_Usage__c where (Referring_Service__c =:child.id ) ];
             if (lstSU.size() > 0){
             
                 for (Service_Usage__c rec: lstSU ){
                     System.debug('>>>>>>>>>refName:' + rec.Name);
                     System.debug('>>>>>>>>>refId:  ' + rec.id);
                     rec.Referring_Service__c = master.id;
                     lstSURefToUpdate.add(rec);
                 }
                 if (lstSURefToUpdate.size() > 0){
                     Savepoint sp = Database.setSavepoint();
                    try
                      {
                      //Update ServiceUsage records.
                      upsert lstSURefToUpdate;
                      }catch(Exception ex){Database.rollback(sp);
                           ApexPages.Message message = new ApexPages.message(ApexPages.severity.ERROR,'An error occurred while updating Service Usages.');
                           ApexPages.addMessage(message);
                           return null;}
                 
                 }
             
             }
        } catch (DmlException e) {
    // Process exception here
        }
     return new Pagereference('/'+master.Id);
    }

//Test script for code coverage.
public testMethod static void testController(){
	Id servRT;
	servRT = [select Id from RecordType where DeveloperName ='External' and SObjectType='Services__c'].id;
	
	Id servUseageRT;
	servUseageRT = [select Id from RecordType where DeveloperName ='Outgoing_Referral' and SObjectType='Service_Usage__c'].id;
	
    Account accRec = new Account(Name='Essex Locality',RecordTypeId=[Select Id from RecordType where SObjectType='Account' and Name ='Internal Organisation'].id);
    insert accRec;
    
    Services__c serv1 = new Services__c(Locality__c=accRec.id, RecordTypeId=servRT ,Service_Type__c='Befriending', Name='testControllerService');
    insert serv1;
    Services__c serv2 = new Services__c(Locality__c=accRec.id, RecordTypeId=servRT, Service_Type__c='Befriending', Name='testControllerService2');
    insert serv2;

	Contact con1 = new Contact(Salutation='Mr',FirstName='Abc',LastName='Test1',mailingPostalCode ='ABC123', Birthdate =Date.Today(),
				RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and name like 'Person with dementia%'].id);
    insert con1;
    
    Service_Usage__c servUsg1 = new Service_Usage__c(Service_Field__c=serv2.id,Primary_Service_User__c=con1.id,
        		Service_Type__c='Befriending', RecordTypeId= servUseageRT);
    insert servUsg1;
    
    Service_Usage__c servUsg2 = new Service_Usage__c(Service_Field__c=serv1.id,Primary_Service_User__c=con1.id,
        		Service_Type__c='Befriending', Referring_Service__c=serv2.id, RecordTypeId= servUseageRT);
    insert servUsg2;
    
    //Create instance of the class to test and initialise the list 
    ApexPages.currentPage().getParameters().put('masterid', serv1.id); 
    ApexPages.currentPage().getParameters().put('childid', serv2.id);
    mergeServices conCls= new mergeServices(); 
    conCls.mergeService();
    //conCls.requestMergeService();
    }    
}