src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <description>Category of External Organisation</description>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Statutory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Landlord</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Landlord Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Landlord Solicitor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Landlord_Agent__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Landlord Agent</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Category__c</field>
                <operation>equals</operation>
                <value>Landlord, Landlord Agent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties (Landlord Agent)</relationshipLabel>
        <relationshipName>Locations6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Landlord__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Landlord</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Category__c</field>
                <operation>equals</operation>
                <value>Landlord, Landlord Agent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties (Landlord)</relationshipLabel>
        <relationshipName>Locations5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Where__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Region / Area / Locality / Service Office 
 Always enter the lowest of the hierarchy in case of Combined Use</inlineHelpText>
        <label>Who</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Organisation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties (Where)</relationshipLabel>
        <relationshipName>Locations4</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Site_Survey__c.object
<CustomObject>
    <description>Property/site survey for Facilities</description>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Site Surveys</relationshipLabel>
        <relationshipName>Site_Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>{YYYY}-{000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SiteSurveyController.cls
public class SiteSurveyController {
    public Site_Survey__c survey;
    
    public SiteSurveyController (ApexPages.StandardController controller) {
        //Contact c = (Contact)controller.getRecord();
        survey = new Site_Survey__c();
    }
    
    //
    // Properties
    //
    public Site_Survey__c getSurvey() {
        if(survey == null)
            survey = new Site_Survey__c();
        return survey;
    }
    
    public PageReference section1() {
        return Page.SiteSurvey1;
    }
    
    public PageReference section2() {
        return Page.SiteSurvey2;
    }
    
    public PageReference section3() {
        return Page.SiteSurvey3;
    }
    
    public PageReference section4() {
        return Page.SiteSurvey4;
    }
    
    public PageReference section5() {
        return Page.SiteSurvey5;
    }
    
    public PageReference section6() {
        return Page.SiteSurvey6;
    }
    
    public PageReference section7() {
        return Page.SiteSurvey7;
    }
    
    public PageReference section8() {
        return Page.SiteSurvey8;
    }
    
    public PageReference section9() {
        return Page.SiteSurvey9;
    }
    
    public PageReference section10() {
        return Page.SiteSurvey10;
    }
    
    public PageReference save() {
        upsert survey;
        
        PageReference contPage = new PageReference('/' + survey.Id);
        contPage.setRedirect(true);
        return contPage;
    }
    
    // Return the user to the Site Survey tab
    public PageReference cancel() {
        PageReference contPage = new PageReference('/a0C/o');
        contPage.setRedirect(true);
        return contPage;
    }
    
    //
    // TEST METHOD
    //
    private static testMethod void testSiteSurvey() {
        Site_Survey__c survey = new Site_Survey__c();
        
        Account acc = new Account(Name='Test Region',RecordTypeId=[Select Id from RecordType where
                             SObjectType='Account' and Name like 'Internal%'].id);
        insert acc; 
        Account landlord = new Account(Name='Test landlord',Category__c='Landlord',RecordTypeId=[Select Id from RecordType where
                             SObjectType='Account' and Name like 'External%'].id);
        insert landlord;                    
        Account landlordagent = new Account(Name='Test landlord agent',Category__c='Landlord Agent',RecordTypeId=[Select Id from RecordType where
                             SObjectType='Account' and Name like 'External%'].id);
        insert landlordagent;
        Location__c loc = new Location__c(Name='Test Location',RecordTypeId=[Select Id from RecordType where SObjectType='Location__c' and Name Like 'Lease/License'].id,
                             Where__c=acc.Id, Landlord__c=landlord.Id, Landlord_Agent__c=landlordagent.Id);
        insert loc;
        
        PageReference pageRef = Page.SiteSurvey1;
        test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdCon = new ApexPages.StandardController(survey);
        SiteSurveyController cont = new SiteSurveyController(stdCon);
        
        cont.cancel();
        cont.getSurvey();
        
        cont.section1();
        cont.section2();
        cont.section3();
        cont.section4();
        cont.section5();
        cont.section6();
        cont.section7();
        cont.section8();
        cont.section9();
        cont.section10();
        
        cont.survey.Location__c = loc.Id;
        cont.save(); 
    }
}