src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <formula>IF( Record_Type_Name__c = &quot;InternalOrganisation&quot;,
IF( CONTAINS(Name, &quot;Locality&quot;) , Parent.Name ,
IF(CONTAINS(Name,&quot;Area&quot;), Name,
IF(CONTAINS(Name, &quot;Local Service Office&quot;), Parent.Parent.Name, &quot;&quot;)
))
,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Area</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/BDR__c.object
<CustomObject>
    <description>The entry point for a defined business relationship related to a set of service proposals, funding proposals and contracts. The BDR can be linked to multiple services, but at present only one Income Block.</description>
    <fields>
        <fullName>A2D_Locality__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A2D Locality</description>
        <inlineHelpText>Select the Locality</inlineHelpText>
        <label>Locality</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>BDR_Organisation__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Locality</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>BDR_Organisation__c</referenceTo>
        <relationshipLabel>BDRs</relationshipLabel>
        <relationshipName>BDRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actual_Value__c</fullName>
        <description>The actual value of the BDR. This is used to drive the delegated approval levels</description>
        <label>Actual Value</label>
        <summarizedField>Income_Block__c.Total_Amount__c</summarizedField>
        <summaryForeignKey>Income_Block__c.BDR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Area_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Who is the responsible ROM</inlineHelpText>
        <label>Regional Operations Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>Area Management</value>
            </filterItems>
            <infoMessage>Regional Operations Manager</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Business_Development_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <description>This uses the new A2D_Locality Table to derive Area, which represents the new A2D data. 

FOR REFERENCE :
This formula references the Org Table
IF( CONTAINS(Locality__r.Name, &quot;Locality&quot;) , Locality__r.Parent.Name , 
IF(CONTAINS(Locality__r.Name,&quot;Area&quot;), Locality__r.Name, 
IF(CONTAINS(Locality__r.Name, &quot;Region&quot;), Locality__r.Name, 
IF(CONTAINS(Locality__r.Name, &quot;Local Service Office&quot;), Locality__r.Parent.Parent.Name, 
&quot;&quot;))))</description>
        <formula>A2D_Locality__r.Area__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BDM</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>BDM</value>
            </filterItems>
            <infoMessage>Select the BDM or enter a different user name if none exists</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>BDRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BDR_Name__c</fullName>
        <description>The Name of the BDR</description>
        <inlineHelpText>The BDR name should begin with the Area abbreviation (see user guide), followed by the service name and then town or geographical area</inlineHelpText>
        <label>BDR Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_List__c</fullName>
        <description>An internal field that stores a single character for each component that is part of the BDR. Makes it easy to show which BDRs have which components in a list view</description>
        <label>Components</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HR_Implications__c</fullName>
        <inlineHelpText>Tick this box if any of these may apply:  Recruitment – will need to recruit staff and/or volunteer; Redundancy – may need to make redundancies (as described above), TUPE – a tender requires existing staff to transfer to a new provider</inlineHelpText>
        <label>HR Implications</label>
        <picklist>
            <picklistValues>
                <fullName>Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redundancy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TUPE</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Income_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Funder comes from the Organisations table.</description>
        <inlineHelpText>Use lookup box to choose appropriate potential funder. If the funder is not listed, save your BDR, then go to Organisations to add them. If no funding has been identified, leave blank.</inlineHelpText>
        <label>Income Source</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BDRs (Income Source)</relationshipLabel>
        <relationshipName>Business_Development_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intended_Start_Date__c</fullName>
        <description>The intended start date for the Income. This will be used to calculate the Financial Years</description>
        <inlineHelpText>Enter your best estimate of the Intended Start Date. (This will be used to calculate the Financial Years)</inlineHelpText>
        <label>Intended Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Locality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>zzArea or Locality</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <errorMessage>This organisation is not an area or locality</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Organisation</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>contains</operation>
                <value>Locality</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>contains</operation>
                <value>Area</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BDRs (Area or Locality)</relationshipLabel>
        <relationshipName>BDRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the business development record</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Value__c</fullName>
        <description>An estimate of the income required to fund the services</description>
        <inlineHelpText>Enter an estimate of the total income required to fund  all the services associated with the  BDR.</inlineHelpText>
        <label>Estimated Income Required</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>BDR</label>
    <nameField>
        <displayFormat>BDR-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BDR_Organisation__c.object
<CustomObject>
    <description>Allows BDCS application to manage A2D Organisations</description>
    <fields>
        <fullName>Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the Area</inlineHelpText>
        <label>Area</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>BDR_Organisation__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Area</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>BDR_Organisation__c</referenceTo>
        <relationshipLabel>Localities for this Area</relationshipLabel>
        <relationshipName>BDR_Org_Area</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Business Development Manager</description>
        <inlineHelpText>Select the Business Development Manager for the Region</inlineHelpText>
        <label>BDM</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Title</field>
                <operation>contains</operation>
                <value>Business Development Manager</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>BDR_Org_BDM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BDR Organisation</label>
    <nameField>
        <label>Organisation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BDR Organisations</pluralLabel>
    <recordTypes>
        <fullName>Area</fullName>
        <active>true</active>
        <description>Localities are grouped into Area</description>
        <label>Area</label>
    </recordTypes>
    <recordTypes>
        <fullName>Locality</fullName>
        <active>true</active>
        <description>Locality</description>
        <label>Locality</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <description>The Society Area to which the user is allocated (if any).</description>
        <inlineHelpText>Must match Name from corresponding Internal Organisation.</inlineHelpText>
        <label>Area</label>
        <picklist>
            <controllingField>Region__c</controllingField>
            <picklistValues>
                <fullName>Central West Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Anglia and Central Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Midlands Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North &amp; East Northern Ireland Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North East Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North Wales Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North West Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South &amp; West Northern Ireland Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South East Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Wales Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South West Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West Midlands Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Whole Wales Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yorkshire Area</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BDRSearchController.cls
public with sharing class BDRSearchController {
 
   /***********************************************************************************************************
    *
    *   @author      :    valerie.dunphy@conseq.co.uk
    *   @date        :     June 2014
    *
    *   @description :  Find BDRs using a set of filter fields for BDR_Search.page
    *   
    ************************************************************************************************************/
 
  // The soql without the order and limit
  transient private String soql {get;set;}
  
  // List of BDR Ids for BDRs pending approval by a selected user
   private List<String> lisObjectIds {get;set;}
  

  // Fields used for applying filters to the results    
  public String ref {get;set;}
  public String bdr_name {get;set;}

  public String locality {get;set;}
  public String income_source {get;set;}
  public String bdm_name {get;set;}
  public String owner {get;set;}

  public String status {get;set;}
  public String approver_name {get;set;}
  public String area {get;set;}

  public Integer resultsCount  {get;set;}
  public Integer filterCount {get;set;}          /* How many filter fields have been used */
  public boolean filtersSelected  {get;set;}
  
  public String filterMessage {get;set;}
  
  /*
   *  Get the number of BDRs Pending Approval by the current user if any
   */
  public Integer getPendingApprovalCount() {     
            return CustomUtils.getObjectIdsPendingApprovalbyUserId(UserInfo.getUserId(), 'BDR__c').size();      
  }
  

  
  /** Generate the URL for creating a new BDR__c object */ 
  public String getCreateUrl() {   
              Schema.DescribeSObjectResult o = BDR__c.SObjectType.getDescribe();
              PageReference pr = new PageReference('/' + o.getKeyPrefix() + '/e');         
              return pr.getUrl();
   }
  
  /** The list of BDR Search Wrapper objects returned by the query */
  public List<BdrSearchWrapper> lisBDR
  {
    get {
            if (lisBDR == null) lisBDR = new List<BDRSearchWrapper>();
            return lisBDR;
        }
        set;
  }      
  
    
  /** The current sort direction. Defaults to desc as most people want to see the new ones first */
  public String sortDir {
    get  { 
        if (sortDir == null) {  
            sortDir = 'desc'; 
        } 
        return sortDir;  
        }
    set;
  }
 
  /** The current field to sort by. Defaults to Created Date */
  public String sortField {
    get  { if (sortField == null) {sortField = 'CreatedDate'; } return sortField;  }
    set;
  }
 

 
  /** Constructor.  */
  public BDRSearchController() {
    
    // This is just called the first time the page loads with no filters
    // Otherwise the search is called using runApexSearch
       	runQuery();
  }
  
    
  private void sendDebugMail(String subject, String body) {
  	Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

	// Strings to hold the email addresses to which you are sending the email.
	String[] toAddresses = new String[] {'valerie.dunphy@conseq.net'}; 
	mail.setToAddresses(toAddresses);
	mail.setSenderDisplayName('Salesforce Testing');
	mail.setSubject('Searching for '+subject);
	
	mail.setUseSignature(false);
	mail.setPlainTextBody(body);
	
	Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
  }
 
  /** Toggles the sorting of query from asc<-->desc */
  public void toggleSort() {

    sortDir = sortDir.equals('asc') ? 'desc' : 'asc';        
    runQuery();     // Run the query again

  }

  
  private String escapeSQ(String field) {
  	return String.escapeSingleQuotes(field);
  }
 
  /** Run the query */
  private void runQuery() {

    generateQueryString();
    lisBDR = new List<BDRSearchWrapper>(); 
    
    try {
        List<BDR__c> lisResults = Database.query(soql);   
        for (BDR__c bdr : lisResults) {
        	lisBdr.add(new BdrSearchWrapper(bdr));        	
        }  
        
    } catch (Exception e) {

      String sMsg = e.getMessage();  
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, sMsg ));
    }
    finally { resultsCount = lisBdr.size();
    	 }
 
  }
  
    
    /** Generate the soql query string using the base query and adding clauses for the  user selected filters */ 
  private void generateQueryString()
  {
  
   soql = 'select Id, ' +
                'Name, ' +
                'Bdr_Name__c,' + 
                'Status__c, ' +
                'A2D_Locality__r.Name,' + 
                'Owner.Name, ' +
                'BDM__c, ' +
                'BDM__r.Name,' +
                'Total_Value__c,' +           // Actual_Value__c
                'Actual_Value__c,' +    
                'Intended_Start_Date__c,'+
                'CreatedDate,'+
                'Component_List__c, ' +
                'HR_Implications__c '+
                
                'from BDR__c where Name != null';
                


    if (!String.isEmpty(ref))  soql += ' and Name LIKE \'%'+escapeSQ(ref)+'%\'';

    if (!String.isEmpty(bdr_name))  soql += ' and BDR_name__c LIKE \'%'+escapeSQ(bdr_name)+'%\'';

    if (!String.isEmpty(bdm_name))  soql += ' and BDM__c = \''+escapeSQ(bdm_name)+'\'';
      
    if (!String.isEmpty(owner))  soql += ' and OwnerId = \''+ owner +'\'';

    if (!String.isEmpty(locality)) soql += ' and A2D_Locality__c = \''+locality+'\'';
         
    if (!String.isEmpty(income_source)) soql += ' and Income_Source__c = \''+income_source+'\'';

    if (!String.isEmpty(status)) soql += ' and Status__c = \''+escapeSQ(status)+'\'';  
    
    if (!String.isEmpty(approver_name)) {
        lisObjectIds = CustomUtils.getObjectIdsPendingApprovalbyUserId(approver_name, 'BDR__c');      
        soql += ' and Id in : lisObjectIds';
    } 
    
    soql += ' order by ' + sortField + ' ' + sortDir + ' limit 200';

  }
 

  
   public List<SelectOption> getBDMs() { 
  	  
		  List<SelectOption> options = new List<SelectOption>();
		  
		  String sLabel, sLastName = '';   		    

		  List<User> BDMs =
		  [ Select  Id, FirstName, LastName, (select Name from BDRs__r) FROM User WHERE Id in (select BDM__c FROM BDR__c ) order by LastName];
    
    	  options.add(new SelectOption('',''));	
          for (User U : BDMs) {
               sLastName = U.LastName.replaceAll('\\(BDM\\)', '').trim();
               sLabel = sLastName + ', ' +U.FirstName + '  (' + U.BDRs__r.size() +')';
               options.add(new SelectOption(U.Id, sLabel));
          }
          return options; 
  }
  

     public List<SelectOption>  getStatusOptions() { 
  	  
		  List<SelectOption> options = new List<SelectOption>();   		
		      
		  options.add(new SelectOption('','')); 
		  AggregateResult[] results = [ Select  Status__c, Count(Name) FROM  BDR__c  group by Status__c ];
			
      		for (AggregateResult ar : results)  {
      			 String val =   String.valueof( ar.get('Status__c'));
      			 String label = val + ' ('+String.valueof(ar.get('expr0')) + ')';
      			 options.add(new SelectOption(val, label));
		}
          return options; 
  }
  
  public List<SelectOption>  getLocalities() { 
  	  
		  List<SelectOption> optionList = new List<SelectOption>();   		    

		  List<BDR_Organisation__c> localities =
		  [ Select  Id, Name, (select Name from BDRs__r) FROM BDR_Organisation__c WHERE Id in (select A2D_Locality__c FROM BDR__c ) order by Name];
    
    	  optionList.add(new SelectOption('',''));	
    	  
          for (BDR_Organisation__c O : localities) {
               String sLabel = O.Name + ' (' + O.BDRs__r.size() +')';
               optionList.add(new SelectOption(O.Id, sLabel));
          }
          return optionList; 
  }
  
  
    public List<SelectOption>  getAreas() { 
  	  
		  List<SelectOption> options = new List<SelectOption>();   		  
		  List<BDR__c> lisAreas = [select Area__c FROM BDR__c];
		  
		  Set<String> stAreaNames= new Set<String>();
		  for (BDR__c org : lisAreas) {
		  	stAreaNames.add(org.Area__c);		  	
		  }
		  
		  List<String> lisAreaNames = new List<String>();
		  lisAreaNames.addAll(stAreaNames);
		  
		  List<BDR_Organisation__c> areas =
		  [ Select  Id, Name, (select Name from BDRs__r) FROM BDR_Organisation__c 
		  WHERE Name in :lisAreaNames order by Name];
    
    	  options.add(new SelectOption('',''));	
    	  
          for (BDR_Organisation__c O : areas) {
               String sLabel = O.Name + ' (' + O.Bdrs__r.size() +')';
               options.add(new SelectOption(O.Name, sLabel));
          }
          return options; 

  }
  

  
  
  public Integer getBDRCount() {
  	return [ SELECT COUNT() FROM BDR__c ];
  	
  }
  
  public Integer getSearchResultsCount() {
  	return lisBDR.size();
  }
  
  public List<SelectOption>  getIncomeSources() { 
  	  
		  List<SelectOption> options = new List<SelectOption>();   		    

		  List<Account> income_sources =[ Select  Id, Name, (select Name from Business_Development_Records__r)  FROM Account WHERE Id in (select income_Source__c FROM BDR__c ) order by Name];
    
    	  options.add(new SelectOption('',''));	
    	  
          for (Account A : income_sources) {
          	   String sourceName = A.Name;
          	   
          	   if (sourceName.length()>40) {
          	   	   sourceName = sourceName.subString(0,40);
          	   }
               String sLabel = sourceName + ' (' + A.Business_Development_Records__r.size() +')';
               options.add(new SelectOption(A.Id, sLabel));
          }
          return options; 

  }
  

  
  public List<SelectOption>  getApprovers() { 
  	  
		  return CustomUtils.getPendingApproversForObjectType('BDR__c'); 
  }
  
  
    public List<SelectOption>  getOwners() { 
      
      List<SelectOption> options = new List<SelectOption>();   
        
      List<User> Owners =[ Select  Id, Name, FirstName, LastName FROM User WHERE Id in (select OwnerId FROM BDR__c ) order by LastName];
        List<AggregateResult> BDRs = [select count(BDR__c.Name), BDR__c.OwnerId from BDR__c group by BDR__c.OwnerId];  
    
        Map<String, String> mapBDRs = new Map<String, String>();  
        for (AggregateResult ar : BDRs) {
            mapBDRs.put(String.valueOf(ar.get('OwnerId')), String.valueOf(ar.get('expr0'))); 
        }  
    
        options.add(new SelectOption('',''));  
          for (User U : Owners) {
        
          String sLastName = U.LastName.replaceAll('\\(BDM\\)', '').trim();
          String sLabel = sLastName + ', '+U.FirstName + ' (' + mapBDRs.get(U.Id) + ')';   
            options.add(new SelectOption(U.Id, sLabel));
          }
          return options; 

  }   
 
  /** Run the search with parameters passed as Querystring parameters */
  public PageReference runApexSearch() { 
  	
  	//Map of PageParameters 
    Map<string,string> pageParams=ApexPages.currentPage().getParameters();
    
    ref = pageParams.get('ref');
    bdr_name = pageParams.get('bdr_name');  
    locality = pageParams.get('locality');
    bdm_name = pageParams.get('bdm_name');
    income_source = pageParams.get('income_source');
    owner = pageParams.get('owner');
    approver_name = pageParams.get('approver_name');
    status = pageParams.get('status');

     filterCount = 0;
    
     if (!String.isEmpty(ref)) { filterCount++; } 
     
     if (!String.isEmpty(bdr_name)) filterCount++; 
     if (!String.isEmpty(bdm_name)) filterCount++; 
     if (!String.isEmpty(owner)) filterCount++; 
     if (!String.isEmpty(locality)) filterCount++; 
     if (!String.isEmpty(income_source)) filterCount++; 
     if (!String.isEmpty(status)) filterCount++; 
     if (!String.isEmpty(approver_name)) filterCount++; 
     
    // Run the query again
    runQuery();
    
    if (filterCount>0) {
     	 filtersSelected = true;
     	 
     	 filterMessage = resultsCount +' BDRs match your selected filters';
     	
     } else
         filterMessage = '';
 
    return null;
  }
  

  /* The search returns a list of BDRs wrapped in a BDRSearchWrapper 
  
  	 Not Used : The wrapper property isSelected enables BDRs to be selected in the list view
     using a checkbox and have some action applied them from a button on the search page
  */   
  public class BdrSearchWrapper
  {
  	
			   public BDR__c bdr {get; set;}
			
			   public String getHR() {
			   	   if (bdr.HR_Implications__c !=null && bdr.HR_Implications__c!='') {
			   	   		return ('&#10004;');
			   	   }
			   	   else return '';
			   }	
			//  	public boolean isSelected {get;set;}
			  	
			 
			  	
			  	public BdrSearchWrapper(BDR__c bdr)
			  	{
			  		this.bdr=bdr;
			 // 		isSelected=false;
			  	}
  	
  }    
  
}