src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AreaLookup__c</fullName>
        <label>AreaLookup</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <formula>IF( Record_Type_Name__c = &quot;InternalOrganisation&quot;,
IF( CONTAINS(Name, &quot;Locality&quot;) , Parent.Name ,
IF(CONTAINS(Name,&quot;Area&quot;), Name,
IF(CONTAINS(Name, &quot;Local Service Office&quot;), Parent.Parent.Name, &quot;&quot;)
))
,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Clinical_Commissioning_Group__c</fullName>
        <label>Clinical Commissioning Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Constituency_Derived__c</fullName>
        <description>Used on Record Types PWD and Carer to hold the Constituency derived from Postcode lookup.</description>
        <label>Postcode Constituency</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_authority__c</fullName>
        <label>Postcode Local Authority</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_care_trust__c</fullName>
        <label>Postcode Primary Care Trust</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organisation Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ward__c</fullName>
        <label>Postcode Ward</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>InternalOrganisation</fullName>
        <active>true</active>
        <description>Use this record type for AS organisational units, local services, area, region, directorate etc</description>
        <label>Internal Organisation</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LastTransactionDateLookup__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>lastTransactionDate__c</fullName>
        <label>lastTransactionDate</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>LastTransactionDateLookup</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LastTransactionDateLookups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>old Area</label>
        <picklist>
            <controllingField>Region__c</controllingField>
            <picklistValues>
                <fullName>Central West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Anglia and Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Midlands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lakes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North and East Northern Ireland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North Wales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South and West Northern Ireland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Wales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West Midlands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yorkshire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Anglia &amp; Central Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Midlands Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South East Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South &amp; West NI Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North &amp; East NI Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North East Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yorkshire Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lakes Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North West Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Wales Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North Wales Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central West Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South West Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West Midlands Area</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Clinical_Commissioning_Group__c</fullName>
        <label>Clinical Commissioning Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode_Constituency__c</fullName>
        <label>Postcode Constituency</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode_Local_Authority__c</fullName>
        <label>Postcode Local Authority</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode_Primary_Care_Trust__c</fullName>
        <label>Postcode Primary Care Trust</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode_Ward__c</fullName>
        <label>Postcode Ward</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AccountTriggerHandler.cls
public with sharing class AccountTriggerHandler {
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : APEX Handler Class contains the execution logic of the Accounts Trigger.
 *  Author  : Mike Tinson
 *  Date    : 13-02-2014
 *  Version : 0.1 Unit Test
 *
 *  Description:    Apex Class calls the LastTransactionDateLookup Apex Class to update the 
 *                  lastTransactionDate__c field for the Accounts Record.
 *               
 *  Modification History
 *  Date            Who                     Description 
 * 15/10/2014      Lakshmi Rajendram        populate Address on internal orgs from property
 *                             
*******************************************************************************************/

    private boolean m_isExecuting = false;
    private integer BatchSize = 0;
    
    public AccountTriggerHandler (boolean isExecuting, integer size){
        m_isExecuting = isExecuting;
        BatchSize = size;
    }

    public void OnAfterInsert(Account[] NewAccounts, Map<ID, Account> AccountsMap){
        System.debug('****** AccountTriggerHandler.OnAfterInsert  ******');
        
        
        UpdateLastTransactionDate(NewAccounts);
    }   
 

    
    public void OnAfterUpdate(Account[] oldAccounts, Account[] updatedAccounts, Map<ID, Account> AccountsMap){
        System.debug('****** AccountsTriggerHandler.OnAfterUpdate  ******');
        //adding a comment
        UpdateLastTransactionDate(updatedAccounts);
    }



    public void OnAfterDelete(Account[] oldAccounts, Map<ID, Account> AccountsMap){
    
        System.debug('****** AccountsTriggerHandler.OnAfterDelete  ******');
        
        UpdateLastTransactionDate(oldAccounts);
    }
     
    public void emptyMethod() {}
    public void abstract emptyAbstract();
    public void virtual emptyVirtual(){}
     
    Public void OnBeforeUpdate(Account[]  updatedAccounts){
    
    Id InternalAccount;
    
    InternalAccount = [select Id from RecordType where SObjectType = 'Account' and DeveloperName ='InternalOrganisation'].Id;
    
    Set<ID> setLocIds = new Set<ID>();
    for (Account na:updatedAccounts) {
        if (na.Property__c != NULL && (na.RecordTypeId == InternalAccount)){
       
         setLocIds.add(na.Property__c);
          }
       
       }
         
      MAP<ID , Location__c> maploc = new MAP<ID , Location__c>([select Postcode__c, Street__c, City__c, County__c, Country__c,Postcode_Constituency__c,Postcode_Local_Authority__c,Postcode_Primary_Care_Trust__c,Postcode_Ward__c,Clinical_Commissioning_Group__c from Location__c where id in: setLocIds]);
            for (Account na:updatedAccounts) {
             if (na.Property__c != NULL && (na.RecordTypeId == InternalAccount)){

           Location__c loc = maploc.get(na.Property__c);

                na.BillingPostalCode = loc.Postcode__c;
                na.BillingStreet = loc.Street__c;
                na.BillingCity = loc.City__c;
                na.BillingState = loc.County__c;
                na.BillingCountry = loc.Country__c;
                na.Constituency_Derived__c = loc.Postcode_Constituency__c;
                na.Local_authority__c      = loc.Postcode_Local_Authority__c;
                na.Primary_care_trust__c = loc.Postcode_Primary_Care_Trust__c;
                na.Ward__c = loc.Postcode_Ward__c;
                na.Clinical_Commissioning_Group__c = loc.Clinical_Commissioning_Group__c;
                na.AreaLookup__c = na.Area__c;   
                
                }   
            }
        
    }
    
  
         
        
        
    public boolean IsTriggerContext{
        get{ return m_isExecuting;}
    }

public void UpdateLastTransactionDate(Account[] updatedSUs){
    System.debug('****** UpdateLastTransactionDate ******');
    List<Id> SUIds = new List<Id>();
    Datetime dtLastTransactionDate = datetime.now();
    
    for(Account df: updatedSUs){
        SUIds.add(df.Id);
    }
    System.debug('****** SUIds.Size ******' + SUIds.Size());

    if(SUIds.isEmpty() == false){
      
      //Call Apex Class to populate LastTransactionDateLookup__c Object passing a RecordId and current DateTime. 
      LastTransactionDateLookup handler = new LastTransactionDateLookup();
      handler.UpdateLastTransactionDate(SUIds[0], dtLastTransactionDate); 
      
        }
    
    }
}