src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Local_authority__c</fullName>
        <label>Postcode Local Authority</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_care_trust__c</fullName>
        <label>Postcode Primary Care Trust</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>$RecordType.DeveloperName</formula>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ward__c</fullName>
        <label>Postcode Ward</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Constituency__c.object
<CustomObject>
    <label>Constituency</label>
    <nameField>
        <label>Constituency</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Constituencies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Constituency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Constituency</label>
        <referenceTo>Constituency__c</referenceTo>
        <relationshipLabel>MPs</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth_Estimated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Date of Birth Estimated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Diagnosis__c</fullName>
        <inlineHelpText>Only to be used for CONFIRMED diagnosis of dementia.</inlineHelpText>
        <label>Dementia diagnosis</label>
        <picklist>
            <picklistValues>
                <fullName>Alzheimer’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Binswanger’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia with Lewy bodies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Down’s syndrome related dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fronto-Temporal dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HIV related dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huntington’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korsakoff’s syndrome</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixed dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parkinson’s disease related dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pick’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prion disease including CJD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vascular dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None - Awaiting Diagnosis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None - Other Mild Cognitive Impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (please list)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mild Cognitive Impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Local_authority__c</fullName>
        <label>Postcode Local Authority</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_care_trust__c</fullName>
        <label>Postcode Primary Care Trust</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>$RecordType.DeveloperName</formula>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ward__c</fullName>
        <label>Postcode Ward</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Collector</fullName>
        <active>true</active>
        <description>Volunteer Collector for Fundraising</description>
        <label>Collector</label>
    </recordTypes>
    <recordTypes>
        <fullName>Former_MP</fullName>
        <active>true</active>
        <description>External Affairs</description>
        <label>Former MP</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lord</fullName>
        <active>true</active>
        <description>Member of the House of Lords</description>
        <label>Lord</label>
    </recordTypes>
    <recordTypes>
        <fullName>MP</fullName>
        <active>true</active>
        <description>Member of Parliament</description>
        <label>MP</label>
    </recordTypes>
    <recordTypes>
        <fullName>Member_of_NI_Legislative_Assembly</fullName>
        <active>true</active>
        <description>Member of NI Legislative Assembly</description>
        <label>Member of NI Legislative Assembly</label>
    </recordTypes>
    <recordTypes>
        <fullName>Member_of_Welsh_Assembly</fullName>
        <active>true</active>
        <description>Member of Welsh Assembly</description>
        <label>Member of Welsh Assembly</label>
    </recordTypes>
    <recordTypes>
        <fullName>Peer</fullName>
        <active>true</active>
        <description>Member of the House of Lords</description>
        <label>Peer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <description>Health, Social Care and other professionals</description>
        <label>Professional / Stakeholder</label>
    </recordTypes>
    <recordTypes>
        <fullName>Volunteer</fullName>
        <active>true</active>
        <description>Volunteers for Group Events</description>
        <label>Volunteer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/listContacts.cls
public with sharing class listContacts {
    public ApexPages.StandardController stdController;
    public List<Contact> lstMatchingContacts {get;set;}
    private Contact person;
    private String lastName;
    private String firstName;
    private String postalcode;
    private String recordTypeName;
    private Id organisationId;
    private Contact c1;
    public Boolean canMerge {get;set;}
    public Boolean showBirthDate {get;set;}
    
// Standard controller constructor.
    public listContacts (ApexPages.StandardController pController) {
        stdController = pController;
        person =  [select id, LastName, FirstName, MailingPostalCode, BirthDate, Record_Type_Name__c, AccountId from Contact where id = :ApexPages.currentPage().getParameters().get('id')];
        system.debug('@@@@@@@@@@@@@@@'+person.id);
        lastName = person.LastName;
        firstName = person.FirstName;
        postalcode = person.MailingPostalCode;
        recordtypeName = person.Record_Type_Name__c;
        organisationId = person.AccountId;
        system.debug('@@@@@@@@@@@@@@@lastname  '+lastname);
        system.debug('@@@@@@@@@@@@@@@firstname '+firstname);
        system.debug('@@@@@@@@@@@@@@@postalcode'+postalcode );
        system.debug('@@@@@@@@@@@@@@@Birthdate '+Person.BirthDate );
        canMerge = Contact.sObjectType.getDescribe().isDeletable();
    }

public PageReference AutoRunListContacts(){ 
    lstMatchingContacts = new List<Contact>();
    Set<Id> contactIds = new Set<Id>();
    DeDuper objDeDuper = new DeDuper();
    if ((lastName =='*****') && (firstName=='*****')){ 
        return null;}
    else {
         if ((recordTypeName == 'Professional')
             ||(recordTypeName=='MP')
             ||(recordTypeName=='Former_MP') 
             ||(recordTypeName=='Peer')
             ||(recordTypeName=='Lord')
             ||(recordTypeName=='Peer')
             ||(recordTypeName=='Member_of_NI_Legislative_Assembly')
             ||(recordTypeName=='Member_of_Welsh_Assembly')
             ||(recordTypeName=='Volunteer')
             ||(recordTypeName=='Collector')
             ){
             contactIds = objDeDuper.SearchProfessionals(lastName, organisationId );
             lstMatchingContacts  = [SELECT id, Name, Email, Record_Type_Name__c, LastName, FirstName,  RecordTypeId, Diagnosis__c, MailingStreet, MailingState, MailingPostalCode, MailingCountry, MailingCity, Phone, Birthdate, Ward__c, Date_of_Birth_Estimated__c,  Primary_care_trust__c, Local_authority__c, Constituency__c, Salutation 
                                     from Contact where id =:contactIds and id != :person.id ];
             showBirthDate=false;}
         else {
                lstMatchingContacts = objDeDuper.SearchNonProfessional(person, lastName, firstName, person.birthdate, PostalCode);
                showBirthDate =true;
             }
         }
    return null;
    }
    
//Test script for code coverage.
public testMethod static void testController()
{
    Contact con1 = new Contact(Salutation='Mr',FirstName='Abc',LastName='Test1',MailingPostalCode ='ABC123', Birthdate =Date.Today(),
        RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and name like 'Person with dementia%'].id);
    insert con1;
    Account accRec = new Account(Name='External Test Org1',BillingPostalCode='SW1A 2AA',RecordTypeId=[Select Id from RecordType where SObjectType='Account' and Name like 'External%'].id);
    insert accRec;
    Contact con2 = new Contact(Salutation='Mr',FirstName='Abc',LastName='ProTest1',MailingPostalCode ='ABC123', Birthdate =Date.Today(),
        AccountId = accRec.id,
        RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and name like 'Professional%'].id);
    insert con2;
    ApexPages.currentPage().getParameters().put('Id', con1.id);        
    listContacts conCls= new listContacts (new ApexPages.StandardController(con1));
    conCls.AutoRunListContacts();
    //now test professionals
    ApexPages.currentPage().getParameters().put('Id', con2.id);
    listContacts conCls2= new listContacts (new ApexPages.StandardController(con2));
    conCls2.AutoRunListContacts();
 
}    
}