src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Completion_Date_Task__c</fullName>
        <description>The actual date on which the task was completed.</description>
        <label>Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Worker Availability to be confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service User Availability to be confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Society</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Service User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Third party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be reassigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be rescheduled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_Outcomes__c</fullName>
        <inlineHelpText>This refers to the Outcome No on Support plan of the Service Usage</inlineHelpText>
        <label>Outcome No(s)</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Client_reference_number__c</fullName>
        <description>System generated unique reference number across all People.</description>
        <displayFormat>P{00000000}</displayFormat>
        <externalId>true</externalId>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Deceased__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>To set a person as deceased please use the Person Wizard.</inlineHelpText>
        <label>Deceased?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event_Attendance_Details__c.object
<CustomObject>
    <fields>
        <fullName>Attendance_Status__c</fullName>
        <label>Attendance Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event_Date_and_Time__c</fullName>
        <label>Event Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Subject__c</fullName>
        <label>Event Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Outcome_No_s__c</fullName>
        <label>Outcome No(s)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Service_Usage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Usage</label>
        <referenceTo>Service_Usage__c</referenceTo>
        <relationshipLabel>Attendance Details</relationshipLabel>
        <relationshipName>Event_Attendance_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Attendance Details</label>
    <nameField>
        <displayFormat>EA-{0000000000}</displayFormat>
        <label>EventAttendeeTiming Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendance Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Usage__c.object
<CustomObject>
    <fields>
        <fullName>Client_reference_number__c</fullName>
        <formula>Primary_Service_User__r.Client_reference_number__c</formula>
        <label>Person ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Service_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service User</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 OR 2) AND ((3 AND 4) OR (5 AND 6) OR 7 OR 8)</booleanFilter>
            <errorMessage>For Day care &amp; support and Community support Services, Service User must be a living Person with Dementia. For other services Service User can also be a Carer of a Person with Dementia. Newsletter is available to all.</errorMessage>
            <filterItems>
                <field>Contact.Deceased_Date__c</field>
                <operation>greaterThan</operation>
                <valueField>$Source.Referral_Date__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.Deceased__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Type__c</field>
                <operation>equals</operation>
                <value>Community support service, Day care and support (establishment based), Registered home care and support</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person with Dementia</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Type__c</field>
                <operation>equals</operation>
                <value>Activity group, Dementia adviser, Dementia support, Dementia cafe, Information programme, Other (one to one), Peer support group, Singing for the Brain, Befriending, Advocacy</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Carer of Person with Dementia, Person with Dementia</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Type__c</field>
                <operation>equals</operation>
                <value>Newsletter</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outgoing Referral</value>
            </filterItems>
            <infoMessage>For Day care &amp; support and Community support Services, Service User must be a living Person with Dementia. For other services Service User can also be a Carer of a Person with Dementia. Newsletter is available to all.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Usage</relationshipLabel>
        <relationshipName>Service_Usage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <description>The type of Service to which Service Usage relates.
Used as a filter when selecting Service.
Used to set Record Type on saving a new Service Usage.</description>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (one to one)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peer support group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered home care and support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singing for the Brain</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Usage</label>
    <nameField>
        <label>Service Usage Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Usage</pluralLabel>
    <recordTypes>
        <fullName>Advocacy</fullName>
        <active>true</active>
        <description>Used for all Advocacy Referrals and Cases</description>
        <label>Advocacy</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>Locality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Locality in which this service is based (left blank for national services).</description>
        <label>Locality</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select an Alzheimer&apos;s Society Locality.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Organisation</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>contains</operation>
                <value>Locality</value>
            </filterItems>
            <infoMessage>Please select a Locality.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Services_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>Internal Service/Activity</description>
        <label>Internal Service</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Locality__c</fullName>
        <description>The Society Locality to which the user is assigned (if any).</description>
        <inlineHelpText>Must match the Name of the corresponding Internal Organisation.</inlineHelpText>
        <label>Locality</label>
        <picklist>
            <controllingField>Area__c</controllingField>
            <picklistValues>
                <fullName>Abertawe Bro Morgannwg Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avon, Gloucestershire &amp; Wiltshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bedfordshire &amp; Luton Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Berkshire, Buckinghamshire, Oxfordshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambridgeshire &amp; Peterborough Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiff and the Vale Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheshire &amp; St Helens Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cumbria Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cwm Taff Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Darlington &amp; Teesside Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Derbyshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Devon, Cornwall &amp; Isles of Scilly Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dorset &amp; Somerset Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durham Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Riding &amp; Humber Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Essex Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Manchester Central &amp; West Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Manchester Central South and East Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gwent Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hampshire, Isle of Wight and the Channel Islands Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Herefordshire &amp; Worcestershire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hertfordshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent &amp; Medway Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lancashire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leicestershire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lincolnshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merseyside &amp; Isle of Man Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Midlands Central Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norfolk Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North &amp; East Northern Ireland Locality</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ServiceUsageRelatedActivitiesController.cls
/******************************************************************************************
 *  Alzheimer's
 *  
 *  Purpose : Provide methods to be called from Visual Force Pages.
 *  Author  : Saaspoint - Mohammed Irfan
 *  Date    : 2011-12-08
 *  Version : 0.1 Unit Tested
 *  Project : 
 *  Copyright (c) Saaspoint 2011 as per Master Services Agreement
 *
 *  Description: VF Controller with Various method handlers for VF.
 *        1) ServiceUsageRelatedActivities
 *
 *  Modification History
 *
 *  Date         Who    Description 
 *  yyyy-mm-dd - XX -   xxxxxxxxxxxxxxxxxxxxxxxxxxxx
 *  2012-07-04 - MT -   Events should return StartTime not completion date.
 *  2012-10-08 - VA -   Updated Activity history PDF to display the Event/Task Status and Outcome Number.
 *  2012-10-09 - VA -   Updated Description field to display 255 charecters, It was 100 earlier.
*   2013-07-23  MT   Updated Description field to display 32000 charecters, It was 255 earlier.
*******************************************************************************************/
public class ServiceUsageRelatedActivitiesController
{
public Service_Usage__c recSU {get;set;}
public List<ActivityInnerClass> lstActivities {get;set;}
public Integer CHARS_TO_SHOW {get{return 32000;}}
public string sortDirection {get;set;}
public Contact person {get; set;}

//Contructor
public ServiceUsageRelatedActivitiesController(ApexPages.StandardController controller) {
        recSU = (Service_Usage__c)controller.getRecord();
        lstActivities = new List<ActivityInnerClass>();
        sortDirection='ASC';
        
        getPersonDetails();
        
        //Populate list with all Events where date is in the past for a SU.
        for(Event eveRec: [Select Subject,StartDateTime, ActivityDate,Description,Owner.Name,Event_Status__c,Related_Outcomes__c from Event where WhatId=:recSU.id and ActivityDate<=TODAY  AND IsDeleted = false ALL ROWS ])
        {
            ActivityInnerClass tmpRec = new ActivityInnerClass();
            tmpRec.recId=eveRec.Id;
            tmpRec.Subject =eveRec.Subject;
            tmpRec.ActivityDate=eveRec.ActivityDate;
            tmpRec.CompletionDate=eveRec.StartDateTime;
            tmpRec.Description=eveRec.Description;
            tmpRec.OwnerName=eveRec.Owner.Name;
            tmpRec.Status=eveRec.Event_Status__c;
            tmpRec.isEventType=true;
            tmpRec.OutcomeNumber=eveRec.Related_Outcomes__c;
            tmpRec.isElipsesOn=(eveRec.Description!=null)?(eveRec.Description.length()>CHARS_TO_SHOW):false;
            
            lstActivities.add(tmpRec);
            
        }
        
        //Populate list with all completed Task records for a SU.
        for(Task tskRec: [Select Subject,Completion_Date_Task__c,ActivityDate,Status, Description,Owner.Name,Related_Outcomes__c from Task where WhatId=:recSU.id and Status='Completed'  AND IsDeleted = false ALL ROWS  ])
        {
            ActivityInnerClass tmpRec = new ActivityInnerClass();
            tmpRec.recId=tskRec.Id;
            tmpRec.Subject =tskRec.Subject;
            tmpRec.ActivityDate=tskRec.ActivityDate;
            tmpRec.CompletionDate=tskRec.Completion_Date_Task__c;
            tmpRec.Description=tskRec.Description;
            tmpRec.OwnerName=tskRec.Owner.Name;
            tmpRec.Status=tskRec.Status;
            tmpRec.isEventType=false;
            tmpRec.OutcomeNumber=tskRec.Related_Outcomes__c;
            tmpRec.isElipsesOn=(tskRec.Description!=null)?(tskRec.Description.length()>CHARS_TO_SHOW):false;//?tskRec.Description.length()>10:false;
            
            lstActivities.add(tmpRec);

        }
        
        //Populate list with all EAD records Events scheduled for a SU and AcitivityDate is in Past.
        for(Event_Attendance_Details__c EADRec: [Select Event_Subject__c,Notes__c,Owner.Name,Attendance_Status__c,Event_Date_and_Time__c,Outcome_No_s__c from 
            Event_Attendance_Details__c where Service_Usage__c=:recSU.id and Event_Date_and_Time__c<=TODAY  AND IsDeleted = false ALL ROWS  ])
        {
            ActivityInnerClass tmpRec = new ActivityInnerClass();
            tmpRec.recId=EADRec.Id;
            tmpRec.Subject =EADRec.Event_Subject__c;
            tmpRec.ActivityDate=EADRec.Event_Date_and_Time__c;
            tmpRec.Description=EADRec.Notes__c;
            tmpRec.OwnerName=EADRec.Owner.Name;
            tmpRec.Status=EADRec.Attendance_Status__c;
            tmpRec.OutcomeNumber=EADRec.Outcome_No_s__c;
            tmpRec.isEventType=true;
            tmpRec.isElipsesOn=(EADRec.Notes__c!=null)?(EADRec.Notes__c.length()>CHARS_TO_SHOW):false;
            
            lstActivities.add(tmpRec);        
        }
        
system.debug('#######Before lstActivities#####'+lstActivities);        
        lstActivities=sortList(lstActivities);
system.debug('#######After lstActivities#####'+lstActivities);
    }
    
    public Contact getPersonDetails(){
        //get the person Id
        Service_Usage__c tempSU = [select id, Primary_Service_User__c from Service_Usage__c where id =:recSU.Id];
        if(tempSU.Primary_Service_User__c!=null) person = [select id, Client_reference_number__c from Contact where id=:tempSU.Primary_Service_User__c];
        return person;
    }

//Sorting the List by Date Chronologically.
private List<ActivityInnerClass> sortList(List<ActivityInnerClass> lstActivities)
{
        if(lstActivities.size()==0)
                return null;
        
        Map<DateTime,DateTime> mapUniqDates = new map<DateTime,DateTime>();
        
        //Prepare a Map with unique Activity date
        for(ActivityInnerClass rec: lstActivities)
        {
            if(!mapUniqDates.containsKey(rec.ActivityDate))
                mapUniqDates.put(rec.ActivityDate,rec.ActivityDate);  
        }
system.debug('##########mapUniqDates##############'+mapUniqDates);        

        //If Dates are found for sorting.
        if(mapUniqDates.keySet().size()>0)
        {
            List<DateTime> lstUniqueDates = mapUniqDates.values();
            
            //Sort the Dates List
            lstUniqueDates.sort();
            List<ActivityInnerClass> lstTmpActRecs = new List<ActivityInnerClass>();

            //If sorting direction is ASC
            if((sortDirection.equalsIgnoreCase('ASC')))
            {
                //Iterate and prepare list.
                for(Integer i=0;i<lstUniqueDates.size();i++)
                {
                    for(ActivityInnerClass rec:lstActivities)
                    {
                        //To add all Acitivities matching the sorted Date
                        if(lstUniqueDates.get(i)==rec.ActivityDate)
                        {
                            rec.rowIndex =lstTmpActRecs.size()+1;
                            lstTmpActRecs.add(rec);
                        }
                    }
                }
            }
            else //If softing direction is DESC
            {
                //Iterate and prepare list in reverse order. 
                for(Integer i=lstUniqueDates.size()-1;i>=0;i--)
                {
                    for(ActivityInnerClass rec:lstActivities)
                    {
                        //To add all Acitivities matching the sorted Date
                        if(lstUniqueDates.get(i)==rec.ActivityDate)
                        {
                            rec.rowIndex =lstTmpActRecs.size()+1;
                            lstTmpActRecs.add(rec);
                        }
                    }
                }            
            }
            
            lstActivities=lstTmpActRecs;
system.debug('##########lstTmpActRecs##############'+lstTmpActRecs);            
        }
        return lstActivities;
}

public PageReference sort()
{
    //Toggle sorting order.
    sortDirection = (sortDirection.equalsIgnoreCase('ASC'))? 'DESC' : 'ASC';
    lstActivities=sortList(lstActivities);
    return null;
}

//CommandLink handler, to show complete description text.
public PageReference FullDesciption()
{
    Integer rowIndex = Integer.valueOf(ApexPages.currentPage().getParameters().get('rowIndex'));
    
    //Toggle the More/Lesser link button on VF Page.
    lstActivities.get(rowIndex-1).isElipsesOn=!lstActivities.get(rowIndex-1).isElipsesOn;
    return null;
}

//Inner class to hold common field values from Event and Task records.
public class ActivityInnerClass
{
    public Id recId {get;set;}
    public string Subject {get;set;}
    public DateTime ActivityDate{get;set;}
    public DateTime CompletionDate{get;set;}
    public string Description{get;set;}
    public string OwnerName{get;set;}
    public string Status{get;set;}
    public boolean isEventType {get;set;}
    public Integer rowIndex {get;set;}
    public string OutcomeNumber{get;set;}
    public boolean isElipsesOn {get;set;}
} 
public testMethod static void testController()
{
    Contact recCon = new Contact(Salutation='Mr', FirstName='Abc',LastName='TestLastName',Deceased__c=false,MailingPostalCode ='ABC123', Birthdate =Date.Today(),
        RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and Name Like 'Person with dementia'].id);
    insert recCon;        
    Account accRec = new Account(Name='Midlands Central Locality',RecordTypeId=[Select Id from RecordType where SObjectType='Account' and Name like 'Internal%'].id);
    insert accRec;
    Services__c serv = new Services__c(Name='Midlands Central Advocacy', Locality__c=accRec.id,Service_Type__c='Advocacy', National_Service__c=false);//Name='testControllerService');
    insert serv;    
    Service_Usage__c recSU = new Service_Usage__c(Service_Field__c= serv.id, Primary_Service_User__c=recCon.id,Service_Type__c='Advocacy');    
    insert recSU;
    
    Event eveRec = new Event(WhatId=recSU.id,Subject='Test Subject',DurationInMinutes=30,
            ActivityDateTime=System.now()-1,Format__c='Face to Face', In_Out__c='Outgoing',Location_Type_Event__c='Service User Home');
    insert eveRec;
    
    Event eveRec2 = new Event(WhatId=recSU.id,Subject='Test Subject',DurationInMinutes=30,
            ActivityDateTime=System.now()-1,Format__c='Face to Face', In_Out__c='Outgoing',Location_Type_Event__c='Office');
    insert eveRec2;    

    Task tskRec = new Task(WhatId=recSU.id,Subject='Test Subject',Format__c='Face to Face', 
            In_Out__c='Outgoing',Status='Completed',Completion_Date_Task__c=Date.Today(),Staff_Time_Minutes__c=30,
            Volunteer_Time_Minutes__c=30);
    insert tskRec; 
    
    Event_Attendance_Details__c EADRec = new Event_Attendance_Details__c(Service_Usage__c=recSU.id, Event_Date_and_Time__c=System.now()-1);  
    insert EADRec; 
    
    ApexPages.currentPage().getParameters().put('id', recSU.id);  
    ServiceUsageRelatedActivitiesController conCls= new ServiceUsageRelatedActivitiesController(new ApexPages.StandardController(recSU));
    ApexPages.currentPage().getParameters().put('rowIndex', '1'); 
    
    conCls.FullDesciption();
    conCls.sort();
    
    update eveRec;

}   
}