src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>$RecordType.DeveloperName</formula>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Diagnosis__c</fullName>
        <inlineHelpText>Only to be used for CONFIRMED diagnosis of dementia.</inlineHelpText>
        <label>Dementia diagnosis</label>
        <picklist>
            <picklistValues>
                <fullName>Alzheimer’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Binswanger’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia with Lewy bodies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Down’s syndrome related dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fronto-Temporal dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HIV related dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huntington’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korsakoff’s syndrome</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixed dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parkinson’s disease related dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pick’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prion disease including CJD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vascular dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None - Awaiting Diagnosis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None - Other Mild Cognitive Impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (please list)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mild Cognitive Impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact__c</fullName>
        <label>Emergency Contact</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>$RecordType.DeveloperName</formula>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <description>Health, Social Care and other professionals</description>
        <label>Professional / Stakeholder</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SFDC_Contact_Connector__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Record_Type__c</fullName>
        <description>Record type of main Contact. Populated by LookupRelationshipRecordTypes trigger</description>
        <label>Contact Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Connection</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Defaults to Ticked.</description>
        <label>Current?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tick if this person is to be contacted in an emergency.</inlineHelpText>
        <label>Emergency Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Keyholder__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox indicating whether this relationship shows the keyholder for a Person with Dementia’s home.  (Only available for Personal relationships involving a Person with Dementia.)</description>
        <label>Keyholder?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Next_of_Kin__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox indicating whether this relationship shows a Person with Dementia’s Next of Kin.  (Only available for Personal relationships involving a Person with Dementia.)</description>
        <label>Next of Kin?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PoA_Holder__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox indicating whether this relationship shows the individual holding a Power of Attorney for a Person with Dementia.  (Only available for Personal relationships involving a Person with Dementia.)</description>
        <label>PoA Holder?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Carer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox indicating whether this relationship shows a Person with Dementia’s Primary Carer.  (Only available for Personal relationships involving a Person with Dementia.  Ideally should have validation to ensure that each Person with Dementia has a maximum of one Primary Carer.)</description>
        <label>Primary Carer?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships (Related Contact)</relationshipLabel>
        <relationshipName>Related_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The name of the EXTERNAL organisation the Professional is attached to. Do NOT just type in name of the organisation – An external Organisation already on the system must be found, selected and inserted by using the Look-Up function (magnifying glass icon)</inlineHelpText>
        <label>Related Organisation</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>External organisation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>R00N30000001JJgjEAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Record_Type__c</fullName>
        <description>Record type of related Contact. Populated by LookupRelationshipRecordTypes trigger</description>
        <label>Related Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reverse_Relationship_Type__c</fullName>
        <label>Reverse Relationship</label>
        <picklist>
            <picklistValues>
                <fullName>Neighbour of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spouse of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Son/daughter of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sibling of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cousin of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uncle/aunt of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nephew/niece of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grandson/daughter of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grandparent of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Son/daughter-in-law of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent in-law of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sibling in-law of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Step-child of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Step-parent of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Step-sibling of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half-sibling of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friend of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient of (GP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient of (Consultant)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client of (Social care worker)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client of (Social worker)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient of (Care Manager)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient of (CPN)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient of (Admiral nurse)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GP of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client of (Care Manager)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community psychiatric nurse of</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Indicates the relationship that the existing person has with the person you are detailing below</inlineHelpText>
        <label>Relationship</label>
        <picklist>
            <picklistValues>
                <fullName>Consultant of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social care worker of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social worker of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care manager of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community psychiatric nurse of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admiral nurse of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient of (GP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient of (Consultant)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient of (Care Manager)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient of (CPN)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient of (Admiral nurse)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client of (Social care worker)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client of (Social worker)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client of (Care manager)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighbour of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spouse of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Son/daughter of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sibling of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cousin of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nephew/niece of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uncle/aunt of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grandparent of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grandson/daughter of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent in-law of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Son/daughter-in-law of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sibling in-law of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Step-parent of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Step-child of</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <recordTypes>
        <fullName>Personal</fullName>
        <active>true</active>
        <description>Personal Relationship</description>
        <label>Personal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <description>Professional Relationship</description>
        <label>Professional</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Contact_Connections_2way.cls
public class Contact_Connections_2way {
  private Contact contact;

  public Contact_Connections_2way() {
        contact = [select id, Salutation, Record_Type_Name__c, RecordTypeId, Diagnosis__c, MailingStreet, MailingState, MailingPostalCode, MailingCountry, MailingCity  from Contact where id = :ApexPages.currentPage().getParameters().get('id')];
  }
  
  public Contact_Connections_2way(ApexPages.StandardController controller) {
        this.contact= (Contact)controller.getRecord();
  }
    
  public String getName() {
        return 'Inbound and Outbound Connections';
  }

  //method to get a list of all first personal connections for the contact
  public list<SFDC_Contact_Connector__c> getFirstPersonalConnections() {
        //get record type name for every relationship
        RecordType rt1 = [Select Name, Id, DeveloperName From RecordType where Name = 'Personal' limit 1];
        
        //get the list of relationships with recordType = 'Personal'
        //and where the contact is first Contact. 
        List<SFDC_Contact_Connector__c> fPersonalConnections = [select id, name, Type__c, Contact__r.RecordTypeId, Contact__r.Record_Type_Name__c, 
        Related_Contact__r.Record_Type_Name__c, Related_Contact__r.name, Reverse_Relationship_Type__c, Related_Contact__r.Diagnosis__c, Related_Contact__r.Salutation,
        Current__c, Description__c, PoA_Holder__c, Related_Organization__r.name, Primary_Carer__c, Next_of_Kin__c, Keyholder__c, Contact__r.Salutation,
        Contact__r.name, Contact__r.Diagnosis__c, RecordTypeId, Contact_Record_Type__c, Related_Record_Type__c, Emergency_Contact__c from SFDC_Contact_Connector__c 
        where Contact__c = :contact.id and RecordTypeId=:rt1.Id order by Current__c, Contact__r.name];
        //where Contact__c = :contact.id and RecordTypeId=:rt.Id OR Related_Contact__c = :contact.id order by Related_Contact__r.name, Contact__r.name];
        
        //get the list of relationships with recordType = 'Personal'
        //and where the contact is second Contact. 
        List<SFDC_Contact_Connector__c> sPersonalConnections = [select id, name, Type__c, Contact__r.RecordTypeId, Contact__r.Record_Type_Name__c, 
        Related_Contact__r.Record_Type_Name__c, Related_Contact__r.name, Reverse_Relationship_Type__c, Related_Contact__r.Diagnosis__c, Related_Contact__r.Salutation,
        Current__c, Description__c, PoA_Holder__c, Related_Organization__r.name, Primary_Carer__c, Next_of_Kin__c, Keyholder__c, Contact__r.Salutation,
        Contact__r.name, Contact__r.Diagnosis__c, RecordTypeId, Contact_Record_Type__c, Related_Record_Type__c, Emergency_Contact__c  from SFDC_Contact_Connector__c 
        //where Contact__c = :contact.id and RecordTypeId=:rt.Id order by Related_Contact__r.name, Contact__r.name];
        where Related_Contact__c = :contact.id and RecordTypeId=:rt1.Id order by Current__c, Contact__r.name];
        
        for(SFDC_Contact_Connector__c sPCon: sPersonalConnections){
            fPersonalConnections.add(sPCon);
        }
        
        return fPersonalConnections.size()>0?fPersonalConnections:null;
  }
  
  //method to get a list of all personal connections for the contact
  public list<SFDC_Contact_Connector__c> getFirstProfessionalConnections() {
        //get record type name for every relationship
        RecordType rt2 = [Select Name, Id, DeveloperName From RecordType where Name = 'Professional' limit 1];
        
        //get the list of relationships with recordType = 'Professional'
        //and where the contact is first Contact. 
        List<SFDC_Contact_Connector__c> fProfessionalConnections = [select id, name, Type__c, Contact__r.RecordTypeId, Contact__r.Record_Type_Name__c, 
        Related_Contact__r.Record_Type_Name__c, Related_Contact__r.name, Reverse_Relationship_Type__c, Related_Contact__r.Diagnosis__c, Related_Contact__r.Salutation,
        Current__c, Description__c, PoA_Holder__c, Related_Organization__r.name, Primary_Carer__c, Next_of_Kin__c, Keyholder__c, Contact__r.Salutation, 
        Contact__r.name, Contact__r.Diagnosis__c, RecordTypeId, Contact_Record_Type__c, Related_Record_Type__c from SFDC_Contact_Connector__c 
        where Contact__c = :contact.id and RecordTypeId=:rt2.Id order by Current__c, Contact__r.name];
        
        //get the list of relationships with recordType = 'Professional'
        //and where the contact is second Contact. 
        List<SFDC_Contact_Connector__c> sProfessionalConnections = [select id, name, Type__c, Contact__r.RecordTypeId, Contact__r.Record_Type_Name__c, 
        Related_Contact__r.Record_Type_Name__c, Related_Contact__r.name, Reverse_Relationship_Type__c, Related_Contact__r.Diagnosis__c, Related_Contact__r.Salutation,
        Current__c, Description__c, PoA_Holder__c, Related_Organization__r.name, Primary_Carer__c, Next_of_Kin__c, Keyholder__c, Contact__r.Salutation, 
        Contact__r.name, Contact__r.Diagnosis__c, RecordTypeId, Contact_Record_Type__c, Related_Record_Type__c from SFDC_Contact_Connector__c 
        where Related_Contact__c = :contact.id and RecordTypeId=:rt2.Id order by Current__c, Contact__r.name];
        
        for(SFDC_Contact_Connector__c sProfCon: sProfessionalConnections){
            fProfessionalConnections.add(sProfCon);
        }
        
        return fProfessionalConnections.size()>0?fProfessionalConnections:null;
  }
  
  //
  // TEST CASE
  //
  private static testMethod void testRelationships() {
        Contact c1 = new Contact(Salutation='Mr',FirstName='one', LastName='related',Deceased__c=false,MailingPostalCode ='ABC123', Birthdate =Date.Today(),
                RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and Name Like 'Person with dementia'].id);
        insert c1;
        
        // Set up the VF page
        PageReference pageRef = Page.Contact_Connections_2way;
        test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', c1.Id);
        
        Contact_Connections_2way cnt = new Contact_Connections_2way();
        ApexPages.StandardController stdCon = new ApexPages.StandardController(c1);
        cnt = new Contact_Connections_2way(stdCon);
        
        cnt.getName();
        cnt.getFirstPersonalConnections();
        cnt.getFirstProfessionalConnections();
    }
}