src/objects/APPG_Meeting__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>EA_Campaign__c</referenceTo>
        <relationshipLabel>APPG Meetings</relationshipLabel>
        <relationshipName>APPG_Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>APPG Meeting</label>
    <nameField>
        <label>APPG Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APPG Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/APPG_Meeting_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>APPG_Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>APPG Meeting</label>
        <referenceTo>APPG_Meeting__c</referenceTo>
        <relationshipLabel>APPG Meeting Attendees</relationshipLabel>
        <relationshipName>APPG_Meeting_Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MP</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>APPG Meeting Attendees</relationshipLabel>
        <relationshipName>APPG_Meeting_Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>APPG Meeting Attendee</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>APPG Meeting Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APPG Meeting Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Attendence__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign Event</label>
        <referenceTo>Campaign_Event__c</referenceTo>
        <relationshipName>Attendences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MP</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Attendences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Invited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Did Not Attend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Campaign Event Attendence</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Attendence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Event Attendences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Campaign_Event__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>EA_Campaign__c</referenceTo>
        <relationshipLabel>Campaign Events</relationshipLabel>
        <relationshipName>R00N7000000256A6EAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Event</label>
    <nameField>
        <label>Campaign Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Consent_Status__c</fullName>
        <inlineHelpText>Seek signed consent as soon as possible. Services cannot be delivered unless verbal consent at least, has been obtained.</inlineHelpText>
        <label>Consent Status</label>
        <picklist>
            <picklistValues>
                <fullName>Awaiting Consent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verbal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Written</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Witnessed Verbal Consent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Witnessed Indicated Consent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proxy Consent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not a Service User</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Debate__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>EA_Campaign__c</referenceTo>
        <relationshipLabel>Debates</relationshipLabel>
        <relationshipName>Debates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organiser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organiser</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Debates Started</relationshipLabel>
        <relationshipName>Debates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Debate</label>
    <nameField>
        <label>Topic</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EA_Campaign__c.object
<CustomObject>
    <description>External Affairs Campaign</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aborted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EDM__c.object
<CustomObject>
    <description>Early Day Motion</description>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Author</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Authored EDMs</relationshipLabel>
        <relationshipName>EDMs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>EA_Campaign__c</referenceTo>
        <relationshipLabel>EDMs</relationshipLabel>
        <relationshipName>EDMs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EDM</label>
    <nameField>
        <label>EDM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EDMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EDM_Sponsor__c.object
<CustomObject>
    <fields>
        <fullName>EDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EDM</label>
        <referenceTo>EDM__c</referenceTo>
        <relationshipLabel>EDM Sponsors</relationshipLabel>
        <relationshipName>R00NS0000000I4zWMAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MP</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sponsored EDMs</relationshipLabel>
        <relationshipName>R00NS0000000I4zoMAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EDM Sponsor</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>EDM Sponsor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EDM Sponsors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MP_Debate_Association__c.object
<CustomObject>
    <fields>
        <fullName>Debate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Debate</label>
        <referenceTo>Debate__c</referenceTo>
        <relationshipLabel>Debate Attendees</relationshipLabel>
        <relationshipName>R00N7000000246hPEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MP</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Debates Attended</relationshipLabel>
        <relationshipName>R00N7000000246hUEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Debate Attendee</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>MP Debate Association ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debate Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MP_EDM_Association__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MP</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Signed EDMs</relationshipLabel>
        <relationshipName>R00N7000000245QaEAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Early Day Motion</description>
        <label>EDM</label>
        <referenceTo>EDM__c</referenceTo>
        <relationshipLabel>EDM Signatories</relationshipLabel>
        <relationshipName>R00N7000000245QZEAY</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EDM Signatory</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>MP_EDM_Association ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EDM Signatories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MP_Score_per_Object__c.object
<CustomObject>
    <description>Contains a score per MP per Object</description>
    <fields>
        <fullName>Activity__c</fullName>
        <description>What the MP did to get this score</description>
        <label>Activity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>EA_Campaign__c</referenceTo>
        <relationshipLabel>MP Scores per Object</relationshipLabel>
        <relationshipName>R00N7000000256AGEAY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MP</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Scores</relationshipLabel>
        <relationshipName>R00NS0000000I2u9MAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MP Score per Object</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>MP Score per Object ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MP Scores per Object</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PQ__c.object
<CustomObject>
    <description>Parliamentary Questions</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>EA_Campaign__c</referenceTo>
        <relationshipLabel>PQs</relationshipLabel>
        <relationshipName>PQs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MP</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PQs</relationshipLabel>
        <relationshipName>PQs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PQ</label>
    <nameField>
        <displayFormat>PQ-{0}</displayFormat>
        <label>PQ ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PQs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TriggerTests.cls
@isTest
private class TriggerTests {
// DEBATE TRIGGER TESTS
    // Positive tests
     static testMethod void debatePositiveTest() {
        // strings for inserting debate and testing score creation
        String activity;
        String debateName = 'Test debate';
        
        // insert a test campaign and two test contacts to work with
        EA_Campaign__c campaign = new EA_Campaign__c(Name='Test campaign');
        Contact personA = new Contact(Birthdate=System.today(),firstName='Person A',lastName = 'Person A');
        Contact personB = new Contact(Birthdate=System.today(),firstName='Person B',lastName = 'Person B');
        insert campaign; insert personA; insert personB;
        
        
        // INSERT TRIGGER
        System.debug('Inserting debate');
        Debate__c debate = new Debate__c(Campaign__c = campaign.Id, Organiser__c = personA.Id, Name = debateName);
        insert debate;
        
        activity = 'Organised Debate: ' + debate.Name;
        
        System.debug('Testing score was created');
        System.assertEquals(activity, [select Activity__c from MP_Score_per_Object__c
                                       where  Campaign__c = :campaign.Id
                                       and    MP__c = :personA.Id limit 1].Activity__c);
                         
                                       
        // UPDATE TRIGGER
        System.debug('Updating debate');
        debate.Organiser__c = personB.Id;
        update debate;
        
        System.debug('Testing score was updated');
        System.assertEquals(activity, [select Activity__c from MP_Score_per_Object__c
                                       where  Campaign__c = :campaign.Id
                                       and    MP__c = :personB.Id limit 1].Activity__c);
                                       
                                       
        // DELETE TRIGGER
        System.debug('Deleting debate');
        delete debate;
        
        System.debug('Testing score was deleted');
        List<MP_Score_per_Object__c> mps = new List<MP_Score_per_Object__c>();
        mps = [select id from MP_Score_per_Object__c where Campaign__c = :campaign.Id];
        //System.assert(mps.isEmpty());
    }
    
       
 // DEBATE ATTENDEE TRIGGER TESTS
    // Positive tests
    static testMethod void debateAttendPositiveTest() {
        // strings for inserting debate and testing score creation
        String activity;
        String debateName = 'Test debate 2';
        
        // insert a test campaign and two test contacts to work with
        EA_Campaign__c campaign = new EA_Campaign__c(Name='Test campaign');
        Contact personA = new Contact(Birthdate=System.today(),firstName='Person A',lastName = 'Person A');
        Contact personB = new Contact(Birthdate=System.today(),firstName='Person B',lastName = 'Person B');
        insert campaign; insert personA; insert personB;
        
        
        // INSERT TRIGGER
        System.debug('Inserting debate attendee');
        Debate__c debate = new Debate__c(Campaign__c = campaign.Id, Name = debateName);
        insert debate;
        MP_Debate_Association__c attendee = new MP_Debate_Association__c(MP__c = personA.id, Debate__c = debate.id);
        insert attendee;
        
        activity = 'Attended Debate: ' + debate.Name;
        
        System.debug('Testing score was created');
        System.assertEquals(activity, [select Activity__c from MP_Score_per_Object__c
                                       where  Campaign__c = :campaign.Id
                                       and    MP__c = :personA.Id limit 1].Activity__c);
                         
                                       
        // UPDATE TRIGGER
        System.debug('Updating debate attendee');
        attendee.MP__c = personB.Id;
        update attendee;
        
        System.debug('Testing score was updated');
        System.assertEquals(activity, [select Activity__c from MP_Score_per_Object__c
                                       where  Campaign__c = :campaign.Id
                                       and    MP__c = :personB.Id limit 1].Activity__c);
                                       
                                       
        // DELETE TRIGGER
        System.debug('Deleting debate attendee');
        delete attendee;
        
        System.debug('Testing score was deleted');
        List<MP_Score_per_Object__c> mps = new List<MP_Score_per_Object__c>();
        mps = [select id from MP_Score_per_Object__c
               where  Campaign__c = :campaign.Id
               and    MP__c = :personB.Id];
        System.assert(mps.isEmpty());
    }
    
    
 // PQ TRIGGER TESTS
    // Positive tests
    static testMethod void pqPositiveTest() {
        // strings for inserting debate and testing score creation
        String activity;
        String pqName = 'Test PQ';
        
        // insert a test campaign and two test contacts to work with
        EA_Campaign__c campaign = new EA_Campaign__c(Name='Test campaign');
        Contact personA = new Contact(Birthdate=System.today(),firstName='First',lastName = 'Person A');
        Contact personB = new Contact(Birthdate=System.today(),firstName='First',lastName = 'Person B');
        insert campaign; insert personA; insert personB;
        
        
        // INSERT TRIGGER
        System.debug('Inserting PQ');
        PQ__c pq = new PQ__c(Campaign__c = campaign.Id, Contact__c = personA.Id, Subject__c = pqName, Question__c = 'Hello?');
        insert pq;
        
        activity = 'Asked PQ: ' + pq.Subject__c;
        
        System.debug('Testing score was created');
        System.assertEquals(activity, [select Activity__c from MP_Score_per_Object__c
                                       where  Campaign__c = :campaign.Id
                                       and    MP__c = :personA.Id limit 1].Activity__c);
                         
                                       
        // UPDATE TRIGGER
        System.debug('Updating PQ');
        pq.Contact__c = personB.Id;
        update pq;
        
        System.debug('Testing score was updated');
        System.assertEquals(activity, [select Activity__c from MP_Score_per_Object__c
                                       where  Campaign__c = :campaign.Id
                                       and    MP__c = :personB.Id limit 1].Activity__c);
                                       
                                       
        // DELETE TRIGGER
        System.debug('Deleting PQ');
        delete pq;
        
        System.debug('Testing score was deleted');
        List<MP_Score_per_Object__c> mps = new List<MP_Score_per_Object__c>();
        mps = [select id from MP_Score_per_Object__c where Campaign__c = :campaign.Id];
        System.assert(mps.isEmpty());
    }
    
    
  // EDM TRIGGER TESTS
    // Positive tests
    static testMethod void edmPositiveTest() {
        // strings for inserting debate and testing score creation
        String activity;
        String edmName = 'Test EDM';
        
        // insert a test campaign and two test contacts to work with
        EA_Campaign__c campaign = new EA_Campaign__c(Name='Test campaign');
        Contact personA = new Contact(Birthdate=System.today(),firstName='First',lastName = 'Person A');
        Contact personB = new Contact(Birthdate=System.today(),firstName='First',lastName = 'Person B');
        insert campaign; insert personA; insert personB;
        
        
        // INSERT TRIGGER
        System.debug('Inserting EDM');
        EDM__c edm = new EDM__c(Campaign__c = campaign.Id, Author__c = personA.Id, Name = edmName);
        insert edm;
        
        activity = 'Authored EDM: ' + edm.Name;
        
        System.debug('Testing score was created');
        System.assertEquals(activity, [select Activity__c from MP_Score_per_Object__c
                                       where  Campaign__c = :campaign.Id
                                       and    MP__c = :personA.Id limit 1].Activity__c);
                         
                                       
        // UPDATE TRIGGER
        System.debug('Updating EDM');
        edm.Author__c = personB.Id;
        update edm;
        
        System.debug('Testing score was updated');
        System.assertEquals(activity, [select Activity__c from MP_Score_per_Object__c
                                       where  Campaign__c = :campaign.Id
                                       and    MP__c = :personB.Id limit 1].Activity__c);
                                       
                                       
        // DELETE TRIGGER
        System.debug('Deleting EDM');
        delete edm;
        
        System.debug('Testing score was deleted');
        List<MP_Score_per_Object__c> mps = new List<MP_Score_per_Object__c>();
        mps = [select id from MP_Score_per_Object__c where Campaign__c = :campaign.Id];
        System.assert(mps.isEmpty());
    }
    

// -- REMOVED BECAUSE NO LONGER A TRIGGER ON SYSTEM
// EDM SPONSOR TRIGGER TESTS
/*
    // Positive tests
    static testMethod void edmSponsorPositiveTest() {
        // strings for inserting debate and testing score creation
        String activity;
        String edmName = 'Test EDM';
        
        // insert a test campaign and two test contacts to work with
        EA_Campaign__c campaign = new EA_Campaign__c(Name='Test campaign');
        Contact personA = new Contact(Birthdate=System.today(),firstName='First',lastName = 'Person A');
        Contact personB = new Contact(Birthdate=System.today(),firstName='First',lastName = 'Person B');
        insert campaign; insert personA; insert personB;
        
        
        // INSERT TRIGGER
        System.debug('Inserting EDM Sponsor');
        EDM__c edm = new EDM__c(Campaign__c = campaign.Id, Name = edmName);
        insert edm;
        EDM_Sponsor__c edmSponsor = new EDM_Sponsor__c(EDM__c = edm.id, MP__c = personA.id);
        insert edmSponsor;
        
        activity = 'Sponsored EDM: ' + edm.Name;
        
        System.debug('Testing score was created');
        System.assertEquals(activity, [select Activity__c from MP_Score_per_Object__c
                                       where  Campaign__c = :campaign.Id
                                       and    MP__c = :personA.Id limit 1].Activity__c);
                         
                                       
        // UPDATE TRIGGER
        System.debug('Updating EDM Sponsor');
        edmSponsor.MP__c = personB.Id;
        update edmSponsor;
        
        System.debug('Testing score was updated');
        System.assertEquals(activity, [select Activity__c from MP_Score_per_Object__c
                                       where  Campaign__c = :campaign.Id
                                       and    MP__c = :personB.Id limit 1].Activity__c);
                                       
                                       
        // DELETE TRIGGER
        System.debug('Deleting EDM Sponsor');
        delete edmSponsor;
        
        System.debug('Testing score was deleted');
        List<MP_Score_per_Object__c> mps = new List<MP_Score_per_Object__c>();
        mps = [select id from MP_Score_per_Object__c
               where  Campaign__c = :campaign.Id
               and    MP__c = :personB.Id];
        System.assert(mps.isEmpty());
    }
*/
    
 // EDM SIGNATORY TRIGGER TESTS
    // Positive tests
    static testMethod void edmSigPositiveTest() {
        // strings for inserting EDM and testing score creation
        String activity;
        String edmName = 'Test EDM';
        
        // insert a test campaign and two test contacts to work with
        EA_Campaign__c campaign = new EA_Campaign__c(Name='Test campaign');
        Contact personA = new Contact(Birthdate=System.today(), firstName='First',lastName = 'Person A');
        Contact personB = new Contact(Birthdate=System.today(),firstName='First',lastName = 'Person B');
        insert campaign; insert personA; insert personB;
        
        
        // INSERT TRIGGER
        System.debug('Inserting EDM Signatory');
        EDM__c edm = new EDM__c(Campaign__c = campaign.Id, Name = edmName);
        insert edm;
        MP_EDM_Association__c edmSig = new MP_EDM_Association__c(EDM__c = edm.id, Contact__c = personA.id);
        insert edmSig;
        
        activity = 'Signed EDM: ' + edm.Name;
        
        System.debug('Testing score was created');
        System.assertEquals(activity, [select Activity__c from MP_Score_per_Object__c
                                       where  Campaign__c = :campaign.Id
                                       and    MP__c = :personA.Id limit 1].Activity__c);
                         
                                       
        // UPDATE TRIGGER
        System.debug('Updating EDM Signatory');
        edmSig.Contact__c = personB.Id;
        update edmSig;
        
        System.debug('Testing score was updated');
        System.assertEquals(activity, [select Activity__c from MP_Score_per_Object__c
                                       where  Campaign__c = :campaign.Id
                                       and    MP__c = :personB.Id limit 1].Activity__c);
                                       
                                       
        // DELETE TRIGGER
        System.debug('Deleting EDM Signatory');
        delete edmSig;
        
        System.debug('Testing score was deleted');
        List<MP_Score_per_Object__c> mps = new List<MP_Score_per_Object__c>();
        mps = [select id from MP_Score_per_Object__c
               where  Campaign__c = :campaign.Id
               and    MP__c = :personB.Id];
        System.assert(mps.isEmpty());
    }
    
    
// CAMPAIGN EVENT ATTENDEE TRIGGER TESTS
    // Positive tests
    static testMethod void campaignEventAttendeePositiveTest() {
        // strings for inserting debate and testing score creation
        String activity;
        String campaignEventName = 'Test Campaign Event';
        
        // insert a test campaign and two test contacts to work with
        EA_Campaign__c campaign = new EA_Campaign__c(Name='Test campaign');
        Contact personA = new Contact(Birthdate=System.today(),firstName='First',lastName = 'Person A');
        Contact personB = new Contact(Birthdate=System.today(),firstName='First',lastName = 'Person B');
        insert campaign; insert personA; insert personB;
        
        // create a test campaign event
        Campaign_Event__c ce = new Campaign_Event__c(Name = campaignEventName, Campaign__c = campaign.id);
        insert ce;
        
        // INSERT TRIGGER
        System.debug('Inserting campaign event attendee');
        Attendence__c attendence = new attendence__c(Campaign_Event__c = ce.Id,
                                                     Contact__c = personA.id,
                                                     Status__c = 'Attended');
        insert attendence;
        
        activity = 'Attended Event: ' + ce.Name;
        
        System.debug('Testing score was created');
        System.assertEquals(activity, [select Activity__c from MP_Score_per_Object__c
                                       where  Campaign__c = :campaign.Id
                                       and    MP__c = :personA.Id limit 1].Activity__c);
                         
                                       
        // UPDATE TRIGGER
        System.debug('Updating campaign event attendee');
        attendence.Contact__c = personB.Id;
        update attendence;
        
        System.debug('Testing score was updated');
        System.assertEquals(activity, [select Activity__c from MP_Score_per_Object__c
                                       where  Campaign__c = :campaign.Id
                                       and    MP__c = :personB.Id limit 1].Activity__c);
                                       
                                       
        // DELETE TRIGGER
        System.debug('Deleting debate attendee');
        delete attendence;
        
        System.debug('Testing score was deleted');
        List<MP_Score_per_Object__c> mps = new List<MP_Score_per_Object__c>();
        mps = [select id from MP_Score_per_Object__c where Campaign__c = :campaign.Id];
        System.assert(mps.isEmpty());
    }
    
// APPG MEETING ATTENDEE TRIGGER TESTS
    // Positive tests
    static testMethod void APPGAttendeePositiveTest() {
        // strings for inserting debate and testing score creation
        String activity;
        String APPGName = 'Test APPG Meeting';
        
        // insert a test campaign and two test contacts to work with
        EA_Campaign__c campaign = new EA_Campaign__c(Name='Test campaign');
        Contact personA = new Contact(Birthdate=System.today(),firstName='First',lastName = 'Person A');
        Contact personB = new Contact(Birthdate=System.today(),firstName='First',lastName = 'Person B');
        insert campaign; insert personA; insert personB;
        
        // create a test campaign event
        APPG_Meeting__c ce = new APPG_Meeting__c(Name = APPGName, Campaign__c = campaign.id);
        insert ce;
        
        // INSERT TRIGGER
        System.debug('Inserting APPG attendee');
        APPG_Meeting_Attendee__c attendence = new APPG_Meeting_Attendee__c(APPG_Meeting__c = ce.Id,
                                                     Contact__c = personA.id);
        insert attendence;
        
        activity = 'Attended APPG Meeting: ' + ce.Name;
        
        System.debug('Testing score was created');
        System.assertEquals(activity, [select Activity__c from MP_Score_per_Object__c
                                       where  Campaign__c = :campaign.Id
                                       and    MP__c = :personA.Id limit 1].Activity__c);
                         
                                       
        // UPDATE TRIGGER
        System.debug('Updating APPG Meeting attendee');
        attendence.Contact__c = personB.Id;
        update attendence;
        
        System.debug('Testing score was updated');
        System.assertEquals(activity, [select Activity__c from MP_Score_per_Object__c
                                       where  Campaign__c = :campaign.Id
                                       and    MP__c = :personB.Id limit 1].Activity__c);
                                       
                                       
        // DELETE TRIGGER
        System.debug('Deleting appg meeting attendee');
        delete attendence;
        
        System.debug('Testing score was deleted');
        List<MP_Score_per_Object__c> mps = new List<MP_Score_per_Object__c>();
        mps = [select id from MP_Score_per_Object__c where Campaign__c = :campaign.Id];
        System.assert(mps.isEmpty());
    }
    
    // CONTACT TRIGGER TESTS
    // Positive tests
    static testMethod void ContactPositiveTest() {
        // insert two test contacts to work with
        Contact personA = new Contact(firstName='First',lastName = 'Person A', Birthdate=System.today());
        //Contact personA = new Contact(firstName='First',lastName = 'Person A', Consent_Status__c='Withdrawn', Birthdate=System.today());
        Contact personB = new Contact(firstName='First',lastName = 'Person B', DoNotCall=true, Birthdate=System.today());
        
        // INSERT TRIGGER
        System.debug('Inserting contact');
        insert personA; insert personB;
        
        System.debug('Testing score was created');
        //System.assertNotEquals(null, [Select c.rrpu__Alert_Message__c, c.Id, c.DoNotCall, c.Consent_Status__c From Contact c
        //                               where  id = :personA.id].rrpu__Alert_Message__c);
                                       
    }
    
    static testMethod void testServiceUsageDelete() {
    
    }
}