src/objects/APPG_Meeting__c.object
<CustomObject>
    <label>APPG Meeting</label>
    <nameField>
        <label>APPG Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APPG Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/APPG_Meeting_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>APPG_Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>APPG Meeting</label>
        <referenceTo>APPG_Meeting__c</referenceTo>
        <relationshipLabel>APPG Meeting Attendees</relationshipLabel>
        <relationshipName>APPG_Meeting_Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MP</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>APPG Meeting Attendees</relationshipLabel>
        <relationshipName>APPG_Meeting_Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>APPG Meeting Attendee</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>APPG Meeting Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APPG Meeting Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>MP</fullName>
        <active>true</active>
        <description>Member of Parliament</description>
        <label>MP</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/contact__c.object
<CustomObject>
    <label>contact</label>
    <nameField>
        <label>contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/addAPPGAttendees.cls
public with sharing class addAPPGAttendees extends addContacts {

    // The APPG meeting MPs will be attending
    public APPG_Meeting__c appg;
    
    // Attendee's status (invited, attending, declined etc)
    //public string attendeeStatus;
    
    // Visualforce extension constructor
    public addAPPGAttendees(ApexPages.StandardController controller) {
        appg = (APPG_Meeting__c)controller.getRecord();
        recordTypeList.add('012700000009SAV'); // MP record type
        recordTypeList.add('012700000009WHH'); // Stakeholder
    }
    
    // ----------------------------------------------------------------------
    // Save Button:
    // - Build a list of new Attendence records relating to the Campaign Event
    // - Upsert and report any errors
    // - Redirect to the Campaign Event
    // ----------------------------------------------------------------------
    public override pageReference doSave() {
        
        // Build a list of new attendence objects to insert
        List<APPG_Meeting_Attendee__c> attendences = new List<APPG_Meeting_Attendee__c>();
        APPG_Meeting_Attendee__c a;
        for (transferContactSearchResults c : searchResults) {
            if (c.selected) {
                // Create a new attendence record for each selected contact
                a = new APPG_Meeting_Attendee__c();
                a.Contact__c = c.contact.ID;
                a.APPG_Meeting__c = appg.Id;
                //a.Status__c = attendeeStatus;
                attendences.add(a);
            }
        }
        if (DebugMode) ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Selected Count: ' + attendences.size()));


        // Process Errors and Count the Number of Records created
        Integer transferCount = 0;
        List<database.Upsertresult> srs = database.upsert(attendences);
        for (database.Upsertresult sr : srs) {
            if (!sr.isSuccess()) {
                ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.FATAL, sr.getId() + '/' + sr.getErrors()[0].getMessage() ));
            } else {
                transferCount++; 
            }
        }
    
        // Display the Transfer Count
        ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.INFO, transferCount + ' Records Successfully Transfered' ));
        
        // Set the flag that this just finished
        transferJustCompleted = true;       
        
        // Send the user to the detail page for the campaign event
        PageReference page = new PageReference('/' + appg.id);
        page.setRedirect(true);
        return page;
    }
    
    // Send user back to campaign event
    public override PageReference cancel() {
        PageReference page = new PageReference('/' + appg.id);
        page.setRedirect(true);
        return page;
    }
}