src/objects/Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Assessment_Header__c</fullName>
        <label>Assessment Header</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Assessment_Section__c</fullName>
        <label>Assessment Section</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AST-{000000}</displayFormat>
        <label>Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assessment_Question__c.object
<CustomObject>
    <fields>
        <fullName>Assessment__c</fullName>
        <label>Assessment</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Assessment Questions</relationshipLabel>
        <relationshipName>Assessment_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Hold DataType.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Combo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Freetext</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Assessment Question</label>
    <nameField>
        <displayFormat>AQ-{0000000000}</displayFormat>
        <label>Assessment Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Completed_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Assessment_Header__c</fullName>
        <formula>Assessment__r.Assessment_Header__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assessment Header</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Completed Assessments</relationshipLabel>
        <relationshipName>Completed_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Usage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Usage</label>
        <referenceTo>Service_Usage__c</referenceTo>
        <relationshipName>Survey_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Completed Assessment</label>
    <nameField>
        <displayFormat>CA-{0000000000}</displayFormat>
        <label>Completed Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Completed Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Usage__c.object
<CustomObject>
    <fields>
        <fullName>Service_Field__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the Service/Activity.
Filtered by Service Type and user&apos;s Locality for internal Service Usage records.
No filter required for &apos;Outgoing Referrals&apos; as these are only ever created in the background (via Referrals screen).</description>
        <label>Service</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 5 AND 6) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>Services__c.service_type__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Type__c</valueField>
            </filterItems>
            <filterItems>
                <field>Services__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Service</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outgoing Referral</value>
            </filterItems>
            <filterItems>
                <field>Services__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Service</value>
            </filterItems>
            <filterItems>
                <field>Services__c.Locality__r.Name</field>
                <operation>equals</operation>
                <valueField>$User.Locality__c</valueField>
            </filterItems>
            <filterItems>
                <field>Services__c.service_status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Services__c</referenceTo>
        <relationshipLabel>Service Usage</relationshipLabel>
        <relationshipName>Service_Usage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <description>The type of Service to which Service Usage relates.
Used as a filter when selecting Service.
Used to set Record Type on saving a new Service Usage.</description>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (one to one)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peer support group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered home care and support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singing for the Brain</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Usage</label>
    <nameField>
        <label>Service Usage Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Usage</pluralLabel>
    <recordTypes>
        <fullName>Advocacy</fullName>
        <active>true</active>
        <description>Used for all Advocacy Referrals and Cases</description>
        <label>Advocacy</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>Locality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Locality in which this service is based (left blank for national services).</description>
        <label>Locality</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select an Alzheimer&apos;s Society Locality.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Organisation</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>contains</operation>
                <value>Locality</value>
            </filterItems>
            <infoMessage>Please select a Locality.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Services_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>service_type__c</fullName>
        <inlineHelpText>Service description will be automatically populated from the service type (or sub type if there is one)</inlineHelpText>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult education &amp; training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (emotional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (financial)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (general)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awareness raising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending / home support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counselling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day support / day care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafés</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exercise / Fitness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home facilities &amp; services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Dementia)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Financial &amp; Legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programmes &amp; provision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>Internal Service/Activity</description>
        <label>Internal Service</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestAssessmentCompletedControllers.cls
@isTest
private class TestAssessmentCompletedControllers {


public testMethod static void testAssessmentCompletedController()
{
    //Assessment__c 
    Assessment__c recSrvy = new Assessment__c(Assessment_Header__c='MI Test Header',Assessment_Section__c='1\tSection1\n2\tSection2',Status__c ='Active');
    insert recSrvy;
    
    //Contact 
    Contact recCon = new Contact(LastName='TestLastName',FirstName='TestFirstName', MailingPostalCode ='ABC123', Birthdate =Date.Today(),
        RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and name like 'Person with dementia%'].id);
    insert recCon;

    //Account 
    Account accRec = new Account(Name='Midlands Central Locality',RecordTypeId=[Select Id from RecordType where SObjectType='Account' and Name like 'Internal%'].id);
    insert accRec;
    Services__c serv = new Services__c(Locality__c=accRec.id,Service_Type__c='Advocacy');//Name='testControllerService');
    insert serv;
       
    Service_Usage__c recSU = new Service_Usage__c(Service_Field__c=serv.id,Primary_Service_User__c=recCon.id,
        Service_Type__c='Advocacy');
    insert recSU;
    
    List<Assessment_Question__c> lstSQ = new List<Assessment_Question__c>();
    lstSQ.add(new Assessment_Question__c(Question__c='Freetext Questionaire',Assessment__c=recSrvy.id,Section_Header__c='Section1',Type__c='Freetext',QuestionNumber__c='1'));
    lstSQ.add(new Assessment_Question__c(Question__c='Combo Questionaire',Assessment__c=recSrvy.id,Section_Header__c='Section2',Type__c='Combo',
    Choices__c='Option1\nOption2\nOption3',Sub_Question__c='SubQues1\nSubQues2\nSubQues3',QuestionNumber__c='2'));
    insert lstSQ;
    
    Completed_Assessment__c recSR = new Completed_Assessment__c(Assessment__c=recSrvy.id,Service_Usage__c=recSU.id);
    insert recSR;
    
    List<Completed_Assessment_Answer__c> lstCAA = new List<Completed_Assessment_Answer__c>();
    lstCAA.add(new Completed_Assessment_Answer__c(Assessment_Question__c=lstSQ.get(0).id,
            Completed_Assessment__c=recSR.id,
            Response_Note__c='Test Notes',ValidFromDateTime__c=system.now()));
    lstCAA.add(new Completed_Assessment_Answer__c(Assessment_Question__c=lstSQ.get(1).id,
            Completed_Assessment__c=recSR.id,   Sub_Question__c='SubQues1',
            Choice__c='Option1',ValidFromDateTime__c=system.now()));
    insert lstCAA;

    ApexPages.currentPage().getParameters().put('suid', recSU.id);   

     ApexPages.Standardcontroller con = new ApexPages.StandardController(recSR);
     system.debug('++++++++recSR++++++++++++++'+recSR);
     system.debug('++++++++con++++++++++++++'+con);    

    AssessmentCompletedController conCls= new AssessmentCompletedController(new ApexPages.StandardController(recSR));
    ApexPages.currentPage().getParameters().put('sid', recSrvy.id);
    
    AssessmentCompletedController conCls2= new AssessmentCompletedController(new ApexPages.StandardController(recSR));
    conCls2.SaveAssessment();
    ApexPages.currentPage().getParameters().put('strReturnToPage', 'false');
    ApexPages.currentPage().getParameters().put('id', recSR.id);
    
    AssessmentCompletedController conCls3= new AssessmentCompletedController(new ApexPages.StandardController(recSR));
    conCls3.lstSections.get(0).lstAssessmentQuestions.get(0).respAnsRec.Response_Note__c='Modified';
    ApexPages.currentPage().getParameters().put('strReturnToPage', 'true');


    conCls3.SaveAssessment();
    conCls3.getAuditTrail();
    
    List<Assessment_Question__c> lstSQ2 = new List<Assessment_Question__c>();
    lstSQ2.add(new Assessment_Question__c(Question__c='Freetext Questionaire',Assessment__c=recSrvy.id,Section_Header__c='Section1',Type__c='Freetext',QuestionNumber__c='1'));
    
    lstSQ2.add(new Assessment_Question__c(Id=lstSQ.get(1).id,Question__c='Combo Questionaire',Assessment__c=recSrvy.id,Section_Header__c='Section2',Type__c='Combo',
    Choices__c='Option1\nOption2\nOption3',Sub_Question__c='SubQues4',QuestionNumber__c='2'));
    
    lstSQ2.add(new Assessment_Question__c(Question__c='Combo Questionaire2',Assessment__c=recSrvy.id,Section_Header__c='Section2',Type__c='Combo',
    Choices__c='Option1\nOption2\nOption3',Sub_Question__c='SubQues1\nSubQues2\nSubQues3',QuestionNumber__c='3'));   
    
    upsert lstSQ2;
    AssessmentCompletedController conCls4= new AssessmentCompletedController(new ApexPages.StandardController(recSR));    

}



//MAT    20131213 - AssessmentCompletedAuditController
static testMethod void TestAssessmentCompletedAuditController()
{
   Assessment__c recSrvy = new Assessment__c(Assessment_Header__c='MI Test Header',Assessment_Section__c='1\tSection1\n2\tSection2',Status__c ='Active');
    insert recSrvy;
    
    Contact recCon = new Contact(Salutation='Mr',FirstName='Abc',LastName='TestLastName',MailingPostalCode ='ABC123', Birthdate =Date.Today(),
        RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and name like 'Person with dementia%'].id);
    insert recCon;

    Account accRec = new Account(Name='Midlands Central Locality',RecordTypeId=[Select Id from RecordType where SObjectType='Account' and Name like 'Internal%'].id);
    insert accRec;
    
    Services__c serv = new Services__c(Locality__c=accRec.id,Service_Type__c='Advocacy');//Name='testControllerService');
    insert serv;    
    
    Service_Usage__c recSU = new Service_Usage__c(Service_Field__c=serv.id,Primary_Service_User__c=recCon.id,
        Service_Type__c='Advocacy');
    insert recSU;
    
    List<Assessment_Question__c> lstSQ = new List<Assessment_Question__c>();
    lstSQ.add(new Assessment_Question__c(Question__c='Freetext Questionaire',Assessment__c=recSrvy.id,Section_Header__c='Section1',Type__c='Freetext',QuestionNumber__c='1'));
    lstSQ.add(new Assessment_Question__c(Question__c='Combo Questionaire',Assessment__c=recSrvy.id,Section_Header__c='Section2',Type__c='Combo',
    Choices__c='Option1\nOption2\nOption3',Sub_Question__c='SubQues1\nSubQues2\nSubQues3',QuestionNumber__c='2'));
    insert lstSQ;
    
    Completed_Assessment__c recSR = new Completed_Assessment__c(Assessment__c=recSrvy.id,Service_Usage__c=recSU.id);
    insert recSR;
    
    List<Completed_Assessment_Answer__c> lstCAA = new List<Completed_Assessment_Answer__c>();
    lstCAA.add(new Completed_Assessment_Answer__c(Assessment_Question__c=lstSQ.get(0).id,
            Completed_Assessment__c=recSR.id,
            Response_Note__c='Test Notes',ValidFromDateTime__c=system.now().addMinutes(-1)));
    lstCAA.add(new Completed_Assessment_Answer__c(Assessment_Question__c=lstSQ.get(1).id,
            Completed_Assessment__c=recSR.id,   Sub_Question__c='SubQues1',
            Choice__c='Option1',ValidFromDateTime__c=system.now().addMinutes(-1)));
    insert lstCAA;

     
    Completed_Assessment_Answer__c recCAA = new Completed_Assessment_Answer__c(
        Completed_Assessment__c=recSR.id,
        Assessment_Question__c=lstSQ.get(1).id,ValidToDateTime__c=system.now(),ValidFromDateTime__c=system.now());
    
    insert recCAA;
            

    ApexPages.currentPage().getParameters().put('id', recCAA.id);
    AssessmentCompletedAuditController conCls= new AssessmentCompletedAuditController(
        new ApexPages.StandardController(recSR));
        
    ApexPages.currentPage().getParameters().put('isFirstRecord', '1');    
    AssessmentCompletedAuditController conCls2= new AssessmentCompletedAuditController(
        new ApexPages.StandardController(recSR));
  
}
public testMethod static void TestAssessmentCompletedViewController()
{
   Assessment__c recSrvy = new Assessment__c(Assessment_Header__c='MI Test Header',Assessment_Section__c='1\tSection1\n2\tSection2',Status__c ='Active');
    insert recSrvy;
    
    Contact recCon = new Contact(Salutation='Mr',FirstName='Abc',LastName='TestLastName',MailingPostalCode ='ABC123', Birthdate =Date.Today(),
        RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and name like 'Person with dementia%'].id);
    insert recCon;

    Account accRec = new Account(Name='Midlands Central Locality',RecordTypeId=[Select Id from RecordType where SObjectType='Account' and Name like 'Internal%'].id);
    insert accRec;
    
    Services__c serv = new Services__c(Locality__c=accRec.id,Service_Type__c='Advocacy');//Name='testControllerService');
    insert serv;    
    
    Service_Usage__c recSU = new Service_Usage__c(Service_Field__c=serv.id,Primary_Service_User__c=recCon.id,
        Service_Type__c='Advocacy');
    insert recSU;
    
    List<Assessment_Question__c> lstSQ = new List<Assessment_Question__c>();
    lstSQ.add(new Assessment_Question__c(Question__c='Freetext Questionaire',Assessment__c=recSrvy.id,Section_Header__c='Section1',Type__c='Freetext',QuestionNumber__c='1'));
    lstSQ.add(new Assessment_Question__c(Question__c='Combo Questionaire',Assessment__c=recSrvy.id,Section_Header__c='Section2',Type__c='Combo',
    Choices__c='Option1\nOption2\nOption3',Sub_Question__c='SubQues1\nSubQues2\nSubQues3',QuestionNumber__c='2'));
    insert lstSQ;
    
    Completed_Assessment__c recSR = new Completed_Assessment__c(Assessment__c=recSrvy.id,Service_Usage__c=recSU.id);
    insert recSR;
    
    List<Completed_Assessment_Answer__c> lstCAA = new List<Completed_Assessment_Answer__c>();
    lstCAA.add(new Completed_Assessment_Answer__c(Assessment_Question__c=lstSQ.get(0).id,
            Completed_Assessment__c=recSR.id,
            Response_Note__c='Test Notes',ValidFromDateTime__c=system.now().addMinutes(-1)));
    lstCAA.add(new Completed_Assessment_Answer__c(Assessment_Question__c=lstSQ.get(1).id,
            Completed_Assessment__c=recSR.id,   Sub_Question__c='SubQues1',
            Choice__c='Option1',ValidFromDateTime__c=system.now().addMinutes(-1)));
    insert lstCAA;

     
    Completed_Assessment_Answer__c recCAA = new Completed_Assessment_Answer__c(
        Completed_Assessment__c=recSR.id,
        Assessment_Question__c=lstSQ.get(1).id,ValidToDateTime__c=system.now(),ValidFromDateTime__c=system.now());
    
    insert recCAA;
            

    ApexPages.currentPage().getParameters().put('id', recSR.id);
    ApexPages.currentPage().getParameters().put('isFirstRecord', '1');  
    AssessmentCompletedViewController conCls= new AssessmentCompletedViewController(
        new ApexPages.StandardController(recSR));
        
    //  
    //AssessmentCompletedViewController conCls2= new AssessmentCompletedViewController(
    //    new ApexPages.StandardController(recSR));
    conCls.getAuditTrail();
    conCls.cancel();
}
public TestMethod static void TestAssessmentCompletedControllerWizard(){
    //Assessment__c 
    Assessment__c recSrvy = new Assessment__c(Assessment_Header__c='MI Test Header',Assessment_Section__c='1\tSection1\n2\tSection2',Status__c ='Active');
    insert recSrvy;
    
    //Contact 
    Contact recCon = new Contact(LastName='TestLastName',FirstName='TestFirstName', MailingPostalCode ='ABC123', Birthdate =Date.Today(),
        RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and name like 'Person with dementia%'].id);
    insert recCon;

    //Account 
    Account accRec = new Account(Name='Midlands Central Locality',RecordTypeId=[Select Id from RecordType where SObjectType='Account' and Name like 'Internal%'].id);
    insert accRec;
    Services__c serv = new Services__c(Locality__c=accRec.id,Service_Type__c='Advocacy');//Name='testControllerService');
    insert serv;
       
    Service_Usage__c recSU = new Service_Usage__c(Service_Field__c=serv.id,Primary_Service_User__c=recCon.id,
        Service_Type__c='Advocacy');
    insert recSU;
    
    List<Assessment_Question__c> lstSQ = new List<Assessment_Question__c>();
    lstSQ.add(new Assessment_Question__c(Question__c='Freetext Questionaire',Assessment__c=recSrvy.id,Section_Header__c='Section1',Type__c='Freetext',QuestionNumber__c='1'));
    lstSQ.add(new Assessment_Question__c(Question__c='Combo Questionaire',Assessment__c=recSrvy.id,Section_Header__c='Section2',Type__c='Combo',
    Choices__c='Option1\nOption2\nOption3',Sub_Question__c='SubQues1\nSubQues2\nSubQues3',QuestionNumber__c='2'));
    insert lstSQ;
    
    Completed_Assessment__c recSR = new Completed_Assessment__c(Assessment__c=recSrvy.id,Service_Usage__c=recSU.id);
    insert recSR;
    
    List<Completed_Assessment_Answer__c> lstCAA = new List<Completed_Assessment_Answer__c>();
    lstCAA.add(new Completed_Assessment_Answer__c(Assessment_Question__c=lstSQ.get(0).id,
            Completed_Assessment__c=recSR.id,
            Response_Note__c='Test Notes',ValidFromDateTime__c=system.now()));
    lstCAA.add(new Completed_Assessment_Answer__c(Assessment_Question__c=lstSQ.get(1).id,
            Completed_Assessment__c=recSR.id,   Sub_Question__c='SubQues1',
            Choice__c='Option1',ValidFromDateTime__c=system.now()));
    insert lstCAA;

    //New survey
    ApexPages.currentPage().getParameters().put('sid', null);
    ApexPages.currentPage().getParameters().put('suid', recSU.id);
    ApexPages.currentPage().getParameters().put('id', null);
    ApexPages.Standardcontroller con = new ApexPages.StandardController(recSR);
    
    AssessmentCompletedControllerWizard conCls= new AssessmentCompletedControllerWizard(new ApexPages.StandardController(recSR));
    ApexPages.currentPage().getParameters().put('sid', recSrvy.id);
    conCls= new AssessmentCompletedControllerWizard(new ApexPages.StandardController(recSR));
 
    //ApexPages.currentPage().getParameters().put('suid', recSU.id);   
    //ApexPages.currentPage().getParameters().put('sid', recSrvy.id);
    //ApexPages.currentPage().getParameters().put('suid', recSU.id);
    ApexPages.currentPage().getParameters().put('id', recSR.id);
    ApexPages.currentPage().getParameters().put('retURL', recSU.id);
    ApexPages.currentPage().getParameters().put('section', '1');
    AssessmentCompletedControllerWizard conCls2= new AssessmentCompletedControllerWizard(new ApexPages.StandardController(recSR));
    conCls2.lstSections.get(0).lstAssessmentQuestions.get(0).respAnsRec.Response_Note__c='Modified';
    conCls2.strReturnToPage ='true';
    conCls2.SaveAssessment();
    conCls2.getAuditTrail();
    conCls2.NextPage();
    conCls2.PreviousPage();
    conCls2.pageNumber = 1;
    conCls2.GoToPage();
    String retStr;
    conCls2.strRetURL = 'http:/test';
    retStr=  conCls2.strRetURL();
    conCls2.strRetURL = recSU.id;
    retStr=  conCls2.strRetURL();
    
    List<Assessment_Question__c> lstSQ2 = new List<Assessment_Question__c>();
    lstSQ2.add(new Assessment_Question__c(Question__c='Freetext Questionaire',Assessment__c=recSrvy.id,Section_Header__c='Section1',Type__c='Freetext',QuestionNumber__c='1'));
    
    lstSQ2.add(new Assessment_Question__c(Id=lstSQ.get(1).id,Question__c='Combo Questionaire',Assessment__c=recSrvy.id,Section_Header__c='Section2',Type__c='Combo',
    Choices__c='Option1\nOption2\nOption3',Sub_Question__c='SubQues4',QuestionNumber__c='2'));
    
    lstSQ2.add(new Assessment_Question__c(Question__c='Combo Questionaire2',Assessment__c=recSrvy.id,Section_Header__c='Section2',Type__c='Combo',
    Choices__c='Option1\nOption2\nOption3',Sub_Question__c='SubQues1\nSubQues2\nSubQues3',QuestionNumber__c='3'));   
    
    upsert lstSQ2;
    AssessmentCompletedControllerWizard conCls3= new AssessmentCompletedControllerWizard(new ApexPages.StandardController(recSR));
    
}


}