src/objects/BDR__c.object
<CustomObject>
    <description>The entry point for a defined business relationship related to a set of service proposals, funding proposals and contracts. The BDR can be linked to multiple services, but at present only one Income Block.</description>
    <fields>
        <fullName>Any_redundancies__c</fullName>
        <inlineHelpText>describe if this proposal has the potential to incur redundancies.  This may be because of staff restructuring, or because of a potential loss of funding</inlineHelpText>
        <label>Redundancy Implications</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BDR_Name__c</fullName>
        <description>The Name of the BDR</description>
        <inlineHelpText>The BDR name should begin with the Area abbreviation (see user guide), followed by the service name and then town or geographical area</inlineHelpText>
        <label>BDR Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bid_Sign_Off_Deadline__c</fullName>
        <inlineHelpText>This is the latest possible date when you need all Alzheimer’s Society approvers to have approved your proposal on the system (usually around a week before you need to submit your tender)</inlineHelpText>
        <label>Bid Sign Off Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Bid_Status__c</fullName>
        <label>Bid Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Successful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Bid_Submission_Deadline__c</fullName>
        <inlineHelpText>Make sure you plan to submit at least a day or two before the official deadline in order leave enough time for potential problems with the submission process/portal</inlineHelpText>
        <label>Bid Submission Deadline</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Clarification_Questions_Deadline__c</fullName>
        <description>Deadline for questions on a formal tender</description>
        <label>Clarification Questions Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fixed_Tender_Amount__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is an amount specified by the commissioner or fund source</description>
        <inlineHelpText>Tick if funding available is a fixed amount</inlineHelpText>
        <label>Fixed Tender Amount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recruitment_Required__c</fullName>
        <inlineHelpText>Describe how many staff and/or volunteers you will require to run the service/s and whether these are already in post or will need to be recruited.  Describe the types of staff and/or volunteers you will require</inlineHelpText>
        <label>Any recruitment?</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Tupe_Detail__c</fullName>
        <inlineHelpText>Please include any detail here which will help HR to understand the support you are likely to need from them.</inlineHelpText>
        <label>Tupe Detail</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Tupe__c</fullName>
        <inlineHelpText>If no TUPE implications leave as None. If a tender is likely to involve staff transferring to AS, choose TUPE in. If we have staff in post who might move to a new funder if we are unsuccessful, choose TUPE out.</inlineHelpText>
        <label>Tupe</label>
        <picklist>
            <picklistValues>
                <fullName>Tupe In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tupe Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Recruitment__c</fullName>
        <label>zzAny volunteer recruitment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>BDR</label>
    <nameField>
        <displayFormat>BDR-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BDRBidWizard.cls
public without sharing class BDRBidWizard {
/*

  *************** CAUTION ****************
  This class set to WITHOUT SHARING to enable all records to be updated
  by any user. Access to certain records is controlled via the 
  sharing rules and access to the UI components
    
  gary.grant@conseq.co.uk 
  Jan 2013
  A combined controller to handle creating and editing a bdr package
  The package contains the bdr header, the contract, any related services (with Evidence for Needs), related income blocks
  
  Funding Requirements, Evidence For Needs and Allocations are 
  retrieved and held in both separate lists and inside their respective wrappers
  This avoids the need for multiple queries inside each wrapper and also 
  enables the set of records to be updated in a single operation
  
  This is odd (having the same object accessible via a wrapper and 
  as a consolidated standalone list), but it's a Salesforce thing....   


  TODO !! Remove actions : Contract, BID, Partner, Income
  
*/

public ApexPages.StandardController stdController;
public BDR__c bdr  {get;set;} 
public string BDRName  {get;set;}
public string BDRReference {get;set;}
public id BDRid  {get;set;}
public Boolean inWizard {get;set;}
public Boolean bHasBid  {get;set;}


//constructor

public BDRBidWizard (ApexPages.StandardController pController) {
    stdController = pController;
    bdr = [select id, Name, BDR_Name__c, 
                            Bid_Status__c, 
                            Clarification_Questions_Deadline__c,
                            Bid_Sign_Off_Deadline__c,
                            Bid_Submission_Deadline__c,
                            Fixed_Tender_Amount__c,
                            Tupe__c,
                            Tupe_Detail__c,
                            Recruitment_Required__c,
                            Any_Redundancies__c,
                            Volunteer_Recruitment__c
             from BDR__c where id=:ApexPages.currentPage().getParameters().get('id')]; 
    BDRid  =bdr.id;
    BDRName = bdr.BDR_Name__c;
    BDRReference = bdr.Name;
    String strWizard;
    strWizard=ApexPages.currentPage().getParameters().get('BDRwizard');
    if (strWizard==null) {inWizard = false;}
    if (strWizard=='1') {inWizard = true;} else {inWizard=false;}
    
    if ((bdr.Bid_Status__c==null)||(bdr.bid_status__c=='')){
        bHasBid=false;}
    else {        bHasBid=true;}

}

    public PageReference cancel(){
        return new PageReference('/apex/BDRView?id='+ bdrid );
    } 
    public PageReference nextPage(){
        if (inWizard){
            return new PageReference('/apex/BDRAddContractWizard?id='+ bdrid +'&BDRWizard=1');
        }
        else {
            return new PageReference('/apex/BDRView?id='+ bdrid );
        }
    }

 public PageReference AddBid(){
     bHasBid=true;
     return null;
 }
 public PageReference saveBidAndContinue(){
      update bdr;
      return null;
 }
  public PageReference saveBid(){
      update bdr;
      return nextPage();
 }
}