src/objects/BDR__c.object
<CustomObject>
    <description>The entry point for a defined business relationship related to a set of service proposals, funding proposals and contracts. The BDR can be linked to multiple services, but at present only one Income Block.</description>
    <fields>
        <fullName>Bid_Feedback_Detail__c</fullName>
        <description>More detail about the reasons a bid or tender was not successful</description>
        <inlineHelpText>Provide some detail about the reasons a bid or tender was not successful</inlineHelpText>
        <label>Feedback Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Bid_Feedback__c</fullName>
        <description>The primary factor a contract or tender was not successful</description>
        <inlineHelpText>The primary factor a contract or tender bid was not successful</inlineHelpText>
        <label>External Feedback</label>
        <picklist>
            <picklistValues>
                <fullName>Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price/Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strong Competition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capacity to Deliver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Fit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partnership</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BDR</label>
    <nameField>
        <displayFormat>BDR-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Evidence_for_Need__c.object
<CustomObject>
    <description>A document recording the evidence for the need for a specific service</description>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BDR Evidence for Need</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDR Evidence for Needs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Funding_Requirement__c.object
<CustomObject>
    <description>A single figure representing the funding requirement to cover the costs of providing the service, including FCR</description>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Financial Year</label>
        <picklist>
            <picklistValues>
                <fullName>2010/11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011/12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012/13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013/14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014/15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015/16</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BDR Service Cost</label>
    <nameField>
        <displayFormat>FR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDR Service Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>service_status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestBDRComponents.cls
@isTest
public class TestBDRComponents {

    /***********************************************************************************************
     * @author          gary.grant@conseq.co.uk   
     * @date            June 2013 
     * @description     A set of test methods for BDR Application components
    ***********************************************************************************************/

static testMethod void TestAddServices()
{
	Map<String, Object> mapTestData= TestBdrUtils.getTestData();
	Map<String, BDR__c> mapBdr = (Map<String,BDR__c>)mapTestData.get('bdr');
	BDR__c bdr = (BDR__c)mapBdr.get('bdr1');   
	BdrWrapper bdrW = new BdrWrapper(bdr);
	
	Services__c svc = bdrW.services.svcRecords[0];
	
	bdrW.removeService(svc.id, false);
	BdrUtils.addService(bdr.id, svc.id);
	
	bdrW.removeService(svc.id, false);
	List<String> lisSvcIds = new List<String>();
	lisSvcIds.add(svc.id);
	BdrUtils.addServices(bdr.id, lisSvcIds);
	
}


static testMethod void TestDeleteService()
{
	Map<String, Object> mapTestData= TestBdrUtils.getTestData();
	Map<String, BDR__c> mapBdr = (Map<String,BDR__c>)mapTestData.get('bdr');
	BDR__c bdr = (BDR__c)mapBdr.get('bdr1');   
	BdrWrapper bdrW = new BdrWrapper(bdr);
	
	BDR__c bdr2 = (BDR__c)mapBdr.get('bdr2');
	
	List<BdrServiceWrapper> lis = bdrW.services.svcWrappers;
    BdrServiceWrapper svcW1 = lis[0];
    BdrServiceWrapper svcW2 = lis[1];
    
    Services__c svc1 = svcW1.svc;
    Services__c svc2 = svcW2.svc;
    
    /* True means delete as well as remove. 
       This will not actually do the deletion because the service is still linked to the orther BDR 
    */
    bdrW.removeService(svc1.id, true);
    bdrW.removeService(svc2.id, false);
	
	Test.startTest();
	ApexPages.StandardController sc = new ApexPages.standardController(bdr2);           
    BdrControllerExtension e = new BdrControllerExtension(sc); 
	
	/*Use the second BDR linked to the service. Deletion would fail if the Service was still connected to the first BDR 
	  in which case it would just be removed and not deleted. 	
	*/
	e.rid=(svc1.id);
	e.removeService();
	
	/*This deletion will succeed because the service is no longer linked to any other BDRs */  
	e.rid=(svc2.id);
	e.deleteService();
	
}





/*
static  testMethod void TestUpdateStatusUnsuccessful()
  {
	Map<String, Object> mapTestData= TestBdrUtils.getTestData();
	Map<String, BDR__c> mapBdr = (Map<String,BDR__c>)mapTestData.get('bdr');
	BDR__c bdr = (BDR__c)mapBdr.get('bdr1');   
	BdrWrapper bdrW = new BdrWrapper(bdr);
    
    Test.StartTest();
    
    Schema.DescribeFieldResult field = BDR__c.Bid_Feedback__c.getDescribe();
    Schema.PicklistEntry PickEntry = field.getPicklistValues()[0]; 
    String s = PickEntry.getLabel();    
    bdr.Bid_Feedback__c = s; 
  //  bdr.Bid_Feedback_Detail__c='This is a reason for unsuccessful';
    
    bdrW.updateStatus('Unsuccessful');
        
  // Service status will have rem,ained unaffected
    List<Services__c> lis = bdrW.services.svcRecords;
    for (Services__c svc : lis) {    
        System.assert(svc.service_status__c=='Draft');
    }

    ShowActionsTest(bdr);    
    
}*/

static void ShowActionsTest(BDR__c bdr){

    ApexPages.StandardController sc = new ApexPages.standardController(bdr);
    BdrControllerExtension e = new BdrControllerExtension(sc);
    
    boolean b = e.hasFiscalYears;    
    b = e.showSuccessActions;    
    b = e.showDeclinedAction;                      
    b = e.showAddServicesAction;

}

static testMethod void BdrControllerExtensionNewBdrTest()
{
   BDR__c bdr = new BDR__c();
   ApexPages.StandardController sc = new ApexPages.standardController(bdr);
   BdrControllerExtension e = new BdrControllerExtension(sc);
   
    boolean b = e.showSuccessActions;  
    b = e.showDeclinedAction;    
    b = e.showAddServicesAction;
   
}


static testMethod void BdrControllerExtensionSubmitTest()
{
      
	Map<String, Object> mapTestData= TestBdrUtils.getTestData();
	Map<String, BDR__c> mapBdr = (Map<String,BDR__c>)mapTestData.get('bdr');
	BDR__c bdr = (BDR__c)mapBdr.get('bdr1');   
  
    ApexPages.StandardController sc = new ApexPages.standardController(bdr);
   
    Test.startTest();    
    BdrControllerExtension e = new BdrControllerExtension(sc);

    List<BdrServiceWrapper> lis = e.bdrWrapper.services.svcWrappers;
    BdrServiceWrapper svcW = lis[0];
    Services__c svc = svcW.svc;
    Evidence_For_Need__c efn = svcW.evidence;
    
    e.evid=efn.id;
    e.updateEvidence();
    
    e.validateSubmit();
    
    e.cancel();
    e.cancelUpdateEvidence();

}

static testMethod void BdrControllerExtensionAddRemoveService()
{
      
	Map<String, Object> mapTestData= TestBdrUtils.getTestData();
	Map<String, BDR__c> mapBdr = (Map<String,BDR__c>)mapTestData.get('bdr');
	BDR__c bdr = (BDR__c)mapBdr.get('bdr1'); 
	BdrWrapper bdrW = new BdrWrapper(bdr);  	
  
    ApexPages.StandardController sc = new ApexPages.standardController(bdr);

    List<BdrServiceWrapper> lis = bdrW.services.svcWrappers;
    BdrServiceWrapper svcW = lis[0];
    Services__c svc = svcW.svc;
    
    Test.startTest();
    BdrControllerExtension e = new BdrControllerExtension(sc);

    e.rid=svc.id;
    e.removeService();    
    e.addServices();        
    Decimal d = e.servicesCount;        
    
}

static testMethod void BdrDeleteTest()
{

	Map<String, Object> mapTestData= TestBdrUtils.getTestData();
	Map<String, BDR__c> mapBdr = (Map<String,BDR__c>)mapTestData.get('bdr');
	BDR__c bdr = (BDR__c)mapBdr.get('bdr1');   

    ApexPages.StandardController sc = new ApexPages.standardController(bdr);
   
    Test.startTest();   
    BdrControllerExtension e = new BdrControllerExtension(sc);  
    e.doDelete();

}
/* Run thru the error trapping code in BdrServiceWrapperListUtils */  
static testMethod void BdrServiceWrapperListTest()
{
	Map<String, Object> mapTestData= TestBdrUtils.getTestData();
	Map<String, BdrServiceWrapperList> mapSwl = (Map<String, BdrServiceWrapperList>)mapTestData.get('swl');
	BdrServiceWrapperList svcWL = (BdrServiceWrapperList)mapSwl.get('swl1');   
	BdrServiceWrapper svcW = svcWL.svcWrappers[0];
	
    Evidence_for_Need__c efn = svcW.evidence;
    /* This is too big for the field size, so should throw an error and run the method thru the failed save code*/
    efn.Version__c=500000;
     
    boolean b = BdrServiceWrapperUtils.updateEvidence(efn, svcW.svc);
    System.assert(b==false);	
	
	List<BdrFundReqWrapper> lisFrW = svcW.fundReqWrappers;
	BdrFundReqWrapper frW = lisFrW[0];
	BdrFundReqWrapper frW2 = lisFrW[1];
	
	Funding_Requirement__c fr = frW.freq;
	Funding_Requirement__c fr2 = frW2.freq;
	
	/* This will throw an error on the uniqueFiscalService Field because of the duplicate fiscal year-service combo*/
	fr2.Fiscal_Year__c = fr.Fiscal_Year__c;
	
	List<Funding_Requirement__c> lisFr = new List<Funding_Requirement__c>();
	lisFr.add(fr);
	lisFr.add(fr2);
	
	b = BdrServiceWrapperUtils.updateFundingRequirements(lisFr, svcW.svc);
	system.assert(b==false);
	
}



static testMethod void BdrControllerExtensionSetDeclinedTest()
{
      
	Map<String, Object> mapTestData= TestBdrUtils.getTestData();
	Map<String, BDR__c> mapBdr = (Map<String,BDR__c>)mapTestData.get('bdr');
	BDR__c bdr = (BDR__c)mapBdr.get('bdr1');   
  
    ApexPages.StandardController sc = new ApexPages.standardController(bdr);
    
    Schema.DescribeFieldResult field = BDR__c.Bid_Feedback__c.getDescribe();
    Schema.PicklistEntry PickEntry = field.getPicklistValues()[0]; 
    String s = PickEntry.getLabel();    
    bdr.Bid_Feedback__c = s; 
    bdr.Bid_Feedback_Detail__c='This is a reason for unsuccessful';
    
    Test.startTest();

    BdrControllerExtension e = new BdrControllerExtension(sc);
    e.setDeclined();
}

static testMethod void BdrControllerExtensionSetUnSuccessfulTest()
{
      
	Map<String, Object> mapTestData= TestBdrUtils.getTestData();
	Map<String, BDR__c> mapBdr = (Map<String,BDR__c>)mapTestData.get('bdr');
	BDR__c bdr = (BDR__c)mapBdr.get('bdr1');   
  
    ApexPages.StandardController sc = new ApexPages.standardController(bdr);
    
    Schema.DescribeFieldResult field = BDR__c.Bid_Feedback__c.getDescribe();
    Schema.PicklistEntry PickEntry = field.getPicklistValues()[0]; 
    String s = PickEntry.getLabel();    
    bdr.Bid_Feedback__c = s; 
   bdr.Bid_Feedback_Detail__c='This is a reason for unsuccessful';
    
    Test.startTest();

    BdrControllerExtension e = new BdrControllerExtension(sc);
    e.setUnsuccessful();
}

static testMethod void BdrDependentTest()
{
      
	Map<String, Object> mapTestData= TestBdrUtils.getTestData();
	Map<String, BDR__c> mapBdr = (Map<String,BDR__c>)mapTestData.get('bdr');
	BDR__c bdr = (BDR__c)mapBdr.get('bdr1');   
	BdrWrapper bdrW = new BdrWrapper(bdr);
    
    Test.startTest();
    List<BDR__c> lisBdr = BdrUtils.getDependentBdrs(bdrW);      

}

static testMethod void bdrWrapperAllocationCalcTest()
{

	Map<String, Object> mapTestData= TestBdrUtils.getTestData();
	Map<String, BDR__c> mapBdr = (Map<String,BDR__c>)mapTestData.get('bdr');
	BDR__c bdr = (BDR__c)mapBdr.get('bdr1');   
	BdrWrapper bdrW = new BdrWrapper(bdr);
    
    Test.startTest();
    String s='';
    s=bdrW.hasPartner;
    boolean b = bdrW.hasFiscalYears;
            
    Decimal d = 0;
    d=bdrW.totalAllocation;
    d=bdrW.totalFundingRequirement;
    d=bdrW.totalOtherSecureAllocation;
    d=bdrW.totalOtherProposedAllocation;
    
}

static testMethod void TestValidateBdr()
{

	Map<String, Object> mapTestData= TestBdrUtils.getTestData();
	Map<String, BDR__c> mapBdr = (Map<String,BDR__c>)mapTestData.get('bdr');
	BDR__c bdr = (BDR__c)mapBdr.get('bdr1');   
	BdrWrapper bdrW = new BdrWrapper(bdr);

	List<String> lis = bdrW.validateBDR();

}

static testMethod void TestCustomUtils()
{
	Map<String, Object> mapTestData= TestBdrUtils.getTestData();
	Map<String, User> mapUser = (Map<String,User>)mapTestData.get('users');
	User u = (User)mapUser.get('userBDM');   
	
	List<Group> lis = CustomUtils.getGroupsForUser(u.id);
	boolean b = CustomUtils.isUserInPermissionSet(u.id, 'Dummy Set');

	/* Get a random role name */
	UserRole role = [select name from UserRole limit 1];	
	b = CustomUtils.isUserInOrAboveRole(u.id, role.Name);
	
}


}