src/objects/BDR__c.object
<CustomObject>
    <description>The entry point for a defined business relationship related to a set of service proposals, funding proposals and contracts. The BDR can be linked to multiple services, but at present only one Income Block.</description>
    <fields>
        <fullName>BDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BDM</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>BDM</value>
            </filterItems>
            <infoMessage>Select the BDM or enter a different user name if none exists</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>BDRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BDR</label>
    <nameField>
        <displayFormat>BDR-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ConfigText__c.object
<CustomObject>
    <description>A block of text that can be used in any application to configurable blocks of text, lists etc</description>
    <fields>
        <fullName>Body__c</fullName>
        <description>The text of the configuration item</description>
        <label>Body Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>BDR: Contract Risk Index</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDR: Income Block Help Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDR: Approval Dialog Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDR: Introduction Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDR: BDR Search Screen Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDR: Services Search Screen Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDR: Fund Coverage Search Screen Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>ConfigText</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ConfigTexts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Disable_Rules__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>A collection of vars that can be included in code to disable action in certain instances.</description>
    <fields>
        <fullName>Disable_Triggers__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use this value in a Trigger to disable the code.</description>
        <label>Disable Triggers</label>
        <type>Checkbox</type>
    </fields>
    <label>Disable Rules</label>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>National_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>National Service?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>service_street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>service_type__c</fullName>
        <inlineHelpText>Service description will be automatically populated from the service type (or sub type if there is one)</inlineHelpText>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult education &amp; training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (emotional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (financial)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (general)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awareness raising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending / home support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counselling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day support / day care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafés</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exercise / Fitness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home facilities &amp; services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Dementia)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Financial &amp; Legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programmes &amp; provision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <recordTypes>
        <fullName>External</fullName>
        <active>true</active>
        <description>External Service/Activity</description>
        <label>External Service</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CustomUtils_Test.cls
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : APEX Test Class for SelectObjectForInitConfigController.
 *  Author  : Lakshmi Rajendram
 *  Date    : 25-11-2014
 *  Version : 0.1 Unit Test
 *
 *               
 *  Modification History
 *  Date            Who         Description 
 *  dd-mm-yyyy      ??          ????                           
*******************************************************************************************/
@isTest                    
public class CustomUtils_Test {


	   static TestMethod void test_isApprovalInProcess()
	   {	   	 
		 boolean b = CustomUtils.isApprovalInProcess('RandomIdText');	   		                     
	   }
	   


	   public static TestMethod void test_ApprovalMethods()
	   {
	   	
	   	   Map<String, Object> mapTestData= TestBdrUtils.getTestData();
	  	   Map<String, BDR__c> mapBdr = (Map<String,BDR__c>)mapTestData.get('bdr');
	  	   BDR__c bdr = (BDR__c)mapBdr.get('bdr1');   	   
	  
	  	   /* Submit for approval */	
	       Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
	       req.setComments('Submitted for approval. Please approve this Participant for Active status.');
	       req.setObjectId(bdr.id);
	       Approval.ProcessResult result = Approval.process(req);	 	
	   	
	       String s = CustomUtils.getCurrentApprovalActorName(bdr.id);
	       
	       User u1 = [select id from User where isActive = true limit 1];
	       boolean b = CustomUtils.isCurrentApprovalActor(bdr.id, u1.id);                            
	       
	       List<String> lis = CustomUtils.getObjectIdsPendingApprovalbyUserId(bdr.BDM__c, 'BDR__c');                            
	       List<SelectOption> lisOptions = CustomUtils.getPendingApproversForObjectType('BDR__c');                            
	                                   
	       List<ProcessInstance> LisPi = CustomUtils.getApprovalHistories(bdr.id);
	       
	       List<Group> lisGrp = CustomUtils.getGroupsForUser(bdr.BDM__c); 
	                                   
	   }
	   
	   
	   static TestMethod void test_getCurrentUserProfileName() {
	   
	     String s = CustomUtils.getCurrentUserProfileName();
	   }
	
	   static TestMethod void test_hasUserAccess()
	   {              
	       
	       User u1 = [select id from User where isActive = true limit 1];
	       ConfigText__c cfg = new ConfigText__c(Type__c = 'TestType', OwnerId = u1.id);	       
	       insert cfg;
	    	       
	       CustomUtils.hasUserAccess(cfg.id, u1.id, 'Edit');
	       CustomUtils.hasUserAccess(cfg.id, u1.id, 'Read');
	       CustomUtils.hasUserAccess(cfg.id, u1.id, 'All');
	       CustomUtils.hasUserAccess(cfg.id, u1.id, 'Update');
	       
	       
	   }
	
	   /* Check for modifyAllData permissions */
	   public static TestMethod void test_isModifyAllData()
	   {
	   	   User u1 = [select id from User where isActive=true limit 1];
	   	   CustomUtils.isModifyAllData(u1.id);
	   	               
	   } 
	 
	   /* Get a Config Text Item for a given type*/  
	   public static TestMethod void test_getConfigText()
	   {
	     
	     ConfigText__c cfg = new ConfigText__c(Type__c = 'TestType');
	     insert cfg;
	     
	     ConfigText__c cfg1 = CustomUtils.getConfigText('TestType');
	     cfg1 = CustomUtils.getConfigText('OtherType');
	          
	
	   }
	   
	   /* Test if a user is in a Permission Set */
	   public static TestMethod void test_isUserInPermissionSet()
	   {	   	
	   	   PermissionSetAssignment psa = [select AssigneeId, PermissionSet.Name from PermissionSetAssignment limit 1];         			
	   	   Boolean b = CustomUtils.isUserInPermissionSet(psa.AssigneeId, psa.PermissionSet.Name);
	   	   system.assert(b);
	   }
	
	
	    public static TestMethod void test_isUserInOrAboveRole() {
	 	    
	     User u1 = [select id, UserRole.Name from User where isActive=true and UserRole.Name!= null limit 1];
	     Boolean b = CustomUtils.isUserInOrAboveRole(u1.id, u1.UserRole.Name); 
	    
	  }
		      
	  public static TestMethod void test_objectWithAllFields()
	  {
	    
	     ConfigText__c cfg = new ConfigText__c(Type__c = 'TestType');
	     insert cfg;
	     
	     SObject o = CustomUtils.objectWithAllFields('id', cfg.id, Schema.sObjectType.ConfigText__c);	    
	        
	  } 
	 
	      
   public static TestMethod void  test_objectMapWithAllFields()
	  {
	    
	       ConfigText__c cfg = new ConfigText__c(Type__c = 'TestType');
	       insert cfg;
	       
	       List<String> lis = new List<String>();
	       lis.add(cfg.id);
	       
	       Map<String, sObject> mapO = CustomUtils.objectMapWithAllFields('id', lis, Schema.sObjectType.ConfigText__c);
	  }
	   
   public static TestMethod void  test_getGroupsForUser()
	   {
	   	   User u1 = [select id from User where isActive = true limit 1];
	   	   List<Group> lisGroup = CustomUtils.getGroupsForUser(u1.id);
	   }
	   
	public static TestMethod void  test_getFieldValues() {
	  
	       ConfigText__c cfg = new ConfigText__c(Type__c = 'TestType');
	       insert cfg;
	       
	       sObject[] v = new sObject[1];	     
	       v[0] = cfg;  
	         
	       Schema.DescribeFieldResult F = ConfigText__c.Type__c.getDescribe();
		   Schema.sObjectField T = F.getSObjectField();  
	       Set<String> setV = CustomUtils.getFieldValues(v,T); 
	} 
	

	public static TestMethod void test_getObjectFieldIds() 
	  {
	   
	   	ConfigText__c cfg = new ConfigText__c(Type__c = 'TestType', Body__c = 'F1:V1;F2:V2', Name = 'ConfigText_fields');
	    insert cfg;
	    
	    Map<String, String> mapO = CustomUtils.getObjectFieldIds('ConfigText');	      
	    mapO = CustomUtils.getObjectFieldIds('NoSuchObject');
	  
	  } 
	  
	public static TestMethod void test_initObjectFieldConfigTexts()
	{
		
		List<String> lis = new List<String>();
		lis.add('ConfigText__c');
		CustomUtils.initObjectFieldConfigTexts(lis);
		
	}  
	
	
    public static TestMethod void test_wrapApostrophe() {
	       
	    String s = CustomUtils.wrapApostrophe('RandomText');
	} 

	public  testMethod static void TestDisableTriggers() {
	 
	 Disable_Rules__c dr = new  Disable_Rules__c(Disable_Triggers__c=true,SetupOwnerId = UserInfo.getprofileId());
	 insert dr;
	
	 boolean b = CustomUtils.isDisabledTriggers();	
	 
	 Account acc1 = new Account(Name='Midlands Central Locality',RecordTypeId=[Select Id from RecordType where SObjectType='Account' and Name like 'External%'].id);
	 insert acc1;
	              
	 System.debug('Account: [' + acc1.AccountNumber+ '] has inserted into system.');
	 Services__c s = new Services__c(Name='Midlands Central Advocacy',service_street__c= 'test the street name long ass string first more than 80 character for testing the',Service_Type__c='Advocacy', National_Service__c=True,RecordTypeId=[Select Id from RecordType where SObjectType='Services__c' and Name like 'External%'].id);
	 insert s;
	            
	 delete dr;
	        
	 s.service_street__c = 'test with three\nline address this\nis street address\nthis is street address 3';
	 update s;
	 
	 
	}
		 
	public static TestMethod void test_getOptions() 
	 {	
	    List<SelectOption> options = CustomUtils.getOptions(ConfigText__c.Type__c.getDescribe());	    			
	 }
	 
	 public static TestMethod void test_listAsString() {		 
	 	
	 	List<String> lis = new List<String>();
	 	lis.add('one');
	 	lis.add('two');
	 	
	 	String s = CustomUtils.listAsString(lis);
	 
	 }
	 
	 public static TestMethod void test_isUserInGroupName() {		 
	 		 	
		User u1 = [select id from User where isActive = true limit 1];
	 	boolean b = CustomUtils.isUserInGroupName(u1.id, 'A Random Group');
	 
	 }  
    
 }