src/objects/Bid__c.object
<CustomObject>
    <fields>
        <fullName>BDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This bid&apos;s Business Development Manager</inlineHelpText>
        <label>BDM</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>startsWith</operation>
                <value>BDM</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>startsWith</operation>
                <value>Regional Management -</value>
            </filterItems>
            <infoMessage>Please select a Business Development Manager</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bid_value__c</fullName>
        <label>Bid value</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The approved proposal that led to this bid.</description>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid</label>
    <nameField>
        <label>Bid Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Proposal__c.object
<CustomObject>
    <fields>
        <fullName>BDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BDM</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>This person is not a Business Development Manager</errorMessage>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>startsWith</operation>
                <value>BDM</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>startsWith</operation>
                <value>Regional Management -</value>
            </filterItems>
            <infoMessage>Please select a Business Development Manager</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_definition__c</fullName>
        <label>zzdel_Service definition</label>
        <picklist>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counselling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day support from other providers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia advisers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafés</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home support from other providers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programmes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information provision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outings and day trips</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provision of grants for holidays/other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singing for the brain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telephone helplines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other services</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Test_BDC_Triggers.cls
/**
 * Test methods for BDC triggers on Bids and Proposals
 */
@isTest
private class Test_BDC_Triggers {
    /*
     * Test Bid sharing with BDM user
     */
    static testMethod void TestBidTrigger() {
        // find BDM user
        UserRole role = [select id from UserRole where Name = 'BDM - North' limit 1]; 
        User u = [select id from User where isActive = true and UserRoleId = :role.Id limit 1];
        
        Bid__c bid = new Bid__c();
        bid.Name = 'Test Bid';
        bid.BDM__c = u.Id;
        bid.Bid_value__c = 12;
        
        insert bid;
    }
    
    
    /*
     * Test Proposal sharing with BDM user
     */
     
    static testMethod void TestProposalTrigger() {
        // find BDM user account
        UserRole role = [select id from UserRole where Name = 'BDM - North' limit 1]; 
        User u = [select id from User where isActive = true and UserRoleId = :role.Id limit 1];
        
        Proposal__c proposal = new Proposal__c();
        proposal.Name = 'Test Proposal';
        proposal.BDM__c = u.Id;
        proposal.Service_definition__c = 'Advocacy';
        
        insert proposal;
    }
}