src/objects/Change_Control__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project that the change is linked to</description>
        <inlineHelpText>Projects are larger chunks of work, and may include many changes raised individually.</inlineHelpText>
        <label>Project</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Change Control</label>
    <nameField>
        <displayFormat>Change-{00000}</displayFormat>
        <label>Change Control Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SFDC_Issue__c.object
<CustomObject>
    <description>Issue related to a Project</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Change Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Feature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defect</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Issue_Detail__c</fullName>
        <inlineHelpText>How to replicate the issue, which browser versions are affected, which users are affected, specific data that triggers the issue, differences between expected and actual behaviour. Include a URL to the affected page is possible.</inlineHelpText>
        <label>Issue Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SFDC_Issue_Description__c</fullName>
        <description>Description of the Issue in detail.</description>
        <label>Issue Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SFDC_Issue_Name__c</fullName>
        <label>Issue Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Issue_Priority__c</fullName>
        <label>Issue Priority</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Critical</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SFDC_Issue_Status__c</fullName>
        <label>Issue Status</label>
        <picklist>
            <picklistValues>
                <fullName>0 - Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1 - Being Addressed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - In Escalation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99 - Not an Issue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SFDC_Project__c</fullName>
        <description>Issues are details of the master project record</description>
        <label>Project</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipLabel>Issues</relationshipLabel>
        <relationshipName>Project_Issues</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>SFDC_Sub_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Project</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Select a sub project from the selected project</errorMessage>
            <filterItems>
                <field>$Source.SFDC_Project__c</field>
                <operation>equals</operation>
                <valueField>SFDC_Sub_Project__c.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SFDC_Sub_Project__c</referenceTo>
        <relationshipLabel>Issues</relationshipLabel>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Issue Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N700000023TWsEAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Issue</label>
    <nameField>
        <displayFormat>ISS - {0000}</displayFormat>
        <label>Issue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SFDC_Project__c.object
<CustomObject>
    <description>Project Management</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SFDC_Sub_Project__c.object
<CustomObject>
    <description>A sub project on a Project</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipLabel>Sub_Projects</relationshipLabel>
        <relationshipName>Sub_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sub Project</label>
    <nameField>
        <label>Sub Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub_Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PI_IssueSearchController.cls
public with sharing class PI_IssueSearchController {


   /***********************************************************************************************************
    *
    *   @author      :    gary.grant@conseq.co.uk
    *   @date        :    April 2015
    *
    *   @description :    Search for Issues in the Projects/ Issues application 
    *   
    ************************************************************************************************************/
 
  // The soql without the order and limit
  transient private String soql {get;set;}
  
  public String project {get;set;}
  public String subProject {get;set;}
  public String owner {get;set;}

  public List<String> status_selection {get;set;}
  public List<String> priority_selection {get;set;}
  public List<String> category_selection {get;set;}

  public List<SFDC_Issue__c> searchResults {get;set;}
  
  public Integer resultCount = 0;

  public PI_IssueSearchController (){
      init();      
  }
  
  
  /* The properties below are the filters available */
  
  /* STATUS */  
  public List<SelectOption> getStatusOptions() {
    Schema.DescribeFieldResult field = SFDC_Issue__c.SFDC_Issue_Status__c.getDescribe();
    return CustomUtils.getOptions(field);          
  }
  
  /* CATEGORY */
  public List<SelectOption> getCategoryOptions() {
    Schema.DescribeFieldResult field = SFDC_Issue__c.Category__c.getDescribe();
    return CustomUtils.getOptions(field);
  }
  
  /* PRIORITY */
  public List<SelectOption> getPriorityOptions() {
    Schema.DescribeFieldResult field = SFDC_Issue__c.SFDC_Issue_Priority__c.getDescribe();
    return CustomUtils.getOptions(field);
  }
  
  /* Project */
  public List<SelectOption> getProjectOptions() {
        
    String sPrefix = SFDC_Issue__c.sObjectType.getDescribe().getKeyPrefix();    
    AggregateResult[] projects = [select SFDC_Project__r.Name, MAX(SFDC_Project__r.id) Id from SFDC_Issue__c group by SFDC_Project__r.Name];
    
    List<SelectOption> options = new List<SelectOption>();             
    options.add(new SelectOption('','')); 
    for (AggregateResult aggr : projects) {

      if ( (String)aggr.get('Id') != null ) {

          String l = (String)aggr.get('Name');
          String v = (String)aggr.get('Id');
          options.add(new SelectOption(v,l));       
       }

       
    }
    
    return options;
    
  }

  /* Sub Project */
  public List<SelectOption> getSubProjectOptions() {
      
    String sPrefix = SFDC_Sub_Project__c.sObjectType.getDescribe().getKeyPrefix();    
    AggregateResult[] items = [select SFDC_Sub_Project__r.Name, MAX(SFDC_Sub_Project__r.id) Id from SFDC_Issue__c where SFDC_Sub_Project__r.Project__c =:project group by SFDC_Sub_Project__r.Name];
    
    List<SelectOption> options = new List<SelectOption>();         
    options.add(new SelectOption('','')); 
    for (AggregateResult aggr : items) {

      if ( (String)aggr.get('Id') != null ) {

          String l = (String)aggr.get('Name');
          String v = (String)aggr.get('Id');
          options.add(new SelectOption(v,l));       
       }

       
    }
    
    return options;

  }
   
  /* Owner */
  public List<SelectOption> getOwnerOptions() {
        
    AggregateResult[] projects = [select User__r.Name, MAX(User__r.id) Id from SFDC_Issue__c group by User__r.Name];
    
    List<SelectOption> options = new List<SelectOption>();             
    options.add(new SelectOption('','')); 
    for (AggregateResult aggr : projects) {

        if ( (String)aggr.get('Id') != null ) {
             
             String l = (String)aggr.get('Name');
  		       String v = (String)aggr.get('Id');
             options.add(new SelectOption(v,l));
        }

    }
    
    return options;
    
  }

  /** The current sort direction. Defaults to desc as most people want to see the new ones first */
  public String sortDir {
    get  { 
        if (sortDir == null) {  
            sortDir = 'asc'; 
        } 
        return sortDir;  
        }
    set;
  }
 
  /** The current field to sort by. Defaults to name */
  public String sortField {
    get  { if (sortField == null) {sortField = 'Name'; } return sortField;  }
    set;
  }
 
  /** Format the soql for display on the visualforce page */
  public String debugSoql {
    get { return soql + ' order by ' + sortField + ' ' + sortDir + ' limit 200'; }
    set;
  }
 
  /** Init the controller and display some sample data when the page loads */
  public void init() {
                            
    searchResults=new List<SFDC_Issue__c>();
        
    project = '';
    owner='';

    status_selection=new List<String>();
    category_selection = new List<String>();
    priority_selection = new List<String>();
        
    runQuery();
  }
 
  /** Toggles the sorting of query from asc<-->desc */
  public void toggleSort() {

    sortDir = sortDir.equals('asc') ? 'desc' : 'asc';        
    runQuery();     // Run the query again

  }
 
  /** Run the query */
  public void runQuery() {

    resultCount=0;
    generateQueryString();
    
    searchResults=new List<SFDC_Issue__c>();
    
    try {
        
        searchResults = Database.query(soql + ' order by ' + sortField + ' ' + sortDir + ' limit 200');   
        resultCount=searchResults.size();
        
    } catch (Exception e) {

      String sMsg = e.getMessage();  
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, sMsg ));
      resultCount=0;
    
    }
    
  }
  
  /** Run the search with parameters passed as Querystring parameters */
  public PageReference runSearch() {
    
    //Map of PageParameters 
    Map<string,string> pageParams=ApexPages.currentPage().getParameters(); 
    
    // Run the query again
    runQuery();
 
    return null;
  }
  
  /** Generate the soql query string */ 
  private void generateQueryString()
  {
  
   soql = 'select Id, ' +
                'Name, ' +   
                'SFDC_Issue_Name__c, ' +
                'SFDC_Issue_Description__c,' +
                'Issue_Detail__c,' + 
                'User__c, ' +
                'Category__c, ' +
                'SFDC_Issue_Priority__c, ' +
                'SFDC_Issue_Status__c, ' +
                'SFDC_Project__c, ' +
                'SFDC_Sub_Project__c ' +
                
                'from SFDC_Issue__c where Name !=\'NulLValue\' ' ;

    
    if (!status_selection.isEmpty())  {       

        soql += ' AND SFDC_Issue_Status__c in (';    
        soql += CustomUtils.listAsString(status_selection);
        soql += ')';
    
    }  
    
    if (!priority_selection.isEmpty())  {       

        soql += ' AND SFDC_Issue_Priority__c in (';    
        soql += CustomUtils.listAsString(priority_selection);
        soql += ')';
    
    }  

    if (!category_selection.isEmpty())  {       

        soql += ' AND Category__c in (';    
        soql += CustomUtils.listAsString(category_selection);
        soql += ')';
    
    }  


    if (project!=null && project !='')  {       

        soql += ' AND SFDC_Project__c =:project';
    
    }  

    if (subProject!=null && subProject !='')  {       

        soql += ' AND SFDC_Sub_Project__c =:subProject';
    
    }

    if (owner!=null && owner != '')  {       

        soql += ' AND User__c =:owner';
    
    }  

    system.debug('Participant Search Query : ' + soql); 

  }
  
  public void clicked()
  {
      // do nothing
  }
 



}