src/objects/Collection__c.object
<CustomObject>
    <description>Fundraising events</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Collection</label>
    <nameField>
        <label>Collection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Collection_Location__c.object
<CustomObject>
    <description>Fundraising Collection Locations</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Organisation that owns the collection point</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Collection Locations</relationshipLabel>
        <relationshipName>Collection_Locations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collection_Activity__c</fullName>
        <description>Activity at the collection point</description>
        <label>Collection Activity</label>
        <picklist>
            <picklistValues>
                <fullName>Bucket collection</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Collection__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Collection</label>
        <referenceTo>Collection__c</referenceTo>
        <relationshipLabel>Collection Locations</relationshipLabel>
        <relationshipName>Collection_Locations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maximum_Number_of_Volunteers__c</fullName>
        <label>Maximum Number of Volunteers</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Number_of_Volunteers__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Minimum Number of Volunteers</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_volunteers_per_session__c</fullName>
        <inlineHelpText>Number of volunteers per session for this location</inlineHelpText>
        <label>Number of volunteers per session</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of the Collection Point</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Collection Location</label>
    <nameField>
        <label>Collection Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Collection_Time_Slot__c.object
<CustomObject>
    <description>A session for a collector</description>
    <fields>
        <fullName>Collection_Location__c</fullName>
        <label>Collection Location</label>
        <referenceTo>Collection_Location__c</referenceTo>
        <relationshipLabel>Collection Time Slots</relationshipLabel>
        <relationshipName>Collection_Time_Slots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Duration_in_minutes__c</fullName>
        <defaultValue>60</defaultValue>
        <inlineHelpText>Duration of collection session.</inlineHelpText>
        <label>Duration in minutes</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Collection Time Slot</label>
    <nameField>
        <displayFormat>CT-{00000}</displayFormat>
        <label>Collection Time Slots Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Time Slots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Collector_Session__c.object
<CustomObject>
    <fields>
        <fullName>CollectionSession__c</fullName>
        <label>Collection Session</label>
        <referenceTo>Collection_Time_Slot__c</referenceTo>
        <relationshipLabel>Collector Sessions</relationshipLabel>
        <relationshipName>Collector_Sessions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Collector__c</fullName>
        <label>Collector</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Collector</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Collector Sessions</relationshipLabel>
        <relationshipName>Collector_Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Collector Session</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Collector Sessions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collector Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Deceased__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>To set a person as deceased please use the Person Wizard.</inlineHelpText>
        <label>Deceased?</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Collector</fullName>
        <active>true</active>
        <description>Volunteer Collector for Fundraising</description>
        <label>Collector</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospective</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Converted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCollectorSessionController.cls
@isTest
public with sharing class TestCollectorSessionController{

/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : Test Class for LastTransactionDateLookup Class.
 *  Author  : Mike Tinson
 *  Date    : 08-10-2014
 *  Version : 0.1 Unit Test
 *
 *  Description:    Apex Class to test CollectorSessionController Class. 
 *               
 *  Modification History
 *
 *  Date            Who     Description 
 *  dd-mm-yyyy      ??      ??
 *                             
*******************************************************************************************/
   static testMethod void TestCollectorSessionController(){
     
    //Add Contact RecordTypes to a Map Collection. 
        Map<String, RecordType> contactRTMap = new Map<String, RecordType>();
        for (RecordType rt : [SELECT rt.Id, rt.DeveloperName FROM RecordType rt WHERE rt.IsActive = true and rt.SObjectType = 'Contact']){
            contactRTMap.put(rt.DeveloperName, rt);
        }             
     Contact ContactToSave = new Contact();    
    Contact recCon = new Contact(FirstName = 'Albert', LastName='TestLastName',Deceased__c=false,MailingPostalCode ='ABC123', Birthdate =Date.Today(),
            RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and Name Like 'Collector'].id);
    insert recCon;  
    datetime dt= datetime.now();
    dt = dt.AddDays(1);
    datetime dt2 = dt.AddDays(10);
        
    Account accRec = new Account(Name='North West London Locality',RecordTypeId=[Select Id from RecordType where SObjectType='Account' and Name like 'External%'].id);
    insert accRec;
    Collection__c CollectRec = new Collection__c (Name='TestCollection', Start_Date__c = dt.date(), End_Date__c = dt2.date());
    insert CollectRec;
    
    Collection_Location__c collLocRec = new Collection_Location__c(Name='TestLocation', Account__c=accRec.id, Collection__c = CollectRec.id, Collection_Activity__c = 'Bucket collection', Maximum_Number_of_Volunteers__c= 20,Minimum_Number_of_Volunteers__c=10, Number_of_volunteers_per_session__c = 5, Status__c ='Open'); 

    insert collLocRec;
    Collection_Time_Slot__c CTSrec = new Collection_Time_Slot__c(Collection_Location__c = collLocRec.id, Duration_in_minutes__c = 60, Start_Date_Time__c = dt);
    insert CTSrec;
    //second collection one day later.
    Collection_Time_Slot__c CTSrec2 = new Collection_Time_Slot__c(Collection_Location__c = collLocRec.id, Duration_in_minutes__c = 60, Start_Date_Time__c = dt.AddDays(1));
    insert CTSrec2;
    //third collection one day later.
    Collection_Time_Slot__c CTSrec3 = new Collection_Time_Slot__c(Collection_Location__c = collLocRec.id, Duration_in_minutes__c = 60, Start_Date_Time__c = dt.AddDays(1));
    insert CTSrec3;
    //insert one session
    Collector_Session__c sessrec = new Collector_Session__c(Collector__c=recCon.Id, CollectionSession__c= CTSrec3.id);
    Insert sessrec;
       //Now insert data causing the DF_Contact__c trigger to fire. 
       
     Test.startTest();
     ApexPages.currentPage().getParameters().put('id', recCon.id);  
     CollectorSessionController conCls= new CollectorSessionController (new ApexPages.StandardController(recCon));       
     List<SelectOption> availDays = conCls.getlstAvailableDays();
     List<SelectOption> availCollections=conCls.getlstCollectionOptions();
     List<SelectOption> availLocations=conCls.getlstLocationOptions();
     conCls.PageSize=1;
     conCls.ClearResult();
     conCls.PageReSized();
     conCls.doSearch();
     
      
     System.debug('.......SearchedSessions size' + conCls.lstSearchedSessions.size()); 
     
     String selectedLocation ='TestLocation';
     conCls.selectLocation=selectedLocation;
     //If (availLocations.size()>0)
     //    {selectedLocation=availLocations.getValue();}
     String selectDate;
     Date tmpDt = date.today().AddDays(1);
     selectDate = tmpDt.format();
     conCls.selectDate = selectDate;
     conCls.doSearch();
     
     //conCls.RetrieveExistingSessions();
     conCls.sortNSearch();
     conCls.next();
     conCls.previous();
    /**
    find a session and select it
    **/ 
    conCls.selectDate=null;
    conCls.selectLocation=null;
    conCls.doSearch();      
    if(conCls.lstSearchedSessions.size()>0) 
    {
        conCls.lstSearchedSessions.get(0).isSelected=true;
        
    }    
    System.debug('.......searchedsessions size' + conCls.lstSearchedSessions.size()); 
    conCls.InsertSelected();
    conCls.doSearch();  
    conCls.saveNReturn();    
    if(conCls.lstSearchedSessions.size()>0) 
    {
        conCls.lstSearchedSessions.get(0).isSelected=true;
        
    }    
    System.debug('.......searchedsessions size' + conCls.lstSearchedSessions.size()); 
    conCls.InsertSelected();
    conCls.saveNReturn();
    
     
       
/**
public  System.PageReference ClearResult()
public  System.PageReference InsertSelected()
public  System.PageReference PageReSized()
private void RetrieveExistingSessions()
public  ANY clone()
public  System.PageReference doSearch()
public  LIST getlstAvailableDays()
public  LIST getlstLocationOptions()
public  System.PageReference next()
public  System.PageReference previous()
public  System.PageReference saveNReturn()
public  System.PageReference sortNSearch()
**/
        Test.stopTest();
                     
    }  
 
}