src/objects/Collection__c.object
<CustomObject>
    <description>Fundraising events</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Collection</label>
    <nameField>
        <label>Collection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Collection_Location__c.object
<CustomObject>
    <description>Fundraising Collection Locations</description>
    <fields>
        <fullName>Collection__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Collection</label>
        <referenceTo>Collection__c</referenceTo>
        <relationshipLabel>Collection Locations</relationshipLabel>
        <relationshipName>Collection_Locations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Count_of_Collectors__c</fullName>
        <label>Total Collector Sessions</label>
        <summarizedField>Collection_Time_Slot__c.Count_of_Collectors__c</summarizedField>
        <summaryForeignKey>Collection_Time_Slot__c.Collection_Location__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of the Collection Point</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Collection Location</label>
    <nameField>
        <label>Collection Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Collection_Time_Slot__c.object
<CustomObject>
    <description>A session for a collector</description>
    <fields>
        <fullName>Collection_Location__c</fullName>
        <label>Collection Location</label>
        <referenceTo>Collection_Location__c</referenceTo>
        <relationshipLabel>Collection Time Slots</relationshipLabel>
        <relationshipName>Collection_Time_Slots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Count_of_Collectors__c</fullName>
        <label>Count of Collectors</label>
        <summaryForeignKey>Collector_Session__c.CollectionSession__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Duration_in_minutes__c</fullName>
        <defaultValue>60</defaultValue>
        <inlineHelpText>Duration of collection session.</inlineHelpText>
        <label>Duration in minutes</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>Calculate end time for session - from duration</description>
        <formula>If (Duration_in_minutes__c &gt;0,Start_Date_Time__c +  (Duration_in_minutes__c /1440),Start_Date_Time__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Session_Available__c</fullName>
        <formula>Count_of_Collectors__c &lt;   Collection_Location__r.Number_of_volunteers_per_session__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Session Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Collection Time Slot</label>
    <nameField>
        <displayFormat>CT-{00000}</displayFormat>
        <label>Collection Time Slots Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Time Slots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Collector_Session__c.object
<CustomObject>
    <fields>
        <fullName>CollectionSession__c</fullName>
        <label>Collection Session</label>
        <referenceTo>Collection_Time_Slot__c</referenceTo>
        <relationshipLabel>Collector Sessions</relationshipLabel>
        <relationshipName>Collector_Sessions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Collector__c</fullName>
        <label>Collector</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Collector</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Collector Sessions</relationshipLabel>
        <relationshipName>Collector_Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Collector Session</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Collector Sessions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collector Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>Locality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Locality in which this service is based (left blank for national services).</description>
        <label>Locality</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select an Alzheimer&apos;s Society Locality.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Organisation</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>contains</operation>
                <value>Locality</value>
            </filterItems>
            <infoMessage>Please select a Locality.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Services_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>service_type__c</fullName>
        <inlineHelpText>Service description will be automatically populated from the service type (or sub type if there is one)</inlineHelpText>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult education &amp; training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (emotional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (financial)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (general)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awareness raising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending / home support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counselling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day support / day care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafés</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exercise / Fitness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home facilities &amp; services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Dementia)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Financial &amp; Legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programmes &amp; provision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CollectorSessionController.cls
public class CollectorSessionController 
{
public ApexPages.StandardController stdController;
public Contact con;
public String selectLocation {get;set;}
public String selectCollection {get;set;}
public String selectDate {get;set;}
public List<SearchedSessionClass> lstToShowSearchedSessions {get;set;}
public List<SearchedSessionClass> lstSearchedSessions {get;set;}
public List<SearchedSessionClass> lstAddedSessions {get;set;}
public boolean bolUnSelect {get;set;}

public boolean hasNext {get;set;}
public boolean hasPrevious {get;set;}

public string sortExpression {get;set;}
public string sortDirection {get;set;}
public Integer PageSize {get;set;}
public Integer nextStartRowNum {get;set;}
public Integer prevStartRowNum {get;set;}
private boolean isSorting;
private Map<String, ID> MapAddedSessions {get;set;}


public CollectorSessionController (ApexPages.StandardController pController) {
    stdController = pController;
    con = (Contact) stdController.getRecord(); 
    lstAddedSessions = new List<SearchedSessionClass>();
    lstSearchedSessions  = new List<SearchedSessionClass>();
    MapAddedSessions = new Map<String, ID>();
    PageSize = 12;
    sortDirection='ASC';
    RetrieveExistingSessions();
    
}
private void RetrieveExistingSessions() { 
    List<Collector_Session__c> lstExistingSessions = new List<Collector_Session__c>([SELECT CollectionSession__c FROM Collector_Session__c WHERE Collector__c = :con.id]);
    List<Id> lstId = new List<Id>();

    if (lstExistingSessions.size()>0) {
        for (Collector_Session__c rec : lstExistingSessions)
        {
            lstId.add(rec.CollectionSession__c);
        }
        // get details of sessions
        List<Collection_Time_Slot__c> tmpListSessions = new List<Collection_Time_Slot__c>();
        tmpListSessions = [SELECT id, name, Collection_Location__c,Collection_Location__r.name,  Start_Date_Time__c, Duration_in_minutes__c, End_Date_Time__c, Count_of_Collectors__c 
                           from Collection_Time_Slot__c  WHERE id in :lstId ];
        for (Collection_Time_Slot__c  rec: tmpListSessions ){
            SearchedSessionClass tmpCls = new SearchedSessionClass();
            //CollectionSession__c tmpCS = new CollectionSession__c;
            //tmpCS = CollectionSession__c;
            
            tmpCls.recCTS = rec;
            //tmpCls.Collection_Location = Collection_Location__r.name;
            tmpCls.IsNew = false;
            //tmpCls.Collection_Location  = rec2.Collection_Location__r.Name;
            //tmpCls.recSU.Service_Field__c=rec2.id;
            //tmpCls.recServ=((Services__c)rec2);
            lstAddedSessions.add(tmpCls);
            MapAddedSessions.put(rec.id, rec.id);
        
        }
        
    }
}
//Inner Class to hold flags, Service and ServiceUsage data.
public class SearchedSessionClass
{
    public Collection_Time_Slot__c recCTS {get;set;}
    //public Services__c recServ {get;set;}
    public String Collection_Location {get;set;}
    public boolean isSelected {get;set;}
    //public boolean isSU_Rec_Outgoing {get;set;}
    public boolean isNew {get;set;}
}
//Handle column sorting click.
public PageReference sortNSearch()
{
    //Toggle sorting order.
    sortDirection = (sortDirection.equalsIgnoreCase('ASC'))? 'DESC' : 'ASC';
    
    isSorting=true;
    //Invoke search method.
    doSearch();
    isSorting=false;
    return null;
}



public List<SelectOption> getlstAvailableDays(){
    List<SelectOption> lstTmpAvailDays = new List<SelectOption>();
    lstTmpAvailDays.add(new SelectOption('', '-- Select One --')); 
    String searchLocation = (selectLocation==null)? '%' : selectLocation;
    List<AggregateResult> datesAvailable = new List<AggregateResult>();
    if (searchLocation =='%')
    {
        datesAvailable = [select DAY_ONLY(Start_Date_Time__c) avail FROM Collection_Time_Slot__c WHERE Session_Available__c=true AND Collection_Location__r.Status__c='Open'  GROUP BY DAY_ONLY(Start_Date_Time__c) ORDER BY DAY_ONLY(Start_Date_Time__c)];
    }
    else 
    {
        datesAvailable = [select DAY_ONLY(Start_Date_Time__c) avail FROM Collection_Time_Slot__c WHERE Session_Available__c=true AND Collection_Location__r.Status__c='Open' and Collection_Location__c=:searchLocation   GROUP BY DAY_ONLY(Start_Date_Time__c) ORDER BY DAY_ONLY(Start_Date_Time__c)];
    }
    for (AggregateResult loc: datesAvailable)
    {
    
        Date dt = Date.valueof(loc.get('avail'));
        //String aaa = String.valueof(loc.get('avail'));
        String aaa = dt.format();
        lstTmpAvailDays.add (new SelectOption (aaa, aaa));
    }
    
    return lstTmpAvailDays;
}


public List<SelectOption> getlstCollectionOptions() {

    List<SelectOption> lstCollectionOptions= new List<SelectOption>();
    lstCollectionOptions.add(new SelectOption('', '-- Select One --')); 
    
    for (Collection__c loc:[select id, name from Collection__c  WHERE Status__c='Open' ORDER BY name])
    {
        //String aaa = loc.name;
        lstCollectionOptions.add (new SelectOption (loc.id, loc.name));
    }

    return lstCollectionOptions;

}
public List<SelectOption> getlstLocationOptions() {

    List<SelectOption> lstLocationOptions = new List<SelectOption>();
    lstLocationOptions.add(new SelectOption('', '-- Select One --')); 
    String searchCollection = (selectCollection==null)? '%' : selectCollection;
    for (Collection_Location__c loc:[select id, name from Collection_Location__c  WHERE Status__c='Open' AND Collection__c =:searchCollection ORDER BY name])
    {
        //String aaa = loc.name;
        lstLocationOptions.add (new SelectOption (loc.id, loc.name));
    }

    return lstLocationOptions;

}

//Clear previous search result, button handler
    public PageReference ClearResult()
    {
        //searchService.service_type__c='';
        //searchService.Locality__c=null;
        //strSearchKeyword='';
        //lstToShowSearchedSessions = new List<SearchedSessionClass>();
        
        return null;
    }
 public PageReference doSearch()
    {
    Date searchDay;
    Date searchDay_plus_1;
    LIST<LIST<SObject>> lstSearchResult = new LIST<LIST<SObject>>();
    String searchLocation = (selectLocation==null)? '%' : selectLocation;
    String searchCollection = (selectCollection==null)? '%' : selectCollection;
    System.debug('###########selectDate=' + selectDate);
    If (selectDate!=null) 
    {
        searchDay =Date.parse(selectDate);
        searchDay_plus_1 =searchDay.addDays(1);
    
    }
   
    System.debug('##########searchLocation ' + searchLocation );
    if (searchLocation!='%') 
    {
        if (selectDate!=null)
        {
        lstSearchResult.add([SELECT id, name, Collection_Location__c,Collection_Location__r.name,  Start_Date_Time__c, Duration_in_minutes__c, End_Date_Time__c, Count_of_Collectors__c , Collection_Location__r.Collection__c
        FROM Collection_Time_Slot__c 
        WHERE Session_Available__c=true AND Collection_Location__r.Status__c='Open' 
        AND Collection_Location__c = :searchLocation 
        AND Collection_Location__r.Collection__c=:searchCollection 
        AND Start_Date_Time__c >= :searchDay 
        AND Start_Date_Time__c < :searchDay_plus_1
        ORDER BY Collection_Location__r.name, Start_Date_Time__c]);
       
        }
        else
        {
        lstSearchResult.add([SELECT id, name, Collection_Location__c,Collection_Location__r.name,  Start_Date_Time__c, Duration_in_minutes__c, End_Date_Time__c, Count_of_Collectors__c, Collection_Location__r.Collection__c
        FROM Collection_Time_Slot__c 
        WHERE Session_Available__c=true AND Collection_Location__r.Status__c='Open' 
        AND Collection_Location__c = :searchLocation  
        AND Collection_Location__r.Collection__c=:searchCollection 
        ORDER BY Collection_Location__r.name, Start_Date_Time__c]);
        }
    }
    else
    {
        if (searchCollection!='%')
        {
        
        //no collection or location specified
            lstSearchResult.add([SELECT id, name, Collection_Location__c,Collection_Location__r.name,  Start_Date_Time__c, Duration_in_minutes__c, End_Date_Time__c, Count_of_Collectors__c, Collection_Location__r.Collection__c 
            FROM Collection_Time_Slot__c 
            WHERE Session_Available__c=true AND Collection_Location__r.Status__c='Open' 
            AND Start_Date_Time__c >= :searchDay 
            AND Start_Date_Time__c < :searchDay_plus_1
            
            ORDER BY Collection_Location__r.name, Start_Date_Time__c]);
        }
        else 
        {
        //no location but have a collection
        lstSearchResult.add([SELECT id, name, Collection_Location__c,Collection_Location__r.name,  Start_Date_Time__c, Duration_in_minutes__c, End_Date_Time__c, Count_of_Collectors__c , Collection_Location__r.Collection__c
            FROM Collection_Time_Slot__c 
            WHERE Session_Available__c=true AND Collection_Location__r.Status__c='Open' 
            AND Collection_Location__r.Collection__c=:searchCollection 
            AND Start_Date_Time__c >= :searchDay 
            AND Start_Date_Time__c < :searchDay_plus_1
            
            ORDER BY Collection_Location__r.name, Start_Date_Time__c]);

        
        }
    }
            
    system.debug('##########lstSearchResult.size=' + lstSearchResult.size());
    Integer rowNum=1;
    lstSearchedSessions = new List<SearchedSessionClass>();
    lstToShowSearchedSessions= new List<SearchedSessionClass>();
    for(List<SObject> rec : lstSearchResult)
        {
            for(SObject rec2: rec)
            {
                
                SearchedSessionClass tmpCls = new SearchedSessionClass();
                tmpCls.recCTS = new Collection_Time_Slot__c ();
                tmpCls.recCTS=(Collection_Time_Slot__c)rec2;
                tmpCls.isSelected=false;
                //tmpCls.Collection_Location  = rec2.Collection_Location__r.Name;
                //tmpCls.recSU.Service_Field__c=rec2.id;
                //tmpCls.recServ=((Services__c)rec2);
                //ignore record if already added
                if (!MapAddedSessions.containsKey(tmpCls.recCTS.id))
                {
                    lstSearchedSessions.add(tmpCls);
                
                    //No. of rows to show from List.
                    if(rowNum++<=PageSize){
                        lstToShowSearchedSessions.add(tmpCls);}
                }
                else
                {system.debug('###########added already' + tmpCls.recCTS.id);}
             }
        }
    //Re-arrange record pointers.
        hasNext = lstSearchedSessions.size()>PageSize;
        hasPrevious = false;
        nextStartRowNum=PageSize+1;
        prevStartRowNum =1;
        if(lstSearchedSessions.size()==0 ){
                ApexPages.Message message = new ApexPages.message(ApexPages.severity.WARNING,'No records were found based on your criteria.' );
                ApexPages.addMessage(message);
                }
        else {
                ApexPages.Message message = new ApexPages.message(ApexPages.severity.INFO, lstSearchedSessions.size() + ' Records found based on your criteria.');
                ApexPages.addMessage(message);
                }
    return null;
    }
    //No. of Records to show/Page combo change handler
    public PageReference PageReSized()
    {
        Integer rowNum=1;
        lstToShowSearchedSessions = new List<SearchedSessionClass>();
        
        //Populate subset of records to show. Always show first set of PageSize records.
        for(SearchedSessionClass rec : lstSearchedSessions)
        {
            if(rowNum++<=PageSize)
                lstToShowSearchedSessions.add(rec);
        }
        
        //Re-arranging row pointers.
        hasNext = lstSearchedSessions.size()>PageSize;
        hasPrevious = false;
        nextStartRowNum=PageSize+1;
        prevStartRowNum =1;
        return null;
    }

    //Previous link button handler
    public PageReference previous()
    {
        Integer rowNum=1;
        lstToShowSearchedSessions =  new List<SearchedSessionClass>();
        //Populate subset of records to show.
        for(SearchedSessionClass rec : lstSearchedSessions)
        {
        system.debug('###############'+rowNum+'/////'+nextStartRowNum+'/////'+(nextStartRowNum-PageSize));
            if(rowNum>=prevStartRowNum  && rowNum<(prevStartRowNum+PageSize))
                lstToShowSearchedSessions.add(rec);

          rowNum++;      
        }   
        
        //Re-arranging row pointers.
        nextStartRowNum=prevStartRowNum+PageSize;
        prevStartRowNum -= PageSize;
        hasPrevious =   (prevStartRowNum >0); 
        hasNext = (lstSearchedSessions.size()>=(nextStartRowNum));
        return null;
    }
    
    //Next link button handler
    public PageReference next()
    {
        Integer rowNum=1;
        lstToShowSearchedSessions =  new List<SearchedSessionClass>();
        //Populate subset of records to show.
        for(SearchedSessionClass rec : lstSearchedSessions)
        {
        //system.debug('###############'+rowNum+'/////'+nextStartRowNum+'/////'+rowNum+'/////'+(nextStartRowNum+PageSize));
            if(rowNum>=nextStartRowNum && rowNum<(nextStartRowNum+PageSize))
                lstToShowSearchedSessions.add(rec);

          rowNum++;      
        }   
        
        //Re-arranging row pointers.
        prevStartRowNum =nextStartRowNum-PageSize;
        nextStartRowNum+=PageSize;
        hasNext =   (lstSearchedSessions.size()>=nextStartRowNum); 
        hasPrevious = (prevStartRowNum >=1);
        return null;
    }  
    
    //InsertSelected button handler.
    public PageReference InsertSelected()
    { 
        List<SearchedSessionClass> lstTmp= new List<SearchedSessionClass>();
        //Get all SessionUsage RecordTypes.
        //Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Session_Usage__c.getRecordTypeInfosByName(); 
                  
        
        //Add the selected Sessions to AddList.
        for(SearchedSessionClass rec: lstSearchedSessions)
        {
            if(rec.isSelected)
            {
                //rec.recCTS = rec.recServ;

                rec.isNew=true;

                lstAddedSessions.add(rec);
                MapAddedSessions.put(rec.recCTS.id, rec.recCTS.id);
            }
            else
            {
                lstTmp.add(rec);
            }
        }
        
        system.debug('##########lstTmp#########'+lstTmp);

        //Refresh searched List, by removing selected Sessions.
        lstSearchedSessions=lstTmp;

        bolUnSelect=false;
        
        Integer rowNum=1;
        lstToShowSearchedSessions = new List<SearchedSessionClass>();

        //Refresh list, no. of rows to show
        for(SearchedSessionClass rec : lstSearchedSessions)
        {
                if(rowNum++<=PageSize)
                    lstToShowSearchedSessions.add(rec);
        }
        
        //Re-arrange record pointers.
        hasNext = lstSearchedSessions.size()>PageSize;
        hasPrevious = false;
        nextStartRowNum=PageSize+1;
        prevStartRowNum =1;
        
        system.debug('##########before return############');
        return null;

    }  
//Save and Return Button handler.
public PageReference saveNReturn() {
      ///Saving or Creation logic
      Id contactId = ApexPages.currentPage().getParameters().get('id');
      List<Collector_Session__c> lstCollectorSessionToCreate = new List<Collector_Session__c>();
    
    
      //Iterate through all Added Sessions List to set default values;    
      for(SearchedSessionClass rec:lstAddedSessions)
      {
          try
          {
          //Set default values only if record is New/To be created and not for Update.
          if(rec.isNew ==true)
          {
            Collector_Session__c CSinstance = new Collector_Session__c();
            CSinstance.Collector__c = con.id;
            CSinstance.CollectionSession__c = rec.recCTS.id;
            lstCollectorSessionToCreate.add(CSinstance);
          }
          
          }catch(Exception ex){
          //throw ex;}
                    ApexPages.Message message = new ApexPages.message(ApexPages.severity.ERROR,'An error occurred while creating Sessions.');
                    ApexPages.addMessage(message);
                    return null;      }
      }
      
      system.debug('###########lstAddedSessions#############'+lstAddedSessions);
      if(lstCollectorSessionToCreate.size()>0)
      {
          // Create a savepoint because the data should not be committed to the database
          Savepoint sp = Database.setSavepoint();
    
          try
          {
              //Insert or Update SessionUsage records.
              upsert lstCollectorSessionToCreate;
          }catch(Exception ex){Database.rollback(sp);
                               ApexPages.Message message = new ApexPages.message(ApexPages.severity.ERROR,'An error occurred while updating Sessions.');
                               ApexPages.addMessage(message);
                               return null;}
      }
      //Navigate back to Contact Detail Page.
      return new PageReference('/'+ApexPages.currentPage().getParameters().get('id'));
     }    
}