src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Date_of_diagnosis__c</fullName>
        <inlineHelpText>This is required if a diagnosis has been given. If full date of diagnosis is unknown, enter it to the nearest year or month (e.g. 01/01/1945 if diagnosis year is 1945; or 01/08/1945 if diagnosis date is estimated). Then tick ‘Approximate Date’ box</inlineHelpText>
        <label>Date of diagnosis</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Diagnosis__c</fullName>
        <inlineHelpText>Only to be used for CONFIRMED diagnosis of dementia.</inlineHelpText>
        <label>Dementia diagnosis</label>
        <picklist>
            <picklistValues>
                <fullName>Alzheimer’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Binswanger’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia with Lewy bodies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Down’s syndrome related dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fronto-Temporal dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HIV related dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huntington’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korsakoff’s syndrome</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixed dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parkinson’s disease related dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pick’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prion disease including CJD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vascular dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None - Awaiting Diagnosis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None - Other Mild Cognitive Impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (please list)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mild Cognitive Impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Diagnosis_made_by__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Diagnosis made by</description>
        <inlineHelpText>To record which professional made the diagnosis. Do NOT just type in name – A Professional already entered on the system must be found, selected and inserted by using the Look-Up function (magnifying glass icon).</inlineHelpText>
        <label>Diagnosis made by</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Professional / Stakeholder</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Diagnosis made by)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_user_aware_of_diagnosis__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service User aware of diagnosis</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Specialist_Communication_Needs__c</fullName>
        <inlineHelpText>To record information to assist communication, such as whether the speak English; if they need an interpreter; if they use BSL; what may help effective communication, etc.</inlineHelpText>
        <label>Specialist Communication Needs</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>rrpu__Alert_Message__c</fullName>
        <description>This field is installed by Riptide Pop-up Alerts and is used in conjunction with the Pop-up Alert S-Control.</description>
        <inlineHelpText>Any user can create an alert using the Public Alert Message Required on a service usage record.</inlineHelpText>
        <label>Alert Message</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact_History__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Alert_Message__c</fullName>
        <label>Alert Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Audit Trail</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact History (Contact History)</relationshipLabel>
        <relationshipName>Contact_History1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_of_Diagnosis__c</fullName>
        <label>Date of Diagnosis</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Diagnosis__c</fullName>
        <label>Key Health Issues</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Diagnosis_made_by__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Diagnosis made by</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact History</relationshipLabel>
        <relationshipName>Contact_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Firstname__c</fullName>
        <label>Firstname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lastname__c</fullName>
        <label>Lastname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingCity__c</fullName>
        <label>MailingCity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingCountry__c</fullName>
        <label>MailingCountry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingPostalCode__c</fullName>
        <label>MailingPostalCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingState__c</fullName>
        <label>MailingState</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingStreet__c</fullName>
        <label>MailingStreet</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Address__c</fullName>
        <label>Mailing Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_User_aware_of_diagnosis__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service User aware of diagnosis</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Specialist_Communication_Needs__c</fullName>
        <label>Specialist Communication Needs</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Contact History</label>
    <nameField>
        <label>Contact History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactHistoryAuditTrail.cls
/******************************************************************************************
 *  Alzheimer's
 *  
 *  Purpose : Class to retrieve the audit trail list for Contact.
 *  Author  : Fujitsu - Nupoor Pandey
 *  Date    : 2012-03-14
 *  Version : 0.1 Unit Tested
 *  Project : CRSProto
 *
 *  Description: Class to retrieve the audit trail list for Contact. 
 *               
 *               
 *  Modification History
 *
 *  Date         Who    Description 
 *  04/08/2012 17:19  Gunish Chawla    Live version
 *  19/1/2015  Mike Tinson    update slow running test - remove to separate test class and update version of this class
 *                             
*******************************************************************************************/
public with sharing class ContactHistoryAuditTrail {

    public Contact person {get; private set;}
    public List<Contact_History__c> contactHistory{get; private set;}

    /**
    Constructor to get the Contact Id from the page and retrieve the following:
        :ContactHistory__c
    */
    public ContactHistoryAuditTrail(ApexPages.StandardController controller) {
        Id id = ApexPages.currentPage().getParameters().get('id');
        person = (id == null) ? new Contact() : 
            [Select c.rrpu__Alert_Message__c, c.Date_of_diagnosis__c, c.Diagnosis__c, c.Diagnosis_made_by__c, c.Id, c.Firstname, c.LastName, 
            c.MailingStreet, c.MailingCity, c.MailingState, c.MailingCountry, c.MailingPostalCode, c.Service_user_aware_of_diagnosis__c, 
            c.Specialist_Communication_Needs__c From Contact c WHERE id = :id];
            
            contactHistory = [Select c.User__c, c.SystemModstamp, c.Specialist_Communication_Needs__c, c.Service_User_aware_of_diagnosis__c, 
            c.OwnerId, c.Name, c.Mailing_Address__c, c.MailingStreet__c, c.MailingState__c, c.MailingPostalCode__c, c.MailingCountry__c, 
            c.MailingCity__c, c.Lastname__c, c.LastModifiedDate, c.LastModifiedById, c.IsDeleted, c.Id, c.Firstname__c, c.Diagnosis_made_by__c, 
            c.Diagnosis__c, c.Date_of_Diagnosis__c, c.Date__c, c.CreatedDate, c.CreatedById, c.Contact_History__c, c.Alert_Message__c, c.Action__c 
            From Contact_History__c c where Contact_History__c = :person.Id Order by Date__c DESC];
    }   
 
}