src/objects/contact__c.object
<CustomObject>
    <label>contact</label>
    <nameField>
        <label>contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact_Event__c.object
<CustomObject>
    <description>For recording each time that contact is made with a client of any type</description>
    <fields>
        <fullName>Contact_Date_Time__c</fullName>
        <label>Contact Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration (mins)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <picklist>
            <picklistValues>
                <fullName>Phone call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting at office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting at client&apos;s home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting elsewhere</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contact Interaction</label>
    <nameField>
        <label>Contact Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Interactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact_Event_Contact_Connector__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Event__c</fullName>
        <label>Contact Interaction</label>
        <referenceTo>Contact_Event__c</referenceTo>
        <relationshipLabel>People Involved</relationshipLabel>
        <relationshipName>Contact_Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Interaction Involvement</relationshipLabel>
        <relationshipName>Contact_Event_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Event Attendee</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Contact Event Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContactEventWizardController.cls
public class ContactEventWizardController {
	public Contact_Event__c contactEvent;
	public Contact_Event_Contact_Connector__c person;
	
	//
    // Constructor
    //
	public ContactEventWizardController(ApexPages.StandardController controller) {
		contactEvent = new Contact_Event__c();
		person = new Contact_Event_Contact_Connector__c();
	}
	
	//
    // Properties
    //
    public Contact_Event__c getContactEvent() {
        if(contactEvent == null)
            contactEvent = new Contact_Event__c();
        return contactEvent;
    }
    
    public Contact_Event_Contact_Connector__c getPerson() {
    	if (person == null)
    		person = new Contact_Event_Contact_Connector__c();
    	return person;
    }
    
    // 
    // Navigation methods
    //
    // Return the user to the Contact Events/Interactions tab
    public PageReference cancel() {
        PageReference contPage = new PageReference('/a0t/o');
        contPage.setRedirect(true);
        return contPage;
    }
    
    //
    // Save record methods
    //
    private void saveEvent() {
    	upsert contactEvent;
    	
    	// Link person to contact event/interaction and upsert
    	Contact_Event_Contact_Connector__c p = new Contact_Event_Contact_Connector__c(
    													 Contact_Event__c = contactEvent.Id
    													,Contact__c = person.Contact__c);
    	upsert p;
    }
    
    public PageReference save() {
    	saveEvent();
    	
    	// Send user to the detail page for the contact
        PageReference opptyPage = new PageReference('/' + contactEvent.id);
        opptyPage.setRedirect(true);
        return opptyPage;
    }
    
    public PageReference saveAdd() {
    	saveEvent();
    	
    	// Send user to add people to Contact Event/Interaction
        PageReference newCont = new PageReference('/apex/AddContactEventAttendees?id=' + contactEvent.Id);
        newCont.setRedirect(true);
        return newCont;
    }
    
    //
	// TEST ContactWizardController
	//
	private static testMethod void testContactEventWiz () {
		User currentuser = [Select ID, LocaleSidKey, Alias From User WHERE IsActive = True AND Id = :UserInfo.getUserID() LIMIT 1];
		
		Contact_Event__c ce = new Contact_Event__c(name = 'test', ownerId = currentuser.Id);
		
		// Create test contact
		Contact contact = new Contact(FirstName = 'test', LastName='Test', ownerId = currentuser.Id);
        insert contact;
        
        // Create a PageReference to the VF page being tested       
        PageReference pageRef = Page.NewContactInteraction;
        test.setCurrentPage(pageRef);
        
        // Now create the standard controller for the contact event
        ApexPages.StandardController stdCon = new ApexPages.StandardController(ce);
        
        // Test constructors
        ContactEventWizardController cnt = new ContactEventWizardController(stdCon);
        
        // Test properties
        cnt.getContactEvent();
        cnt.getPerson();
        
        // Set fields
        cnt.contactEvent.Name = 'test event';
        cnt.contactEvent.Duration__c = 2;
        cnt.contactEvent.Contact_Date_Time__c = Date.today();
        cnt.contactEvent.Format__c = 'Email';
        cnt.contactEvent.OwnerId = currentuser.Id;
        
        cnt.person.Contact__c = contact.Id;
		
        // Test save methods
        cnt.save();
        cnt.saveAdd();
        cnt.cancel();
	}
}