src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Deceased__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>To set a person as deceased please use the Person Wizard.</inlineHelpText>
        <label>Deceased?</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <description>Used as default Record Type for helpline calls etc.</description>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/contact__c.object
<CustomObject>
    <label>contact</label>
    <nameField>
        <label>contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Usage__c.object
<CustomObject>
    <fields>
        <fullName>Closure_Date__c</fullName>
        <inlineHelpText>Set only when case is closed. Must be set if a ‘Closure Reason’ is set</inlineHelpText>
        <label>Closure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Service_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service User</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 OR 2) AND ((3 AND 4) OR (5 AND 6) OR 7 OR 8)</booleanFilter>
            <errorMessage>For Day care &amp; support and Community support Services, Service User must be a living Person with Dementia. For other services Service User can also be a Carer of a Person with Dementia. Newsletter is available to all.</errorMessage>
            <filterItems>
                <field>Contact.Deceased_Date__c</field>
                <operation>greaterThan</operation>
                <valueField>$Source.Referral_Date__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.Deceased__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Type__c</field>
                <operation>equals</operation>
                <value>Community support service, Day care and support (establishment based), Registered home care and support</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person with Dementia</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Type__c</field>
                <operation>equals</operation>
                <value>Activity group, Dementia adviser, Dementia support, Dementia cafe, Information programme, Other (one to one), Peer support group, Singing for the Brain, Befriending, Advocacy</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Carer of Person with Dementia, Person with Dementia</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Type__c</field>
                <operation>equals</operation>
                <value>Newsletter</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outgoing Referral</value>
            </filterItems>
            <infoMessage>For Day care &amp; support and Community support Services, Service User must be a living Person with Dementia. For other services Service User can also be a Carer of a Person with Dementia. Newsletter is available to all.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Usage</relationshipLabel>
        <relationshipName>Service_Usage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral_Outcome__c</fullName>
        <inlineHelpText>The outcome of the assessment of the referral – whether ‘Case Opened’ or ‘Service Required’. Specifies if person accepted onto the service or not (and any action taken)</inlineHelpText>
        <label>Referral Outcome</label>
        <picklist>
            <picklistValues>
                <fullName>Case Opened</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Eligible (Referred on)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Eligible (No further action)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Declined (Referred on)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Declined (No further action)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable to contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Field__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the Service/Activity.
Filtered by Service Type and user&apos;s Locality for internal Service Usage records.
No filter required for &apos;Outgoing Referrals&apos; as these are only ever created in the background (via Referrals screen).</description>
        <label>Service</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 5 AND 6) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>Services__c.service_type__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Type__c</valueField>
            </filterItems>
            <filterItems>
                <field>Services__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Service</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outgoing Referral</value>
            </filterItems>
            <filterItems>
                <field>Services__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Service</value>
            </filterItems>
            <filterItems>
                <field>Services__c.Locality__r.Name</field>
                <operation>equals</operation>
                <valueField>$User.Locality__c</valueField>
            </filterItems>
            <filterItems>
                <field>Services__c.service_status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Services__c</referenceTo>
        <relationshipLabel>Service Usage</relationshipLabel>
        <relationshipName>Service_Usage</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Usage</label>
    <nameField>
        <label>Service Usage Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Usage</pluralLabel>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <description>Used to track referrals and service provision for any other (non standard) Society run services.</description>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>SSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Services Manager</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 OR 4 OR 5) AND (2 OR 3 OR 6 OR 7 OR 8)</booleanFilter>
            <errorMessage>Value does not exist or does not match filter criteria. Must be a Services Manager</errorMessage>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>CRS and BDC</value>
            </filterItems>
            <filterItems>
                <field>User.Title</field>
                <operation>startsWith</operation>
                <value>Services Manager</value>
            </filterItems>
            <filterItems>
                <field>User.Title</field>
                <operation>equals</operation>
                <value>SM</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>CRS and Service Data Manager</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Force.com - Service Data Manager</value>
            </filterItems>
            <filterItems>
                <field>User.Title</field>
                <operation>contains</operation>
                <value>Operations Manager</value>
            </filterItems>
            <filterItems>
                <field>User.Title</field>
                <operation>contains</operation>
                <value>Regional Operations Manager</value>
            </filterItems>
            <filterItems>
                <field>User.Title</field>
                <operation>startsWith</operation>
                <value>Locality Manager</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Services_Activities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/UI_Participant__c.object
<CustomObject>
    <description>A User Involvement Participant with Consent</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This has to be look-up, not a Master-Detail so that anyone can own a Participant, regardless of the Contact Owner.</description>
        <inlineHelpText>The CRS Person record for this Participant. You may have limited access to data on the Person Profile</inlineHelpText>
        <label>Person Record</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Records</relationshipLabel>
        <relationshipName>User_Involvement_Participant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requires_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the Person is an active service user at the point they are set to Active, and the current user is not a CRS user with access to the Person record then 
approval will be requested from the Service Usage primary contact</description>
        <inlineHelpText>If this Person is an active service user, and you do not already have access to their personal details, then approval will be requested from their current Primary Service Usage Assigned Worker.</inlineHelpText>
        <label>Requires Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SU_SSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Services Manager for the most recently used Service Usage. 
Computed in by the trigger, used in the approval workflow.</description>
        <inlineHelpText>The Services Manager for the most recently used Service Usage. 
Computed in by the trigger, used in the approval workflow.</inlineHelpText>
        <label>SU Services Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UI_Participant_SSM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Participant</description>
        <inlineHelpText>The current status of Participant.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unconfirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>User Involvement Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UIUtils.cls
/*******************  USER INVOLVEMENT  *************************************
   * @author          gary.grant@conseq.co.uk
   * @date            November 2014
   * @description     A set of utility methods for User Involvement
                      
   *     
   ***************************************************************************/  

public without sharing class UIUtils {

	
	public static void setParticipantDeceased(Contact contact)
	{
		List<Contact> lis = new List<Contact>();
		if (contact != null) lis.add(Contact);
		setParticipantsDeceased(lis); 
	}


    /* For a deceased Contact, find the Participant and set them deceased 
       This can be used from a Trigger
    */
	public static void setParticipantsDeceased(List<Contact> lisContacts)
	{
			     
		List<String> lisContactIds = new List<String>();	
		for (Contact c : lisContacts) {		
			if ( c.Deceased__c == true ) {
			    lisContactIds.add(c.id);
			}		
		}	
			  		
		List<UI_Participant__c> lisParticipants = [select id, Name, Status__c from UI_Participant__c where Contact__c in:lisContactIds and Status__c !='Merged'];
		List<UI_Participant__c> lisParticipantsToUpdate = new List<UI_Participant__c>();
		
		List<String> lisParticipantIds = new List<String>();		
		for (UI_Participant__c p : lisParticipants) {			
							
			if (p.Status__c != 'Deceased') { 
				p.Status__c = 'Deceased';
				lisParticipantsToUpdate.add(p);
			}
		}		
				  
		update lisParticipantsToUpdate;		  
		
		List<ProcessInstanceWorkitem> lisWorkItems =  [Select Id, ProcessInstance.TargetObjectId from ProcessInstanceWorkitem where ProcessInstance.TargetObjectId in: lisParticipantsToUpdate];		
		for (ProcessInstanceWorkitem piwi : lisWorkItems) {
		
			try {
		            
				system.debug('*^*^* : In Participant Trigger for Deceased Contact: Processing Piwi ' + piwi.id);
													    
		    	Approval.ProcessWorkitemRequest req2 = new Approval.ProcessWorkitemRequest();
		    	req2.setComments('Rejected because the Person is deceased.');
		    	req2.setAction('Reject');        		        
		    	req2.setWorkitemId(piwi.id);        
		    	Approval.ProcessResult result2 =  Approval.process(req2);	    		
	
			}
							
			catch (Exception x) {
				system.debug('Auto Workflow approval on deceased Participant failed ' + piwi.id);
				system.debug(x.getMessage());
			}
		
		}
				
		
	}

    /* Create manual sharing records for the Person. This will share the Person record to
       users in the User Involvement User public group
    */   
    public static Boolean doSharePersonRecords(List<String> lisContactIds)
    {
    
        if (lisContactIds== null || lisContactIds.isEmpty()) { return true; }
    
        //Get the id of the User Involvement Public Group
        Group grp = [select id from Group where DeveloperName = 'User_Involvement_Users'];
        if (grp==null) {            
            return false;
        }
        
        String userOrGroupId = grp.id;
                
        List<ContactShare> lisContactShares = [SELECT Id, ContactId FROM ContactShare WHERE ContactId IN :lisContactIds AND UserOrGroupId =: userOrGroupId and RowCause='Manual'];
        
        Map<String, ContactShare> mapContactShares = new Map<String, ContactShare>();
        for (ContactShare share : lisContactShares) {
            mapContactShares.put(share.ContactId, share);
        }
                
        List<ContactShare> lisContactSharesAdd = new List<ContactShare>();        
        for (String id : lisContactIds) {

            ContactShare sh = mapContactShares.get(id);
            system.debug(sh==null);         
            
                
            if ( sh == null ) {
                
                system.debug('UI_Participant : Creating Sharing Rule : ' + id);
                    
                ContactShare share = new ContactShare();
                share.ContactId = id;
                share.ContactAccessLevel ='Read';
                share.RowCause = 'Manual';
                share.UserOrGroupId = grp.id;
                
                lisContactSharesAdd.add(share);                             
            }
    
        }
        
        insert lisContactSharesAdd;
        return true;
    
    }

    /* Remove manual sharing records for the Person. This will remove share records for the Person record for
       users in the User Involvement User public group
    */
    public static Boolean doUnsharePersonRecords(List<String> lisContactIds)
    {
        
        if (lisContactIds== null || lisContactIds.isEmpty()) {  return true; } 
        
        //Get the id of the User Involvement Public Group
        Group grp = [select id from Group where DeveloperName = 'User_Involvement_Users'];
        if (grp==null) {        
            return false;
        }
        
        String userOrGroupId = grp.id;
        
        List<ContactShare> lisContactSharesRemove = [SELECT Id FROM ContactShare WHERE ContactId IN :lisContactIds AND UserOrGroupId =: userOrGroupId and RowCause = 'Manual'];
        if (lisContactSharesRemove.size()>0) {          
            delete lisContactSharesRemove;          
        }
        
        return true;
    }

	/* If the Person is an active service user, get the name of the Service Managers 
       Supports bulk updates by returning a Map keyed on Person Id      
    */        
    public static Map<String, Service_Usage__c> getSuServiceManagers(List<String> lisContactIds)
    {
        
        Map<String, Service_Usage__c> mapSu = new Map<String, Service_Usage__c>();
            
        List<Service_Usage__c> lisSu = 
                            [select id, Primary_Service_User__c, Service_Field__c, Service_Field__r.SSM__c, Service_Field__r.SSM__r.Name, Service_Field__r.SSM__r.IsActive from Service_Usage__c 
                                where 
                                Primary_Service_User__c in :lisContactIds and
                                Referral_Outcome__c in ('Service Required', 'Case Opened', 'Active User') and 
                                Closure_Date__c = null and 
                                Service_Field__r.SSM__c <> null and 
                                Service_Field__r.SSM__r.isActive = true
                                order by Primary_Service_User__c, LastModifiedDate asc];

        if ( lisSu.isEmpty() ) { return mapSu; }
        
        /* The sort order of the query ensures that the most recent SU will get into the map for each user
           since the map can only have one entry per user
        */
        for (Service_Usage__c su : lisSu) {                 
             mapSu.put(su.Primary_Service_User__c, su);
        }                                   
        
        return mapSu;
        
    }



    
    /* Prepare for submission into approval
       Note : the function does not call update on the Participant
       
       Approval is only actually required for users who do not normally 
       have access to the Person record. This value is ignored for all other users          
    */
    public static boolean setParticipantRequiresApproval(UI_Participant__c p, Service_Usage__c su)
    {
        boolean bActive = false;
        boolean bSSM = true;
        
        system.debug('Setting Participant SU Details');
        
        if ( p.Status__c == 'Active' ) {            
            bActive=true;                        
            system.debug('Setting Participant SU Details - Active is True');
        }


        /* If there is no service manager or the service manager is no longer with the Society
           Then this process should mail the Engagement and Participation Officer
           for the relevant region
           NOTE : EPO's are not in Salesforce at the moment, so cannot be identified                      
            */         
        if ( su==null || su.Service_Field__c==null || su.Service_Field__r.SSM__c==null || su.Service_Field__r.SSM__r.isActive==false ) {           
            
            system.debug('Setting Participant SU Details - SU_SSM is null or other');
            
            p.SU_SSM__c = null;
            bSSM = false;

        } else { 

			//!!! TODO Engagement and Participation Officers need to be plugged in here
			//    and asked to do the approval if there is no Service Manager available. 

			system.debug('Setting Participant SU Details - SU_SSM is being Set to ' + su.Service_Field__r.SSM__c);

            p.SU_SSM__c = su.Service_Field__r.SSM__c;
            bSSM = true;

        }

        if ( (bActive == false) && (bSSM == true)) {
            p.Requires_Approval__c = true;
            
            system.debug('Setting Participant SU Details - Requires Approval is set to True');
            
            return true;
        }
        
        return false;    
        
    }
    
    
    public static Service_Usage__c getLatestServiceUsage(String contactId) {
    
    			 
		   List<Service_Usage__c> lisSu =   
		         [select id, Primary_Service_User__c, Service_Field__c, Service_Field__r.Name, Service_Field__r.SSM__c, Service_Field__r.SSM__r.Name, Service_Field__r.SSM__r.IsActive from Service_Usage__c 
		          where 
		          Primary_Service_User__c =:contactId and
		          Referral_Outcome__c in ('Service Required', 'Case Opened', 'Active User') and 
		          Closure_Date__c = null and
		          Service_Field__r.SSM__c <> null and 
		          Service_Field__r.SSM__r.isActive = true
		          order by LastModifiedDate desc];
		        	             
		    if (!lisSu.isEmpty()) {
		    	
		    	 Service_Usage__c su = lisSu[0];
		    	 system.debug('Fetching Service Usage: ' + su.id + ':' + su.Service_Field__r.SSM__r.Name); 
		       	 return su;
	    	}
	         
	        return null;
    }
    
 }