src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <description>Alzheimer&apos;s Trading Ltd</description>
        <inlineHelpText>Please choose Contact Type</inlineHelpText>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>Associate Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/External_Contacts__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <inlineHelpText>Contact Type=Public Contact then the contact name gets updated on the service record.</inlineHelpText>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>Public Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Contact</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>External Contacts</label>
    <nameField>
        <displayFormat>EC{00000}</displayFormat>
        <label>External Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ExternalContactsTriggerHandler_Test.cls
@isTest
/***********************************************************************************************
* @author          Lakshmi Rajendram 
* @date            02-03-2015
* @description     Test class for ExternalContactsTriggerHandler
***********************************************************************************************/


public class ExternalContactsTriggerHandler_Test {
    static testMethod void TestOnAfterInsertUpdateExContact()
    {
        
        Map<String, Object> mapTestData= TestDataFactory_Services.getTestData();
        External_Contacts__c exContact = (External_Contacts__c)mapTestData.get('exContact');
        exContact.Contact_Type__c='Public Contact;Primary Contact';
        update exContact;
        
    }
    
    
    
}