src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Client_reference_number__c</fullName>
        <description>System generated unique reference number across all People.</description>
        <displayFormat>P{00000000}</displayFormat>
        <externalId>true</externalId>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/contact__c.object
<CustomObject>
    <label>contact</label>
    <nameField>
        <label>contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Demographic_Information__c.object
<CustomObject>
    <description>Demographic Information held against the People (Contact) record.</description>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Demographic Information</relationshipLabel>
        <relationshipName>Demographic_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Demographic Information</label>
    <nameField>
        <label>Person Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demographic Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UI_Participant__c.object
<CustomObject>
    <description>A User Involvement Participant with Consent</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This has to be look-up, not a Master-Detail so that anyone can own a Participant, regardless of the Contact Owner.</description>
        <inlineHelpText>The CRS Person record for this Participant. You may have limited access to data on the Person Profile</inlineHelpText>
        <label>Person Record</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Records</relationshipLabel>
        <relationshipName>User_Involvement_Participant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Participant</description>
        <inlineHelpText>The current status of Participant.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unconfirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>User Involvement Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UIContactWrapper.cls
public without sharing class UIContactWrapper{

  /***********************************************************************************************************
    *
    *   @author        :  gary.grant@conseq.co.uk
    *   @date          :  August 2014
    *   @description   :  A wrapper class for a Contact in the context of User Involvement 
    *                     Contains data about the Contact, demographic data and General Consent   
                          which is in the Participant record                  
    *     
    ************************************************************************************************************/

    public UI_Participant__c participant {get;set;}
    public Contact contact {get;set;}
    public Demographic_Information__c dgdata {get;set;}
    
    /* Constructor for a single instance. Do not use this version of the constructor for list - that will exceed the 
       query governor limits very quickly. */ 
    public UIContactWrapper(Contact c) {
    
      contact = c;       

      /* Demographic information is stored on a separate record in the database 
         This record will not be saved but is there to make the data model complete. 
      */  

	  dgdata = (Demographic_Information__c)CustomUtils.ObjectWithAllFields('Person__c', contact.id , Schema.sObjectType.Demographic_Information__c);
      if (dgdata == null) {
          dgdata = new Demographic_Information__c();
          dgdata.Person__c = contact.id;
          dgdata.OwnerId = contact.OwnerId;
          dgdata.Name = contact.Client_reference_number__c;          
      }
      
      
      /* The User Involvement data is stored in a separate record that records general consent to be involved */         
      participant = (UI_Participant__c)CustomUtils.ObjectWithAllFields('Contact__c', contact.id , Schema.sObjectType.UI_Participant__c);      
      if (participant==null) {               
            // Create a new Consent Object. This is used in the view and may not be saved. 
            participant = new UI_Participant__c();
            participant.Contact__c = contact.id;
            participant.Status__c = 'Unconfirmed';              
      }
    
    }

	// Partial Constructor
    public UIContactWrapper(Contact c, UI_Participant__c p) {
    
      contact = c;       
      participant = p;
                  
      /* The User Involvement data is stored in a separate record that records general consent to be involved        
         Create a new Consent Object. This is used in the view and may not be saved.
      */                    
      if (participant==null) {                      
          participant = new UI_Participant__c();
          participant.Contact__c = contact.id;
          participant.Status__c = 'Unconfirmed';              
      }
    
    }

	// Full Constructor
    public UIContactWrapper(Contact c, UI_Participant__c p, Demographic_Information__c dg) {
    
      contact = c;       
      participant = p;
      dgdata = dg;      

      /* Demographic information is stored on a separate record in the database 
         This record will not be saved but is there to make the data model complete. 
      */  

      if (dgdata == null) {
          dgdata = new Demographic_Information__c();
          dgdata.Person__c = contact.id;
          dgdata.OwnerId = contact.OwnerId;
          dgdata.Name = contact.Client_reference_number__c;          
      }
      
      
      /* The User Involvement data is stored in a separate record that records general consent to be involved        
         Create a new Consent Object. This is used in the view and may not be saved.
      */                    
      if (participant==null) {                      
          participant = new UI_Participant__c();
          participant.Contact__c = contact.id;
          participant.Status__c = 'Unconfirmed';              
      }
    
    }


}