src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Deceased__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>To set a person as deceased please use the Person Wizard.</inlineHelpText>
        <label>Deceased?</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <description>Used as default Record Type for helpline calls etc.</description>
        <label>Other</label>
    </recordTypes>
    <recordTypes>
        <fullName>Peer</fullName>
        <active>true</active>
        <description>Member of the House of Lords</description>
        <label>Peer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RegionAreaLocalityMap__c.object
<CustomObject>
    <description>Used as a reference/Lookup for Mapping the new Region | Area | Locality set-up.</description>
    <fields>
        <fullName>RegionAreaLocalityNameNew__c</fullName>
        <label>RegionAreaLocalityNameNew</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RegionAreaLocalityName__c</fullName>
        <label>RegionAreaLocalityName</label>
        <type>TextArea</type>
    </fields>
    <label>RegionAreaLocalityMap</label>
    <nameField>
        <label>RegionAreaLocalityMap Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RegionAreaLocalityMap</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Usage__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Service_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service User</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 OR 2) AND ((3 AND 4) OR (5 AND 6) OR 7 OR 8)</booleanFilter>
            <errorMessage>For Day care &amp; support and Community support Services, Service User must be a living Person with Dementia. For other services Service User can also be a Carer of a Person with Dementia. Newsletter is available to all.</errorMessage>
            <filterItems>
                <field>Contact.Deceased_Date__c</field>
                <operation>greaterThan</operation>
                <valueField>$Source.Referral_Date__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.Deceased__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Type__c</field>
                <operation>equals</operation>
                <value>Community support service, Day care and support (establishment based), Registered home care and support</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person with Dementia</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Type__c</field>
                <operation>equals</operation>
                <value>Activity group, Dementia adviser, Dementia support, Dementia cafe, Information programme, Other (one to one), Peer support group, Singing for the Brain, Befriending, Advocacy</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Carer of Person with Dementia, Person with Dementia</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Type__c</field>
                <operation>equals</operation>
                <value>Newsletter</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outgoing Referral</value>
            </filterItems>
            <infoMessage>For Day care &amp; support and Community support Services, Service User must be a living Person with Dementia. For other services Service User can also be a Carer of a Person with Dementia. Newsletter is available to all.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Usage</relationshipLabel>
        <relationshipName>Service_Usage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Field__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the Service/Activity.
Filtered by Service Type and user&apos;s Locality for internal Service Usage records.
No filter required for &apos;Outgoing Referrals&apos; as these are only ever created in the background (via Referrals screen).</description>
        <label>Service</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 5 AND 6) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>Services__c.service_type__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Type__c</valueField>
            </filterItems>
            <filterItems>
                <field>Services__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Service</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outgoing Referral</value>
            </filterItems>
            <filterItems>
                <field>Services__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Service</value>
            </filterItems>
            <filterItems>
                <field>Services__c.Locality__r.Name</field>
                <operation>equals</operation>
                <valueField>$User.Locality__c</valueField>
            </filterItems>
            <filterItems>
                <field>Services__c.service_status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Services__c</referenceTo>
        <relationshipLabel>Service Usage</relationshipLabel>
        <relationshipName>Service_Usage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <description>The type of Service to which Service Usage relates.
Used as a filter when selecting Service.
Used to set Record Type on saving a new Service Usage.</description>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (one to one)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peer support group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered home care and support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singing for the Brain</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Share_with_colleagues__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the Service Usage should be automatically shared with colleagues (via trigger).</description>
        <inlineHelpText>Indicates whether the Service Usage record should be shared with colleagues. All records are shared by default unless the checkbox is deselected by an SSM or above</inlineHelpText>
        <label>Share with colleagues?</label>
        <type>Checkbox</type>
    </fields>
    <label>Service Usage</label>
    <nameField>
        <label>Service Usage Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Usage</pluralLabel>
    <recordTypes>
        <fullName>Advocacy</fullName>
        <active>true</active>
        <description>Used for all Advocacy Referrals and Cases</description>
        <label>Advocacy</label>
    </recordTypes>
    <recordTypes>
        <fullName>Newsletter</fullName>
        <active>true</active>
        <description>Used to put individual on Newsletter distribution list (for a specific Newsletter)</description>
        <label>Newsletter</label>
    </recordTypes>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <description>Used to track referrals and service provision for any other (non standard) Society run services.</description>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>Locality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Locality in which this service is based (left blank for national services).</description>
        <label>Locality</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select an Alzheimer&apos;s Society Locality.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Organisation</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>contains</operation>
                <value>Locality</value>
            </filterItems>
            <infoMessage>Please select a Locality.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Services_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>National_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>National Service?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>service_type__c</fullName>
        <inlineHelpText>Service description will be automatically populated from the service type (or sub type if there is one)</inlineHelpText>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult education &amp; training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (emotional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (financial)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (general)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awareness raising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending / home support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counselling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day support / day care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafés</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exercise / Fitness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home facilities &amp; services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Dementia)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Financial &amp; Legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programmes &amp; provision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (one to one)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peer support group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered home care and support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singing for the Brain</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>Internal Service/Activity</description>
        <label>Internal Service</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ServiceChangeUpdateServiceUsage1_Test.cls
@isTest
public class ServiceChangeUpdateServiceUsage1_Test {
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : Test APEX Class for ServiceChangeUpdateServiceUsage Apex Class.
 *  Author  : Mike Tinson
 *  Date    : 26-06-2014
 *  Version : 0.1 Unit Test
 *
 *  Description:    Test APEX Class for ServiceChangeUpdateServiceUsage Apex Class which 
 *                  realigns service usage records for a selected Service.
 *
 *                  *Note that since email messages aren’t sent from tests, and because the batch 
 *                  class is invoked by a test method, the email notifications won’t be sent in this case. 
 *
 *  Modification History
 *  Date            Who         Description 
 *  dd-mm-yyyy      ??          ??
 *                             
*******************************************************************************************/
static testMethod void mainTest(){
    Contact recCon = new Contact(FirstName = 'Albert', LastName='TestLastName',Deceased__c=false,MailingPostalCode ='ABC123', Birthdate =Date.Today(),
    RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and Name Like 'Person with dementia'].id);
    insert recCon;  
    System.debug('****** Contact ******: ' + recCon.FirstName);
    Account accRec = new Account(Name='Midlands Central Locality',RecordTypeId=[Select Id from RecordType where SObjectType='Account' and Name like 'Internal%'].id);
    insert accRec;
    System.debug('****** Account ******: ' + accRec.Name);
    Services__c serv = new Services__c(Name='Awareness Raising - East Herts', Locality__c=accRec.id,Service_Type__c='Dementia support', National_Service__c=false);//Name='testControllerService');
    insert serv; 
    //create look up used by trigger on Service Usage
    RegionAreaLocalityMap__c RALMap = new RegionAreaLocalityMap__c();
    RALMap.RegionAreaLocalityName__c='Locality Management - Midlands Central';
    RALMap.RegionAreaLocalityNameNew__c = 'Locality Management - Birmingham, Solihull, Coventry & Warks';
    insert RALMap;   
    System.debug('****** Services******: ' + serv.Name);
    Service_Usage__c recSU = new Service_Usage__c(Service_Field__c= serv.id, Primary_Service_User__c=recCon.id,Service_Type__c='Dementia support', RecordTypeId=[
            select id from RecordType where Name ='Outgoing Referral' and SobjectType = 'Service_Usage__c'].id,Share_with_colleagues__c=True);    
    insert recSU;
    System.debug('****** Service Usage******: ' + recSU.Name);
    serv.Service_Type__c='Dementia adviser';
    update serv;
    
    ServiceChangeUpdateServiceUsage1 subatch=new ServiceChangeUpdateServiceUsage1();
    subatch.isRunningTest=true;
    String resultStr;
        resultStr = suBatch.CheckServiceType('xxx','Activity group');
        resultStr = suBatch.CheckServiceType('xxx','Advocacy');
        resultStr = suBatch.CheckServiceType('xxx','Befriending');
        resultStr = suBatch.CheckServiceType('xxx','Community support service');
        resultStr = suBatch.CheckServiceType('xxx','Day care and support (establishment based)');
        resultStr = suBatch.CheckServiceType('xxx','Dementia adviser');
        resultStr = suBatch.CheckServiceType('xxx','Dementia cafe');
        resultStr = suBatch.CheckServiceType('xxx','Dementia support');
        resultStr = suBatch.CheckServiceType('xxx','Information programme');
        resultStr = suBatch.CheckServiceType('xxx','Newsletter');
        resultStr = suBatch.CheckServiceType('xxx','Other (one to one)');
        resultStr = suBatch.CheckServiceType('xxx','Peer support group');
        resultStr = suBatch.CheckServiceType('xxx','Registered home care and support');
        resultStr = suBatch.CheckServiceType('xxx','Singing for the Brain');
        resultStr = suBatch.CheckServiceType('xxx','yyyy');
    Id resultId;
        //call routine to fill map with record types.  This is usually done at start of execute call.
        suBatch.GetRecordtypes();
        resultId = suBatch.CheckRecordType(recSU.recordtypeid,'Activity group');     
        resultId = suBatch.CheckRecordType(recSU.recordtypeid,'Advocacy');
        resultId = suBatch.CheckRecordType(recSU.recordtypeid,'Befriending');
        resultId = suBatch.CheckRecordType(recSU.recordtypeid,'Community support service');
        resultId = suBatch.CheckRecordType(recSU.recordtypeid,'Day care and support (establishment based)');
        resultId = suBatch.CheckRecordType(recSU.recordtypeid,'Dementia adviser');
        resultId = suBatch.CheckRecordType(recSU.recordtypeid,'Dementia cafe');
        resultId = suBatch.CheckRecordType(recSU.recordtypeid,'Dementia support');
        resultId = suBatch.CheckRecordType(recSU.recordtypeid,'Information programme');
        resultId = suBatch.CheckRecordType(recSU.recordtypeid,'Newsletter');
        resultId = suBatch.CheckRecordType(recSU.recordtypeid,'Other (one to one)');
        resultId = suBatch.CheckRecordType(recSU.recordtypeid,'Peer support group');
        resultId = suBatch.CheckRecordType(recSU.recordtypeid,'Registered home care and support');
        resultId = suBatch.CheckRecordType(recSU.recordtypeid,'Singing for the Brain');
        resultId = suBatch.CheckRecordType(recSU.recordtypeid,'yyyy');
    Database.executeBatch(subatch,1);
    System.assert(true);
}
}