src/objects/contact__c.object
<CustomObject>
    <label>contact</label>
    <nameField>
        <label>contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UI_Activity__c.object
<CustomObject>
    <description>A User Involvement Activity. There may be Participation from one or more UI Participants</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>When will the Activity end ( could be the same day as the Start)</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>When did the Activity Start ?</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>User Involvement Activity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Involvement Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/UI_Activity_Participation__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Person Profile for this Participant. You may have limited access to the Person profile.</inlineHelpText>
        <label>Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Involvement Participation</relationshipLabel>
        <relationshipName>UI_Participation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>Date the Involvement ended (may be the same date as Start Date)</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>The date the Activity took place for the Participant.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The Status of this Participation</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UI_Activity__c</fullName>
        <inlineHelpText>The Activity with which the Participant was Involved</inlineHelpText>
        <label>Involvement Activity</label>
        <referenceTo>UI_Activity__c</referenceTo>
        <relationshipLabel>Involvement Participation</relationshipLabel>
        <relationshipName>UI_Participation</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UI_Participant__c</fullName>
        <inlineHelpText>The Participant</inlineHelpText>
        <label>Participant</label>
        <referenceTo>UI_Participant__c</referenceTo>
        <relationshipLabel>Involvement Participation</relationshipLabel>
        <relationshipName>Participation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>User Involvement Participation</label>
    <nameField>
        <displayFormat>APA-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Involvement Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UI_Participant__c.object
<CustomObject>
    <description>A User Involvement Participant with Consent</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This has to be look-up, not a Master-Detail so that anyone can own a Participant, regardless of the Contact Owner.</description>
        <inlineHelpText>The CRS Person record for this Participant. You may have limited access to data on the Person Profile</inlineHelpText>
        <label>Person Record</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Records</relationshipLabel>
        <relationshipName>User_Involvement_Participant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Participant</description>
        <inlineHelpText>The current status of Participant.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unconfirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Valid_To_Date__c</fullName>
        <description>The date the consent should be reviewed. Participation should not be considered if this date is passed and not updated.</description>
        <inlineHelpText>The date the consent should be reviewed. Participation should not be considered if this date is passed and not continued consent has not be confirmed.</inlineHelpText>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <label>User Involvement Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UIRestUtils.cls
global without sharing class UIRestUtils {

  /*******************  USER INVOLVEMENT  *************************************
   * @author          gary.grant@conseq.co.uk
   * @date            November 2014
   * @description     A set of methods that can be called by custom buttons 
                      on Standard page layouts in the User Involvement Application
                      
                      Sample code : 
                        {!REQUIRESCRIPT("/soap/ajax/32.0/connection.js")} 
                        {!REQUIRESCRIPT("/soap/ajax/32.0/apex.js")} 
                        
                        var sUrl = "" + sforce.apex.execute(
                            "UIRestUtils",
                            "getParticpationUrl",
                            {activityId:window.sfdcPage.entityId}); 
                        
                        if (sUrl.length > 0) { 
                            alert(sUrl); 
                        } 
                        else { 
                            alert("Webservice call failed!"); 
                        }             
                      
   *     
   ***************************************************************************/  

  /** Create a new participation record */ 
  webService static String getParticipantParticipationUrl(String participantId) {
           
        UI_Participant__c p = [select Id, Name, Status__c, Valid_To_Date__c from UI_Participant__c where id =:participantId];
        if (p.Status__c !='Active' || p.Valid_To_Date__c < Date.today() ) {
            return 'Error: Participant Status must be active and review date not exceeded to create Participation';            
        } 
        
        /* This uses the URL Hack to get the fields pre-populated in the standard form. That 
           allows the user to back out of creating the record by hitting cancel.
         
           Custom fields take a CF prefix on lookup fields
           The Name field is identified by name only
        */
         
        Map<String, String> participationObjectFields = CustomUtils.getObjectFieldIds('UI_Activity_Participation__c'); 
        String sQueryString = '?' + participationObjectFields.get('UI_Participant') + '=' + p.Name;
        sQueryString = sQueryString  + '&' + participationObjectFields.get('UI_Participant') + '_lkid=' + p.id;
        sQueryString = sQueryString + '&' + participationObjectFields.get('Status') + '=Planned';
              
        PageReference pr = new PageReference('/' + UI_Activity_Participation__c.SObjectType.getDescribe().getKeyPrefix() + '/e' + sQueryString);
        pr.setRedirect(true);
        
        return pr.getUrl();
  
  }


webService static String getActivityParticpationUrl(String activityId)
    {
   
       UI_Activity__c activity = [select Id, Name, Start_Date__c, End_Date__c from UI_Activity__c where id =:activityId];
    
        /* This uses the URL Hack to get the fields pre-populated in the standard form. That 
           allows the user to back out of creating the record by hitting cancel.
         
           Custom fields take a CF prefix on lookup fields
           The Name field is identified by name only
        */
    
        Map<String, String> mapParticipationObjectFields = CustomUtils.getObjectFieldIds('UI_Activity_Participation__c'); 
                
        String sQueryString = '?' + mapParticipationObjectFields.get('UI_Activity') + '=' + activity.Name;
        sQueryString = sQueryString  + '&' + mapParticipationObjectFields.get('UI_Activity') + '_lkid=' + activity.id;
        
        DateTime dt = activity.Start_Date__c;
        String startDate = dt.format('dd/MM/yyyy');
        
        dt=activity.End_Date__c;
        String endDate = dt.format('dd/MM/yyyy');
            
        sQueryString = sQueryString + '&' + mapParticipationObjectFields.get('Start_Date') + '= ' + startDate;
        sQueryString = sQueryString + '&' + mapParticipationObjectFields.get('End_Date') + '= ' + endDate;
    
        sQueryString = sQueryString + '&' + mapParticipationObjectFields.get('Status') + '=Planned';
              
        String url = '/'+ UI_Activity_Participation__c.SObjectType.getDescribe().getKeyPrefix() + '/e' + sQueryString;
                      
        return url;     
        
}


webService static String getParticipantUrl(String contactId)
    {
   
        UI_Participant__c p = null; 
   
        try {                     
              p = [select id from UI_Participant__c where Status__c != 'Merged' and Contact__c =: contactId];                              
        
        } catch (Exception x) {
          
            // Get the contact record
            Contact contact = [select id, firstName, lastName, Name from Contact where id =: ContactId];  
          
            
            /*  The record has to be created in all cases and the user diverted to the view screen. 
            
				The New (UI_Participant__c) action has to be overriden to divert to the search screen everywhere in
                the application, to ensure no participants are created that duplicate existing contacts. It should not be possible
                to create a new Participant__c without going thru the duplicate screen, aside from directly out of the Contact form.  
                
            */
            
            p = new UI_Participant__c();
            p.Contact__c=contact.id;
            p.Name = contact.Name;
            p.Status__c = 'Unconfirmed'; 
            insert p;
              
        }
              
        PageReference pr = new PageReference('/' + p.id);                          
        pr.setRedirect(true);
                   
        return pr.getUrl();
}

    
}