src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Worker_Type__c</fullName>
        <inlineHelpText>Specifies whether the user is a member of staff or a volunteer.</inlineHelpText>
        <label>Worker Type</label>
        <picklist>
            <picklistValues>
                <fullName>Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volunteer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Person_with_dementia</fullName>
        <active>true</active>
        <description>CRS Use only</description>
        <label>Person with Dementia</label>
    </recordTypes>
    <recordTypes>
        <fullName>Volunteer</fullName>
        <active>true</active>
        <description>Volunteers for Group Events</description>
        <label>Volunteer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event_Attendance_Details__c.object
<CustomObject>
    <fields>
        <fullName>Service_Usage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Usage</label>
        <referenceTo>Service_Usage__c</referenceTo>
        <relationshipLabel>Attendance Details</relationshipLabel>
        <relationshipName>Event_Attendance_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Event Attendance Details</label>
    <nameField>
        <displayFormat>EA-{0000000000}</displayFormat>
        <label>EventAttendeeTiming Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendance Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RegionAreaLocalityMap__c.object
<CustomObject>
    <description>Used as a reference/Lookup for Mapping the new Region | Area | Locality set-up.</description>
    <fields>
        <fullName>RegionAreaLocalityNameNew__c</fullName>
        <label>RegionAreaLocalityNameNew</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RegionAreaLocalityName__c</fullName>
        <label>RegionAreaLocalityName</label>
        <type>TextArea</type>
    </fields>
    <label>RegionAreaLocalityMap</label>
    <nameField>
        <label>RegionAreaLocalityMap Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RegionAreaLocalityMap</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Usage__c.object
<CustomObject>
    <fields>
        <fullName>Service_Type__c</fullName>
        <description>The type of Service to which Service Usage relates.
Used as a filter when selecting Service.
Used to set Record Type on saving a new Service Usage.</description>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (one to one)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peer support group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered home care and support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singing for the Brain</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Usage</label>
    <nameField>
        <label>Service Usage Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Usage</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>Locality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Locality in which this service is based (left blank for national services).</description>
        <label>Locality</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select an Alzheimer&apos;s Society Locality.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Organisation</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>contains</operation>
                <value>Locality</value>
            </filterItems>
            <infoMessage>Please select a Locality.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Services_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>service_type__c</fullName>
        <inlineHelpText>Service description will be automatically populated from the service type (or sub type if there is one)</inlineHelpText>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult education &amp; training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (emotional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (financial)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (general)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awareness raising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending / home support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counselling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day support / day care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafés</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exercise / Fitness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home facilities &amp; services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Dementia)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Financial &amp; Legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programmes &amp; provision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>Internal Service/Activity</description>
        <label>Internal Service</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Locality__c</fullName>
        <description>The Society Locality to which the user is assigned (if any).</description>
        <inlineHelpText>Must match the Name of the corresponding Internal Organisation.</inlineHelpText>
        <label>Locality</label>
        <picklist>
            <controllingField>Area__c</controllingField>
            <picklistValues>
                <fullName>Abertawe Bro Morgannwg Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avon, Gloucestershire &amp; Wiltshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bedfordshire &amp; Luton Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Berkshire, Buckinghamshire, Oxfordshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambridgeshire &amp; Peterborough Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiff and the Vale Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheshire &amp; St Helens Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cumbria Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cwm Taff Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Darlington &amp; Teesside Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Derbyshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Devon, Cornwall &amp; Isles of Scilly Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dorset &amp; Somerset Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durham Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Riding &amp; Humber Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Essex Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Manchester Central &amp; West Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Manchester Central South and East Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gwent Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hampshire, Isle of Wight and the Channel Islands Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Herefordshire &amp; Worcestershire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hertfordshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent &amp; Medway Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lancashire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leicestershire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lincolnshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merseyside &amp; Isle of Man Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Midlands Central Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norfolk Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North &amp; East Northern Ireland Locality</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Worker_Type__c</fullName>
        <description>Specifies whether the user is a member of staff or a volunteer.</description>
        <label>Worker Type</label>
        <picklist>
            <picklistValues>
                <fullName>Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volunteer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/EventAttendeeController_Test.cls
@isTest
public class EventAttendeeController_Test{
/******************************************************************************************
 *  Alzheimer's 
 *  
 *  Purpose : Test Class for EventAttendeeController
 *  Author  : Mike Tinson
 *  Date    : 21-01-2015
 *  Version : 1
 *  Project : 
 *
 *  Modification History
 *
 *  Date         Who    Description 
 *  yyyy-mm-dd - XX -   xxxxxxxxxxxxxxxxxxxxxxxxxxxx
 *  21-01-2015    MT      Moved to separate test class from orignal test routine in EventAttendeeController          
*******************************************************************************************/
static testMethod void testEventAttendeeController(){

    
    Account acc = new Account(Name='Midlands Central Locality',RecordTypeId=[Select Id from RecordType where 
            SObjectType='Account' and Name like 'Internal%'].id);
    insert acc;
    
    Services__c serv = new Services__c(Locality__c=acc.id,Name='testControllerService',Service_Type__c='Dementia cafe');
    insert serv;    
    
    //create look up used by trigger on Service Usage
    RegionAreaLocalityMap__c RALMap = new RegionAreaLocalityMap__c();
    RALMap.RegionAreaLocalityName__c='Locality Management - Midlands Central';
    RALMap.RegionAreaLocalityNameNew__c = 'Locality Management - Birmingham, Solihull, Coventry & Warks';
    insert RALMap;
    
    Id conRecTypeId =[Select Id from RecordType where SObjectType='Contact' and name like 'Person with dementia%'].id;
    Id volRecTypeId =[Select Id from RecordType where SObjectType='Contact' and name like 'Volunteer%'].id;
    
    Contact con1 = new Contact(Salutation='Mr',FirstName='Abc',LastName='Test1',MailingPostalCode ='ABC123', Birthdate =Date.Today(),
        RecordTypeId=conRecTypeId);
    insert con1;
    
    Contact con2 = new Contact(Salutation='Mr',FirstName='Abc',LastName='Test2',MailingPostalCode ='ABC123', Birthdate =Date.Today(),
        RecordTypeId=conRecTypeId);
    insert con2;
    Contact volCon = new Contact(Salutation='Mr',FirstName='Abc',LastName='Volunteer1',MailingPostalCode ='ABC123', Birthdate =Date.Today(),
        RecordTypeId=volRecTypeId, Worker_Type__c='Volunteer');
    insert volCon;
    
    Service_Usage__c servUsg1 = new Service_Usage__c(Service_Field__c=serv.id,Primary_Service_User__c=con1.id,Service_Type__c='Dementia cafe');
    insert servUsg1;
    
    Service_Usage__c servUsg2 = new Service_Usage__c(Service_Field__c=serv.id,Primary_Service_User__c=con2.id,Service_Type__c='Dementia cafe');
    insert servUsg2;
        
    Test.StartTest();
    
    
    Event eveRec = new Event(WhatId=serv.Id,Subject='TestController',DurationInMinutes=30,
    ActivityDateTime=System.Today(),
    ActivityDate = System.Today() ,
    RecurrenceEndDateOnly = System.Today().addDays(7) ,
    RecurrenceStartDateTime = System.Today(),
    RecurrenceType = 'RecursEveryWeekday',
    RecurrenceDayofWeekMask = 64,
    IsRecurrence = TRUE,Format__c='Face to Face', In_Out__c='Outgoing',Location_Type_Event__c='Office');
    insert eveRec;
    
    Event_Attendance_Details__c eveAttn = new Event_Attendance_Details__c(EventNumber__c=[Select EventNumber__c from Event where id=:eveRec.id].EventNumber__c,Contact__c=volCon.id,Type__c='Contact');
    insert eveAttn;

    ApexPages.currentPage().getParameters().put('Id', eveRec.id);        
    EventAttendeeController conCls= new EventAttendeeController(new ApexPages.StandardController(eveRec));
    conCls.removeConId=con1.id;
    conCls.AddToList();
    conCls.saveUsersNReturn();

    conCls.RemoveContact();
    conCls.lstAvailableCons[0].isSelected=true;
    conCls.AddToList();
    conCls.saveContactsNReturn();

    eveRec.WhatId=acc.id;
    update eveRec;
    delete eveRec;
    delete con1;
   
}
static testMethod void testEventAttendeeController2(){
    //test single event, contact already added.
    
    Account acc = new Account(Name='Midlands Central Locality',RecordTypeId=[Select Id from RecordType where 
            SObjectType='Account' and Name like 'Internal%'].id);
    insert acc;
    
    Services__c serv = new Services__c(Locality__c=acc.id,Name='testControllerService',Service_Type__c='Dementia cafe');
    insert serv;    
    
    //create look up used by trigger on Service Usage
    RegionAreaLocalityMap__c RALMap = new RegionAreaLocalityMap__c();
    RALMap.RegionAreaLocalityName__c='Locality Management - Midlands Central';
    RALMap.RegionAreaLocalityNameNew__c = 'Locality Management - Birmingham, Solihull, Coventry & Warks';
    insert RALMap;
    
    Id conRecTypeId =[Select Id from RecordType where SObjectType='Contact' and DeveloperName = 'Person_with_dementia'].id;
    Id volRecTypeId =[Select Id from RecordType where SObjectType='Contact' and DeveloperName = 'Volunteer'].id;
    
    Contact con1 = new Contact(Salutation='Mr',FirstName='Abc',LastName='Test1',MailingPostalCode ='ABC123', Birthdate =Date.Today(),
        RecordTypeId=conRecTypeId);
    insert con1;
    
    Contact con2 = new Contact(Salutation='Mr',FirstName='Abc',LastName='Test2',MailingPostalCode ='ABC123', Birthdate =Date.Today(),
        RecordTypeId=conRecTypeId);
    insert con2;
    Contact volCon = new Contact(Salutation='Mr',FirstName='Abc',LastName='Volunteer1',MailingPostalCode ='ABC123', Birthdate =Date.Today(),
        RecordTypeId=volRecTypeId, Worker_Type__c='Volunteer');
    insert volCon;
    
    Service_Usage__c servUsg1 = new Service_Usage__c(Service_Field__c=serv.id,Primary_Service_User__c=con1.id,Service_Type__c='Dementia cafe');
    insert servUsg1;
    
    Service_Usage__c servUsg2 = new Service_Usage__c(Service_Field__c=serv.id,Primary_Service_User__c=con2.id,Service_Type__c='Dementia cafe');
    insert servUsg2;
        
    Test.StartTest();
    
    
    Event eveRec = new Event(WhatId=serv.Id,Subject='TestController',DurationInMinutes=30,
    ActivityDateTime=System.Today().addDays(1),
    ActivityDate = System.Today().addDays(1) ,
    IsRecurrence = FALSE,
    Format__c='Face to Face', 
    In_Out__c='Outgoing',
    Location_Type_Event__c='Office');
    insert eveRec;
    
    Event_Attendance_Details__c eveAttn = new Event_Attendance_Details__c(EventNumber__c=[Select EventNumber__c from Event where id=:eveRec.id].EventNumber__c,Contact__c=Con1.id,Type__c='Contact', Service_usage__c = servUsg1.id, Attendance_Status__c='Attended');
    insert eveAttn;

    //add contact (service user)
    Event_Attendance_Details__c eveAttn2 = new Event_Attendance_Details__c(EventNumber__c=[Select EventNumber__c from Event where id=:eveRec.id].EventNumber__c,Contact__c=volCon.id,Type__c='Contact', Attendance_Status__c='Attended');
    insert eveAttn2;


    ApexPages.currentPage().getParameters().put('Id', eveRec.id);        
    EventAttendeeController conCls= new EventAttendeeController(new ApexPages.StandardController(eveRec));
    
    conCls.strInsertWithStatus='Attended';
    conCls.AddToList();
    conCls.saveContactsNWorkers();
    conCls.saveUsersNServiceUsers();
    conCls.removeConId=con1.id;
    conCls.RemoveContact();
    conCls.lstAvailableCons[0].isSelected=true;
    conCls.AddToList();
    conCls.saveContactsNReturn();
    

    /*
    eveRec.WhatId=acc.id;
    update eveRec;
    delete eveRec;
    delete con1;
    */

}

}