src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Deceased__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>To set a person as deceased please use the Person Wizard.</inlineHelpText>
        <label>Deceased?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event_Attendance_Details__c.object
<CustomObject>
    <fields>
        <fullName>Attendance_Status__c</fullName>
        <label>Attendance Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event_Date_and_Time__c</fullName>
        <label>Event Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Service_Usage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Usage</label>
        <referenceTo>Service_Usage__c</referenceTo>
        <relationshipLabel>Attendance Details</relationshipLabel>
        <relationshipName>Event_Attendance_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Attendance Details</label>
    <nameField>
        <displayFormat>EA-{0000000000}</displayFormat>
        <label>EventAttendeeTiming Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendance Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Usage__c.object
<CustomObject>
    <fields>
        <fullName>Service_Type__c</fullName>
        <description>The type of Service to which Service Usage relates.
Used as a filter when selecting Service.
Used to set Record Type on saving a new Service Usage.</description>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (one to one)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peer support group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered home care and support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singing for the Brain</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Usage</label>
    <nameField>
        <label>Service Usage Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Usage</pluralLabel>
    <recordTypes>
        <fullName>Advocacy</fullName>
        <active>true</active>
        <description>Used for all Advocacy Referrals and Cases</description>
        <label>Advocacy</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>Locality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Locality in which this service is based (left blank for national services).</description>
        <label>Locality</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select an Alzheimer&apos;s Society Locality.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Organisation</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>contains</operation>
                <value>Locality</value>
            </filterItems>
            <infoMessage>Please select a Locality.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Services_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>National_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>National Service?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>service_type__c</fullName>
        <inlineHelpText>Service description will be automatically populated from the service type (or sub type if there is one)</inlineHelpText>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult education &amp; training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (emotional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (financial)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (general)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awareness raising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending / home support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counselling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day support / day care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafés</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exercise / Fitness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home facilities &amp; services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Dementia)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Financial &amp; Legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programmes &amp; provision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>Internal Service/Activity</description>
        <label>Internal Service</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Locality__c</fullName>
        <description>The Society Locality to which the user is assigned (if any).</description>
        <inlineHelpText>Must match the Name of the corresponding Internal Organisation.</inlineHelpText>
        <label>Locality</label>
        <picklist>
            <controllingField>Area__c</controllingField>
            <picklistValues>
                <fullName>Abertawe Bro Morgannwg Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avon, Gloucestershire &amp; Wiltshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bedfordshire &amp; Luton Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Berkshire, Buckinghamshire, Oxfordshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambridgeshire &amp; Peterborough Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiff and the Vale Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheshire &amp; St Helens Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cumbria Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cwm Taff Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Darlington &amp; Teesside Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Derbyshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Devon, Cornwall &amp; Isles of Scilly Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dorset &amp; Somerset Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durham Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Riding &amp; Humber Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Essex Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Manchester Central &amp; West Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Manchester Central South and East Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gwent Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hampshire, Isle of Wight and the Channel Islands Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Herefordshire &amp; Worcestershire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hertfordshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent &amp; Medway Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lancashire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leicestershire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lincolnshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merseyside &amp; Isle of Man Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Midlands Central Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norfolk Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North &amp; East Northern Ireland Locality</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ServiceUsageDateOfLastActivity.cls
/******************************************************************************************
 *  Alzheimer's
 *  
 *  Purpose : Retrive Last Activity Date (Task/Event/Event_Attendance) created against SU.
 *  Author  : Saaspoint - Mohammed Irfan
 *  Date    : 2012-01-12
 *  Version : 0.1 Unit Tested
 *  Project : CRSProto
 *  Copyright (c) Saaspoint 2012 as per Master Services Agreement
 *
 *  Description: Class with static method to retrive/calculate last Activity schedule for SU records. 
 *               
 *               
 *  Modification History
 *
 *  Date         Who    Description 
 *  yyyy-mm-dd - XX -   xxxxxxxxxxxxxxxxxxxxxxxxxxxx
 *  2013-10-30   Ian Smith  Add Start and Stop tests to stop govenor limits being blown                           
*******************************************************************************************/
public class ServiceUsageDateOfLastActivity
{
    //Static method, returns SU Id and Last Activity date for given list of SU Ids.
    public static Map<id,Date> getDateOfLastActivity(Set<Id> SUIds)
    {
        Map<id,date> mapSUActivityDates = new Map<id,date>();
        
        //Retrive Max date of Event for scheduled date is lesser than today
        for(AggregateResult rec: [Select max(ActivityDateTime) MaxDate,WhatId from Event where ActivityDateTime <= Today 
                and WhatId=:SUIds group by WhatId])
        {
            if(rec.get('WhatId')==null) continue;
            
            if(!mapSUActivityDates.containsKey((id)rec.get('WhatId')))
            {
                DateTime dt = (DateTime)rec.get('MaxDate');
                mapSUActivityDates.put((id)rec.get('WhatId'),date.newinstance(dt.Year(), dt.Month(), dt.day()));
            }
        }
        
        //Retrive Max date of EventAttendanceDetail for status is Attended
        for(AggregateResult rec: [Select max(Event_Date_and_Time__c) MaxDate, Service_Usage__c from Event_Attendance_Details__c 
                where Attendance_Status__c='Attended' and Service_Usage__c =:SUIds group by Service_Usage__c])
        {
            if(rec.get('Service_Usage__c')==null) continue;
            
            DateTime dt = (DateTime)rec.get('MaxDate');
            //If SU and Date not added earlier
            if(!mapSUActivityDates.containsKey((id)rec.get('Service_Usage__c')))
            {
                mapSUActivityDates.put((id)rec.get('Service_Usage__c'),date.newinstance(dt.Year(), dt.Month(), dt.day()));
            }
            else
            {
                //Check previous added SU Activity date is lesser than current Max date, if so replace/update new date.
                if(mapSUActivityDates.get((id)rec.get('Service_Usage__c'))<dt)
                     mapSUActivityDates.put((id)rec.get('Service_Usage__c'),date.newinstance(dt.Year(), dt.Month(), dt.day()));
            }
        }        
        
        
       //Retrive Max date of Task for status is completed.
        for(Task rec: [Select ActivityDate, WhatId from Task where Status='Completed' and WhatId=:SUIds and ActivityDate <> null])
        {
            if(rec.WhatId==null) continue;

            if(!mapSUActivityDates.containsKey(rec.WhatId))
            {
                mapSUActivityDates.put(rec.WhatId,rec.ActivityDate);
            }
            else
            {
                if(mapSUActivityDates.get(rec.WhatId)<rec.ActivityDate)
                    mapSUActivityDates.put(rec.WhatId,rec.ActivityDate);
            }
        }
    return mapSUActivityDates;
    }
public testMethod static void testController()
{

    Contact recCon = new Contact(Salutation='Mr',FirstName='Abc',LastName='TestLastName',Deceased__c=false,MailingPostalCode ='ABC123', Birthdate =Date.Today(),
        RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and Name Like 'Person with dementia'].id);
    insert recCon;        

    Account accRec = new Account(Name='Midlands Central Locality',RecordTypeId=[Select Id from RecordType where SObjectType='Account' and Name like 'Internal%'].id);
  insert accRec;
    Services__c serv = new Services__c(Name='Midlands Central Advocacy', Locality__c=accRec.id,Service_Type__c='Advocacy', National_Service__c=false);//Name='testControllerService');
    insert serv;
  // Start the test.
  test.startTest();

    Service_Usage__c recSU = new Service_Usage__c(Service_Field__c= serv.id, Primary_Service_User__c=recCon.id,Service_Type__c='Advocacy');    
    insert recSU;

//    Service_Usage__c recSU2 = new Service_Usage__c(Service_Field__c= serv.id,Primary_Service_User__c=recCon.id,Service_Type__c='Advocacy');    
//    insert recSU2;    
    
//    Service_Usage__c recSU3 = new Service_Usage__c(Service_Field__c= serv.id,Primary_Service_User__c=recCon.id,Service_Type__c='Advocacy');    
//    insert recSU3;        
  // Stop the test.
  test.stopTest();
      
    Event eveRec = new Event(WhatId=recSU.id,Subject='Test Subject',DurationInMinutes=30,
            ActivityDateTime=System.now()-1,Format__c='Face to Face', In_Out__c='Outgoing',Location_Type_Event__c='Service User Home');
    insert eveRec;
    
    Event eveRec2 = new Event(WhatId=recSU.id,Subject='Test Subject',DurationInMinutes=30,
            ActivityDateTime=System.now()-1,Format__c='Face to Face', In_Out__c='Outgoing',Location_Type_Event__c='Office');
    insert eveRec2;    

    Task tskRec = new Task(WhatId=recSU.id,Subject='Test Subject',Format__c='Face to Face', 
            In_Out__c='Outgoing',Status='Completed',Completion_Date_Task__c=Date.Today(),Staff_Time_Minutes__c=30,
            Volunteer_Time_Minutes__c=30,ActivityDate=System.Today()-1);
    insert tskRec; 
        
    Event_Attendance_Details__c EADRec = new Event_Attendance_Details__c(Service_Usage__c=recSU.id, 
            Event_Date_and_Time__c=System.now()+1,Attendance_Status__c='Attended');  
    insert EADRec; 
    
//        Event_Attendance_Details__c EADRec2 = new Event_Attendance_Details__c(Service_Usage__c=recSU3.id, 
//            Event_Date_and_Time__c=System.now(),Attendance_Status__c='Attended');  
//    insert EADRec2;     
    
    Task tskRec2 = new Task(WhatId=recSU.id,Subject='Test Subject',Format__c='Face to Face', 
            In_Out__c='Outgoing',Status='Completed',Completion_Date_Task__c=Date.Today(),Staff_Time_Minutes__c=30,
            Volunteer_Time_Minutes__c=30,ActivityDate=System.Today()+2);
    insert tskRec2;
    
//    Task tskRec3 = new Task(WhatId=recSU2.id,Subject='Test Subject',Format__c='Face to Face', 
//            In_Out__c='Outgoing',Status='Completed',Completion_Date_Task__c=Date.Today(),Staff_Time_Minutes__c=30,
//            Volunteer_Time_Minutes__c=30,ActivityDate=System.Today());
//    insert tskRec3;      
    
    update eveRec;
    tskRec.WhatId=recSU.id;
    update tskRec;
    
    ServiceUsageDateOfLastActivity.getDateOfLastActivity(new Set<Id>{recSU.id});//,recSU2.id,recSU3.id removed

    //system.debug('########## SU Last Activity ###########'+[Select Date_of_last_Activity__c from Service_Usage__c where Id=:recSU.id ].Date_of_last_Activity__c);
    
  

  }      
}