src/objects/contact__c.object
<CustomObject>
    <label>contact</label>
    <nameField>
        <label>contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Demographic_Information__c.object
<CustomObject>
    <description>Demographic Information held against the People (Contact) record.</description>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Demographic Information</relationshipLabel>
        <relationshipName>Demographic_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Demographic Information</label>
    <nameField>
        <label>Person Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demographic Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UI_Participant__c.object
<CustomObject>
    <description>A User Involvement Participant with Consent</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This has to be look-up, not a Master-Detail so that anyone can own a Participant, regardless of the Contact Owner.</description>
        <inlineHelpText>The CRS Person record for this Participant. You may have limited access to data on the Person Profile</inlineHelpText>
        <label>Person Record</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Records</relationshipLabel>
        <relationshipName>User_Involvement_Participant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Participant</description>
        <inlineHelpText>The current status of Participant.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unconfirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>User Involvement Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UIDemographicInfoRLController.cls
public with sharing class UIDemographicInfoRLController {

    public boolean showAddButton {get;set;}
    public boolean showData {get;set;}

    public List<Demographic_Information__c> lisDgData = new List<Demographic_Information__c>();
    public List<Demographic_Information__c> dgData { get;set; }
    
    //used to get a hold of the Demographic_Information__c record selected for deletion
    public string SelectedId { get; set; }
 
 
    public UIDemographicInfoRLController (ApexPages.StandardController controller) {

        UI_Participant__c p = [select id, Status__c from UI_Participant__c where id = :System.currentPageReference().getParameters().get('Id')];                           
        lisDgData = [SELECT Id, Name, Person__c FROM Demographic_Information__c 
                    WHERE Person__c IN (SELECT Contact__c 
                                        FROM UI_Participant__c where Id = :p.id)];                     

		showAddButton = (p.Status__c=='Active' && lisDgData.size() == 0);
		showData=false;        

		/* Hide the data if the user is not Active */
        if (p.Status__c == 'Active') {
            dgData = lisDgData; 
            showData=true;
        }
    }
        
    public void create() {
        showAddButton = false;
    }
    
}