src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <description>Alzheimer&apos;s Trading Ltd</description>
        <inlineHelpText>Please choose Contact Type</inlineHelpText>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>Associate Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/External_Contacts__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Name_Formula__c</fullName>
        <formula>Related_Contact__r.FirstName &amp;&apos; &apos;&amp; Related_Contact__r.LastName</formula>
        <label>Contact Name Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <inlineHelpText>Contact Type=Public Contact then the contact name gets updated on the service record.</inlineHelpText>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>Public Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Contact</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>External_Service__c</fullName>
        <label>External Service</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Services__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Service</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Services__c</referenceTo>
        <relationshipLabel>External Contacts</relationshipLabel>
        <relationshipName>External_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Other, Professional / Stakeholder</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>External Contacts</relationshipLabel>
        <relationshipName>External_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>External Contacts</label>
    <nameField>
        <displayFormat>EC{00000}</displayFormat>
        <label>External Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact_External__c</fullName>
        <description>replace contact first name and last name</description>
        <label>Public contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SFDC_Contact_Connector__c.object
<CustomObject>
    <fields>
        <fullName>Related_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships (Related Contact)</relationshipLabel>
        <relationshipName>Related_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ExternalContactsTriggerHandler.cls
Public class ExternalContactsTriggerHandler{
    
    /******************************************************************************************
*  Alzheimer's Society
*  
*  Purpose : APEX Handler Class contains the execution logic of the External_Contacts__c Trigger.
*  Author  : Lakshmi Rajendram
*  Date    : 29-01-2015
*  Version : 0.1 Unit Test
*
*  Description:    Runs the ExternalContactTrigger logic.
*               
*  Modification History
*  Date            Who         Description 

*******************************************************************************************/
    
    private boolean m_isExecuting = false;
    private integer BatchSize = 0;
    
    public ExternalContactsTriggerHandler(boolean isExecuting, integer size){
        m_isExecuting = isExecuting;
        BatchSize = size;
    }
    
    
    
    public void OnAfterInsert(External_Contacts__c[] newContact, Map<ID, External_Contacts__c> ContactMap){
        System.debug('****** ExternalContactTriggerHandler.OnAfterInsert  ******');
        
        
        OnAfterInsertUpdateExContact(newContact);
    }   
    
    
    
    public void OnAfterUpdate(External_Contacts__c[] oldContact, External_Contacts__c[] updatedContact, Map<ID, External_Contacts__c> ContactMap){
        System.debug('****** ExternalContactTriggerHandler.OnAfterUpdate  ******');
        OnAfterInsertUpdateExContact(oldContact);
        
        
    }
    public void OnAfterInsertUpdateExContact(List<External_Contacts__c> exList){
        Map<ID, Services__c> parent = new Map<ID, Services__c> ();
        List <External_Contacts__c> lisContact = new List<External_Contacts__c>();
        set <id> listParent = new set<id>();
        Boolean isPublicContact=False;
        
        for(External_Contacts__c ec:exList){
            if(ec.Contact_Type__c.contains('Public Contact')){
                listParent.add(ec.External_Service__c);
            }
        }
        if(listParent.size()>0)
        {
            
            parent = new Map<Id, Services__c>([Select id,Primary_Contact_External__c ,(SELECT id,Related_Contact__r.name FROM External_Contacts__r)from Services__c where id in:listParent]);
            
            for(External_Contacts__c ecc:exList){
                Services__c myParentServ = parent.get(ecc.External_Service__c);
                
                myParentServ.Primary_Contact_External__c=ecc.Contact_Name_Formula__c;
                
            }
            update parent.values();
            
        }
        
    }
}