src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Date_of_diagnosis__c</fullName>
        <inlineHelpText>This is required if a diagnosis has been given. If full date of diagnosis is unknown, enter it to the nearest year or month (e.g. 01/01/1945 if diagnosis year is 1945; or 01/08/1945 if diagnosis date is estimated). Then tick ‘Approximate Date’ box</inlineHelpText>
        <label>Date of diagnosis</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Diagnosis_Details__c</fullName>
        <inlineHelpText>For additional details about dementia diagnosis. This is required if ‘Other’ is selected from the ‘Dementia Diagnosis’ list.</inlineHelpText>
        <label>Diagnosis Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Diagnosis__c</fullName>
        <inlineHelpText>Only to be used for CONFIRMED diagnosis of dementia.</inlineHelpText>
        <label>Dementia diagnosis</label>
        <picklist>
            <picklistValues>
                <fullName>Alzheimer’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Binswanger’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia with Lewy bodies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Down’s syndrome related dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fronto-Temporal dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HIV related dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huntington’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korsakoff’s syndrome</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixed dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parkinson’s disease related dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pick’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prion disease including CJD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vascular dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None - Awaiting Diagnosis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None - Other Mild Cognitive Impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (please list)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mild Cognitive Impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Diagnosis_made_by__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Diagnosis made by</description>
        <inlineHelpText>To record which professional made the diagnosis. Do NOT just type in name – A Professional already entered on the system must be found, selected and inserted by using the Look-Up function (magnifying glass icon).</inlineHelpText>
        <label>Diagnosis made by</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Professional / Stakeholder</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Diagnosis made by)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_language__c</fullName>
        <inlineHelpText>The language they prefer to use MUST be entered. If not in list, select ‘OTHER’ and include in ‘Specialist Communication Needs’ box.</inlineHelpText>
        <label>Preferred language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Afrikaans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algerian Spoken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amharic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assamese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awadhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijani, North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijani, South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarusan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bengali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhojpuri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgarian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burmese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cebuano</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chhattisgarhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Cantonese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Gan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Hakka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Jinyu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Mandarin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Min Bei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Min Nan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Wu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Xiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chittagonian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Czech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deccan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dutch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Egyptian Spoken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Key_Health_Issues__c</fullName>
        <label>Key Health Issues</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functional mental health issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visual impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hearing impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speech impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobility impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning difficulties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communication Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diabetic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Epileptic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobility Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Motor Skills Impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered Blind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered Disabled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wheelchair User</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Known_as__c</fullName>
        <label>Known as</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Means_of_first_contact__c</fullName>
        <label>Means of first contact</label>
        <picklist>
            <picklistValues>
                <fullName>Telephone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Face to face</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Other_Demographic_Details__c</fullName>
        <inlineHelpText>This MUST be completed if ‘OTHER’ has been selected in any of the demographic fields.</inlineHelpText>
        <label>Other Demographic Details</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PoA_Notes__c</fullName>
        <inlineHelpText>PoA Notes is to be used to specify the type of PoA and any other relevant PoA information.</inlineHelpText>
        <label>PoA Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Preferred_means_of_contact__c</fullName>
        <inlineHelpText>Can include any specific details about when/how to contact the person</inlineHelpText>
        <label>Preferred method/time of contact</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Service_user_aware_of_diagnosis__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service User aware of diagnosis</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Social_Service_Ref_No__c</fullName>
        <label>Social Service Ref. No.</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Specialist_Communication_Needs__c</fullName>
        <inlineHelpText>To record information to assist communication, such as whether the speak English; if they need an interpreter; if they use BSL; what may help effective communication, etc.</inlineHelpText>
        <label>Specialist Communication Needs</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <description>Used as default Record Type for helpline calls etc.</description>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact_History__c.object
<CustomObject>
    <fields>
        <fullName>Contact_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Audit Trail</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact History (Contact History)</relationshipLabel>
        <relationshipName>Contact_History1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Diagnosis__c</fullName>
        <label>Date of Diagnosis</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Diagnosis__c</fullName>
        <label>Key Health Issues</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Diagnosis_made_by__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Diagnosis made by</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact History</relationshipLabel>
        <relationshipName>Contact_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_User_aware_of_diagnosis__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service User aware of diagnosis</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Specialist_Communication_Needs__c</fullName>
        <label>Specialist Communication Needs</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <label>Contact History</label>
    <nameField>
        <label>Contact History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AnonymisePersonExtension.cls
/******************************************************************************************
 *  Alzheimer's
 *  
 *  Purpose : Anonymise a person. Delete Contact History.
 *  Author  : Fujitsu - Nupoor Pandey
 *  Date    : 2012-02-07
 *  Version : 0.1 Unit Tested
 *  Project : CRSProto
 *
 *  Description: Class to anonymise a contact. 
 *               
 *               
 *  Modification History
 *
 *  Date         Who    Description 
 *  yyyy-mm-dd - XX -   xxxxxxxxxxxxxxxxxxxxxxxxxxxx
 *  20130403    MT    Check that all service usages are not active.
 *                             
*******************************************************************************************/
public with sharing class Anonymise_PersonExtension {
    
    public Contact person {get; private set;}
    public boolean consent {get; private set;}
    private List<Contact_History__c> contactHistory; 
    public String diagnosis {get; private set;}
    public boolean isError {get; private set;}
    private boolean ActiveServiceUsage;
    private List<Service_Usage__c> lstServUsage;
    /**
    Constructor to get the Contact Id from the page and retrieve the following:
        :Contact
    */
    public AnonymisePersonExtension() {
        Id id = ApexPages.currentPage().getParameters().get('id');
        person = (id == null) ? new Contact() : 
            [Select c.Specialist_Communication_Needs__c, c.Social_Service_Ref_No__c, c.Service_user_aware_of_diagnosis__c, 
            c.Salutation, c.Preferred_means_of_contact__c, c.PoA_Notes__c, c.Other_Demographic_Details__c, c.OtherStreet, 
            c.OtherState, c.OtherPhone, c.OtherCountry, c.OtherCity, c.MobilePhone, c.Means_of_first_contact__c, c.Diagnosis__c, 
            c.MailingStreet, c.MailingState, c.MailingCountry, c.MailingCity, c.LastName, c.Known_as__c, c.Id, c.HomePhone, 
            c.First_language__c, c.FirstName, c.Email, c.Key_Health_Issues__c,  
            c.Diagnosis_made_by__c, c.Diagnosis_Details__c, 
            c.Date_of_diagnosis__c, c.Consent_Status__c, c.Brief_Outline_of_Personal_History__c, c.Approximate_date_of_diagnosis__c, 
            c.Advance_Directives__c, c.Additional_Health_Information__c, c.rrpu__Alert_Message__c, c.Phone From Contact c WHERE id = :id];
            
            contactHistory = new List<Contact_History__c>();
            System.debug('111111111111111111111111111111111 person.Consent_Status__c: '+person.Consent_Status__c);
            isError=false;
    }
    public PageReference AutoRunAnonymisePerson(){            
            //for page rendering
            if ((person==null || person.Consent_Status__c=='Awaiting Consent' || person.Consent_Status__c=='None' || 
                        person.Consent_Status__c=='' || person.Consent_Status__c==null)==false){
                        
                ApexPages.Message message = new ApexPages.message(ApexPages.severity.ERROR,'This person cannot be anonymised as the consent status is not \'Awaiting Consent\' or \'None\'');
                ApexPages.addMessage(message);
                isError = true;  
                return null;             
                }
           //check for ALL Service Usages with a referral outcome of either "service declined" or "service inappropriate" or "person ineligible for service"
           List<Service_Usage__c> lstServUsage = [Select Id, Name,Referral_Outcome__c from Service_Usage__c where Primary_Service_User__c=:person.id];
           for(Service_Usage__c rec: lstServUsage){
               System.debug('#############id:'+rec.id + ' ' + rec.name);
               System.debug('#############outcome:' + rec.Referral_Outcome__c);
               if ((rec.Referral_Outcome__c ==null || rec.Referral_Outcome__c =='' ||
                   rec.Referral_Outcome__c =='Not Eligible (Referred on)' ||
                   rec.Referral_Outcome__c =='Not Eligible (No further action)' || 
                   rec.Referral_Outcome__c =='Service Declined (Referred on)' || 
                   rec.Referral_Outcome__c =='Service Declined (No further action)' || 
                   rec.Referral_Outcome__c =='Not Interested')==false) { 
                   ActiveServiceUsage= true;
                   if (ActiveServiceUsage==true){
                          ApexPages.Message message = new ApexPages.message(ApexPages.severity.ERROR,'This person cannot be anonymised.  There are service usages that have a Referral Outcome that is not  \'Service Declined...\', \'Not Eligible...\', \'Not Interested...\'.');
                          ApexPages.addMessage(message);
                          isError = true;
                          return null;  
               }
            }
        }
    return null;  
    }
    
    public void emptyMethod() {}
    
    /**
        Method to delete the details of the contact record.
    */
    public PageReference AnonymisePerson() {
        Id thisUserId;
        Integer count;
        thisUserId = UserInfo.getUserId();

        //delete contact details
        if(person.Consent_Status__c!='Awaiting Consent' && person.Consent_Status__c!='None' && person.Consent_Status__c!=null){
            System.debug('222222222222222222222222222222222 person.Consent_Status__c: '+person.Consent_Status__c);
            return new PageReference('/'+person.Id);
        }
        // Create a savepoint because the data should not be committed to the database
        Savepoint sp = Database.setSavepoint();
        boolean hasDMLExceptionRaised=false;
        Exception exToPass;

        try{
            person.Specialist_Communication_Needs__c = '';
            person.Social_Service_Ref_No__c = '';
            person.Service_user_aware_of_diagnosis__c = false;
            person.Salutation = '';
            person.Preferred_means_of_contact__c = '';
            person.PoA_Notes__c = '';
            person.Other_Demographic_Details__c = '';
            person.OtherStreet = '';
            person.OtherState = '';
            person.OtherPhone = '';
            person.OtherCountry = '';
            person.OtherCity = '';
            person.OtherPostalCode='';
            person.MobilePhone = '';
            person.Means_of_first_contact__c = '';
            person.MailingStreet = '';
            person.MailingState = '';
            person.MailingCountry = '';
            person.MailingCity = '';
            person.MailingPostalCode='';
            person.LastName = '*****';
            person.Known_as__c = '';
            person.HomePhone = '';
            person.First_language__c = '';
            person.FirstName = '*****';
            person.Email = '';
            person.Key_Health_Issues__c = '';
            person.Diagnosis_made_by__c = null;
            diagnosis = person.Diagnosis__c;
            if (diagnosis!=null && diagnosis!='' && diagnosis.contains('Other')) 
                person.Diagnosis_Details__c = '*****';
            else 
                person.Diagnosis_Details__c = '';   
            person.Date_of_diagnosis__c = Date.today();
            person.Consent_Status__c = '';
            person.Brief_Outline_of_Personal_History__c = '';
            person.Approximate_date_of_diagnosis__c = false;
            person.Advance_Directives__c = '';
            person.Additional_Health_Information__c = '';
            person.Phone = '';
            if(person.DoNotCall) person.rrpu__Alert_Message__c = '******'; else person.rrpu__Alert_Message__c = '';
            
            update person;
            
            //remove the contact details from contct history as well
            contactHistory = [Select c.OwnerId, c.Specialist_Communication_Needs__c, c.Service_User_aware_of_diagnosis__c, c.Name, c.Mailing_Address__c, 
                                c.Lastname__c, c.Id, c.Firstname__c, c.Diagnosis_made_by__c, c.Diagnosis__c, c.Date_of_Diagnosis__c, 
                                c.Contact_History__c, c.Alert_Message__c From Contact_History__c c 
                                where Contact_History__c = :person.Id];
            //update owner of contact history records
            count = 0;
            List<Contact_History__c> chToUpdate = new List<Contact_History__c>();
            for(Contact_History__c ch : contactHistory ){
                if(ch.OwnerId!= thisUserId){
                     ch.OwnerId = thisUserId;
                     chToUpdate.add(ch);
                     count++;
                                          }   
            
            }
            if (count>0){
                system.debug('##########records to be updated ##########' + count);
                update chToUpdate;
                }
            delete contactHistory;
            
        }catch(Exception ex){exToPass=ex;hasDMLExceptionRaised=true;}
      // Revert the database to the original state on Exception
      if(hasDMLExceptionRaised)
      {
        Database.rollback(sp);      
        ApexPages.addMessages(exToPass);

        ApexPages.Message message = new ApexPages.message(ApexPages.severity.INFO, 'Contact The CRS Helpdesk.');
        ApexPages.addMessage(message);
        return null;  
      }  
      return new PageReference('/'+person.Id);
    }
    
    public PageReference cancel() {
        return new PageReference('/'+person.Id);
    }
    
    /**
      Test case coverage = 100%
      */
      public testMethod static void testController(){
            //Initialise
            Contact recCon = new Contact(Salutation='Mr',FirstName='Abc',LastName='TestLastName',Deceased__c=false,MailingPostalCode ='ABC123', Birthdate =Date.Today(),
            RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and Name Like 'Person with dementia'].id);
            insert recCon;        
            
            //Create instance of the class to test and initialise the list 
            ApexPages.currentPage().getParameters().put('id', recCon.id);  
            AnonymisePersonExtension ext= new AnonymisePersonExtension();
            ext.AutoRunAnonymisePerson();
            //ext.setSuo(outcomeList);
            
            //test case
            System.assertNotEquals(ext.AnonymisePerson(), null);
            System.assertNotEquals(ext.cancel(), null);
      }
}