src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Client_reference_number__c</fullName>
        <description>System generated unique reference number across all People.</description>
        <displayFormat>P{00000000}</displayFormat>
        <externalId>true</externalId>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Deceased__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>To set a person as deceased please use the Person Wizard.</inlineHelpText>
        <label>Deceased?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Usage__c.object
<CustomObject>
    <fields>
        <fullName>Client_reference_number__c</fullName>
        <formula>Primary_Service_User__r.Client_reference_number__c</formula>
        <label>Person ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Service_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service User</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 OR 2) AND ((3 AND 4) OR (5 AND 6) OR 7 OR 8)</booleanFilter>
            <errorMessage>For Day care &amp; support and Community support Services, Service User must be a living Person with Dementia. For other services Service User can also be a Carer of a Person with Dementia. Newsletter is available to all.</errorMessage>
            <filterItems>
                <field>Contact.Deceased_Date__c</field>
                <operation>greaterThan</operation>
                <valueField>$Source.Referral_Date__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.Deceased__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Type__c</field>
                <operation>equals</operation>
                <value>Community support service, Day care and support (establishment based), Registered home care and support</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person with Dementia</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Type__c</field>
                <operation>equals</operation>
                <value>Activity group, Dementia adviser, Dementia support, Dementia cafe, Information programme, Other (one to one), Peer support group, Singing for the Brain, Befriending, Advocacy</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Carer of Person with Dementia, Person with Dementia</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Type__c</field>
                <operation>equals</operation>
                <value>Newsletter</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outgoing Referral</value>
            </filterItems>
            <infoMessage>For Day care &amp; support and Community support Services, Service User must be a living Person with Dementia. For other services Service User can also be a Carer of a Person with Dementia. Newsletter is available to all.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Usage</relationshipLabel>
        <relationshipName>Service_Usage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <description>The type of Service to which Service Usage relates.
Used as a filter when selecting Service.
Used to set Record Type on saving a new Service Usage.</description>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (one to one)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peer support group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered home care and support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singing for the Brain</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Usage</label>
    <nameField>
        <label>Service Usage Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Usage</pluralLabel>
    <recordTypes>
        <fullName>Advocacy</fullName>
        <active>true</active>
        <description>Used for all Advocacy Referrals and Cases</description>
        <label>Advocacy</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Usage_Outcome__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_Identified__c</fullName>
        <label>Date Identified</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Outcome_Met__c</fullName>
        <label>Date Outcome Met</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outcome_No__c</fullName>
        <description>This is the outcome number auto generated by the system.</description>
        <inlineHelpText>Auto generated by the system, any value input here will be over written by the system. It is based on the number of Outcomes already created for related Service Usage.</inlineHelpText>
        <label>Outcome No.</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Outcome_Status__c</fullName>
        <label>Outcome Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ongoing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No longer required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Person_Identified_Outcome__c</fullName>
        <label>Person Identified Outcome</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service_Usage__c</fullName>
        <label>Related Service Usage</label>
        <referenceTo>Service_Usage__c</referenceTo>
        <relationshipLabel>Support Plan</relationshipLabel>
        <relationshipName>Service_Usage_Outcomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Service Usage Outcome</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Service Usage Outcome ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Usage Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>Locality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Locality in which this service is based (left blank for national services).</description>
        <label>Locality</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select an Alzheimer&apos;s Society Locality.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Organisation</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>contains</operation>
                <value>Locality</value>
            </filterItems>
            <infoMessage>Please select a Locality.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Services_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>National_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>National Service?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>service_type__c</fullName>
        <inlineHelpText>Service description will be automatically populated from the service type (or sub type if there is one)</inlineHelpText>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult education &amp; training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (emotional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (financial)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (general)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awareness raising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending / home support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counselling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day support / day care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafés</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exercise / Fitness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home facilities &amp; services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Dementia)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Financial &amp; Legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programmes &amp; provision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>Internal Service/Activity</description>
        <label>Internal Service</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ServiceUsageOutcomeList.cls
/******************************************************************************************
 *  Alzheimer's
 *  
 *  Purpose : Provide a screen with a list of all the Service Usage Outcomes related to a Service Usage.
 *  Author  : Fujitsu - Nupoor Pandey
 *  Date    : 2012-02-02
 *  Version : 0.1 Unit Tested
 *  Project : CRSProto
 *
 *  Description: Class with public method to retrive list of Service_Usage_Outcome__c for a Service_Usage__c. 
 *               
 *               
 *  Modification History
 *
 *  Date         Who    Description 
 *  08/09/2014 - Lakshmi Rajendram-   Included completed outcomes 
 *                             
*******************************************************************************************/
public with sharing class ServiceUsageOutcomeList {

    public Service_Usage__c su {get; set;}
    public List<Service_Usage_Outcome__c> suo;
     public List<Service_Usage_Outcome__c> suoo;
    public Contact person {get; set;}

    /**
    Constructor to get the Service Usage Id from the page and retrieve the following:
        :Service_Usage__c
        :Service_Usage_Outcome__c
    */
    public ServiceUsageOutcomeList(ApexPages.StandardController controller) {
        su = (Service_Usage__c)controller.getRecord();
        su = (su == null) ? new Service_Usage__c() : [Select s.Name, s.Id, s.Primary_Service_User__c From Service_Usage__c s WHERE id = :su.id];
        suo = (su == null) ? new List<Service_Usage_Outcome__c>() : [Select Name, s.Outcome_No__c, s.Service_Usage__c, s.Person_Identified_Outcome__c, 
                                                                    s.Outcome_Status__c, s.Date_Outcome_Met__c, s.Date_Identified__c, s.Action__c 
                                                                    From Service_Usage_Outcome__c s where s.Service_Usage__c = :su.Id 
                                                                    ORDER BY Outcome_No__c ASC ];
        suoo =(su == null)?new List<Service_Usage_Outcome__c>():     [Select Name, s.Outcome_No__c, s.Service_Usage__c, s.Person_Identified_Outcome__c, 
                                                                    s.Outcome_Status__c, s.Date_Outcome_Met__c, s.Date_Identified__c, s.Action__c 
                                                                    From Service_Usage_Outcome__c s where s.Service_Usage__c = :su.Id AND s.Outcome_Status__c='Ongoing'
                                                                    ORDER BY Outcome_No__c ASC ];  
                                                           
        if(su.Primary_Service_User__c!=null) person = [select id, Client_reference_number__c from Contact where id=:su.Primary_Service_User__c];
    }       

    public List<Service_Usage_Outcome__c> getSuo() {
        return suo;
    }
      public List<Service_Usage_Outcome__c> getSuoo() {
        return suoo;
    }
    
/**    
    public void setSuo(List<Service_Usage_Outcome__c> s) {
        suo = s;
    }
**/
/**    
    public PageReference cancel() {
        return new PageReference('/'+ApexPages.currentPage().getParameters().get('id'));
    }
**/    
    /**
    Do Not Delete: Code for mass upload of Service_Usage_Outcome__c  
    */
      /**public List<WrapperQueAns> lstQueAns = new List<WrapperQueAns>{};
      public List<WrapperQueAns> propLstQuesAns { get { return lstQueAns; } set { lstQueAns = value; } }
                                                  
      Public ServiceUsageOutcomeList(){
           WrapperQueAns wqa = new WrapperQueAns();
           //wqa.propAns = '';
           wqa.suo = new Service_Usage_Outcome__c ();
           lstQueAns.add(wqa);
      }

      public void DynamicRow(){
           for(Integer i=0;i<1;i++){
                WrapperQueAns wqa = new WrapperQueAns();
                //wqa.propAns    = '';
                wqa.suo = new Service_Usage_Outcome__c ();
                lstQueAns.add(wqa);
           }
      }
      public class WrapperQueAns{
           //public String propAns { get; set; }
           public Service_Usage_Outcome__c suo {get; set; } 
      }//End Class WrapperQueAns
      
      public void saveList(){
           List<Service_Usage_Outcome__c> suoList = new List<Service_Usage_Outcome__c>();
           //System.debug('here is the propLstQuesAns list:' + propLstQuesAns);
           //System.debug('here is the lstQueAns list:' + lstQueAns);
           for(WrapperQueAns wq:propLstQuesAns){
                System.debug('here is the wq.suo:' + wq.suo);
                suoList.add(wq.suo);
           }
           System.debug('here is the suoList list:' + suoList);
           upsert suoList;
      }**/
      
      /**
      Test case coverage = 100%
      */
      public testMethod static void testController(){
            //Initialise
            Contact recCon = new Contact(Salutation='Mr',FirstName='Abc',LastName='TestLastName',Deceased__c=false,MailingPostalCode ='ABC123', Birthdate =Date.Today(),
            RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and Name Like 'Person with dementia'].id);
            insert recCon;        
            Account accRec = new Account(Name='Midlands Central Locality',RecordTypeId=[Select Id from RecordType where SObjectType='Account' and Name like 'Internal%'].id);
            insert accRec;
            Services__c serv = new Services__c(Name='Midlands Central Advocacy', Locality__c=accRec.id,Service_Type__c='Advocacy', National_Service__c=false);//Name='testControllerService');
            insert serv;    
            Service_Usage__c recSU = new Service_Usage__c(Service_Field__c= serv.id, Primary_Service_User__c=recCon.id,Service_Type__c='Advocacy');    
            insert recSU;
            Service_Usage_Outcome__c recSUO = new Service_Usage_Outcome__c(Person_Identified_Outcome__c='some text1', Service_Usage__c=recSU.id, Date_Identified__c=Date.Today());    
            //List<Service_Usage_Outcome__c> outcomeList = new List<Service_Usage_Outcome__c>();
            //outcomeList.add(recSUO);
            //insert outcomeList;
            insert recSUO;
            recSUO.Person_Identified_Outcome__c='some updated text1';
            recSUO.Action__c = 'new text';
            recSUO.Date_Outcome_Met__c = Date.Today();
            recSUO.Date_Identified__c = Date.Today().addDays(-7);
            update recSUO;
            
            //Create instance of the class to test and initialise the list
            //CreateRelationshipController cnt = new CreateRelationshipController();
            //ServiceUsageOutcomeList SUOList= new ServiceUsageOutcomeList(recSU);
            //SUOList.setSuo(outcomeList);
            //ApexPages.StandardController stdCon = new ApexPages.StandardController(SUOList);
            //ServiceUsageOutcomeList cnt = new QuickEntryTaskPersonController(stdCon);
            PageReference pageRef = Page.ServiceUsageOutcomeListView;
            test.setCurrentPage(pageRef);
            // Now create the standard controller for the SU
            ApexPages.StandardController stdCon = new ApexPages.StandardController(recSU);
            ServiceUsageOutcomeList  suol = new ServiceUsageOutcomeList(stdCon );
            suol.getSUo();

            /**ApexPages.currentPage().getParameters().put('id', recSU.id);  
            ServiceUsageOutcomeList SUOList= new ServiceUsageOutcomeList(recSU);
            SUOList.setSuo(outcomeList);
            
            //test case
            System.assertNotEquals(SUOList.getSuo(), null);
            System.assertNotEquals(SUOList.cancel(), null);**/
      }
}