src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Deceased_Date__c</fullName>
        <label>Deceased Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deceased__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>To set a person as deceased please use the Person Wizard.</inlineHelpText>
        <label>Deceased?</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Carer</fullName>
        <active>true</active>
        <description>CRS Use only</description>
        <label>Carer of Person with Dementia</label>
    </recordTypes>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <description>Used as default Record Type for helpline calls etc.</description>
        <label>Other</label>
    </recordTypes>
    <recordTypes>
        <fullName>Peer</fullName>
        <active>true</active>
        <description>Member of the House of Lords</description>
        <label>Peer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Person_with_dementia</fullName>
        <active>true</active>
        <description>CRS Use only</description>
        <label>Person with Dementia</label>
    </recordTypes>
    <recordTypes>
        <fullName>Volunteer</fullName>
        <active>true</active>
        <description>Volunteers for Group Events</description>
        <label>Volunteer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Usage__c.object
<CustomObject>
    <fields>
        <fullName>Closure_Date__c</fullName>
        <inlineHelpText>Set only when case is closed. Must be set if a ‘Closure Reason’ is set</inlineHelpText>
        <label>Closure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Closure_Reason__c</fullName>
        <inlineHelpText>Set only when case is closed. Must be set if ‘Closure Date’ is set</inlineHelpText>
        <label>Closure Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Case complete - outcomes met</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Reasons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person Declined Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person no longer eligible for service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service no longer required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service user moved into full time care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service user moved out of area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service user or person cared for deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Suspension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred to another service</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_Service_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service User</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 OR 2) AND ((3 AND 4) OR (5 AND 6) OR 7 OR 8)</booleanFilter>
            <errorMessage>For Day care &amp; support and Community support Services, Service User must be a living Person with Dementia. For other services Service User can also be a Carer of a Person with Dementia. Newsletter is available to all.</errorMessage>
            <filterItems>
                <field>Contact.Deceased_Date__c</field>
                <operation>greaterThan</operation>
                <valueField>$Source.Referral_Date__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.Deceased__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Type__c</field>
                <operation>equals</operation>
                <value>Community support service, Day care and support (establishment based), Registered home care and support</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person with Dementia</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Type__c</field>
                <operation>equals</operation>
                <value>Activity group, Dementia adviser, Dementia support, Dementia cafe, Information programme, Other (one to one), Peer support group, Singing for the Brain, Befriending, Advocacy</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Carer of Person with Dementia, Person with Dementia</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Type__c</field>
                <operation>equals</operation>
                <value>Newsletter</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outgoing Referral</value>
            </filterItems>
            <infoMessage>For Day care &amp; support and Community support Services, Service User must be a living Person with Dementia. For other services Service User can also be a Carer of a Person with Dementia. Newsletter is available to all.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Usage</relationshipLabel>
        <relationshipName>Service_Usage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Field__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the Service/Activity.
Filtered by Service Type and user&apos;s Locality for internal Service Usage records.
No filter required for &apos;Outgoing Referrals&apos; as these are only ever created in the background (via Referrals screen).</description>
        <label>Service</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 5 AND 6) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>Services__c.service_type__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Type__c</valueField>
            </filterItems>
            <filterItems>
                <field>Services__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Service</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outgoing Referral</value>
            </filterItems>
            <filterItems>
                <field>Services__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Service</value>
            </filterItems>
            <filterItems>
                <field>Services__c.Locality__r.Name</field>
                <operation>equals</operation>
                <valueField>$User.Locality__c</valueField>
            </filterItems>
            <filterItems>
                <field>Services__c.service_status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Services__c</referenceTo>
        <relationshipLabel>Service Usage</relationshipLabel>
        <relationshipName>Service_Usage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <description>The type of Service to which Service Usage relates.
Used as a filter when selecting Service.
Used to set Record Type on saving a new Service Usage.</description>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (one to one)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peer support group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered home care and support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singing for the Brain</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_User_Record_Type__c</fullName>
        <formula>Primary_Service_User__r.Record_Type_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service User Record Type</label>
        <type>Text</type>
    </fields>
    <label>Service Usage</label>
    <nameField>
        <label>Service Usage Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Usage</pluralLabel>
    <recordTypes>
        <fullName>Advocacy</fullName>
        <active>true</active>
        <description>Used for all Advocacy Referrals and Cases</description>
        <label>Advocacy</label>
    </recordTypes>
    <recordTypes>
        <fullName>Newsletter</fullName>
        <active>true</active>
        <description>Used to put individual on Newsletter distribution list (for a specific Newsletter)</description>
        <label>Newsletter</label>
    </recordTypes>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <description>Used to track referrals and service provision for any other (non standard) Society run services.</description>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>service_closedate__c</fullName>
        <inlineHelpText>If the service has closed you also need to update the status to &apos;Closed&apos; to prevent it displaying on the website.</inlineHelpText>
        <label>Close date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>service_type__c</fullName>
        <inlineHelpText>Service description will be automatically populated from the service type (or sub type if there is one)</inlineHelpText>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult education &amp; training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (emotional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (financial)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (general)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awareness raising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending / home support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counselling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day support / day care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafés</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exercise / Fitness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home facilities &amp; services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Dementia)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Financial &amp; Legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programmes &amp; provision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (one to one)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peer support group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered home care and support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singing for the Brain</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>Internal Service/Activity</description>
        <label>Internal Service</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ServiceChangeUpdateServiceUsage.cls
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : Batch APEX Class to re-align Service Usage records after a service record is changed.
 *  Author  : Mike Tinson
 *  Date    : 25-06-2014
 *  Version : 0.1 Unit Test
 *
 *  Description:    Batch APEX Class to re-align Service Usage records after a service record is changed
 *                  
 *
 *                  Called via the Execute Anonymous window. 
 *                  ServiceChangeUpdateServiceUsage suBatch = new ServiceChangeUpdateServiceUsage ();
 *                  suBatch.ServiceIdList = <<List of Ids for internal services to be updated>>
 *                  suBatch.BatchDescription = 'Test of Service Usage ServiceChangeUpdateServiceUsage';
 *                  suBatch.email=UserInfo.getUserEmail();
 *                  //Invoke the Batch class.
 *                  ID batchprocessid = Database.executeBatch(suBatch, 20);
 *                  
 *  Modification History
 *  Date            Who         Description 
 *  9-07-2014        MT         Do not attempt to update professionals who have been referred to a service (they should not!)
 *  MT 1/10/2014 Do not close service usage if closure date on service in future                           
*******************************************************************************************/

global class ServiceChangeUpdateServiceUsage implements Database.Batchable<sObject>{

Public List<Id> ServiceIdList {get;set;}
Public String email{get;set;}
Public String BatchDescription{get;set;}
Public Map<String, Id> SURecordtypeMap;

global Database.querylocator start(Database.BatchableContext BC){
    String  qryCommand;
    qryCommand = 'SELECT id, name, service_type__c, closure_date__c, closure_reason__c, Primary_Service_User__r.LastName, Primary_Service_User__r.FirstName, Service_Field__r.Name,  primary_service_user__r.Deceased__c ,service_field__c, service_field__r.service_type__c,service_field__r.service_closedate__c, recordtypeid from service_usage__c where service_field__c';
    qryCommand = qryCommand + ' IN :ServiceIdList';
    qryCommand = qryCommand + '  and closure_date__c =null and ((primary_service_user__r.Deceased__c=true and primary_service_user__r.Deceased_Date__c!=null) or (primary_service_user__r.Deceased__c=false))';
    qryCommand = qryCommand + '  and Service_User_Record_Type__c IN (\'Carer\',\'Person_with_dementia\')';
    System.debug('################query##############' + qryCommand );
    return Database.getQueryLocator(qryCommand );}

global void execute(Database.BatchableContext BC, List<sObject> scope){
    Boolean bUpdateRecord;
    String service_type;
    Id recordtypeId;
    String TestSUName;
    //get current date and time
    Datetime myDT = Datetime.now();
    //build map of recordtypes to be used later
    GetRecordtypes();
    List<Service_Usage__c> sus = new List<Service_Usage__c>();

       for(sObject s : scope){
            Service_Usage__c a = (Service_Usage__c)s;
            //flag to see if record needs updating
            bUpdateRecord = false;
            //if service is closed close service usage
            if(a.service_field__r.service_closedate__c != null && a.Closure_reason__c==null && a.service_field__r.service_closedate__c<=myDT){
                a.Closure_date__c = a.service_field__r.service_closedate__c;
                a.Closure_reason__c = 'Service closed';
                bUpdateRecord = true;
                }
            //Service type changes - recalculate what the service type should be from the service type on the service.
                service_type = CheckServiceType(a.service_type__c,a.service_field__r.service_type__c);  
                if (service_type !=a.service_type__c){
                    a.service_type__c=service_type;
                    bUpdateRecord = true;
                }
            //check that the record type is correct.  
                recordtypeId = CheckRecordType(a.recordtypeid, a.service_field__r.service_type__c);
                if (recordtypeId!=a.recordtypeid){
                    a.recordtypeid = recordtypeid;
                    bUpdateRecord = true;
                }
            //check if name of service has changed
                TestSUName = a.Primary_Service_User__r.LastName + ', ' + a.Primary_Service_User__r.FirstName + ' (' +  a.Service_Field__r.Name ;    
                TestSUName = TestSUName.Left(79) + ')';
                if (TestSUName != a.Name){
                    bUpdateRecord = true;
                    //workflow rule will update name of record.
                }
            //if record has been updated, then add to list    
                if (bUpdateRecord == true){
                    sus.add(a);
                }
        }
    update sus;
    
}
global void finish(Database.BatchableContext BC){
// First, reserve email capacity for the current Apex transaction to ensure
// that we won't exceed our daily email limits when sending email after
// the current transaction is committed.
Messaging.reserveSingleEmailCapacity(1);

Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

mail.setToAddresses(new String[] {email});
mail.setReplyTo(email);
mail.setSenderDisplayName('Batch Processing');
mail.setSubject('Batch Process Completed');
String strMessage = 'Batch Process has completed';
strMessage = strMessage  + '\n Service IDs: ' + ServiceIdList;
strMessage = strMessage  + '\n BatchDescription: ' + BatchDescription;
strMessage = strMessage  + '\n Batch Process Completed';
mail.setPlainTextBody( strMessage );

Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
}
global Id CheckRecordType(Id psu_recortypeid, String pservice_service_type){
    //from the service type of the dementia connnect service work out what the service type on the service usage should be.
    Id recordtypeId;
    if (pservice_service_type =='Activity group'){
        recordtypeId = SURecordtypeMap.get('Social Activity Group');
        return recordtypeId;
    }
    if (pservice_service_type =='Advocacy'){
        recordtypeId = SURecordtypeMap.get('Advocacy');
        return recordtypeId;
    }
    if (pservice_service_type =='Befriending'){
        recordtypeId = SURecordtypeMap.get('Volunteer Befriending');
        return recordtypeId;
    }
    if (pservice_service_type =='Community support service'){
        recordtypeId = SURecordtypeMap.get('Social Inclusion');
        return recordtypeId;
    }
    if (pservice_service_type =='Day care and support (establishment based)'){
        recordtypeId = SURecordtypeMap.get('Day Support (Premises Based)');
        return recordtypeId;
    }
    if (pservice_service_type =='Dementia adviser'){
        recordtypeId = SURecordtypeMap.get('Dementia Adviser');
        return recordtypeId;
    }
    if (pservice_service_type =='Dementia cafe'){
        recordtypeId = SURecordtypeMap.get('Dementia Cafe');
        return recordtypeId;
    }
    if (pservice_service_type =='Dementia support'){
        recordtypeId = SURecordtypeMap.get('Dementia Support');
        return recordtypeId;
    }
    if (pservice_service_type =='Information programme'){
        recordtypeId = SURecordtypeMap.get('Information Programme');
        return recordtypeId;
    }
    if (pservice_service_type =='Newsletter'){
        recordtypeId = SURecordtypeMap.get('Newsletter');
        return recordtypeId;
    }
    if (pservice_service_type =='Other (one to one)'){
        recordtypeId = SURecordtypeMap.get('Other');
        return recordtypeId;
    }
    if (pservice_service_type =='Peer support group'){
        recordtypeId = SURecordtypeMap.get('Peer Support Group');
        return recordtypeId;
    }
    if (pservice_service_type =='Registered home care and support'){
        recordtypeId = SURecordtypeMap.get('Home Support (Registered)');
        return recordtypeId;
    }
    if (pservice_service_type =='Singing for the Brain'){
        recordtypeId = SURecordtypeMap.get('Singing for the Brain');
        return recordtypeId;
    }
    return psu_recortypeid;
}
global String CheckServiceType(String psu_service_type, String pservice_service_type){
    //make sure that the service type on the service usage matches the corresponding service type on the service.  
    //at the moment there is a one to one equivalence, but that may not always be the case.
    System.debug('############# Service Usage : ' + psu_service_type);
    System.debug('############# Service       : ' + pservice_service_type);
    
    if (pservice_service_type =='Activity group'){
        return 'Activity group';
    }
    if (pservice_service_type =='Advocacy'){
        return 'Advocacy';
    }
    if (pservice_service_type =='Befriending'){
        return 'Befriending';
    }
    if (pservice_service_type =='Community support service'){
        return 'Community support service';
    }
    if (pservice_service_type =='Day care and support (establishment based)'){
        return 'Day care and support (establishment based)';
    }
    if (pservice_service_type =='Dementia adviser'){
        return 'Dementia adviser';
    }
    if (pservice_service_type =='Dementia cafe'){
        return 'Dementia cafe';
    }
    if (pservice_service_type =='Dementia support'){
        return 'Dementia support';
    }
    if (pservice_service_type =='Information programme'){
        return 'Information programme';
    }
    if (pservice_service_type =='Newsletter'){
        return 'Newsletter';
    }
    if (pservice_service_type =='Other (one to one)'){
        return 'Other (one to one)';
    }
    if (pservice_service_type =='Peer support group'){
        return 'Peer support group';
    }
    if (pservice_service_type =='Registered home care and support'){
        return 'Registered home care and support';
    }
    if (pservice_service_type =='Singing for the Brain'){
        return 'Singing for the Brain';
    }
    return psu_service_type;
    }
Public boolean GetRecordtypes(){
    SURecordtypeMap= new Map<String, Id>();
    List <Recordtype> RTList= new List<Recordtype>([SELECT Name, Id from Recordtype where Sobjecttype='Service_usage__c' and Name!='Outgoing Referral']);
    For (Recordtype rec: RTList){
        SURecordtypeMap.put(rec.name, rec.id);
    }
    if  (SURecordtypeMap.size() > 0) {
        return true;}
    else {
        return false;}
    }
}