src/objects/contact__c.object
<CustomObject>
    <label>contact</label>
    <nameField>
        <label>contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Usage__c.object
<CustomObject>
    <label>Service Usage</label>
    <nameField>
        <label>Service Usage Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Usage</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/UI_Participant__c.object
<CustomObject>
    <description>A User Involvement Participant with Consent</description>
    <fields>
        <fullName>Activity_Types__c</fullName>
        <inlineHelpText>Types of Activity for which the Participant has given consent to be Involved</inlineHelpText>
        <label>Activity Types</label>
        <picklist>
            <picklistValues>
                <fullName>Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awareness raising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundraising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Governance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Areas_Of_Expertise__c</fullName>
        <inlineHelpText>Types of Activity where this Participant can provide particularly relevant skills or experience</inlineHelpText>
        <label>Areas Of Expertise</label>
        <picklist>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care homes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public speaking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This has to be look-up, not a Master-Detail so that anyone can own a Participant, regardless of the Contact Owner.</description>
        <inlineHelpText>The CRS Person record for this Participant. You may have limited access to data on the Person Profile</inlineHelpText>
        <label>Person Record</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Records</relationshipLabel>
        <relationshipName>User_Involvement_Participant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Methods_of_Involvement__c</fullName>
        <inlineHelpText>Methods of Involvement for which the Participant has given Involvement Consent</inlineHelpText>
        <label>Methods of Involvement</label>
        <picklist>
            <picklistValues>
                <fullName>Questionnaire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Discussion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Speaking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Steering Group Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Focus Group</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Requires_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the Person is an active service user at the point they are set to Active, and the current user is not a CRS user with access to the Person record then 
approval will be requested from the Service Usage primary contact</description>
        <inlineHelpText>If this Person is an active service user, and you do not already have access to their personal details, then approval will be requested from their current Primary Service Usage Assigned Worker.</inlineHelpText>
        <label>Requires Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Participant</description>
        <inlineHelpText>The current status of Participant.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unconfirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>User Involvement Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UIParticipantControllerExtension.cls
public with sharing class UIParticipantControllerExtension extends BaseControllerExtension {
    
/*******************************************************************************************************************************************
@author             gary.grant@conseq.co.uk
@date               Jan 2014
@description        Controller Extension. 
  
                        A combined controller to handle creating and editing UI Participant record
  
********************************************************************************************************************************************/

 private UI_Participant__c participant;
  
 public String[] activity_types_selection {get;set;}  
 public String[] areas_of_expertise_selection{get;set;}  
 public String[] methods_of_involvement_selection {get;set;}
     
 public List<SelectOption> getActivity_Types_Options() {    
          return getOptionList(UI_Participant__c.Activity_Types__c.getDescribe());
 }  
  
 public List<SelectOption> getAreas_Of_Expertise_Options() {            
           return getOptionList(UI_Participant__c.Areas_of_Expertise__c.getDescribe());            
 }
 
  public List<SelectOption> getMethods_of_Involvement_Options() {    
         return getOptionList(UI_Participant__c.Methods_of_Involvement__c.getDescribe());    
 } 
 
 /* Generic method to get the picklist values */
 private List<SelectOption> getOptionList(Schema.DescribeFieldResult describeResult ) {    
     
          List<SelectOption> options = new List<SelectOption>();                
          
          // Get the picklist values
          List<schema.picklistentry> values = describeResult.getPickListValues();
          for (Schema.PicklistEntry entry : values) {
               options.add(new SelectOption(entry.getLabel(), entry.getValue()));
          }
          return options;  
 }  
  
 /* See the save method for how these values are set */ 
 public boolean saveResult {get;set;}
 public boolean activeRequiresApproval{
 	get {    
         return ( participant.Requires_Approval__c==true &&         
       	   		  !CustomUtils.hasUserAccess(participant.Contact__c, UserInfo.getUserId(), 'Read')); 	       			       		 	
 	}
 	set;
 }  
  
 public UIParticipantControllerExtension(ApexPages.StandardController controller) 
 {
     
        // Call the constructor of BaseControllerExtension
         super(controller);
     
         // ctl is the StandardController set in BaseControllerExtension
         participant=(UI_Participant__c)ctl.getRecord();

        // Populate the Muli-value checkbox arrays from the associated picklist values in the object data
         activity_types_selection = participant.Activity_Types__c==null ? new List<String>() : participant.Activity_Types__c.split(';');
         areas_of_expertise_selection = participant.Areas_of_Expertise__c==null ? new List<String>() : participant.Areas_Of_Expertise__c.split(';'); 
		 methods_of_involvement_selection = participant.Methods_of_Involvement__c==null ? new List<String>() : participant.Methods_Of_Involvement__c.split(';');
           
         if (participant.id==null) {
            participant.Status__c='Unconfirmed';             
         }
         
 }
 
 /* Get an Active Service Usage record for the current Participant, if on exists 
    Fetched using a without sharing sub class 
 */ 
 public Service_Usage__c su { 
 	
 	get {	 	
	 	if (su != null) { return su; }	 
	 	return UIUtils.getLatestServiceUsage(participant.Contact__c);
 	}
 	set;        
 }
 
 public boolean saveRecord()
 {     
     
  ctl.getRecord().put('Activity_Types__c',   String.join(activity_types_selection,';'));
  ctl.getRecord().put('Methods_of_Involvement__c',   String.join(methods_of_involvement_selection,';'));
  ctl.getRecord().put('Areas_of_Expertise__c',   String.join(areas_of_expertise_selection,';'));
     
   
  if   (ctl.save()==null) {
       
       /* The trigger will have set the RequiresApproval value on the record */  
	   participant=(UI_Participant__c)ctl.getRecord();
	   
	   saveResult=false;	   		
       return false;		       
  }    
    
  participant=(UI_Participant__c)ctl.getRecord();      
  saveResult=true;
    
  /* Update the time stamp to avoid erroneous contention errors */
  oSystemModStamp = (DateTime)ctl.getRecord().get('SystemModStamp');
  
  return true;

 }
 
 public pageReference clicked()
 {          
  	return null;
 }
 
 
 public pageReference save()
 {          
 	saveRecord();
  	return null;
 }
 
 /* Request Approval for setting the participant to active. 
    This is required if the user does not have sufficient access
    to set Active Status, which is the case for non-CRS users
    where the Person is an active service user
  */
 public pageReference saveAndRequestApproval()
 {
 	ctl.getRecord().put('Status__c','Pending Approval');
 	ctl.getRecord().put('OwnerId', UserInfo.getUserId());
 	if( saveRecord() ) {
 		
 			// create the new approval request to submit
            Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
            req.setComments('Submitted for approval. Please approve this Participant for Active status.');
            req.setObjectId(participant.id);
            Approval.ProcessResult result = Approval.process(req);	 		
 	} 
 	
 	return new PageReference('/' + participant.id);
 	
 }
  
 public pageReference saveAndClose()
 {          
  
  if (saveRecord()) { 
  	return new PageReference('/' + participant.id);
  } else {
  	return null;
  }

 } 
  
}