src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <description>Used as default Record Type for helpline calls etc.</description>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/UI_Activity__c.object
<CustomObject>
    <description>A User Involvement Activity. There may be Participation from one or more UI Participants</description>
    <fields>
        <fullName>UI_Programme__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The programme this activity forms a part of</description>
        <inlineHelpText>The Project/Programme this Activity is associated with.</inlineHelpText>
        <label>User Involvement Programme</label>
        <referenceTo>UI_Programme__c</referenceTo>
        <relationshipLabel>Involvement Activities</relationshipLabel>
        <relationshipName>Society_Activities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>User Involvement Activity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Involvement Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/UI_Participant__c.object
<CustomObject>
    <description>A User Involvement Participant with Consent</description>
    <label>User Involvement Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/UI_Programme__c.object
<CustomObject>
    <label>User Involvement Project/Programme</label>
    <nameField>
        <label>Project/Programme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Involvement Projects/Programmes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UIRestUtils_Test.cls
/**

 */
@isTest
private class UIRestUtils_Test {

	/* Test the methods that generate URL strings for the action buttons on the Page layouts
   		These URLS redirect to create pages for other objects */ 
	@isTest(SeeAllData=true)    
	static void testWebServiceGetUrls() {
                   
        Contact contact = UiUtils_Test.getTestContact();           
        UI_Programme__c programme = UIUtils_Test.getTestProgramme();
        UI_Activity__c activity = UIUtils_Test.getTestActivity(programme);
        
        String s = UIRestUtils.getParticipantUrl(contact.id);
        
        UI_Participant__c participant = UiUtils_Test.getTestParticipant(contact,true);                
    	s = UIRestUtils.getParticipantParticipationUrl(participant.id);     
    	s = UIRestUtils.getActivityParticpationUrl(activity.id);
    	    	
	}	
	
}