src/objects/contact__c.object
<CustomObject>
    <label>contact</label>
    <nameField>
        <label>contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event_Attendance_Details__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Event_Attendee_Timings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventAttendeeId__c</fullName>
        <label>EventAttendeeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventId__c</fullName>
        <label>EventId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventNumber__c</fullName>
        <label>EventNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Usage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Usage</label>
        <referenceTo>Service_Usage__c</referenceTo>
        <relationshipLabel>Attendance Details</relationshipLabel>
        <relationshipName>Event_Attendance_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Attendance Details</label>
    <nameField>
        <displayFormat>EA-{0000000000}</displayFormat>
        <label>EventAttendeeTiming Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendance Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Usage__c.object
<CustomObject>
    <label>Service Usage</label>
    <nameField>
        <label>Service Usage Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Usage</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MikeTestClass.cls
public class MikeTestClass {
// test class
public MikeTestClass(){
Set<String> s1 = new Set<String>{'a', 'b + c'};
Set<String> setEventNumbers = new Set<String>{'E-0000124606', 'E-0000124570'};

String sqlStr = 'Select Service_Usage__c,EventAttendeeId__c, Contact__c,EventNumber__c,EventId__c from Event_Attendance_Details__c where EventNumber__c IN :setEventNumbers ';
system.debug('#############sqlStr##############'+sqlStr);
List<Event_Attendance_Details__c> mtest = Database.query(sqlStr);
system.debug('#############sqlStr##############'+mtest.size());
}
//    
// TEST CASE    
//    
private static testMethod void testMikeTestClass() 
{
// Create the standard controller for the service
//   Contact c1 = new Contact(FirstName='one', LastName='related');    
//    insert c1; 
    
//    Services__c service = new Services__c(Name='Test service');
//    insert service;      
}
}