src/objects/Contract_Cost__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Service_Contract__c</referenceTo>
        <relationshipLabel>Costs</relationshipLabel>
        <relationshipName>Contract_Costs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost (inc FCR)</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FCR__c</fullName>
        <label>Actual FCR</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pays_VAT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pays VAT?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Definition__c</fullName>
        <label>Service Definition</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awareness raising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information provision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online forum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (one to one)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peer support group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered home care and support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singing for the Brain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telephone helpline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>The financial year for which the cost / income is being record</description>
        <inlineHelpText>The financial year for which the cost / income is being record</inlineHelpText>
        <label>Financial Year</label>
        <picklist>
            <picklistValues>
                <fullName>2008/09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009/10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010/11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011/12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012/13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013/14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014/15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015/16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016/17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017/18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018/19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019/20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020/21</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract Cost</label>
    <nameField>
        <displayFormat>{YYYY}-{000}</displayFormat>
        <label>Contract Cost Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Name__c</fullName>
        <label>Contract Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Service Contract</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ServiceContractWizard.cls
public class ServiceContractWizard {
    public Service_Contract__c contract;
    public List<Contract_Cost__c> costs;
    
    // The number of contract cost lines to show on the 2nd step of the wizard
    private final Integer NUM_COST_LINES = 25;
    
    //
    // Constructor
    //
    public ServiceContractWizard(ApexPages.StandardController controller) {
        contract = (Service_Contract__c)controller.getRecord();

        // Initialise the costs array
        costs = new List<Contract_Cost__c>();
        
        costs = [select Cost__c, Year__c, Service_Definition__c, FCR__c, Pays_VAT__c
                 from Contract_Cost__c where Contract__c = :contract.Id
                 order by Year__c, Service_Definition__c];
        
        // Add as many cost lines as specified in variable NUM_COST_LINES
        for (Integer i=costs.size(); i < NUM_COST_LINES; i++)
            costs.add( new Contract_Cost__c() );
    }
    
    //
    // Properties
    //
    public Service_Contract__c getContract() {
        if (contract == null)
            contract = new Service_Contract__c();
        return contract;
    }
    
    public List<Contract_Cost__c> getCosts() {
        return costs;
    }
    
    public void setCosts(List<Contract_Cost__c> c) {
        costs = c;
    }
    
    // Shows default of £0.00 in 'Suggested FCR' field
    public string getDefaultFCR() {
        return '0.00';
    }
    
    // Mandatory setter for 'Suggested FCR' field. Doesn't need to do anything
    public void setDefaultFCR(string fcr) {
        // Do nothing
    }
    
    // 
    // Navigation methods
    //
    // Go to first page of wizard
    public PageReference back() {
        return Page.ServiceContract1;
    }
    
    // Go to second page of wizard
    public PageReference next() {
        return Page.ServiceContract2;
    }
    
    // Return the user to the Service Contract tab
    public PageReference cancel() {
        PageReference contPage = new PageReference('/a0A/o');
        contPage.setRedirect(true);
        return contPage;
    }
    
    // Return to service contract page
    public PageReference cancelCosts() {
        PageReference contPage = new PageReference('/' + contract.Id);
        contPage.setRedirect(true);
        return contPage;
    }
    
    //
    // Save record methods
    //
    public PageReference save() {
        try {
            insert contract;
        }
        catch (DMLException de) {
            System.debug('ERROR: inserting Service Contract. Name: ' + contract.Contract_Name__c);
        }
        
        // Save contract cost records and navigate to service contract record
        return saveCosts();
    }
    
    public PageReference saveCosts() {
        Integer i = 0;
        
        // Remove any contract cost lines without a 'financial year' -- they are blank line
        // Loop backwards because removing forwards causes records to be missed
        for (i = costs.size()-1; i > 0; i--)
            if ((costs[i].Year__c == null) && (costs[i].Service_Definition__c == null))
                costs.remove(i);
        
        try {
            // Link each cost line to the service contract 
            for (i = 0; i < costs.size(); i++)
                if (costs[i].Id == null)
                    costs[i].Contract__c = contract.Id;
        
            // Insert cost lines (as long as list isn't empty)
            if (!costs.isEmpty())
                upsert costs;
        }
        catch (Exception e) {
              System.debug('INSERT CONTRACT COSTS:');
              for (Contract_Cost__c c : costs)
                System.debug('-- Year:' + c.Year__c + '; Contract:' + c.Contract__c); 
        }
        
        // Return to new service contract page
        PageReference contPage = new PageReference('/' + contract.Id);
        contPage.setRedirect(true);
        return contPage;
    }
    
    //
    // TEST ServiceContractWizard
    //
    private static testMethod void testContract () {
        Service_Contract__c contract = new Service_Contract__c(Contract_Name__c = 'test contract');
        insert contract;
        
        List<Contract_Cost__c> costs = new List<Contract_Cost__c>();
        costs.add( new Contract_Cost__c(Contract__c = contract.Id) );
        
        // Create a PageReference to the VF page being tested       
        PageReference pageRef = Page.ServiceContract1;
        test.setCurrentPage(pageRef);
        
        // Now create the standard controller for the contact event
        ApexPages.StandardController stdCon = new ApexPages.StandardController(contract);
        
        // Test constructors
        ServiceContractWizard cnt = new ServiceContractWizard(stdCon);
        
        cnt.getContract();
        cnt.getCosts();
        cnt.setCosts(costs);
        cnt.getDefaultFCR();
        cnt.setDefaultFCR('0.00');
        
        cnt.back();
        cnt.next();
        cnt.cancel();
        cnt.cancelCosts();
        
        cnt.save();
    }
}