src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Consent_Status__c</fullName>
        <inlineHelpText>Seek signed consent as soon as possible. Services cannot be delivered unless verbal consent at least, has been obtained.</inlineHelpText>
        <label>Consent Status</label>
        <picklist>
            <picklistValues>
                <fullName>Awaiting Consent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verbal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Written</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Witnessed Verbal Consent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Witnessed Indicated Consent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proxy Consent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not a Service User</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Database_consent_Date__c</fullName>
        <label>Date consent obtained</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Change_of_Living_Arrangements__c</fullName>
        <label>Date of Change of Living Arrangements</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_diagnosis__c</fullName>
        <inlineHelpText>This is required if a diagnosis has been given. If full date of diagnosis is unknown, enter it to the nearest year or month (e.g. 01/01/1945 if diagnosis year is 1945; or 01/08/1945 if diagnosis date is estimated). Then tick ‘Approximate Date’ box</inlineHelpText>
        <label>Date of diagnosis</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deceased_Date__c</fullName>
        <label>Deceased Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deceased__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>To set a person as deceased please use the Person Wizard.</inlineHelpText>
        <label>Deceased?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Diagnosis__c</fullName>
        <inlineHelpText>Only to be used for CONFIRMED diagnosis of dementia.</inlineHelpText>
        <label>Dementia diagnosis</label>
        <picklist>
            <picklistValues>
                <fullName>Alzheimer’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Binswanger’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia with Lewy bodies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Down’s syndrome related dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fronto-Temporal dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HIV related dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huntington’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korsakoff’s syndrome</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixed dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parkinson’s disease related dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pick’s disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prion disease including CJD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vascular dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None - Awaiting Diagnosis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None - Other Mild Cognitive Impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (please list)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mild Cognitive Impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Diagnosis_made_by__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Diagnosis made by</description>
        <inlineHelpText>To record which professional made the diagnosis. Do NOT just type in name – A Professional already entered on the system must be found, selected and inserted by using the Look-Up function (magnifying glass icon).</inlineHelpText>
        <label>Diagnosis made by</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Professional / Stakeholder</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Diagnosis made by)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Key_Health_Issues__c</fullName>
        <label>Key Health Issues</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functional mental health issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visual impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hearing impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speech impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobility impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning difficulties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communication Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diabetic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Epileptic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobility Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Motor Skills Impairment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered Blind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered Disabled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wheelchair User</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Power_of_attorney_established__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Power of attorney established?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_user_aware_of_diagnosis__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service User aware of diagnosis</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Specialist_Communication_Needs__c</fullName>
        <inlineHelpText>To record information to assist communication, such as whether the speak English; if they need an interpreter; if they use BSL; what may help effective communication, etc.</inlineHelpText>
        <label>Specialist Communication Needs</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Street_Line_1__c</fullName>
        <label>Street Line 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Line_2__c</fullName>
        <label>Street Line 2</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Line_3__c</fullName>
        <label>Street Line 3</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Line_4__c</fullName>
        <label>Street Line 4</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rrpu__Alert_Message__c</fullName>
        <description>This field is installed by Riptide Pop-up Alerts and is used in conjunction with the Pop-up Alert S-Control.</description>
        <inlineHelpText>Any user can create an alert using the Public Alert Message Required on a service usage record.</inlineHelpText>
        <label>Alert Message</label>
        <type>TextArea</type>
    </fields>
    <recordTypes>
        <fullName>Person_with_dementia</fullName>
        <active>true</active>
        <description>CRS Use only</description>
        <label>Person with Dementia</label>
    </recordTypes>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <description>Health, Social Care and other professionals</description>
        <label>Professional / Stakeholder</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ContactTriggerHandler_Test.cls
@isTest
public class ContactTriggerHandler_Test {
 
   
    static testMethod void testContactTriggerHandler() {
   
     Contact c1 = new Contact(FirstName='one', LastName='test',MailingPostalCode ='ABC123', Birthdate =Date.Today().addyears(-1),
        rrpu__Alert_Message__c='test',
        RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and Name Like 'Person with dementia'].id);    
    insert c1;
    Contact c2 = new Contact(FirstName='two', LastName='test2',MailingPostalCode ='ABC123', Birthdate =Date.Today().addyears(-1),
        MailingCity='Abcd', MailingCountry='Abcd', MailingState='Abcd', MailingStreet='Abcd',
        RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and DeveloperName = 'Professional'].id);    
    insert c2;
     Contact c3 = new Contact(FirstName='three', LastName='test3',MailingPostalCode ='ABCD123',MailingStreet= 'test the street name long ass string first more than 80 character for testing the', Birthdate=System.today(),RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and DeveloperName = 'Person_with_dementia'].id);
        insert c3;
            
       
        c3= [SELECT AccountId,MailingStreet,Street_Line_1__c, Street_Line_2__c,Street_Line_3__c,Street_Line_4__c  FROM Contact WHERE Id =:c3.Id Limit 1];
        
        System.assertEquals(c3.Street_Line_1__c,'test the street name long ass string first more than 80 character for testing th');
        System.assertEquals(c3.Street_Line_2__c,'e');
        System.assertEquals(c3.Street_Line_3__c,null);
        System.assertEquals(c3.Street_Line_4__c,null);
       
        
        c3.MailingStreet = 'test with three\nline address this\nis street address\nthis is street address 3';
        update c3;                        
        c3.MailingStreet = 'test with two\nline address this\nis shipping address on when second line is overshot the length by 80 or more characters on the third line of the address\nfourth line';
        update c3;
        c3.MailingStreet = 'test with two\nis shipping address on when second line is overshot the length by 80 or more characters on the third line of the addressline address this\n\nfourth line';
        update c3;
        c3.MailingStreet = 'test the street name less than 80 character\n111111111122222222223333333333444444444455555555556666666666777777777788888888889\nthird line\nfourth line';
        update c3;
        c3.MailingStreet ='test the street name less than 80 character\nsecond line\nthird line 11111111112222222222333333333344444444445555555555666666666677777777778888888888\nfourth line';
        update c3;
        c3.MailingStreet ='test the street name less than 80 character\nsecond line\nthird line\nfourth line 1111111111222222222233333333334444444444555555555566666666667777777';
        update c3;
        c3.MailingStreet ='test the street name less than 80 character\nsecond line\nthird line\nfourth line' ;
        update c3;
        
      
       
    c1.Lastname='test2';
    update c1;
    c1.MailingCity='Abcd';
    c1.MailingCountry='Abcd';
    c1.MailingState='Abcd';
    c1.MailingStreet='Abcd';
    update c1;
   
    c1.Lastname='test3';
    c1.MailingStreet='Abcde';
    c1.MailingCity='Abcde';
    c1.BirthDate=Date.Today().addyears(-10);
    c1.Service_user_aware_of_diagnosis__c=true;
    c1.Specialist_Communication_Needs__c='abcde';
    c1.Diagnosis_made_by__c = c2.id;
    c1.Date_of_Diagnosis__c = Date.Today().addmonths(-9);
    c1.Diagnosis__c = 'Dementia with Lewy bodies';
    c1.Firstname='newadcd';
    c1.Consent_Status__c='Awaiting Consent';
    c1.Database_consent_Date__c=Date.Today().Addmonths(-4);
    c1.Date_of_Change_of_Living_Arrangements__c=Date.Today().Addmonths(-4);
    c1.Key_Health_Issues__c ='Hearing impairment';
    c1.Power_of_attorney_established__c=true;
    c1.Consent_Status__c='Withdrawn';
    update c1;
    c1.Consent_Status__c='Awaiting Consent';
    c1.rrpu__Alert_Message__c = '';
    c1.DoNotCall = true;
    update c1;

    
    c1.Deceased__c = true;
    c1.Deceased_Date__c = Date.Today().adddays(-3);
    update c1;
    
    delete c1;
    }
 

}