src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Carer</fullName>
        <active>true</active>
        <description>CRS Use only</description>
        <label>Carer of Person with Dementia</label>
    </recordTypes>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <description>Health, Social Care and other professionals</description>
        <label>Professional / Stakeholder</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/contact__c.object
<CustomObject>
    <label>contact</label>
    <nameField>
        <label>contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SFDC_Contact_Connector__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Connection</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships (Related Contact)</relationshipLabel>
        <relationshipName>Related_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Same_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate that this Person resides as the same address as Person 1</description>
        <inlineHelpText>If this is checked, address of Person1 is the same as that of Person2</inlineHelpText>
        <label>Same Address?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Indicates the relationship that the existing person has with the person you are detailing below</inlineHelpText>
        <label>Relationship</label>
        <picklist>
            <picklistValues>
                <fullName>Consultant of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social care worker of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social worker of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care manager of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community psychiatric nurse of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admiral nurse of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient of (GP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient of (Consultant)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient of (Care Manager)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient of (CPN)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient of (Admiral nurse)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client of (Social care worker)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client of (Social worker)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client of (Care manager)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighbour of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spouse of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Son/daughter of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sibling of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cousin of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nephew/niece of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uncle/aunt of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grandparent of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grandson/daughter of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent in-law of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Son/daughter-in-law of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sibling in-law of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Step-parent of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Step-child of</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <recordTypes>
        <fullName>Personal</fullName>
        <active>true</active>
        <description>Personal Relationship</description>
        <label>Personal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <description>Professional Relationship</description>
        <label>Professional</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestTriggerExistingRelation.cls
@isTest
private class TestTriggerExistingRelation{

static testMethod void mytestclass(){
    Contact c1 = new Contact(FirstName='one', LastName='test',MailingPostalCode ='ABC123', Birthdate =Date.Today().addyears(-1),
            MailingCity='Abcd', MailingCountry='Abcd', MailingState='Abcd', MailingStreet='Abcd',
            RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and Name Like 'Person with dementia'].id);    
        insert c1;
    Contact relcon = new Contact(FirstName='two', LastName='related',MailingPostalCode ='ABC123', Birthdate =Date.Today().addyears(-1),
            RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and Name Like 'Carer of Person with Dementia'].id);  
        insert relcon;
    Id personal = [SELECT Id,Name FROM RecordType WHERE SobjectType='SFDC_Contact_Connector__c' AND Name ='Personal'].id;
    Id professional  = [SELECT Id,Name FROM RecordType WHERE SobjectType='SFDC_Contact_Connector__c' AND Name ='Professional'].id;
    
     SFDC_Contact_Connector__c Relation1 = new SFDC_Contact_Connector__c(RecordTypeId=personal, Contact__c=c1.id, Related_Contact__c=relcon.id, Type__c='Spouse of',Same_Address__c=true);
     insert Relation1;
     SFDC_Contact_Connector__c Relation2 = new SFDC_Contact_Connector__c(RecordTypeId=personal, Contact__c=c1.id, Related_Contact__c=c1.id, Type__c='Spouse of',Same_Address__c=true);     
     SFDC_Contact_Connector__c Relation3 = new SFDC_Contact_Connector__c(RecordTypeId=personal, Contact__c=c1.id, Related_Contact__c=relcon.id, Type__c='Spouse of',Same_Address__c=true);
      try
        {
            insert Relation2;
        }
        catch(System.DMLException e)
        {
         System.assert(e.getMessage().contains('Relationship with Self can not be created'));
        }    
        try
        {
            insert Relation3;
        }
        catch(System.DMLException e)
        {
         System.assert(e.getMessage().contains('A Relationship already exists with the same person'));
        }     
        
 }
}