src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Deceased__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>To set a person as deceased please use the Person Wizard.</inlineHelpText>
        <label>Deceased?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Usage__c.object
<CustomObject>
    <fields>
        <fullName>Service_Field__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the Service/Activity.
Filtered by Service Type and user&apos;s Locality for internal Service Usage records.
No filter required for &apos;Outgoing Referrals&apos; as these are only ever created in the background (via Referrals screen).</description>
        <label>Service</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 5 AND 6) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>Services__c.service_type__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Type__c</valueField>
            </filterItems>
            <filterItems>
                <field>Services__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Service</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outgoing Referral</value>
            </filterItems>
            <filterItems>
                <field>Services__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Service</value>
            </filterItems>
            <filterItems>
                <field>Services__c.Locality__r.Name</field>
                <operation>equals</operation>
                <valueField>$User.Locality__c</valueField>
            </filterItems>
            <filterItems>
                <field>Services__c.service_status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Services__c</referenceTo>
        <relationshipLabel>Service Usage</relationshipLabel>
        <relationshipName>Service_Usage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <description>The type of Service to which Service Usage relates.
Used as a filter when selecting Service.
Used to set Record Type on saving a new Service Usage.</description>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (one to one)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peer support group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered home care and support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singing for the Brain</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Usage</label>
    <nameField>
        <label>Service Usage Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Usage</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>Locality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Locality in which this service is based (left blank for national services).</description>
        <label>Locality</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select an Alzheimer&apos;s Society Locality.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Organisation</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>contains</operation>
                <value>Locality</value>
            </filterItems>
            <infoMessage>Please select a Locality.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Services_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>National_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>National Service?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>service_type__c</fullName>
        <inlineHelpText>Service description will be automatically populated from the service type (or sub type if there is one)</inlineHelpText>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult education &amp; training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (emotional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (financial)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (general)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awareness raising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending / home support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counselling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day support / day care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafés</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exercise / Fitness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home facilities &amp; services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Dementia)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Financial &amp; Legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programmes &amp; provision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>Internal Service/Activity</description>
        <label>Internal Service</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Locality__c</fullName>
        <description>The Society Locality to which the user is assigned (if any).</description>
        <inlineHelpText>Must match the Name of the corresponding Internal Organisation.</inlineHelpText>
        <label>Locality</label>
        <picklist>
            <controllingField>Area__c</controllingField>
            <picklistValues>
                <fullName>Abertawe Bro Morgannwg Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avon, Gloucestershire &amp; Wiltshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bedfordshire &amp; Luton Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Berkshire, Buckinghamshire, Oxfordshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambridgeshire &amp; Peterborough Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiff and the Vale Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheshire &amp; St Helens Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cumbria Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cwm Taff Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Darlington &amp; Teesside Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Derbyshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Devon, Cornwall &amp; Isles of Scilly Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dorset &amp; Somerset Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durham Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Riding &amp; Humber Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Essex Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Manchester Central &amp; West Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Manchester Central South and East Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gwent Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hampshire, Isle of Wight and the Channel Islands Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Herefordshire &amp; Worcestershire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hertfordshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent &amp; Medway Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lancashire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leicestershire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lincolnshire Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merseyside &amp; Isle of Man Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Midlands Central Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norfolk Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North &amp; East Northern Ireland Locality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North West London Locality</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestSwapServiceUsageOwnership.cls
@isTest
public class TestSwapServiceUsageOwnership{

static testMethod void mainTest(){
User U1 = [select id, name from User where Profile.Name='CRS' and UserRole.Name like 'Dementia Adviser & Dementia Support - North West London%'  and IsActive=true LIMIT 1];
User U2 = [select id, name from User where Profile.Name='CRS' and UserRole.Name like 'Dementia Adviser & Dementia Support - North West London%' and IsActive=true AND id!=:u1.id LIMIT 1];
      
System.debug ('###############u1###########'+u1.name);
System.debug ('###############u2###########'+u2.name);

Contact recCon = new Contact(FirstName = 'Albert', LastName='TestLastName',Deceased__c=false,MailingPostalCode ='ABC123', Birthdate =Date.Today(),
        RecordTypeId=[Select Id from RecordType where SObjectType='Contact' and Name Like 'Person with dementia'].id);
insert recCon;  

Account accRec = new Account(Name='North West London Locality',RecordTypeId=[Select Id from RecordType where SObjectType='Account' and Name like 'Internal%'].id);
insert accRec;
Services__c serv = new Services__c(Name='North West London DS test', Locality__c=accRec.id,Service_Type__c='Dementia support', National_Service__c=false);//Name='testControllerService');
insert serv;    
Service_Usage__c recSU = new Service_Usage__c(Service_Field__c= serv.id, Primary_Service_User__c=recCon.id,Service_Type__c='Dementia support');
    
insert recSU;
recSU.ownerid = u1.id;
recSU.closure_reason__c = null;
update recSU;

    ApexPages.currentPage().getParameters().put('id', recSU.id);  
    SwapServiceUsageOwnership conCls= new SwapServiceUsageOwnership(new ApexPages.StandardController(recSU));
Test.StartTest();
    conCls.Find();
    //this not a user id
    conCls.fromSU.ownerid=recSU.id;
    conCls.toSU.ownerid=U2.id;
    conCls.Find();
    //now find using correct id
    conCls.fromSU.ownerid=recSU.ownerid;
    conCls.Find();
    //cause error message one or more services must be selected.
    conCls.submit(); 
    //select all services and submit
    For (SwapServiceUsageOwnership.ServiceCountWrapper SWp : conCls.ServiceWp){
        SWp.isSelected=true;}
    conCls.submit();
    conCls.Cancel();
Test.StopTest();
}

}