src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Carer</fullName>
        <active>true</active>
        <description>CRS Use only</description>
        <label>Carer of Person with Dementia</label>
    </recordTypes>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <description>Health, Social Care and other professionals</description>
        <label>Professional / Stakeholder</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/contact__c.object
<CustomObject>
    <label>contact</label>
    <nameField>
        <label>contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact_Event__c.object
<CustomObject>
    <description>For recording each time that contact is made with a client of any type</description>
    <label>Contact Interaction</label>
    <nameField>
        <label>Contact Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Interactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact_Event_Contact_Connector__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Event__c</fullName>
        <label>Contact Interaction</label>
        <referenceTo>Contact_Event__c</referenceTo>
        <relationshipLabel>People Involved</relationshipLabel>
        <relationshipName>Contact_Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Interaction Involvement</relationshipLabel>
        <relationshipName>Contact_Event_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Event Attendee</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Contact Event Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/addContactEventAttendees.cls
public class addContactEventAttendees extends addContacts {
    public Contact_Event__c contactEvent;
    
    // Visualforce extension constructor
    public addContactEventAttendees(ApexPages.StandardController controller) {
        contactEvent = (Contact_Event__c)controller.getRecord();
        
        recordTypeList.add('012700000009b4B'); // Person with dementia
        recordTypeList.add('012700000009b49'); // Carer / family member / friend
        recordTypeList.add('012700000009b4A'); // Health/Social Care Professional record type
    }
        
    // ----------------------------------------------------------------------
    // Save Button:
    // - Build a list of new Attendence records relating to the contact Event
    // - Upsert and report any errors
    // - Redirect to the contact Event
    // ----------------------------------------------------------------------
    public override pageReference doSave() {
        
        // Build a list of new attendence objects to insert
        List<Contact_Event_Contact_Connector__c> attendences = new List<Contact_Event_Contact_Connector__c>();
        Contact_Event_Contact_Connector__c a;
        for (transferContactSearchResults c : searchResults) {
            if (c.selected) {
                // Create a new attendence record for each selected contact
                a = new Contact_Event_Contact_Connector__c();
                a.Contact__c = c.contact.ID;
                a.Contact_Event__c = contactEvent.Id;
                attendences.add(a);
            }
        }
        if (DebugMode) ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Selected Count: ' + attendences.size()));


        // Process Errors and Count the Number of Records created
        Integer transferCount = 0;
        List<database.Upsertresult> srs = database.upsert(attendences);
        for (database.Upsertresult sr : srs) {
            if (!sr.isSuccess()) {
                ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.FATAL, sr.getId() + '/' + sr.getErrors()[0].getMessage() ));
            } else {
                transferCount++; 
            }
        }
    
        // Display the Transfer Count
        ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.INFO, transferCount + ' Records Successfully Transfered' ));
        
        // Set the flag that this just finished
        transferJustCompleted = true;       
        
        // Send the user to the detail page for the contact event
        PageReference page = new PageReference('/' + contactEvent.id);
        page.setRedirect(true);
        return page;
    }
    
    // Send user back to contact event
    public override PageReference cancel() {
        PageReference page = new PageReference('/' + contactEvent.id);
        page.setRedirect(true);
        return page;
    }
}