src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Attended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attended?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contacted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contacted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Eligible?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospective</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Converted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DF_EventAttendee__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DF_Contact__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dementia Friend Champion</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF EventAttendance</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DF_Event__c</fullName>
        <label>DF Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DF_Event__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Champion Training Course</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>DF_Event__c</referenceTo>
        <relationshipLabel>DF EventAttendees</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DF EventAttendee</label>
    <nameField>
        <displayFormat>DFE-{0000000}</displayFormat>
        <label>DF EventAttendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF EventAttendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DfEventAttendeeController.cls
public class DfEventAttendeeController{
 private final DF_Event__c dfevent;
 List<DF_EventAttendee__c> lsteventattendees;
 List<DF_Contact__c> lstdfcons;
 List<Id> conids = new List<Id>();
 //DF_Event__c dfeventnew;
 public DfEventAttendeeController(ApexPages.StandardController stdController){
     this.dfevent= (DF_Event__c)stdController.getRecord();
     //system.debug('@@@@@@@@@@@'+dfevent.Id);
     Id dfeveid = dfevent.Id;
 lsteventattendees = (List<DF_EventAttendee__c>)[Select Id, Name, DF_Contact__c, DF_Event__c, 
                       DF_EventAttendee__c.DF_Contact__r.Status__c,DF_EventAttendee__c.DF_Contact__r.Email__c
                       FROM DF_EventAttendee__c Where DF_Event__c =:dfeveid];
        
  for(DF_EventAttendee__c rec:lsteventattendees){
        conids.add(rec.DF_Contact__c);
  }             
  lstdfcons = [Select Name, Status__c, Email__c, Contact_Number__c, Note__c, Eligible__c, Contacted__c, 
                              Attended__c FROM DF_Contact__c Where DF_Contact__c.Id IN:conids]; 
  lstdfcons.sort();                                                          
  }                                                          
  /* public List<DF_EventAttendee__c> getlsteventattendees(){
     return lsteventattendees;
 } */
 public List<DF_Contact__c> getlstdfcontacts(){
     return lstdfcons;
    }
  public Pagereference save(){
    update lstdfcons;
    return (new ApexPages.StandardController(dfevent)).view();
    //return null;
 }
 public testmethod static void testdfcontroller()
 {
    DF_Contact__c dfcon = new DF_Contact__c(Name='Test dfcontact',First_Name__c='Test',Last_Name__c='dfcontact',Status__c='Prospective',Email__c='test@dfcon.com',
   RecordTypeId=[Select Id from RecordType where SObjectType='DF_Contact__c' and Name Like 'Dementia Friend Champion'].Id,
                                            Contact_Number__c='12345678',Eligible__c=FALSE,Contacted__c=FALSE,
                                            Attended__c=FALSE,Note__c='Test Notes');
    insert dfcon;
    DF_Event__c dfeve = new DF_Event__c(Name='dfevent test',
       RecordTypeId=[Select Id from RecordType where SObjectType='DF_Event__c' and Name Like 'Champion Training Course'].Id);
    insert dfeve;
    DF_EventAttendee__c dfeveattnd = new DF_EventAttendee__c(DF_Contact__c=dfcon.Id,DF_Event__c=dfeve.Id);
    ApexPages.currentPage().getParameters().put('id',dfeve.Id);
    DfEventAttendeeController dfcont = new DfEventAttendeeController(new ApexPages.Standardcontroller(dfeve));  
    dfcont.getlstdfcontacts();
    dfcont.save();                                       
  }
}