src/objects/DF_Contact__c.object
<CustomObject>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Partner_Organisation__c.object
<CustomObject>
    <fields>
        <fullName>DFC_Code__c</fullName>
        <label>DFC Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Partner External Id</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestLastTransactionDateLookup.cls
@isTest
public with sharing class TestLastTransactionDateLookup {

/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : Test Class for LastTransactionDateLookup Class.
 *  Author  : Ian Smith
 *  Date    : 28-01-2014
 *  Version : 0.1 Unit Test
 *
 *  Description:    Apex Class to test LastTransactionDateLookup Class. 
 *               
 *  Modification History
 *
 *  Date            Who     Description 
 *  dd-mm-yyyy      ??      ??
 *                             
*******************************************************************************************/

    static testMethod void TestLastDateModifiedLookup(){
              
        // New Contact Record to be added to the Friend_Survey__c test Data.
        Partner_Organisation__c pa = new Partner_Organisation__c(Name='Test Org', DFC_Code__c='ABC123', Partner_External_Id__c=1234);
        insert pa;              
        
        //Now insert data causing the DF_Contact__c trigger to fire. 
        Test.startTest();
        
        LastTransactionDateLookup handler = new LastTransactionDateLookup();
        handler.UpdateLastTransactionDate(pa.id, datetime.now());
        //now update the item
        handler.UpdateLastTransactionDate(pa.id, datetime.now());

        Test.stopTest();
                     
    }  
 
}