src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Ext_Id__c</fullName>
        <externalId>true</externalId>
        <label>Contact Ext Id</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Organisation_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Organisation ID</label>
        <referenceTo>Partner_Organisation__c</referenceTo>
        <relationshipLabel>DF Champions</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Partner_Organisation__c.object
<CustomObject>
    <fields>
        <fullName>DFC_Code__c</fullName>
        <label>DFC Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Partner External Id</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDF_ContactTriggerHandler.cls
@isTest
public with sharing class TestDF_ContactTriggerHandler{
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : Test Class for DF_ContactTriggerHandler Trigger.
 *  Author  : Ian Smith
 *  Date    : 23-01-2014
 *  Version : 0.1 Unit Test
 *
 *  Description:	Apex Class to test DF_ContactTriggerHandler trigger on the DF_Contact__c object. 
 *               
 *  Modification History
 *  Date        	Who    	Description 
 *  dd-mm-yyyy		??		??
 *                             
*******************************************************************************************/

    static testMethod void testInsert(){
              
		//New Partner_Organisation__c Record to be added to the DF_Contact__c test Data.
		Partner_Organisation__c pa = new Partner_Organisation__c(Name='Test Org', DFC_Code__c='ABC123', Partner_External_Id__c=1234);
		insert pa;              
		
		//New DF_Contact__c Record to be added to the test Data.
		DF_Contact__c df = new DF_Contact__c(Name='Test DFC', Partner_Organisation_ID__c = pa.id, Contact_Ext_Id__c = 12345678);
        
        //Now insert data causing the DF_Contact__c trigger to fire. 
        Test.startTest();
		insert df;
        Test.stopTest(); 
    }
    
    
    
	static testMethod void testBulkInsert(){
              
		//New Partner_Organisation__c Record to be added to the DF_Contact__c test Data.
		Partner_Organisation__c pa = new Partner_Organisation__c(Name='Test Org', DFC_Code__c='ABC123', Partner_External_Id__c=1234);
		insert pa;              
		
		//New DF_Contact__c Record to be added to the test Data.
        DF_Contact__c[] dfConToCreate = new DF_Contact__c[]{};
        
        //Create 200 new DF_Contact Records for a Bulk test.
        for(Integer i=0; i< 200; i++){
            DF_Contact__c df = new DF_Contact__c(Name = 'Test DF Con',
				Contact_Ext_Id__c = i,
				Partner_Organisation_ID__c = pa.id
			);
            dfConToCreate.add(df);
        }
        
        //Now insert data causing the DF_Contact__c trigger to fire. 
        Test.startTest();	
        insert dfConToCreate;
        Test.stopTest();	
    }    
    
    
    
    static testMethod void testUpdate(){
    	
		// New Partner_Organisation__c Record to be added to the DF_Contact__c test Data.
		Partner_Organisation__c pa = new Partner_Organisation__c(Name='Test Org', DFC_Code__c='ABC123', Partner_External_Id__c=1234);
		insert pa;              
		
		// New DF_Contact__c Record to be added to the test Data.
		DF_Contact__c df = new DF_Contact__c(Name='Test DFC', Partner_Organisation_ID__c = pa.id, Contact_Ext_Id__c = 12345678);
		insert df;	
		
		Test.startTest();  // Start Executing the test.

		df.Name = 'TestDFC';
		df.First_Name__c = 'Test FirstName';
		df.Last_Name__c = 'Test LastName';	
		update df;
		        
        Test.stopTest();  // Stops the test execution.
                
        System.assertEquals('TestDFC', [select Name from DF_Contact__c where id =: df.id].Name);
	}
  
  
  
	static testMethod void testBulkUpdate(){
    	
		//New Partner_Organisation__c Record to be added to the DF_Contact__c test Data.
		Partner_Organisation__c pa = new Partner_Organisation__c(Name='Test Org', DFC_Code__c='ABC123', Partner_External_Id__c=1234);
		insert pa;              
		
		//New Batch of DF_Contact__c Records to be added to the test Data.
		List<DF_Contact__c> lstDFContact = new List<DF_Contact__c>();

		//Create 200 new DF_Contact Records for a Bulk test.
		for (Integer i=0 ; i <200; i++) {
			DF_Contact__c df = new DF_Contact__c(
				Name = 'Test DF Con',
				Contact_Ext_Id__c = i,
				Partner_Organisation_ID__c = pa.id
			);	
            lstDFContact.add(df);
        }

		List<DF_Contact__c> lstToUpdate = [select Id, Name from DF_Contact__c where Name = 'Test DF Con'];
		for(DF_Contact__c df : lstToUpdate){
            df.Name = 'TestDFcon';
        }
	 
		Test.startTest();  // Start Executing the test.	 
		update lstToUpdate;
        Test.stopTest();  // Stops the test execution.
	}
    
    
    
    static testMethod void testDelete(){

		//New Partner_Organisation__c Record to be added to the DF_Contact__c test Data.
		Partner_Organisation__c pa = new Partner_Organisation__c(Name='Test Org', DFC_Code__c='ABC123', Partner_External_Id__c=1234);
		insert pa;              
		
		//New DF_Contact__c Record to be added to the test Data.
		DF_Contact__c df = new DF_Contact__c(Name='Test DFC', Partner_Organisation_ID__c = pa.id, Contact_Ext_Id__c = 12345678);
		insert df;
		
		Test.startTest();  // Start Executing the test.		       
		delete df;
		Test.stopTest();  // Stops the test execution.
  }    
    
 
 
}