src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Ext_Id__c</fullName>
        <externalId>true</externalId>
        <label>Contact Ext Id</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Partner_Organisation_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Organisation ID</label>
        <referenceTo>Partner_Organisation__c</referenceTo>
        <relationshipLabel>DF Champions</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>Dementia_Friend_Champion</fullName>
        <active>true</active>
        <label>Dementia Friend Champion</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>Session_Organiser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Session Organiser</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Sessions Organised</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <recordTypes>
        <fullName>Dementia_Friend_Awareness_Session</fullName>
        <active>true</active>
        <description>Events organised by DF Champions</description>
        <label>Dementia Friend Awareness Session</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DF_EventAttendee__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DF_Contact__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dementia Friend Champion</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF EventAttendance</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DF_EntAtExt_Id__c</fullName>
        <externalId>true</externalId>
        <label>DF EntAtExt Id</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>DF_Event__c</fullName>
        <label>DF Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DF_Event__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Champion Training Course</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>DF_Event__c</referenceTo>
        <relationshipLabel>DF EventAttendees</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DF EventAttendee</label>
    <nameField>
        <displayFormat>DFE-{0000000}</displayFormat>
        <label>DF EventAttendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF EventAttendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Partner_Organisation__c.object
<CustomObject>
    <fields>
        <fullName>DFC_Code__c</fullName>
        <label>DFC Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Partner External Id</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDF_EventAttendeeTriggerHandler.cls
@isTest
public with sharing class TestDF_EventAttendeeTriggerHandler{
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : Test Class for DF_EventAttendeeTriggerHandler Trigger.
 *  Author  : Ian Smith
 *  Date    : 29-01-2014
 *  Version : 0.1 Unit Test
 *
 *  Description:	Apex Class to test DF_EventAttendeeTriggerHandler trigger on the DF_EventAttendee__c object. 
 *               
 *  Modification History
 *  Date        	Who    	Description 
 *  dd-mm-yyyy		??		??
 *                             
*******************************************************************************************/

    static testMethod void testInsert(){

		//Select DF_Event__c RecordTypeId for "Dementia Friend Awareness Session".
		RecordType rTypedf = [Select Id from RecordType where DeveloperName ='Dementia_Friend_Awareness_Session' and SobjectType = 'DF_Event__c'];
		
		//Select DF_Contact__c RecordTypeId for "Dementia Friend Champion".
		RecordType rTypedfc = [Select Id from RecordType where DeveloperName ='Dementia_Friend_Champion' and SobjectType = 'DF_Contact__c'];
		
		//New Partner_Organisation__c Record to be added to the DF_Contact__c test Data.
		Partner_Organisation__c pa = new Partner_Organisation__c(Name='Test Org', DFC_Code__c='ABC123', Partner_External_Id__c=1234);
		insert pa; 
		
		//New DF_Contact__c Record to be added to the test Data.
		DF_Contact__c df = new DF_Contact__c(RecordTypeId = rTypedfc.id, Name='Test DFC', Partner_Organisation_ID__c = pa.id, Contact_Ext_Id__c = 12345678);
        insert df;
        
		//New DF_Event__c Record to be added to the test Data.
		DF_Event__c dfEvent = new DF_Event__c(RecordTypeId = rTypedf.id, Name = 'Test DFEvent', Session_Organiser__c = df.Id);
        insert dfEvent;
        
		//New DF_Event__c Record to be added to the test Data.
		DF_EventAttendee__c dfEventAtt = new DF_EventAttendee__c(DF_Contact__c = df.Id, DF_Event__c = dfEvent.Id, DF_EntAtExt_Id__c = 1234);
        
        //Now insert data causing the DF_Event__c trigger to fire. 
        Test.startTest();
		insert dfEventAtt;
        Test.stopTest(); 
    }
    
    
    
	static testMethod void testBulkInsert(){
              
		//Select DF_Event__c RecordTypeId for "Dementia Friend Awareness Session".
		RecordType rTypedf = [Select Id from RecordType where DeveloperName ='Dementia_Friend_Awareness_Session' and SobjectType = 'DF_Event__c'];
		
		//Select DF_Contact__c RecordTypeId for "Dementia Friend Champion".
		RecordType rTypedfc = [Select Id from RecordType where DeveloperName ='Dementia_Friend_Champion' and SobjectType = 'DF_Contact__c'];
		
		//New Partner_Organisation__c Record to be added to the DF_Contact__c test Data.
		Partner_Organisation__c pa = new Partner_Organisation__c(Name='Test Org', DFC_Code__c='ABC123', Partner_External_Id__c=1234);
		insert pa; 
		
		//New DF_Contact__c Record to be added to the test Data.
		DF_Contact__c df = new DF_Contact__c(RecordTypeId = rTypedfc.id, Name='Test DFC', Partner_Organisation_ID__c = pa.id, Contact_Ext_Id__c = 12345678);
        insert df;
        
		//New DF_Event__c Record to be added to the test Data.
		DF_Event__c dfEvent = new DF_Event__c(RecordTypeId = rTypedf.id, Name = 'Test DFEvent', Session_Organiser__c = df.Id);
        insert dfEvent;
        
		//New DF_EventAttendee__c Records to be added to the test Data.
		DF_EventAttendee__c[] dfEventAttToCreate = new DF_EventAttendee__c[]{};
        
        for(Integer i=0; i< 200; i++){
            DF_EventAttendee__c dfEventAtt = new DF_EventAttendee__c(DF_Contact__c = df.Id, 
	            DF_Event__c = dfEvent.Id, 
	            DF_EntAtExt_Id__c = i
			);
            dfEventAttToCreate.add(dfEventAtt);
        }
        
        //Now insert data causing the DF_EventAttendee__c trigger to fire. 
        Test.startTest();
        insert dfEventAttToCreate;
        Test.stopTest(); 
    }    
    
    
    
    static testMethod void testUpdate(){
    	
		//Select DF_Event__c RecordTypeId for "Dementia Friend Awareness Session".
		RecordType rTypedf = [Select Id from RecordType where DeveloperName ='Dementia_Friend_Awareness_Session' and SobjectType = 'DF_Event__c'];
		
		//Select DF_Contact__c RecordTypeId for "Dementia Friend Champion".
		RecordType rTypedfc = [Select Id from RecordType where DeveloperName ='Dementia_Friend_Champion' and SobjectType = 'DF_Contact__c'];
		
		//New Partner_Organisation__c Record to be added to the DF_Contact__c test Data.
		Partner_Organisation__c pa = new Partner_Organisation__c(Name='Test Org', DFC_Code__c='ABC123', Partner_External_Id__c=1234);
		insert pa; 
		
		//New DF_Contact__c Record to be added to the test Data.
		DF_Contact__c df = new DF_Contact__c(RecordTypeId = rTypedfc.id, Name='Test DFC', Partner_Organisation_ID__c = pa.id, Contact_Ext_Id__c = 12345678);
        insert df;
        
		//New DF_Event__c Record to be added to the test Data.
		DF_Event__c dfEvent = new DF_Event__c(RecordTypeId = rTypedf.id, Name = 'Test DFEvent', Session_Organiser__c = df.Id);
        insert dfEvent; 
        
		//New DF_Event__c Record to be added to the test Data.
		DF_EventAttendee__c dfEventAtt = new DF_EventAttendee__c(DF_Contact__c = df.Id, DF_Event__c = dfEvent.Id, DF_EntAtExt_Id__c = 1234);
        insert dfEventAtt;
    		
		Test.startTest();  //Start Executing the test.

		dfEventAtt.DF_EntAtExt_Id__c = 1235;
		update dfEventAtt;
		        
        Test.stopTest();  //Stops the test execution.
                
        System.assertEquals(1235, [select DF_EntAtExt_Id__c from DF_EventAttendee__c where id =: dfEventAtt.id].DF_EntAtExt_Id__c);
	}
  
  
  
	static testMethod void testBulkUpdate(){
		
		//Select DF_Event__c RecordTypeId for "Dementia Friend Awareness Session".
		RecordType rTypedf = [Select Id from RecordType where DeveloperName ='Dementia_Friend_Awareness_Session' and SobjectType = 'DF_Event__c'];
		
		//Select DF_Contact__c RecordTypeId for "Dementia Friend Champion".
		RecordType rTypedfc = [Select Id from RecordType where DeveloperName ='Dementia_Friend_Champion' and SobjectType = 'DF_Contact__c'];
		
		//New Partner_Organisation__c Record to be added to the DF_Contact__c test Data.
		Partner_Organisation__c pa = new Partner_Organisation__c(Name='Test Org', DFC_Code__c='ABC123', Partner_External_Id__c=1234);
		insert pa; 
		
		//New DF_Contact__c Record to be added to the test Data.
		DF_Contact__c df = new DF_Contact__c(RecordTypeId = rTypedfc.id, Name='Test DFC', Partner_Organisation_ID__c = pa.id, Contact_Ext_Id__c = 12345678);
        insert df;
        
		//New DF_Event__c Record to be added to the test Data.
		DF_Event__c dfEvent = new DF_Event__c(RecordTypeId = rTypedf.id, Name = 'Test DFEvent', Session_Organiser__c = df.Id);
        insert dfEvent; 
        
		//New Batch of DF_EventAttendee__c Records to be added to the test Data.
		List<DF_EventAttendee__c> lstDFEventAtt = new List<DF_EventAttendee__c>();

		for (Integer i=0 ; i <200; i++) {
			DF_EventAttendee__c dfEventAtt = new DF_EventAttendee__c(DF_Contact__c = df.Id, 
	            DF_Event__c = dfEvent.Id, 
	            DF_EntAtExt_Id__c = i
			);	
            lstDFEventAtt.add(dfEventAtt);
        }
        insert lstDFEventAtt;

		Integer i = 0;

		List<DF_EventAttendee__c> lstToUpdate = [select Id, DF_EntAtExt_Id__c from DF_EventAttendee__c where DF_EntAtExt_Id__c = 1234];
		for(DF_EventAttendee__c dfe : lstToUpdate){
            dfe.DF_EntAtExt_Id__c = i + 1;
        }
	 
		Test.startTest();  //Start Executing the test.	 
		update lstToUpdate;
        Test.stopTest();  //Stops the test execution.
	}
    
    
    
    static testMethod void testDelete(){
    	
		//Select DF_Event__c RecordTypeId for "Dementia Friend Awareness Session".
		RecordType rTypedf = [Select Id from RecordType where DeveloperName ='Dementia_Friend_Awareness_Session' and SobjectType = 'DF_Event__c'];
		
		//Select DF_Contact__c RecordTypeId for "Dementia Friend Champion".
		RecordType rTypedfc = [Select Id from RecordType where DeveloperName ='Dementia_Friend_Champion' and SobjectType = 'DF_Contact__c'];
		
		//New Partner_Organisation__c Record to be added to the DF_Contact__c test Data.
		Partner_Organisation__c pa = new Partner_Organisation__c(Name='Test Org', DFC_Code__c='ABC123', Partner_External_Id__c=1234);
		insert pa; 
		
		//New DF_Contact__c Record to be added to the test Data.
		DF_Contact__c df = new DF_Contact__c(RecordTypeId = rTypedfc.id, Name='Test DFC', Partner_Organisation_ID__c = pa.id, Contact_Ext_Id__c = 12345678);
        insert df;
        
		//New DF_Event__c Record to be added to the test Data.
		DF_Event__c dfEvent = new DF_Event__c(RecordTypeId = rTypedf.id, Name = 'Test DFEvent', Session_Organiser__c = df.Id);
        insert dfEvent; 
        
		//New DF_Event__c Record to be added to the test Data.
		DF_EventAttendee__c dfEventAtt = new DF_EventAttendee__c(DF_Contact__c = df.Id, DF_Event__c = dfEvent.Id, DF_EntAtExt_Id__c = 1234);
        insert dfEventAtt; 
		
		Test.startTest();  //Start Executing the test.		       
		delete dfEventAtt;
		Test.stopTest();  //Stops the test execution.
  }    
    
 
 
}