src/objects/Enhanced_Lookup__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Inactive items will not show in list.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lookup_Description__c</fullName>
        <label>Lookup Description</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lookup_Value__c</fullName>
        <label>Lookup Value</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>Order of list</description>
        <label>Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lookup_field__c</fullName>
        <label>Lookup Field</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Enhanced Lookup</label>
    <nameField>
        <displayFormat>Lookup-{0000}</displayFormat>
        <label>Enhanced Lookup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enhanced Lookups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CRSHelpController.cls
public without sharing class CRSHelpController {

    public CRSHelpController() {

    }

    
  public String controllerValue;
  public String HelpType;
    
  public void setControllerValue (String s) {
    controllerValue = s;
  }
    
  public String getControllerValue() {
    return controllerValue;
  }
  public String getHelpType(){
      return HelpType;
  }
  public void setHelpType(String s){
      HelpType = s;
  }
  public Boolean ShowQuestion;
  public Boolean getShowQuestion() {
      return ShowQuestion;
  }
  public void setShowQuestion(Boolean b) {
      ShowQuestion = b;
  }
  
  
  private List<Enhanced_Lookup__c> lstPvtHelp{get;set;} 
  
  public List<Enhanced_Lookup__c> lstHelp{
     get { fetchHelpDetails();
           return lstPvtHelp;}
     set;
  
 } 
  public CRSHelpController(ApexPages.StandardController controller) {
  fetchHelpDetails();
  
  }
  private void fetchHelpDetails(){
         lstPvtHelp= new List<Enhanced_Lookup__c>(); 
         lstPvtHelp= [SELECT  Name, Lookup_Description__c, lookup_field__c, Lookup_Value__c 
                             FROM Enhanced_Lookup__c 
                             WHERE lookup_field__c = :controllerValue 
                             AND Active__c=true order by Order__c];
   }
  
  
  
}