src/objects/Evidence_for_Need__c.object
<CustomObject>
    <description>A document recording the evidence for the need for a specific service</description>
    <label>BDR Evidence for Need</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDR Evidence for Needs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fund_Allocation__c.object
<CustomObject>
    <description>A link between a Service Costs and an Income Block for a Financial Year</description>
    <label>BDR Income Allocation</label>
    <nameField>
        <displayFormat>FAR-{0000}</displayFormat>
        <label>Fund Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDR income Allocation Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>4</scale>
        <type>Location</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BdrServiceWrapper.cls
public class BdrServiceWrapper {

/***************************************************************************************
 *   @author        gary.grant@conseq.co.uk
 *   @date          july 2014
 *   @description   A wrapper for a Services__c class that contains associated records for 
 *                  funding and income related to a proposal
 *   
 *                  The service wrapper should be used  with a ServiceWrapperList
 
 *                  The ServiceWrapper list takes a list or services and will create a list of 
 *                  service wrappers that contain both the related FundingRequirementWrappers 
 *                  The FundRequirementWrappers are populated with the funding requirement object 
 *                  and related fund allocations 
 *  
 *                  ServiceWrapperList
 *                  contains { BdrServiceWrappers )
 *
 *                  ServiceWrapper
 *                  contains(services__c, list of BdrFundReqWrappers, latest Evidence For Need)
 *   
 *                  BdrFundReqWrapper
 *                  contains(Fund_Requirement__c, list of Fund_Allocation__c)
 *   
 *                  That enables views over a list of services, listing their funding status
 *                  in a given (or set of ) fiscal period(s)    
 *   
 *****************************************************************************************/
  
  
  public Services__c svc {get;set;}    /* A single Service - despite the misleading plural name */
  public List<BdrFundReqWrapper> fundReqWrappers {get;set;}       
  public Evidence_For_Need__c evidence {get;set;}
  
  public Location__c location {get;set;}
  
  public Boolean isSelected {get; set;}

  public BdrServiceWrapper(Services__c svc)
  {
    this.svc=svc;    

    //Don't call this on the constructor. Too many SOQL queries
    //this.evidence = getLatestEvidenceForNeed();

    isSelected = false;
    fundReqWrappers = new List<BdrFundReqWrapper>();
  }
  
  public void addFr(BdrFundReqWrapper freq)
  {
     fundReqWrappers.add(freq);
  }

  public void newEvidenceForNeed()  
  {
     String sid = svc.id; 
     this.evidence=BdrServiceWrapperUtils.createEfn(sid);
  }
  
}