src/objects/Evidence_for_Need__c.object
<CustomObject>
    <description>A document recording the evidence for the need for a specific service</description>
    <fields>
        <fullName>Release_Date__c</fullName>
        <label>Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <referenceTo>Services__c</referenceTo>
        <relationshipName>Evidence_for_Needs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isCurrent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isCurrent</label>
        <type>Checkbox</type>
    </fields>
    <label>BDR Evidence for Need</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDR Evidence for Needs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EvidenceForNeedControllerExtension.cls
public with sharing class EvidenceForNeedControllerExtension {

/*
  gary.grant@conseq.co.uk 
  Mar 2013
  Controller extension supporting the Evidence for Need object  
*/

 ApexPages.StandardController ctl;
 Evidence_For_Need__c en;

 public EvidenceForNeedControllerExtension(ApexPages.StandardController controller) 
 {
    ctl=controller;
    en = (Evidence_For_Need__c)ctl.getRecord();    
 }
 
 public void cancel()
 {
     ctl.cancel();
 }
 
 public void save() 
 {
    en = (Evidence_For_Need__c)ctl.getRecord();    

    /*Set the next version number for this type of ConfigText*/
    List<Evidence_For_Need__c> lis = [select version__c from Evidence_For_Need__c where Service__c =:en.Service__c and id<>:en.id order by version__c desc limit 1];        
    if(lis!=null && lis.size()>0) {
       en.version__c = (lis[0].version__c +1);
    } else {
        en.version__c = 1;
    }

   ctl.save();
     
 }
 
 public pageReference newVersion()
 {
     Evidence_For_Need__c newEn= en.clone(false,true);
     newEn.version__c = en.version__c+1;
     newEn.isCurrent__c = false;
     insert newEn;
     
     PageReference pr=new PageReference('/'+ newEn.id);
     pr.setRedirect(true);    
     return pr;
    
 }
 
 
 public void makeCurrent()
 {    
    List<Evidence_For_Need__c> lis =[select id, isCurrent__c from Evidence_For_Need__c where Service__c =:en.Service__c and id<>:en.id and isCurrent__c=true limit 1];
    
    if(lis!=null && lis.size()>0) {    
        Evidence_For_Need__c enCurr = lis[0];        
        enCurr.isCurrent__c=false;
    }
    
    en.isCurrent__c=true;
    en.Release_Date__c = date.Today();
    lis.add(en);

    update lis;    
 }

}