src/objects/Fund_Allocation__c.object
<CustomObject>
    <description>A link between a Service Costs and an Income Block for a Financial Year</description>
    <fields>
        <fullName>Allocation_Amount__c</fullName>
        <description>The amount of funds allocated from the source to the service funding requirement</description>
        <label>Allocation Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BDR_Name__c</fullName>
        <formula>Income_Block_Period__r.Income_Block__r.BDR__r.Name</formula>
        <label>BDR Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <formula>Text(Funding_Requirement__r.Fiscal_Year__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fiscal Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Funding_Requirement__c</fullName>
        <label>Funding Requirement</label>
        <referenceTo>Funding_Requirement__c</referenceTo>
        <relationshipName>Fund_Allocation_Records</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Income_Block_Period__c</fullName>
        <label>Income Block Period</label>
        <referenceTo>Income_Block_Period__c</referenceTo>
        <relationshipName>Fund_Allocation_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the funding allocation</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BDR Income Allocation</label>
    <nameField>
        <displayFormat>FAR-{0000}</displayFormat>
        <label>Fund Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDR income Allocation Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Funding_Requirement__c.object
<CustomObject>
    <description>A single figure representing the funding requirement to cover the costs of providing the service, including FCR</description>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Financial Year</label>
        <picklist>
            <picklistValues>
                <fullName>2010/11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011/12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012/13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013/14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014/15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015/16</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <description>The Service to which this Funding Requirement relates</description>
        <inlineHelpText>Select the service for which this funding requirement applies</inlineHelpText>
        <label>Service</label>
        <referenceTo>Services__c</referenceTo>
        <relationshipName>Funding_Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Enter full cost of service per financial year. Details should already exist for existing services but adjust or add additional years if needed. If service is expanding, ensure entire cost is included. If service is for part year, reduce amount accordingly</inlineHelpText>
        <label>Total Amount</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cover_Potential_Percent__c</fullName>
        <formula>if(BLANKVALUE(Total_Cover_Potential__c,0) ==0,0,   
    if(BLANKVALUE(Total_Amount__c,0)==0,0,
        Total_Cover_Potential__c  /  Total_Amount__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cover Potential Percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Total_Cover_Potential__c</fullName>
        <formula>Total_Cover_Amount__c  +  Total_Cover_Proposed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cover Potential</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>BDR Service Cost</label>
    <nameField>
        <displayFormat>FR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDR Service Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Income_Block__c.object
<CustomObject>
    <description>A block of income from an Income Source</description>
    <label>BDR Income Block</label>
    <nameField>
        <displayFormat>IB-{0000}</displayFormat>
        <label>Income Block Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDR Income Blocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Income_Block_Period__c.object
<CustomObject>
    <description>An amount from an income block for a specified Financial Year</description>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Financial Year</label>
        <picklist>
            <picklistValues>
                <fullName>2010/11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011/12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012/13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013/14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014/15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015/16</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Income_Block__c</fullName>
        <label>Income Block</label>
        <referenceTo>Income_Block__c</referenceTo>
        <relationshipName>Income_Block_Periods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <description>The amount of funds available in this period</description>
        <inlineHelpText>Total income per financial year that you expect to receive, including full costs.</inlineHelpText>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>BDR Income Block Period</label>
    <nameField>
        <displayFormat>IBP-{0000}</displayFormat>
        <label>Income Block Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDR Income Blocks Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BDRServiceCostExtension.cls
public without sharing class BDRServiceCostExtension {

/*******************************************************************************************************************************************
 *            @author             gary.grant@conseq.co.uk
 *            @date               Sept 2014
 *            @description        Controller Extension for BDR Service Cost Page inserted into DC page to show overview of service funding
 *  
 ********************************************************************************************************************************************/


 public List<Fund_Allocation__c> allocations {get;set;}   
 public List<BDRFundReqWrapper> fundReqWrappers {get;set;}

 public BDRServiceCostExtension(ApexPages.StandardController controller) 
 {
    Services__c svc =(Services__c)controller.getRecord();
    
    fundReqWrappers = new List<BDRFundReqWrapper>();

    /* Get all Allocations that are either Draft, Accepted, Proposed or Live */
    allocations = [select id, 

                   Income_Block_Period__r.Income_Block__r.Contract__r.name,  
                   Income_Block_Period__r.Income_Block__r.Contract__r.id,  
                   Income_Block_Period__r.Income_Block__r.Contract__r.Status__c,
                   Income_Block_Period__r.Income_Block__r.Contract__r.End_Date__c,
                   Income_Block_Period__r.Income_Block__r.Contract__r.Renewal_Risk__c,
        
                   Income_Block_Period__r.Income_Block__r.BDR__r.Status__c,
                   Income_Block_Period__r.Income_Block__r.BDR__r.Name,
                   Income_Block_Period__r.Income_Block__r.BDR__r.BDR_Name__c,
                   Income_Block_Period__r.Income_Block__r.BDR__r.Id,

                   Income_Block_Period__r.Income_Block__r.BDR__r.Income_Source__r.Name,
        
                   Funding_Requirement__c,
        
                   Allocation_Amount__c
                   
                   from fund_allocation__c where Funding_Requirement__c in (select id from Funding_Requirement__c where Service__c  =: svc.id ) 
                   and Income_Block_Period__r.Income_Block__r.BDR__r.Status__c in ('Draft', 'Accepted', 'Proposed', 'Live')
                   order by Fiscal_Year__c desc
                   
                   ];

    system.debug('BDR Service Cost Summary Allocations: ' + allocations.size());
 
    List<Funding_Requirement__c> lisFR = [select id, name, Fiscal_Year__c, Total_Amount__c , Total_Cover_Potential__c, Total_Cover_Potential_Percent__c from Funding_Requirement__c where Service__c =:svc.id order by Fiscal_Year__c desc];

    system.debug('BDR Service Cost Summary Funding Requirements: ' + lisFr.size());

    for (Funding_Requirement__c fr : lisFr) {
    
        BdrFundReqWrapper frW = new BdrFundReqWrapper(fr);
        for (Fund_Allocation__c fa : allocations) {
        
            if (fa.Funding_Requirement__c == fr.id) {
                frW.addAllocationToList(fa); 
                system.debug('BDR Service Cost Summary Adding Fa to Fr: ' + fa.id + ':' + fr.id);
            }
        
        }
        fundReqWrappers.add(frW);
        system.debug('BDR Service Cost Summary Add FundReqWrapper: ' + fundReqWrappers.size());    
    
    }    

 }

}