src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Where__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Region / Area / Locality / Service Office 
 Always enter the lowest of the hierarchy in case of Combined Use</inlineHelpText>
        <label>Who</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Organisation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties (Where)</relationshipLabel>
        <relationshipName>Locations4</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Property_Audit__c.object
<CustomObject>
    <description>Used to hold results of property audits</description>
    <fields>
        <fullName>Audit_Date__c</fullName>
        <label>Audit Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Property Audits</relationshipLabel>
        <relationshipName>R00N70000002GNrgEAG</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>NumberofFloors__c</fullName>
        <label>Number of Floors</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Property Audit</label>
    <nameField>
        <displayFormat>PS{00000}</displayFormat>
        <label>Property Audit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Audits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestPropertyAuditTriggerHandler.cls
@isTest
public with sharing class TestPropertyAuditTriggerHandler{
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : Test Class for PropertyAuditTriggerHandler.
 *  Author  : Sri Tadikonda
 *  Date    : 27-02-2014
 *  Version : 0.1 Unit Test
 *
 *  Description:    Apex Class to test PropertyAuditTriggerHandlertrigger on the User object. 
 *               
 *  Modification History
 *
 *  Date            Who     Description 
 *  dd-mm-yyyy      ??      ??
 *                             
*******************************************************************************************/

static testMethod void testInsert()
    {
        Account accRec = new Account(Name='Midlands Central Locality',RecordTypeId=[Select Id from RecordType where SObjectType='Account' and Name like 'Internal%'].id);
        Test.startTest();
        insert accRec;
        
        Location__c propertyRec = new Location__c(Name='Alzheimers Soceity',Where__c = accRec.Id,RecordTypeId=[Select Id from RecordType where SObjectType='Location__c' and Name like 'Lease%'].id);
                
        insert propertyRec ;
        
        Property_Audit__c paRec = new Property_Audit__c(Location__c = propertyRec.Id,Audit_Date__c = system.today());
        
        insert paRec;
        
        paRec.NumberofFloors__c ='4';
        update paRec;
        
        delete paRec;
        
        Test.stopTest(); 

    } 
}