src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Break_Date__c</fullName>
        <label>old Break Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Where__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Region / Area / Locality / Service Office 
 Always enter the lowest of the hierarchy in case of Combined Use</inlineHelpText>
        <label>Who</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Organisation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties (Where)</relationshipLabel>
        <relationshipName>Locations4</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Property_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Property</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Property Contracts</relationshipLabel>
        <relationshipName>Property_Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Property Contract</label>
    <nameField>
        <displayFormat>PCN-{00}</displayFormat>
        <label>Property Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property_Contract_Break__c.object
<CustomObject>
    <fields>
        <fullName>Break_Date__c</fullName>
        <label>Break Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Break_Notice_Months__c</fullName>
        <label>Break Notice (Months)</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property_Contract__c</fullName>
        <label>Property Contract</label>
        <referenceTo>Property_Contract__c</referenceTo>
        <relationshipLabel>Property Contracts Break</relationshipLabel>
        <relationshipName>Property_Contracts_Break</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Property Contract Break</label>
    <nameField>
        <displayFormat>BN-{00}</displayFormat>
        <label>Break Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Contracts Break</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestPropertyContractBreakTriggerHandler.cls
@isTest
public with sharing class TestPropertyContractBreakTriggerHandler{
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : Test Class for PropertyContractBreakTriggerHandler.
 *  Author  : Sri Tadikonda
 *  Date    : 27-02-2014
 *  Version : 0.1 Unit Test
 *
 *  Description:    Apex Class to test PropertyContractBreakTriggerHandler on the User object. 
 *               
 *  Modification History
 *
 *  Date            Who     Description 
 *  dd-mm-yyyy      ??      ??
 *                             
*******************************************************************************************/

static testMethod void testInsert()
    {
        Account accRec = new Account(Name='Midlands Central Locality',RecordTypeId=[Select Id from RecordType where SObjectType='Account' and Name like 'Internal%'].id);
        Test.startTest();
        insert accRec;
        
        Location__c propertyRec = new Location__c(Name='Alzheimers Soceity',Where__c = accRec.Id,RecordTypeId=[Select Id from RecordType where SObjectType='Location__c' and Name like 'Lease%'].id);      
        insert propertyRec ;
        
        Property_Contract__c pcRec = new Property_Contract__c(Location__c = propertyRec.Id);
        insert pcRec;
        
        Property_Contract_Break__c pcbRec = new Property_Contract_Break__c (Break_Notice_Months__c = 2,Property_Contract__c = pcRec.Id);
        insert pcbRec;
        
        pcbRec.Break_Date__c = system.today();
        update pcbRec;
        
        delete pcbRec;
        
        Test.stopTest(); 

    } 
}