src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>Default_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the venue where your service takes place from the pick list. If your venue is not listed, please contact your Area Coordinator or Locality Administrator</inlineHelpText>
        <label>Service Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Dementia Connect - Services</relationshipLabel>
        <relationshipName>Services_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>National_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>National Service?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>service_city__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>service_description__c</fullName>
        <inlineHelpText>Service description is  automatically populated from the service types for internal services</inlineHelpText>
        <label>Service Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>service_postcode__c</fullName>
        <label>Postcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>service_status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>service_street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DcoBatchGeocoder.cls
global class DcoBatchGeocoder implements Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable 
{

   global Database.QueryLocator start(Database.BatchableContext BC)
   {
      String query = 'select Name, service_description__c, service_postcode__c, '+
                         'service_street__c, service_city__c, '+
                         'Default_Location__r.Postcode__c, '+
                         'Default_Location__r.Geographic_location__latitude__s,'+ 
                         'Default_Location__r.Geographic_location__longitude__s '+
                         'from Services__c '+
                         'where Location__latitude__s = null '+
                         'and service_status__c = \'Open\' '+
                         'and National_Service__c = false '+
                         'and (Service_Postcode__c <> null or (Default_Location__r.Postcode__c <> null and Default_Location__r.Geographic_location__latitude__s <> null))';
      return Database.getQueryLocator(query);
   }
   
   global void execute(Database.BatchableContext BC, List<sObject> scope)
   {
     for(sobject svc : scope){
      DcoGeocodeUtils.geocode((Services__c)svc);
     }
     update scope;
   } 
   
   global void finish(Database.BatchableContext BC)
   {
   }

  global void execute(SchedulableContext SC) 
  {
      DcoBatchGeocoder geocoder = new DcoBatchGeocoder();
      Database.executeBatch(geocoder,4);
  }

}