src/objects/Service_Usage__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Worker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the worker (staff or volunteer) assigned to service delivery.  NOTE THAT THIS MAY NEED TO BE REPLACED WITH A LOOKUP TO A WORKER OBJECT (OR CONTACT OF TYPE &apos;WORKER&apos;).</description>
        <inlineHelpText>The name of the worker assigned to provide the service if not the Record Owner (i.e. Home Support Worker, Befriender). Do NOT just type in paid worker/volunteer name – A paid worker/volunteer already on the system must be found, selected and inserted.</inlineHelpText>
        <label>Assigned Worker</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Usage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closure_Reason__c</fullName>
        <inlineHelpText>Set only when case is closed. Must be set if ‘Closure Date’ is set</inlineHelpText>
        <label>Closure Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Case complete - outcomes met</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Reasons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person Declined Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person no longer eligible for service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service no longer required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service user moved into full time care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service user moved out of area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service user or person cared for deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Suspension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred to another service</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Field__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the Service/Activity.
Filtered by Service Type and user&apos;s Locality for internal Service Usage records.
No filter required for &apos;Outgoing Referrals&apos; as these are only ever created in the background (via Referrals screen).</description>
        <label>Service</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 5 AND 6) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>Services__c.service_type__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Type__c</valueField>
            </filterItems>
            <filterItems>
                <field>Services__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Service</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outgoing Referral</value>
            </filterItems>
            <filterItems>
                <field>Services__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Service</value>
            </filterItems>
            <filterItems>
                <field>Services__c.Locality__r.Name</field>
                <operation>equals</operation>
                <valueField>$User.Locality__c</valueField>
            </filterItems>
            <filterItems>
                <field>Services__c.service_status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Services__c</referenceTo>
        <relationshipLabel>Service Usage</relationshipLabel>
        <relationshipName>Service_Usage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_User_Deceased__c</fullName>
        <description>Shows whether the Person has been identified as deceased.</description>
        <formula>IF(Primary_Service_User__r.Deceased__c ,&quot;TRUE&quot;,&quot;FALSE&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service User Deceased</label>
        <type>Text</type>
    </fields>
    <label>Service Usage</label>
    <nameField>
        <label>Service Usage Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Usage</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SwapServiceUsageOwnership.cls
Public with sharing class SwapServiceUsageOwnership {

//Public User FromUser {get;set;}
//Public User ToUser {get;set;}

Public Service_Usage__c fromSU {get;set;}
Public Service_Usage__c toSU {get;set;}
Public list<ServiceCountWrapper> ServiceWp {get;set;}
Public String debugLog {get;set;}
Public String ProcessingStage {get;set;}
Public SwapServiceUsageOwnership(ApexPages.StandardController stdCon){
//    FromUser = New User();
//    ToUser = New User();
    fromSU = New Service_Usage__c ();
    toSU = New Service_Usage__c ();
    ServiceWp = new List<ServiceCountWrapper>();
    ProcessingStage = '1';
    }
Public PageReference cancel() {
        return new PageReference('/');
    }
Public PageReference Find() {
    
    if ((fromSU.ownerid!=null)&&(toSU.ownerid!=null))
    {
        ServiceWp.Clear();
        List<aggregateResult> suAgg = [select service_field__c, service_field__r.name, count(id)
        from service_usage__c where ownerid=:fromSU.ownerid and closure_reason__c =null and Service_User_Deceased__c = 'FALSE'
        group by service_field__c, service_field__r.name
        order by service_field__r.name ];
        if (suAgg.size()>0){
            for (AggregateResult ar : suAgg){
            
            ServiceCountWrapper s = new ServiceCountWrapper();

            s.Serviceid =(String)ar.get('service_field__c');
            s.ServiceName = (String)ar.get('Name') ;
            s.isSelected = false;
            s.CountServiceUsage = (integer)ar.get('expr0') ;
            ServiceWp.Add(s);
            }    
            ProcessingStage = '2';
        }
        
        else
        {
        ApexPages.Message message = new ApexPages.message(ApexPages.severity.WARNING,'No open service usage records found for old user.');
        ApexPages.addMessage(message);
        }
    } 
    else
    {
    ApexPages.Message message = new ApexPages.message(ApexPages.severity.ERROR,'From and to owners must be selected.');
    ApexPages.addMessage(message);
    }
    return null;
    } 
    
Public pageReference submit(){
    
    List <ServiceCountWrapper> suUpdateList = new list<ServiceCountWrapper>();
    String sfIds = '';
    debugLog = '';
    for (ServiceCountWrapper rec: ServiceWp){
        if (rec.isSelected) {
            suUpdateList.add(rec);
//            debugLog = debugLog + rec.serviceId + '=' + rec.ServiceName + ' ;';
            sfIds = sfIds + '\'' + rec.serviceId + '\',';
        }
    }
    if(suUpdateList.size()==0){
        ApexPages.Message message = new ApexPages.message(ApexPages.severity.ERROR,'One or more service must be selected.');
        ApexPages.addMessage(message);
    }else{
        sfIds = sfIds.substring(0, sfIds.lastindexof(','));
        String query = 'select  id, name, ownerid, Assigned_Worker__c from Service_usage__c where service_field__c in (' + sfIds + ') and ownerid = \'' + fromSU.ownerid + '\'' + ' and closure_reason__c =null and Service_User_Deceased__c = \'FALSE\'';
        debugLog = debugLog + '<br/>Query is  ' + query; 
        ServiceUsageOwnerReassignment reassign = new ServiceUsageOwnerReassignment();
        reassign.query= query;
        reassign.email=UserInfo.getUserEmail();
        reassign.fromUserId = fromSU.ownerid;
        reassign.toUserId = toSU.ownerid;
        ID batchprocessid = Database.executeBatch(reassign, 20);
        
        debugLog=debugLog + '<br/> The batch results will be sent to  ' + UserInfo.getUserEmail();
        debugLog= debugLog + ' ' + '<br/> The batch process ID is batchprocessid  = ' + batchprocessid ;
        ProcessingStage = '3';
    }
    return null;  
}       
Public Class ServiceCountWrapper{
    Public Boolean isSelected {get; set;}
    Public String serviceId {get;set;}
    Public String ServiceName {get;set;}
    Public integer CountServiceUsage {get;set;}
    }
}