src/objects/Service_Usage_Outcome__c.object
<CustomObject>
    <label>Service Usage Outcome</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Service Usage Outcome ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Usage Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>Locality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Locality in which this service is based (left blank for national services).</description>
        <label>Locality</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select an Alzheimer&apos;s Society Locality.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Organisation</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>contains</operation>
                <value>Locality</value>
            </filterItems>
            <infoMessage>Please select a Locality.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Services_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>National_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>National Service?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>service_type__c</fullName>
        <inlineHelpText>Service description will be automatically populated from the service type (or sub type if there is one)</inlineHelpText>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult education &amp; training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (emotional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (financial)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (general)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awareness raising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending / home support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counselling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day support / day care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafés</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exercise / Fitness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home facilities &amp; services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Dementia)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Financial &amp; Legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programmes &amp; provision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>Internal Service/Activity</description>
        <label>Internal Service</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ServiceActivityExtension.cls
public class ServiceActivityExtension {

/******************************************************************************************
 *  Alzheimer's
 *  
 *  Purpose : Select record type for Event/Task.
 *  Author  : Fujitsu - Nupoor Pandey
 *  Date    : 2012-02-07
 *  Version : 0.1 Unit Tested
 *  Project : CRSProto
 *
 *  Description: Class to select record type for Event/Task. 
 *               
 *               
 *  Modification History
 *
 *  Date         Who    Description 
 *  yyyy-mm-dd - XX -   xxxxxxxxxxxxxxxxxxxxxxxxxxxx
 *                             
*******************************************************************************************/
    
    public Services__c sa {get; private set;}
    //public List<Service_Usage_Outcome__c> suo;

    /**
        Constructor to get the Service Activity Id from the page and retrieve the following:
        :Services__c
    */
    public ServiceActivityExtension(ApexPages.StandardController controller) {
        Id id = ApexPages.currentPage().getParameters().get('id');
        sa = (id == null) ? new Services__c() : [Select s.Name, s.Id, s.service_type__c From Services__c s WHERE id = :id];
    }   
    
    /**public PageReference assignEventRecordType() {
        String recordTypeName;
        RecordType rt;
        if(sa.Service_Type__c=='Awareness raising'){
            recordTypeName = 'Awareness Raising Event';
        }else if(sa.Service_Type__c=='Activity group'){
            recordTypeName = 'CRS Group Event';
        }else{
            return new PageReference('/apex/Event_Error');
        }
        rt = [Select Id, Name from RecordType where IsActive=true and SobjectType='Event' and Name = :recordTypeName];
        return new PageReference('/00U/e?what_id='+sa.id+'&retURL=%2F'+sa.id+'&RecordType='+rt.Id+'&ent=Event');
    }*/
    
    public PageReference cancel() {
        return new PageReference('/'+sa.Id);

}
//
// TEST CASE
//
  private static testMethod void testServiceActivityExtension() {
    Account accRec = new Account(Name='Midlands Central Locality',RecordTypeId=[Select Id from RecordType where SObjectType='Account' and Name like 'Internal%'].id);
    insert accRec;
    Services__c service = new Services__c(Name='Midlands Central Advocacy', Locality__c=accRec.id,Service_Type__c='Advocacy', National_Service__c=false);//Name='testControllerService');
    insert service;    
    
    //Services__c service = new Services__c(Name='Test service');
    
    ApexPages.StandardController stdCon = new ApexPages.StandardController(service);        
    
        
    ServiceActivityExtension sae = new ServiceActivityExtension(stdCon);
    sae.sa = service;
        
    sae.cancel();    
    }
}