src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>National_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>National Service?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>service_city__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>service_description__c</fullName>
        <inlineHelpText>Service description is  automatically populated from the service types for internal services</inlineHelpText>
        <label>Service Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>service_postcode__c</fullName>
        <label>Postcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>service_status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>service_street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DcoApiServiceHtmlController_Test.cls
@isTest
private class DcoApiServiceHtmlController_Test 
{
    @isTest
    private static void runTest()
    {
    	Services__c svc = new Services__c();
      svc.Name = 'Test Service 1';
      svc.service_description__c = 'Test Service 1';
      svc.service_postcode__c = 'SW18 4DU';
      svc.service_street__c = '241 Garratt lane Wandsworth';
      svc.service_city__c = 'London';
      svc.service_status__c = 'Open';
      svc.Location__Latitude__s = 52;
      svc.Location__Longitude__s = 0;
      svc.National_Service__c = true;
      insert svc;
      
      System.RestContext.request = new RestRequest();
      System.RestContext.response = new RestResponse();
      
      DcoApiServiceHtmlController.httpGet();
      
      RestContext.request.requestURI = 'https://test.com/'+svc.Id;  
      DcoApiServiceHtmlController.httpGet();
    }

}