src/objects/Service_Usage__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Worker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the worker (staff or volunteer) assigned to service delivery.  NOTE THAT THIS MAY NEED TO BE REPLACED WITH A LOOKUP TO A WORKER OBJECT (OR CONTACT OF TYPE &apos;WORKER&apos;).</description>
        <inlineHelpText>The name of the worker assigned to provide the service if not the Record Owner (i.e. Home Support Worker, Befriender). Do NOT just type in paid worker/volunteer name – A paid worker/volunteer already on the system must be found, selected and inserted.</inlineHelpText>
        <label>Assigned Worker</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Usage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closure_Date__c</fullName>
        <inlineHelpText>Set only when case is closed. Must be set if a ‘Closure Reason’ is set</inlineHelpText>
        <label>Closure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_last_Activity__c</fullName>
        <description>Calculated field - set to the date of the last completed activity related to the Service Usage or one of its outcomes.</description>
        <label>Date of Last Activity</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Public_Alert_Message_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Only tick if everyone who is involved with this service user should contact you regarding the person.</inlineHelpText>
        <label>Public Alert Message Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referral_Date__c</fullName>
        <label>Referral Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Referral_Outcome__c</fullName>
        <inlineHelpText>The outcome of the assessment of the referral – whether ‘Case Opened’ or ‘Service Required’. Specifies if person accepted onto the service or not (and any action taken)</inlineHelpText>
        <label>Referral Outcome</label>
        <picklist>
            <picklistValues>
                <fullName>Case Opened</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Eligible (Referred on)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Eligible (No further action)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Declined (Referred on)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Declined (No further action)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable to contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Risk_Identified__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates whether any significant risks have been identified and highlighted within an attached Risk Assessment document</inlineHelpText>
        <label>Risk Identified (see Risk Assessment)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Field__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the Service/Activity.
Filtered by Service Type and user&apos;s Locality for internal Service Usage records.
No filter required for &apos;Outgoing Referrals&apos; as these are only ever created in the background (via Referrals screen).</description>
        <label>Service</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 5 AND 6) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>Services__c.service_type__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Type__c</valueField>
            </filterItems>
            <filterItems>
                <field>Services__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Service</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outgoing Referral</value>
            </filterItems>
            <filterItems>
                <field>Services__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Service</value>
            </filterItems>
            <filterItems>
                <field>Services__c.Locality__r.Name</field>
                <operation>equals</operation>
                <valueField>$User.Locality__c</valueField>
            </filterItems>
            <filterItems>
                <field>Services__c.service_status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Services__c</referenceTo>
        <relationshipLabel>Service Usage</relationshipLabel>
        <relationshipName>Service_Usage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <description>The type of Service to which Service Usage relates.
Used as a filter when selecting Service.
Used to set Record Type on saving a new Service Usage.</description>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (one to one)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peer support group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered home care and support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singing for the Brain</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Usage</label>
    <nameField>
        <label>Service Usage Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Usage</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>service_type__c</fullName>
        <inlineHelpText>Service description will be automatically populated from the service type (or sub type if there is one)</inlineHelpText>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Activity group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult education &amp; training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (emotional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (financial)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (general)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice and support (legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awareness raising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending / home support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carer Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community support service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counselling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day care and support (establishment based)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day support / day care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia cafés</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dementia Support &amp; Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exercise / Fitness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home facilities &amp; services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Dementia)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information and Advice (Financial &amp; Legal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information programmes &amp; provision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <recordTypes>
        <fullName>External</fullName>
        <active>true</active>
        <description>External Service/Activity</description>
        <label>External Service</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ServiceServiceUsageRelatedListController.cls
/******************************************************************************************
 *  Alzheimer's
 *  
 *  Purpose : Apex Controller for ServiceServiceUsage RelatedList VF page.
 *  Author  : Mike Tinson
 *  Date    : 27 November 2012
 *                             
*******************************************************************************************/
public class  ServiceServiceUsageRelatedListController
{

public ApexPages.StandardController stdController;
public Services__c serv;
public List<RelatedServiceUsageClass> lstRelSU {get;set;}
public Integer totalRecCnt {get;set;}
public string SUKeyPrefix {get;set;}
public string CONFirstname {get;set;}
public string CONLastname {get;set;}
private string SERVICE_EXT_RECTYPE ='External Service';

    // Standard controller constructor.
    public ServiceServiceUsageRelatedListController(ApexPages.StandardController pController) {
        stdController = pController;
        serv = (Services__c) stdController.getRecord(); 
        system.debug('@@@@@@@@@@@@@@@'+serv.id);
    }
    
    //Method is called when the page is loaded, similar to Constructor
    public PageReference AutoRunNonExternalSU(){    
        SUKeyPrefix = Schema.getGlobalDescribe().get('Service_Usage__c').getDescribe().getKeyPrefix();
        //Full URL parameter defines to limit no. of rows to 5.
        Integer qryLimit = (ApexPages.currentPage().getParameters().get('full')==null) ? 5 : 9999;
        
        Map<Id,Service_Usage__c> lstServUsage = new Map<Id,Service_Usage__c>([Select Name,Referral_Outcome__c,Service_Field__c,Service_Field__r.Name,
            Service_Type__c,Date_of_last_Activity__c,Referral_Date__c,Closure_Date__c,Risk_Identified__c,Public_Alert_Message_Required__c,Assigned_Worker__r.Name  
            from Service_Usage__c where (Service_Field__c =:serv.id ) 
            and Service_Field__r.RecordType.Name !=: SERVICE_EXT_RECTYPE order by Closure_Date__c desc Limit :qryLimit]);
        
        //This is Seperate Class which run query under User privileges.
        ContactServiceUsageWithSharing clsAccessible = new ContactServiceUsageWithSharing();
        
        //Returned accessible/visible ServiceUsage records Ids.
        Set<Id> setAccessibleRecs = clsAccessible.getAccessibleRecords(lstServUsage.keyset());
        
        lstRelSU = new List<RelatedServiceUsageClass>();
        
        //Iterate to populate specail Inner Class with flag to say a ServiceUsage record is accessible to user.
        for(Service_Usage__c rec: lstServUsage.Values())
        {
            RelatedServiceUsageClass cls = new RelatedServiceUsageClass();
            cls.recSU = rec;
            
            //If record found in Accessible set then will have edit and view link of page.
            cls.isAccessible = setAccessibleRecs.contains(rec.id);
            lstRelSU.add(cls);
        }
        
        //Get the count of records, this derives whether More link on Page be shown or not.
        totalRecCnt = [Select count() from Service_Usage__c where (Service_Field__c =:serv.id ) and Service_Field__r.RecordType.Name !=: SERVICE_EXT_RECTYPE];
        //If First Name contains more than one name (such as Mary Ann), return only one
//        string strName;
//        if (serv.FirstName==null)
//            {
//            CONFirstname = '';
//            }
//        else
//            {
//            strName = serv.FirstName;
//            string[] strArr= strName.split(' ');
//            CONFirstname = strArr[0];
//            }
//        //If last name contained a quote, the screen did nothing.  
//        
//        if (serv.LastName==null)
//            {
//            CONLastname = '';
//            }
//        else
//            {
//            String strLastName= String.escapeSingleQuotes(serv.LastName);
//            CONLastName=strLastName;
//            }
      return null;
   }
 
   
//Inner Class
public class RelatedServiceUsageClass
{
    public boolean isAccessible {get;set;}
    public Service_Usage__c recSU {get;set;}
}


}