src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>Needs_Approval__c</fullName>
        <description>Highlight any records that need approval</description>
        <formula>AND( OR(TEXT(service_status__c)==&quot;Open&quot;, TEXT(service_status__c)==&quot;Pending&quot;   ), Record_Type_Name__c==&apos;Internal&apos;,  Display_on_public_website__c ,  Change_Needs_Approval__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>If true then this record will not appear on the website until the record has been sent for approval.</inlineHelpText>
        <label>Needs Approval</label>
        <type>Checkbox</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ServiceAlertMessage.cls
public with Sharing Class ServiceAlertMessage 
{
public Services__c recServ {get; set;}

public ServiceAlertMessage(ApexPages.StandardController controller) {
    this();
    
}
public ServiceAlertMessage() {
    if(ApexPages.currentPage().getParameters().get('id')!=null)
    {
        system.debug('@@@@@@@@@@@@@@@'+ApexPages.currentPage().getParameters().get('id'));
        getServiceDetails();
        system.debug('@@@@@@@@@@@@@@@'+recServ.Needs_Approval__c);
    }
}
public Services__c  getServiceDetails() {
    //recServ = (Services__c)controller.getRecord();
    recServ = [select id, Needs_Approval__c from Services__c where id=:ApexPages.currentPage().getParameters().get('id')];
    return recServ;



}


}