src/objects/Service_Usage__c.object
<CustomObject>
    <label>Service Usage</label>
    <nameField>
        <label>Service Usage Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Usage</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/UI_Participant__c.object
<CustomObject>
    <description>A User Involvement Participant with Consent</description>
    <fields>
        <fullName>Consent_Type__c</fullName>
        <inlineHelpText>In what form was Consent given?</inlineHelpText>
        <label>Consent Type</label>
        <picklist>
            <picklistValues>
                <fullName>Verbal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Written</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Participant</description>
        <inlineHelpText>The current status of Participant.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unconfirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Valid_From_Date__c</fullName>
        <description>The date the consent is valid to be used</description>
        <inlineHelpText>Date Consent is valid from</inlineHelpText>
        <label>Valid From Date</label>
        <type>Date</type>
    </fields>
    <label>User Involvement Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UIParticipantControllerExtension_Test.cls
/**
 */
@isTest
private class UIParticipantControllerExtension_Test {

    @isTest (SeeAllData=true)
    static void TestUIParticipantControllerExtension()
    {
    
        User u1 = UiUtils_Test.getTestUser1();
        User u2 = UiUtils_Test.getTestUser2(u1);
        Contact contact = UiUtils_Test.getTestContact();
        Account acct = UiUtils_Test.getTestAccount();
        Services__c svc = UiUtils_Test.getTestService(acct);
    
        Service_Usage__c su = UIUtils_Test.getTestServiceUsage(u1, u2, contact, acct, svc);
        UI_Participant__c p = UiUtils_Test.getTestParticipant(contact,false);
    
        ApexPages.StandardController sc = new ApexPages.standardController(p);
        
        p.Status__c = 'Unconfirmed';
        p.Consent_Type__c = 'Written';
        p.Valid_From_Date__c = Date.Today();
        
        UIParticipantControllerExtension e = new UIParticipantControllerExtension(sc);
        
        List<SelectOption> lisOptions = e.getActivity_Types_Options();
        lisOptions = e.getAreas_Of_Expertise_Options();
        lisOptions = e.getMethods_Of_Involvement_Options();
        
        Service_Usage__c su2 = e.su;
    
        e.clicked();
        
        e.saveRecord();
        e.save();
        e.saveAndClose();
        
        p.Status__c = 'Active';
        e.saveRecord();   
        
    }
    
    @isTest (SeeAllData=true)
    static void TestUIParticipantControllerExtension2()
    {
    
        User u1 = UiUtils_Test.getTestUser1();
        User u2 = UiUtils_Test.getTestUser2(u1);
        Contact contact = UiUtils_Test.getTestContact();
        Account acct = UiUtils_Test.getTestAccount();
        Services__c svc = UiUtils_Test.getTestService(acct);
    
        Service_Usage__c su = UIUtils_Test.getTestServiceUsage(u1, u2, contact, acct, svc);
        UI_Participant__c p = UiUtils_Test.getTestParticipant(contact,false);
    
    	User u = UiUtils_Test.getTestUserInPermissionSet();
    	System.RunAs(u) { 
    
	        ApexPages.StandardController sc = new ApexPages.standardController(p);
	        
	        p.Status__c = 'Unconfirmed';
	        p.Consent_Type__c = 'Written';
	        p.Valid_From_Date__c = Date.Today();
	        
	        UIParticipantControllerExtension e = new UIParticipantControllerExtension(sc);
	        
	        p.Status__c = 'Active';
	        
	        try {
	        	 e.saveRecord();
	        } catch (Exception x) {
	        	//Do nothing;
	        }  
    	
    	} 
        
    }
    
    @isTest (SeeAllData=true)
    static void TestUIParticipantRequestApproval()
    {
    
        User u1 = UiUtils_Test.getTestUser1();
        User u2 = UiUtils_Test.getTestUser2(u1);
        Contact contact = UiUtils_Test.getTestContact();
        Account acct = UiUtils_Test.getTestAccount();
        Services__c svc = UiUtils_Test.getTestService(acct);
    
        Service_Usage__c su = UIUtils_Test.getTestServiceUsage(u1, u2, contact, acct, svc);
        UI_Participant__c p = UIUtils_Test.getTestParticipant(contact,false);
    
        ApexPages.StandardController sc = new ApexPages.standardController(p);
        
        p.Status__c = 'Unconfirmed';
        p.Consent_Type__c = 'Written';
        p.Valid_From_Date__c = Date.Today();
        
        UIParticipantControllerExtension e = new UIParticipantControllerExtension(sc);        
        e.saveAndRequestApproval();
    
    }

}