src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>Accessibility__c</fullName>
        <inlineHelpText>Select from the drop down list and record additional information in the free text box if required</inlineHelpText>
        <label>Venue Accessibility</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_first_name__c</fullName>
        <label>Contact first name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_last_name__c</fullName>
        <label>Contact last name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parking__c</fullName>
        <inlineHelpText>Select from the drop down list and record additional information in the free text box if required</inlineHelpText>
        <label>Parking</label>
        <picklist>
            <picklistValues>
                <fullName>Yes-on site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes-off site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Toilet_Facilities__c</fullName>
        <inlineHelpText>Select from the drop down list and record additional information in the free text box if required</inlineHelpText>
        <label>Toilet Facilities</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>service_city__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>service_description__c</fullName>
        <inlineHelpText>Service description is  automatically populated from the service types for internal services</inlineHelpText>
        <label>Service Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>service_email__c</fullName>
        <inlineHelpText>This must be the email address for the local service office or locality. No individual email addresses should be used.</inlineHelpText>
        <label>Email address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>service_operationhourscomment__c</fullName>
        <label>Operation hours comment</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>service_postcode__c</fullName>
        <label>Postcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>service_street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>service_targetclientgroup__c</fullName>
        <inlineHelpText>Select who the service is for from the drop down list</inlineHelpText>
        <label>Target client group</label>
        <picklist>
            <picklistValues>
                <fullName>People with Dementia Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carers of People with Dementia Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People with Dementia and their carers, family and friends</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People with Dementia aged under 65</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People with dementia diagnosed under 65</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carers of older people with dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carers of people with dementia of all ages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carers of younger people with dementia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former carers only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mix of carers and former carers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mix of people with dementia, carers and former carers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Older people with dementia (65 and over) and their carers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People of all ages with dementia and their carers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People with dementia diagnosed at 65 and over</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carers of people with dementia diagnosed at 65 and over only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People with dementia of all ages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People with dementia younger (less than 65 years old)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People with dementia, their carers and families, and professionals in health and social care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People with dementia diagnosed under 65 and their carers, family and friends</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carers of people with dementia diagnosed under 65 only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People with dementia and their carers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People with dementia diagnosed at 65 and over and their carers, family and friends</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professionals working in health and social care etc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People over 65</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Younger people with dementia (under 65) and their carers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The general public</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (please describe)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>service_telephone__c</fullName>
        <inlineHelpText>This should be an office phone not an individual mobile number</inlineHelpText>
        <label>Telephone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>service_website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DcoServiceHtmlBuilder.cls
public with sharing class DcoServiceHtmlBuilder 
{
   private String buffer;
   private Services__c svc;

   public String buildHtml(Services__c service)
   {  
   	buffer = '';
      svc = service;
      
      beginElement('html');
      emitHead();
      emitBody();
      closeElement('html');
                  
      return buffer;
    }
    
   private void emitHead()
   {
      beginElement('head');

      emitElement('title', svc.Name);
      emitMetadata();

      closeElement('head');
   }
   
   private void emitMetadata()
   {
	   emitMetaTag('content-language','en');
	   emitMetaTag('robots','index');
	   emitMetaTag('Author','Alzheimer\'s Society');
	   emitMetaTag('Publisher','Alzheimer\'s Society');
	   emitMetaTag('Coverage','UK');
	   emitMetaTag('Description', svc.Service_Description__c);
	   
	   emitMetaTag('DC.creator','Alzheimer\'s Society');
	   emitMetaTag('DC.date.created',svc.CreatedDate.format('yyyy-MM-dd'));
	   emitMetaTag('DC.format','text/html');
	   emitMetaTag('DC.language','en');
	   emitMetaTag('DC.publisher','Alzheimer\'s Society');
	   emitMetaTag('DC.rights.copyright','Copyright Alzheimer\'s Society. Registered charity no 296645.');
	   emitMetaTag('DC.coverage','UK');
	   emitMetaTag('DC.identifier','http://www.alzheimers.org.uk/dco/services/'+svc.Id);
      emitMetaTag('DC.title', svc.Name);
	   emitMetaTag('DC.description', svc.Service_Description__c);
	   
	   if (svc.Location__Latitude__s != null) {
	      emitMetaTag('geo.position', svc.Location__Latitude__s+';'+svc.Location__Longitude__s);
	   }
   }
   
   private void emitBody()
   {
      beginElement('body');

      emitElement('h1', svc.Name);

      emitElement('h2', svc.service_street__c+' '+svc.service_city__c+' '+svc.service_postcode__c);

      emitElement('h3', 'Service Description');
      emitElement('p', svc.service_description__c);

      emitElement('h3', 'Service Details');
      emitElement('p', 'For', svc.service_targetclientgroup__c);
      emitElement('p', 'Parking', svc.Parking__c);
      emitElement('p', 'Toilets', svc.Toilet_Facilities__c);
      emitElement('p', 'Accessibility', svc.Accessibility__c);
      emitElement('p', 'Hours', svc.service_operationhourscomment__c);

      emitElement('h3', 'Contact Information');
      emitElement('p', 'Contact name', svc.Contact_first_name__c+' '+svc.Contact_last_name__c);
      emitElement('p', 'Telephone', svc.service_telephone__c);
      emitElement('p', 'Email', svc.service_email__c);
      emitElement('p', 'Website', svc.service_website__c);

      closeElement('body');
   }
    
   private void emitMetaTag(String name, String content)
   {
      buffer += '<meta name="'+name+'" content="'+escape(content)+'"/>';
   }

   private void beginElement(String name)
   {
      buffer += '<'+name+'>';
   }

   private void closeElement(String name)
   {
      buffer += '</'+name+'>';
   }

   private void emitElement(String name)
   {
      buffer += '<'+name+'/>';
   }

   private void emitElement(String name, String content)
   {
      if (content == null) return;
      buffer += '<'+name+'>'+escape(content)+'</'+name+'>';
   }

   private void emitElement(String name, String label, String content)
   {
      if (content == null) return;
      buffer += '<'+name+'>'+escape(label)+': '+escape(content)+'</'+name+'>';
   }

   private static String escape(String text)
   {
      text = text.replace('<', '&lt;');
      text = text.replace('>', '&gt;');
      text = text.replace('&', '&amp;');
      return text;      
   }

}