src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>Display_on_public_website__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display on public website?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>$RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>service_status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>Internal Service/Activity</description>
        <label>Internal Service</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DcoSitemapController.cls
public with sharing class DcoSitemapController 
{
   //This needs to be CONFIRMED prior to use.
   public static String URL_ROOT = 'http://www.alzheimers.org.uk/local-information/dementia-connect';

   public List<Services__c> getServices()
   {
      Integer block = DcoSitemapIndexController.BLOCK_SIZE;
      Integer offset = DcoSitemapIndexController.BLOCK_SIZE * getPageNumber();
      return [select Id from Services__c 
                       where Display_on_public_website__c = true
                       and Record_Type_Name__c = 'Internal' 
                       and Service_Status__c = 'Open'
                       LIMIT :block OFFSET :offset ];
   }

   public Integer getPageNumber()
   {
      String url = ApexPages.currentPage().getParameters().get('p');
   	return url==null ? 0 : Integer.valueOf(url);  
   }

   public String getUrlRoot()
   {
   	return URL_ROOT;
   }

}