src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>National_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>National Service?</label>
        <type>Checkbox</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ServiceAlertMessageTest.cls
@isTest
private class ServiceAlertMessageTest
{
static testMethod void ServiceAlertMessageTest1(){

    Services__c service = new Services__c(Name='Test service', National_Service__c = true);
    insert service;
    
    PageReference pageRef = Page.ServiceAlertMessage;
    test.setCurrentPage(pageRef);
    
    ApexPages.StandardController stdCon = new ApexPages.StandardController(service );
    pageRef.getParameters().put('id', service.Id);
    ServiceAlertMessage cnt = new ServiceAlertMessage(stdCon);
    
    
    }
}