src/objects/Service_Usage__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Worker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the worker (staff or volunteer) assigned to service delivery.  NOTE THAT THIS MAY NEED TO BE REPLACED WITH A LOOKUP TO A WORKER OBJECT (OR CONTACT OF TYPE &apos;WORKER&apos;).</description>
        <inlineHelpText>The name of the worker assigned to provide the service if not the Record Owner (i.e. Home Support Worker, Befriender). Do NOT just type in paid worker/volunteer name – A paid worker/volunteer already on the system must be found, selected and inserted.</inlineHelpText>
        <label>Assigned Worker</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Usage</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Usage</label>
    <nameField>
        <label>Service Usage Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Usage</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ServiceUsageOwnerReassignment.cls
global class ServiceUsageOwnerReassignment implements Database.Batchable<sObject>{
Public String query {get;set;}
Public String email{get;set;}
Public Id toUserId{get;set;}
Public Id fromUserId{get;set;}

global Database.querylocator start(Database.BatchableContext BC){
    System.debug('################query##############' + query);
    return Database.getQueryLocator(query);}

global void execute(Database.BatchableContext BC, List<sObject> scope){
    List<Service_Usage__c> sus = new List<Service_Usage__c>();

   for(sObject s : scope){Service_Usage__c a = (Service_Usage__c)s;
        if(a.OwnerId==fromUserId){
            a.OwnerId=toUserId;
            a.Assigned_Worker__c=toUserId;
            sus.add(a);
            }
        }

update sus;
    
}
global void finish(Database.BatchableContext BC){
// First, reserve email capacity for the current Apex transaction to ensure
// that we won't exceed our daily email limits when sending email after
// the current transaction is committed.
Messaging.reserveSingleEmailCapacity(1);

Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

mail.setToAddresses(new String[] {email});
mail.setReplyTo('mike.tinson@alzheimers.org.uk');
mail.setSenderDisplayName('Batch Processing');
mail.setSubject('Batch Process Completed');
String strMessage = 'Batch Process has completed';
strMessage = strMessage  + '\n query: ' + query;
strMessage = strMessage  + '\n toUserId: ' + toUserId;
strMessage = strMessage  + '\n fromUserId: ' + fromUserId;
mail.setPlainTextBody( strMessage );
//mail.setPlainTextBody('Batch Process Completed');
Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
}
}