src/objects/Service_Usage__c.object
<CustomObject>
    <fields>
        <fullName>Service_Field__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the Service/Activity.
Filtered by Service Type and user&apos;s Locality for internal Service Usage records.
No filter required for &apos;Outgoing Referrals&apos; as these are only ever created in the background (via Referrals screen).</description>
        <label>Service</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 5 AND 6) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>Services__c.service_type__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Type__c</valueField>
            </filterItems>
            <filterItems>
                <field>Services__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Service</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outgoing Referral</value>
            </filterItems>
            <filterItems>
                <field>Services__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Service</value>
            </filterItems>
            <filterItems>
                <field>Services__c.Locality__r.Name</field>
                <operation>equals</operation>
                <valueField>$User.Locality__c</valueField>
            </filterItems>
            <filterItems>
                <field>Services__c.service_status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Services__c</referenceTo>
        <relationshipLabel>Service Usage</relationshipLabel>
        <relationshipName>Service_Usage</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Usage</label>
    <nameField>
        <label>Service Usage Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Usage</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <fields>
        <fullName>Operated_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the Organisation which operates this service.</description>
        <inlineHelpText>For internal services this should be a local service office unless operated at the locality level</inlineHelpText>
        <label>Operated By</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND (3 OR 4)) OR (5 AND 6)</booleanFilter>
            <errorMessage>Internal Services can only be operated by a Locality or a Local Service Office (this lookup is filtered based on the Locality you selected in the previous field).
External Services can only be Operated By an External Organisation.</errorMessage>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Service</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Organisation</value>
            </filterItems>
            <filterItems>
                <field>Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Locality__c</valueField>
            </filterItems>
            <filterItems>
                <field>Account.Parent.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Locality__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Service</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>External organisation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dementia Connect - Services (Operated By)</relationshipLabel>
        <relationshipName>Services_Activities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Dementia Connect - Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dementia Connect - Services</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BatchRecalculateSUApexSharing.cls
global class BatchRecalculateSUApexSharing implements Database.Batchable <Sobject> {
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : Batch APEX Class to re-calculate the Apex Sharing rules for Service Usage records.
 *  Author  : Ian Smith
 *  Date    : 10-06-2014
 *  Version : 0.1 Unit Test
 *
 *  Description:    Batch APEX Class to re-calculate the Apex Sharing rules for selected Service 
 *                  Usage records. 
 *
 *                  Called via the Execute Anonymous window. 
 *                  BatchRecalculateSUApexSharing su = new BatchRecalculateSUApexSharing();
 *                  su.query = 'SELECT su.Id FROM Service_Usage__c su WHERE su.Service_Field__r.Operated_By__r.Name = 'Black Country Local Service Office'';
 *               
 *  Modification History
 *  Date            Who         Description 
 *  dd-mm-yyyy      ??          ??
 *                             
*******************************************************************************************/
    static String emailAddress = 'crssupport@alzheimers.org.uk';
    global String query {get; set;}
    global List<Service_Usage__c> saveList = new List<Service_Usage__c>();
    
    //*Note - the Query will be set when the code is called from an Execute Anonymous window.
    //Query set to - SELECT su.Id FROM Service_Usage__c su WHERE su.Service_Field__r.Operated_By__r.Name = '<LOCAL SERVICE OFFICE>'
    global Database.querylocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext info, List<Sobject> lstServiceUsage){
        system.debug('****** About to process ' + lstServiceUsage.size() + ' records in BatchRecalculateSUApexSharing.execute ******');

        if(lstServiceUsage.size() > 0){
            
            //get list of Apex sharing rows for these records
            List<Service_Usage__Share> lstSUApexShareToDelete = [SELECT s.Id, s.ParentId, s.IsDeleted, s.AccessLevel, s.RowCause
                                                                 FROM Service_Usage__Share s 
                                                                 WHERE ParentId in :lstServiceUsage 
                                                                 AND IsDeleted!=true
                                                                 AND AccessLevel='Edit' 
                                                                 AND RowCause=:Schema.Service_Usage__Share.RowCause.ApexSharing__c];                                   
            System.debug('****** lstSUApexShareToDelete.Size ******: ' + lstSUApexShareToDelete.Size());
            
            if(lstSUApexShareToDelete.size() > 0){
                //Attempt to delete the Apex Sharing Rules for the specified Service Usage records.
                try{
                    System.debug('****** Deleting Apex Sharing for ******: ' + lstSUApexShareToDelete.size() + ' Records.');
                    delete lstSUApexShareToDelete;
                }
                catch(DmlException e) {
                   //Send an email to crssupport on failure.
                    notificationExceptionEmail(e,'BatchRecalculateSUApexSharing',emailAddress);
                    throw e;
                } 
            } 
            
            if (lstServiceUsage.size() > 0){
                //Attempt to Update the Apex Sharing Rules for the specified Service Usage records lstServiceUsage
                //and force the Service Usage trigger to fire.
                try{
                    System.debug('****** Updating Apex Sharing for ******: ' + lstServiceUsage.size() + ' Records.');
                    update lstServiceUsage;
                }
                catch(DmlException e) {
                   //Send an email to crssupport on failure.
                    notificationExceptionEmail(e,'BatchRecalculateSUApexSharing',emailAddress);
                    throw e;
                }
            }      
        }  
    }
    
    global void finish(Database.BatchableContext BC){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {emailAddress}; 
        mail.setToAddresses(toAddresses);
        mail.setSenderDisplayName('Batch Processing');
        mail.setSubject('Batch Process BatchRecalculateSUApexSharing Completed');
        mail.setPlainTextBody('Batch Process BatchRecalculateSUApexSharing has completed');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }   
    
    public static void notificationExceptionEmail(Exception e, String locationName, String email) {
        //Send an email to crssupport on DmlException failure.
        
        String orgId = UserInfo.getOrganizationId();
        String orgName = UserInfo.getOrganizationName();
        String user = UserInfo.getUserName();
        String message = e.getMessage();
        String stacktrace = e.getStackTraceString();
        String exType = '' + e.getTypeName();
        String line = '' + e.getLineNumber();
        String theTime = '' + System.now();
        
        String subject = String.format('Exception thrown at {0} by user {1} in org {2} (Id: {3})', new List<String>{ locationName, user, orgName, orgId });
        String body = String.format('Time: {0}\nMessage: {1}\nStacktrace: {2}\nLine: {3}', new List<String>{ theTime, message, stacktrace, line });
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {email}; 
        mail.setToAddresses(toAddresses);
        mail.setSenderDisplayName('Batch Processing');
        mail.setSubject(subject);
        mail.setUseSignature(false);
        mail.setPlainTextBody(Body);
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        
    }   
        
}