src/objects/zzDateModifiedLookup__c.object
<CustomObject>
    <fields>
        <fullName>lastDateModified__c</fullName>
        <label>lastDateModified</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>objectAPIName__c</fullName>
        <label>objectAPIName</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>zzDateModifiedLookup</label>
    <nameField>
        <label>DateModifiedLookup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>zzDateModifiedLookup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zzService_Usage_Copy__c.object
<CustomObject>
    <label>zzService_Usage_Copy</label>
    <nameField>
        <label>Service_Usage_Copy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>zzService_Usage_Copy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/zzDateModifiedLookup.cls
public with sharing class zzDateModifiedLookup {

	/*
	
	ADD LOGIC TO UPDATE/CREATE NEW ROWS IN THE zzDateModifiedLookup__c OBJECT.
	
	*/


	public void zzDateModifiedLookupUpdate(){
		
		System.debug('****** Apex Class zzDateModifiedLookupUpdate  ******');

		List<zzDateModifiedLookup__c> zzList = [SELECT id, lastDateModified__c, objectAPIName__c FROM zzDateModifiedLookup__c WHERE objectAPIName__c = 'zzService_Usage_Copy__c'];
  		for(integer i = 0 ; i < zzList.size(); i++){
     		zzList[i].lastDateModified__c = datetime.now();
  		}
		
		update zzList;	
	}	

}